:toc: true
:toclevels: 2
:page-title: Action
:page-pageid: Enumeration/Action
:page-description: The list of actions that can be performed on visual ThoughtSpot entities, such as answers and Liveboards.

= Action

The list of actions that can be performed on visual ThoughtSpot
entities, such as answers and Liveboards.
This enum is used to specify the actions that could be disabled,
hidden or made visible.



`example` : 
```js
const embed = new LiveboardEmbed('#embed-container', {
   ... // other options
   visibleActions: [Action.Save, Action.Explore],
   disableActions: [Action.Save],
   hiddenActions: [Action.Download], // Set either this or visibleActions
})
```





== Enumeration members

=== AddFilter
`AddFilter:= "addFilter"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1859[types.ts, window=_blank]

=== AddFormula
`AddFormula:= "addFormula"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1863[types.ts, window=_blank]

=== AddParameter
`AddParameter:= "addParameter"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1864[types.ts, window=_blank]

=== AddToFavorites
`AddToFavorites:= "addToFavorites"`





`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1971[types.ts, window=_blank]

=== AnswerChartSwitcher
`AnswerChartSwitcher:= "answerChartSwitcher"`





`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1967[types.ts, window=_blank]

=== AnswerDelete
`AnswerDelete:= "onDeleteAnswer"`





`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1963[types.ts, window=_blank]

=== AxisMenuAggregate
`AxisMenuAggregate:= "axisMenuAggregate"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1998[types.ts, window=_blank]

=== AxisMenuConditionalFormat
`AxisMenuConditionalFormat:= "axisMenuConditionalFormat"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2010[types.ts, window=_blank]

=== AxisMenuEdit
`AxisMenuEdit:= "axisMenuEdit"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2030[types.ts, window=_blank]

=== AxisMenuFilter
`AxisMenuFilter:= "axisMenuFilter"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2006[types.ts, window=_blank]

=== AxisMenuGroup
`AxisMenuGroup:= "axisMenuGroup"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2018[types.ts, window=_blank]

=== AxisMenuNumberFormat
`AxisMenuNumberFormat:= "axisMenuNumberFormat"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2034[types.ts, window=_blank]

=== AxisMenuPosition
`AxisMenuPosition:= "axisMenuPosition"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2022[types.ts, window=_blank]

=== AxisMenuRemove
`AxisMenuRemove:= "axisMenuRemove"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2042[types.ts, window=_blank]

=== AxisMenuRename
`AxisMenuRename:= "axisMenuRename"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2026[types.ts, window=_blank]

=== AxisMenuSort
`AxisMenuSort:= "axisMenuSort"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2014[types.ts, window=_blank]

=== AxisMenuTextWrapping
`AxisMenuTextWrapping:= "axisMenuTextWrapping"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2038[types.ts, window=_blank]

=== AxisMenuTimeBucket
`AxisMenuTimeBucket:= "axisMenuTimeBucket"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2002[types.ts, window=_blank]

=== ChooseDataSources
`ChooseDataSources:= "chooseDataSources"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1862[types.ts, window=_blank]

=== CollapseDataSources
`CollapseDataSources:= "collapseDataSources"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1861[types.ts, window=_blank]

=== ConfigureFilter
`ConfigureFilter:= "configureFilter"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1860[types.ts, window=_blank]

=== CopyAndEdit
`CopyAndEdit:= "context-menu-item-copy-and-edit"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1947[types.ts, window=_blank]

=== CopyLink
`CopyLink:= "embedDocument"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1851[types.ts, window=_blank]

=== CopyToClipboard
`CopyToClipboard:= "context-menu-item-copy-to-clipboard"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1946[types.ts, window=_blank]

=== CreateMonitor
`CreateMonitor:= "createMonitor"`





`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1979[types.ts, window=_blank]

=== CrossFilter
`CrossFilter:= "context-menu-item-cross-filter"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1990[types.ts, window=_blank]

=== Download
`Download:= "download"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1884[types.ts, window=_blank]

=== DownloadAsCsv
`DownloadAsCsv:= "downloadAsCSV"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1887[types.ts, window=_blank]

=== DownloadAsPdf
`DownloadAsPdf:= "downloadAsPdf"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1886[types.ts, window=_blank]

=== DownloadAsPng
`DownloadAsPng:= "downloadAsPng"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1885[types.ts, window=_blank]

=== DownloadAsXlsx
`DownloadAsXlsx:= "downloadAsXLSX"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1888[types.ts, window=_blank]

=== DrillExclude
`DrillExclude:= "context-menu-item-exclude"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1945[types.ts, window=_blank]

=== DrillInclude
`DrillInclude:= "context-menu-item-include"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1944[types.ts, window=_blank]

=== Edit
`Edit:= "edit"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1899[types.ts, window=_blank]

=== EditACopy
`EditACopy:= "editACopy"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1850[types.ts, window=_blank]

=== EditDetails
`EditDetails:= "editDetails"`





`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1975[types.ts, window=_blank]

=== EditMeasure
`EditMeasure:= "context-menu-item-edit-measure"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1952[types.ts, window=_blank]

=== EditTML
`EditTML:= "editTSL"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1896[types.ts, window=_blank]

=== EditTitle
`EditTitle:= "editTitle"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1900[types.ts, window=_blank]

=== Explore
`Explore:= "explore"`

Explore action.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1943[types.ts, window=_blank]

=== ExportTML
`ExportTML:= "exportTSL"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1893[types.ts, window=_blank]

=== ImportTML
`ImportTML:= "importTSL"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1894[types.ts, window=_blank]

=== LiveboardInfo
`LiveboardInfo:= "pinboardInfo"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1922[types.ts, window=_blank]

=== MakeACopy
`MakeACopy:= "makeACopy"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1849[types.ts, window=_blank]

=== ManagePipelines
`ManagePipelines:= "manage-pipeline"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1986[types.ts, window=_blank]

=== Pin
`Pin:= "pin"`

Pin action.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1934[types.ts, window=_blank]

=== Present
`Present:= "present"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1897[types.ts, window=_blank]

=== QueryDetailsButtons
`QueryDetailsButtons:= "queryDetailsButtons"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1959[types.ts, window=_blank]

=== Remove
`Remove:= "delete"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1901[types.ts, window=_blank]

=== RemoveCrossFilter
`RemoveCrossFilter:= "context-menu-item-remove-cross-filter"`





`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1994[types.ts, window=_blank]

=== RenameModalTitleDescription
`RenameModalTitleDescription:= "renameModalTitleDescription"`





`version` : SDK: 1.23.0 | ThoughtSpot: 9.4.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L2051[types.ts, window=_blank]

=== ReportError
`ReportError:= "reportError"`





`version` : SDK: 1.11.1 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1983[types.ts, window=_blank]

=== RequestAccess
`RequestAccess:= "requestAccess"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1958[types.ts, window=_blank]

=== Save
`Save:= "save"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1839[types.ts, window=_blank]

=== SaveAsView
`SaveAsView:= "saveAsView"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1848[types.ts, window=_blank]

=== Schedule
`Schedule:= "subscription"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1856[types.ts, window=_blank]

=== SchedulesList
`SchedulesList:= "schedule-list"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1857[types.ts, window=_blank]

=== Separator
`Separator:= "context-menu-item-separator"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1953[types.ts, window=_blank]

=== Share
`Share:= "share"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1858[types.ts, window=_blank]

=== ShareViz
`ShareViz:= "shareViz"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1878[types.ts, window=_blank]

=== ShowUnderlyingData
`ShowUnderlyingData:= "showUnderlyingData"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1883[types.ts, window=_blank]

=== SpotIQAnalyze
`SpotIQAnalyze:= "spotIQAnalyze"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1869[types.ts, window=_blank]

=== Subscription
`Subscription:= "subscription"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1939[types.ts, window=_blank]

=== SyncToOtherApps
`SyncToOtherApps:= "sync-to-other-apps"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1985[types.ts, window=_blank]

=== SyncToSheets
`SyncToSheets:= "sync-to-sheets"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1984[types.ts, window=_blank]

=== ToggleSize
`ToggleSize:= "toggleSize"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1898[types.ts, window=_blank]

=== UpdateTML
`UpdateTML:= "updateTSL"`


Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1895[types.ts, window=_blank]