:toc: true
:toclevels: 2
:page-title: AuthType
:page-pageid: Enumeration/AuthType
:page-description: The authentication mechanism for allowing access to the the embedded app

= AuthType

The authentication mechanism for allowing access to the
the embedded app



`group` : Authentication / Init





== Enumeration members

=== Basic
`Basic:= "Basic"`

Use the ThoughtSpot login API to authenticate to the cluster directly.
Warning: This feature is primarily intended for developer testing. It is
strongly advised not to use this authentication method in production.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L176[types.ts, window=_blank]

=== EmbeddedSSO
`EmbeddedSSO:= "EmbeddedSSO"`

Passthrough SSO to the embedded App within the iframe. Requires least
configuration, but may not be supported by all IDPs. This will behave like `None`
if SSO is not configured on ThoughtSpot.



`example` : 
```js
init({
  // ...
  authType: AuthType.EmbeddedSSO,
 });
```
Set authentication type as Embedded SSO.

To use this:
Your SAML or OpenID provider must allow iframe redirects.
eg. If you are using okta as IdP, you can enable iFrame embedding.



`version:` : SDK: 1.15.0 | ThouhgtSpot: 8.8.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L50[types.ts, window=_blank]

=== None
`None:= "None"`

No authentication on the SDK. Passthrough to the embedded App. Alias for
`Passthrough`.



`example` : 
```js
init({
  // ...
  authType: AuthType.None,
 });
```




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L30[types.ts, window=_blank]

=== OIDCRedirect
`OIDCRedirect:= "SSO_OIDC"`

SSO using OIDC
Will make the host application redirect to the OIDC Idp.
See code samples in xref:SAMLRedirect.adoc[SAMLRedirect].



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L123[types.ts, window=_blank]

=== SAMLRedirect
`SAMLRedirect:= "SSO_SAML"`

SSO using SAML
Will make the host application redirect to the SAML Idp. Use this
when the idp does not allow itself to be embedded.
This redirects the host application to the SAML Idp. The host application
will be redirected back to the ThoughtSpot app after authentication.



`example` : 
```js
init({
  // ...
  authType: AuthType.SAMLRedirect,
 });
```

This opens the SAML Idp in a popup window. The popup is triggered
when the user clicks the trigger button. The popup window will be
closed automatically after authentication.



`example` : 
```js
init({
  // ...
  authType: AuthType.SAMLRedirect,
  authTriggerText: 'Login with SAML',
  authTriggerContainer: '#embed-container',
  inPopup: true,
});
```

Can also use event to trigger the popup flow. Works the same
as above example.



`example` : 
```js
const authEE = init({
 // ...
 authType: AuthType.SAMLRedirect,
 inPopup: true,
});

someButtonOnYourPage.addEventListener('click', () => {
 authEE.emit(AuthEvent.TRIGGER_SSO_POPUP);
});
```




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L110[types.ts, window=_blank]

=== TrustedAuthToken
`TrustedAuthToken:= "AuthServer"`

Trusted authentication server, Use your own authentication server
which returns a bearer token, generated using the secret_key obtained
from ThoughtSpot.



`example` : 
```js
init({
 // ...
 authType: AuthType.TrustedAuthToken,
 getAuthToken: () => {
   return fetch('https://my-backend.app/ts-token')
     .then((response) => response.json())
     .then((data) => data.token);
 }
```




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L148[types.ts, window=_blank]

=== TrustedAuthTokenCookieless
`TrustedAuthTokenCookieless:= "AuthServerCookieless"`

Trusted authentication server Cookieless, Use you own authentication
server which returns a bearer token, generated using the secret_key
obtained from ThoughtSpot. This uses a cookieless authentication
approach, recommended to by pass third-party cookie-blocking restriction
implemented by some browsers



`example` : 
```js
init({
 // ...
 authType: AuthType.TrustedAuthTokenCookieless,
 getAuthToken: () => {
   return fetch('https://my-backend.app/ts-token')
     .then((response) => response.json())
     .then((data) => data.token);
 }
```



`version` : SDK: 1.22.0| ThouhgtSpot: 9.3.0.cl, 9.5.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L169[types.ts, window=_blank]