:toc: true
:toclevels: 2
:page-title: AuthStatus
:page-pageid: Enumeration/AuthStatus
:page-description: Enum for auth status emitted by the emitter returned from {@link init}.

= AuthStatus

Enum for auth status emitted by the emitter returned from xref:init.adoc[init].



`group` : Authentication / Init





== Enumeration members

=== FAILURE
`FAILURE:= "FAILURE"`

Emits when the SDK fails to authenticate



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/auth.ts#L71[auth.ts, window=_blank]

=== LOGOUT
`LOGOUT:= "LOGOUT"`

Emits when a user logs out



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/auth.ts#L83[auth.ts, window=_blank]

=== SDK_SUCCESS
`SDK_SUCCESS:= "SDK_SUCCESS"`

Emits when the SDK authenticates successfully



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/auth.ts#L75[auth.ts, window=_blank]

=== SUCCESS
`SUCCESS:= "SUCCESS"`

Emits when the app sends an authentication success message



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/auth.ts#L79[auth.ts, window=_blank]

=== WAITING_FOR_POPUP
`WAITING_FOR_POPUP:= "WAITING_FOR_POPUP"`

Emitted when inPopup: true in the SAMLRedirect flow.
And, we are waiting for popup to be triggered either programatically
or by the trigger button.



`version` : SDK: 1.19.0




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/auth.ts#L91[auth.ts, window=_blank]