:toc: true
:toclevels: 2
:page-title: EmbedEvent
:page-pageid: Enumeration/EmbedEvent
:page-description: Event types emitted by the embedded ThoughtSpot application.

= EmbedEvent

Event types emitted by the embedded ThoughtSpot application.
To add an event listener use the corresponding
xref:LiveboardEmbed.adoc#on[LiveboardEmbed] or xref:AppEmbed.adoc#on[AppEmbed] or xref:SearchEmbed.adoc#on[SearchEmbed] method.



`example` : 
```js
import { EmbedEvent } from '@thoughtspot/visual-embed-sdk';
// Or
// const { EmbedEvent } = window.tsembed;

// create the liveboard embed.

liveboardEmbed.on(EmbedEvent.Drilldown, (drilldown) => {
  console.log('Drilldown event', drilldown);
}));
```



`group` : Events





== Enumeration members

=== ALL
`ALL:= "*"`

This can be used to register an event listener which
is triggered on all events.



`version` : SDK: 1.10.0 | ThoughtSpot: 8.2.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L971[types.ts, window=_blank]

=== AddRemoveColumns
`AddRemoveColumns:= "addRemoveColumns"`

One or more data columns have been selected.



`returns` : columnIds - the list of columns



`version` : SDK: 1.10.0 | ThoughtSpot: 8.2.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L837[types.ts, window=_blank]

=== AddToFavorites
`AddToFavorites:= "addToFavorites"`

Emitted when a user clicks on the Favorite icon on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1111[types.ts, window=_blank]

=== Alert
`Alert:= "alert"`

The embedded object has sent an alert



`returns` : alert - An alert object




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L883[types.ts, window=_blank]

=== AnswerChartSwitcher
`AnswerChartSwitcher:= "answerChartSwitcher"`

Emitted when an answer is switched to a chart or table view



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1093[types.ts, window=_blank]

=== AnswerDelete
`AnswerDelete:= "answerDelete"`

Emitted when an answer is deleted in the app



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1013[types.ts, window=_blank]

=== AuthExpire
`AuthExpire:= "ThoughtspotAuthExpired"`

The ThoughtSpot auth session has expired.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L887[types.ts, window=_blank]

=== AuthInit
`AuthInit:= "authInit"`

Authentication has either succeeded or failed.



`returns` : isLoggedIn - A Boolean specifying whether authentication was successful.




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L793[types.ts, window=_blank]

=== Cancel
`Cancel:= "cancel"`

Emitted when a user clicks Cancel in edit mode on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1153[types.ts, window=_blank]

=== CopyAEdit
`CopyAEdit:= "copyAEdit"`

Emitted when copy of existing answer on the app



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1081[types.ts, window=_blank]

=== CopyLink
`CopyLink:= "embedDocument"`

Emitted when a user clicks Copy link action on a visualization



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1165[types.ts, window=_blank]

=== CopyToClipboard
`CopyToClipboard:= "context-menu-item-copy-to-clipboard"`

Emitted when copied column value on the app



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1051[types.ts, window=_blank]

=== CrossFilterChanged
`CrossFilterChanged:= "cross-filter-changed"`

Emitted when a user interacts with cross filters on a visualization or liveboard



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1171[types.ts, window=_blank]

=== CustomAction
`CustomAction:= "customAction"`

A custom action has been triggered



`returns` : actionId - The id of the custom action



`returns` : data - The answer or Liveboard data




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L844[types.ts, window=_blank]

=== Data
`Data:= "data"`

Data pertaining to answer or Liveboard is received



`returns` : data - The answer or Liveboard data



`important` : 




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L806[types.ts, window=_blank]

=== DataSourceSelected
`DataSourceSelected:= "dataSourceSelected"`

One or more data sources have been selected.



`returns` : dataSourceIds - the list of data sources




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L830[types.ts, window=_blank]

=== Delete
`Delete:= "delete"`

Emitted when a user clicks Delete on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1141[types.ts, window=_blank]

=== DialogClose
`DialogClose:= "dialog-close"`

Emitted when any modal is closed in the app



`version` : SDK: 1.6.0 | ThoughtSpot: ts8.nov.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L956[types.ts, window=_blank]

=== DialogOpen
`DialogOpen:= "dialog-open"`

Emitted when any modal is opened in the app



`version` : SDK: 1.6.0 | ThoughtSpot: ts8.nov.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L950[types.ts, window=_blank]

=== Download
`Download:= "download"`

Emitted when the download action is triggered on an answer



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L983[types.ts, window=_blank]

=== DownloadAsCsv
`DownloadAsCsv:= "downloadAsCsv"`

Emitted when the Download as CSV action is triggered on an answer



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1001[types.ts, window=_blank]

=== DownloadAsPdf
`DownloadAsPdf:= "downloadAsPdf"`

Emitted when the Download as PDF action is triggered on an answer



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L995[types.ts, window=_blank]

=== DownloadAsPng
`DownloadAsPng:= "downloadAsPng"`

Emitted when the download action is triggered on an answer



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl, 9.4.0-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L989[types.ts, window=_blank]

=== DownloadAsXlsx
`DownloadAsXlsx:= "downloadAsXlsx"`

Emitted when the Download as XLSX action is triggered on an answer



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1007[types.ts, window=_blank]

=== DrillExclude
`DrillExclude:= "context-menu-item-exclude"`

Emitted when a user clicks the Exclude action to exclude a specific value or data
on a chart or table



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1045[types.ts, window=_blank]

=== DrillInclude
`DrillInclude:= "context-menu-item-include"`

Emitted when a user clicks the Include action to include a specific value or data
on a chart or table



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1038[types.ts, window=_blank]

=== Drilldown
`Drilldown:= "drillDown"`

A drill down operation has been performed.



`returns` : additionalFilters - Any additional filters applied



`returns` : drillDownColumns - The columns on which drill down was performed



`returns` : nonFilteredColumns - The columns that were not filtered




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L824[types.ts, window=_blank]

=== Edit
`Edit:= "edit"`

Emitted when a user clicks Edit on a Liveboard or visualization



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1123[types.ts, window=_blank]

=== EditTML
`EditTML:= "editTSL"`

Emitted when a user clicks the Edit TML action



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1063[types.ts, window=_blank]

=== Error
`Error:= "Error"`

An error has occurred.



`returns` : error - An error object or message




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L877[types.ts, window=_blank]

=== Explore
`Explore:= "explore"`

Emitted when a user clicks Explore on a visualization



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1159[types.ts, window=_blank]

=== ExportTML
`ExportTML:= "exportTSL"`

Emitted when ExportTML trigger in answer on the app



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1069[types.ts, window=_blank]

=== GetDataClick
`GetDataClick:= "getDataClick"`

Emitted when  the "Get Data" button in Search Bar embed
is clicked.



`version` : SDK: 1.19.0 | ThoughtSpot: 9.0.0.cl, 9.0.0-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L920[types.ts, window=_blank]

=== Init
`Init:= "init"`

Rendering has initialized.



`returns` : timestamp - The timestamp when the event was generated.




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L787[types.ts, window=_blank]

=== LiveboardInfo
`LiveboardInfo:= "pinboardInfo"`

Emitted when a user clicks Show Liveboard details on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1105[types.ts, window=_blank]

=== LiveboardRendered
`LiveboardRendered:= "PinboardRendered"`

Emitted when the Liveboard shell loads.
You can use this event as a hook to trigger
other events on the rendered Liveboard.



`version` : SDK: 1.9.1 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L964[types.ts, window=_blank]

=== Load
`Load:= "load"`

The embed object container has loaded.



`returns` : timestamp - The timestamp when the event was generated.




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L799[types.ts, window=_blank]

=== MakeACopy
`MakeACopy:= "makeACopy"`

Emitted when a user clicks Make a copy on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1129[types.ts, window=_blank]

=== NoCookieAccess
`NoCookieAccess:= "noCookieAccess"`

Emitted when the embed does not have cookie access. This
happens on Safari where third-party cookies are blocked by default.



`version` : SDK: 1.1.0 | ThoughtSpot: ts7.may.cl, 7.2.1




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L937[types.ts, window=_blank]

=== Pin
`Pin:= "pin"`

Emitted when an answer is pinned to a Liveboard



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1019[types.ts, window=_blank]

=== Present
`Present:= "present"`

Emitted when a user clicks Present on a Liveboard or visualization



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1135[types.ts, window=_blank]

=== QueryChanged
`QueryChanged:= "queryChanged"`

Search query has been updated by the user.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L816[types.ts, window=_blank]

=== RouteChange
`RouteChange:= "ROUTE_CHANGE"`

Detects the route change.



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L924[types.ts, window=_blank]

=== Save
`Save:= "save"`

Emitted when answer is saved in the app



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L977[types.ts, window=_blank]

=== SaveAsView
`SaveAsView:= "saveAsView"`

Emitted when an answer is saved as a view



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1075[types.ts, window=_blank]

=== Schedule
`Schedule:= "subscription"`

Emitted when a user clicks Schedule on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1117[types.ts, window=_blank]

=== SchedulesList
`SchedulesList:= "schedule-list"`

Emitted when a user clicks Manage schedules on a Liveboard



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1147[types.ts, window=_blank]

=== Share
`Share:= "share"`

Emitted when a user shares an object with another user or group



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1031[types.ts, window=_blank]

=== ShowUnderlyingData
`ShowUnderlyingData:= "showUnderlyingData"`

Emitted when a user clicks Show underlying data on an answe



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1087[types.ts, window=_blank]

=== SpotIQAnalyze
`SpotIQAnalyze:= "spotIQAnalyze"`

Emitted when SpotIQ analysis is triggered



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1025[types.ts, window=_blank]

=== UpdateTML
`UpdateTML:= "updateTSL"`

Emitted when a user clicks the Update TML action



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1057[types.ts, window=_blank]

=== VizPointClick
`VizPointClick:= "vizPointClick"`

Listen to clicks on a visualization in a liveboard or Search result.



`example` : 
```js
embed.on(ThoughtSpotEmbed.Event.VizPointClick, ({data}) => {
  console.log(
   data.vizId, // viz id
   data.clickedPoint.selectedAttributes[0].value,
   data.clickedPoint.selectedAttributes[0].column.name,
   data.clickedPoint.selectedMeasures[0].value,
   data.clickedPoint.selectedMeasures[0].column.name,
  )
});
```



`returns` : viz, clickedPoint - metadata about point that is clicked



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw



`important` : 




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L871[types.ts, window=_blank]

=== VizPointDoubleClick
`VizPointDoubleClick:= "vizPointDoubleClick"`

Listen to double clicks on a visualization



`returns` : ContextMenuInputPoints - data point that is double clicked



`version` : SDK: 1.5.0 | ThoughtSpot: ts7.oct.cl, 7.2.1




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L851[types.ts, window=_blank]

=== VizPointRightClick
`VizPointRightClick:= "vizPointRightClick"`

Emitted when a user right clicks on a visualization (chart or table)



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl




Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L1177[types.ts, window=_blank]