:toc: true
:toclevels: 2
:page-title: RuntimeFilterOp
:page-pageid: Enumeration/RuntimeFilterOp
:page-description: A map of the supported runtime filter operations

= RuntimeFilterOp

A map of the supported runtime filter operations




== Enumeration members

=== BEGINS_WITH
`BEGINS_WITH:= "BEGINS_WITH"`

Begins with



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L712[types.ts, window=_blank]

=== BW
`BW:= "BW"`

Between, non-inclusive



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L732[types.ts, window=_blank]

=== BW_INC
`BW_INC:= "BW_INC"`

Between, inclusive of both higher and lower value



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L728[types.ts, window=_blank]

=== BW_INC_MAX
`BW_INC_MAX:= "BW_INC_MAX"`

Between, inclusive of higher value



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L720[types.ts, window=_blank]

=== BW_INC_MIN
`BW_INC_MIN:= "BW_INC_MIN"`

Between, inclusive of lower value



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L724[types.ts, window=_blank]

=== CONTAINS
`CONTAINS:= "CONTAINS"`

Contains



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L708[types.ts, window=_blank]

=== ENDS_WITH
`ENDS_WITH:= "ENDS_WITH"`

Ends with



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L716[types.ts, window=_blank]

=== EQ
`EQ:= "EQ"`

Equals



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L684[types.ts, window=_blank]

=== GE
`GE:= "GE"`

Greater than or equal to



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L704[types.ts, window=_blank]

=== GT
`GT:= "GT"`

Greater than



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L700[types.ts, window=_blank]

=== IN
`IN:= "IN"`

Is included in this list of values



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L736[types.ts, window=_blank]

=== LE
`LE:= "LE"`

Less than or equal to



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L696[types.ts, window=_blank]

=== LT
`LT:= "LT"`

Less than



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L692[types.ts, window=_blank]

=== NE
`NE:= "NE"`

Does not equal



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L688[types.ts, window=_blank]