= ABAC via RLS with variables
:toc: true
:toclevels: 2

:page-title: ABAC via tokens
:page-pageid: abac-via-rls-variables
:page-description: Attribute-based access control pattern with variable attributes referenced in Row-Level Security (RLS) rules on a given table.

In the ABAC via RLS rules implementation, administrators define RLS rules with variable references on the Table from which objects such as Models, Liveboards, and Answers are derived. They can also assign variable values and pass these as user attributes and entitlements via a JWT token. This ensures that all derived objects inherit the data security rules from the Table and are filtered according to the user’s entitlements provided in the token.

[NOTE]
====
Formula variables are available on ThoughtSpot starting from 10.15.0.cl. If this feature is not enabled on your instance, contact ThoughtSpot Support.
====

== ABAC with RLS

To implement data security for your application users, you can use the RLS rules with system variables such as `ts_username` or `ts_groups`. To provide a dynamic and fine-grained filtering that goes beyond what system variables can support, without the need to create and manage many groups or maintain complex ACL tables, administrators can use formula variables in RLS rules.

Formula variables allow you to define custom attributes and assign values at the user, Org, or Model level. This capability is useful if you want to enforce security policies that adapt to user context, such as region or department.

In embedded analytics scenarios, where each user may need different data access, you may want to assign security attributes individually to users along with the RLS rules. The ABAC implementation with custom variables allows assigning variable attributes (`variable_values`) individually to users via JWT tokens, and enforce user-specific data security rules and entitlements at session creation.

=== Implementation steps
The ABAC implementation with formula variables and RLS rules involves the following steps:

* xref:abac_rls-variables.adoc#_create_formula_variables[Creating formula variables] +
To generate tokens with variable attributes, the variable must be created and available on ThoughtSpot. To create variables, use the xref:variables.adoc#_create_a_variable[Variable REST API].
* xref:abac_rls-variables.adoc#_define_rls_rules_with_formula_variable[Adding RLS rules with formula variables to Tables] +
When defining an RLS rule with variables, use the `ts_var` function. These RLS rules will apply to the Models, Liveboards, and other objects derived from that Table.
* xref:abac_rls-variables.adoc#_define_values_and_scope_for_variables[Create a token request and assign variable attributes] +
To generate a JWT token, use the `/api/rest/2.0/auth/token/custom` REST API endpoint. Your token generation request must include the variable attributes that will be used for RLS evaluation, to enable per‑user entitlements and data filters across all the objects derived from the Table.
+
[NOTE]
====
ABAC details are sent in a JWT that can be used as a bearer token for cookieless trusted authentication, REST API calls, or as a sign-in token to start a session. JWTs are compressed by default to handle large payloads. It is recommended to keep the compression enabled to ensure all JWT tokens can get properly interpreted by the application regardless of their size, and to obfuscate the values passed in the JWT payload. If you want to disable it, contact ThoughtSpot Support.
====
* xref:abac_rls-variables.adoc#_verify_entitlements[Verifying entitlements]

=== Session-based rules
The ABAC implementation with formula variables and RLS does not support session-based ABAC rules, so we do not recommend setting the `persist_option` attribute to `NONE`. You can append or replace the attributes by setting the `persist_option` to `APPEND` or `REPLACE`.

Resetting the variable attributes via `"persist_option": "RESET` is also not supported. If you don't want to append or replace any attributes, do not pass any variable values in the token update request.

////
=== Mandatory token filters

The `is_mandatory_token_filter: true` setting in object TML enforces that a filter rule must be provided for a specific column. When this attribute is set on a column in a Model, ThoughtSpot will deny all data access for users who do not have a corresponding filter rule for that column in their ABAC token.

When setting filter rules within the token, you must place the `is_mandatory_token_filter: true` property on every column in a Model where a filter rule is expected. This setting will deny any access to data if a user has not been assigned values for the expected set of fields.

[#column-name-warning]
The filter rules require passing the *exact* column name as defined in the Model. Otherwise, the values will not bind to any column. You must coordinate between the team that maintains the data objects and the team that builds the xref:trusted-auth-token-request-service.adoc[token request service] to know if any changes will be made to a Model and to ensure column names remain consistent. +
For this reason, end users of an embedded app must not be granted edit access to any Model using ABAC rules via tokens. Setting the `is_mandatory_token_filter: true` property on every column where a filter rule is expected ensures that no data is returned for users when column names change.

[NOTE]
====
If a column is set with both `is_hidden: true` and `is_mandatory_token_filter: true`, and filter conditions for that column are defined in the ABAC token, the filter will be applied as expected. The column will be hidden from the user interface, but the mandatory filter requirement will still be enforced, and data will be shown according to the filter values provided in the token.
====
////

=== Indexing
Several features within ThoughtSpot, such as autocompletion in Search on values within columns or the suggestions in *Explore* mode, use ThoughtSpot indexing. Due to the runtime nature of ABAC via tokens, ThoughtSpot indexing will not be restricted by the values supplied in a token. This means the indexed columns may expose values in search suggestions or autocompletion that a user should not see, even if ABAC filters would block access to the underlying data. To prevent this, you can do one of the following:

- Disable indexing for columns and fields that must be restricted by ABAC. You may also want to disable indexing on all sensitive columns.
- Define an RLS rule on those fields, since RLS is enforced at the indexing layer and will secure suggestions and sample values.

== Create formula variables

To view the variables available on your instance, use the `POST /api/rest/2.0/template/variables/search` API call. If you want to create a new variable, use the `/api/rest/2.0/template/variables/create` API endpoint.

To configure formula variables for all Orgs on your instance or the Primary Org, cluster administration privileges are required. Org administrators can configure formula variables for their respective Orgs. Users with the `CAN_MANAGE_VARIABLES` (*Can manage variables*) role privilege can also create and manage variables for their Org context.

The `/api/rest/2.0/template/variables/create` API endpoint allows creating formula variables for the following data types:

* `VARCHAR`
* `INT32`
* `INT64`
* `DOUBLE`
* `DATE`
* `DATE_TIME`

During variable creation, specify the xref:variables.adoc#data_type[`data_type`].

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/]api/rest/2.0/template/variables/create' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "type": "FORMULA_VARIABLE",
  "name": "country_var",
  "is_sensitive": false,
  "data_type": "VARCHAR"
}'
----

The variable update API allows assigning variable values and setting the scope. For the ABAC implementation, administrators can set the variable values and scope when generating a JWT using the `/api/rest/2.0/auth/token/custom` API endpoint.

== Add RLS rules with formula variables to Tables
To set RLS rules with formula variables:

. Navigate to the Data workspace and click the Table for which to define the RLS rules.
. Click *Row security* and then click *+ Add row security*.
. In the *Row Security Editor*, define the rules. To reference the formula variable in the rule, use the `ts_var` function. For example, if you want to limit user access to data of a specific region, you can create a region-specific variable, assign values in the token request, and then add a rule on the underlying Table.

In this example, `country_var` is referenced in the RLS rule to limit user access to country-specific data.

----
country = ts_var('country_var')
----

The RLS rules support the `AND` operator, which means that you can combine multiple conditions in a single RLS rule, so that a row is accessible only if all specified conditions are met.

----
(country in ts_var('country_var')) and (department in ts_var('dept_var')) and (status = 'Active')
----

The following examples show how to define RLS rules with formula  variables of different data types:

RLS rule with a single variable reference::

In the following examples, the formula references `region_var` and `country_var` variables. When the query is executed, the region will translate to the value defined for that variable, for example, West or EMEA. Similarly, `country_var` translates to the value specified for that variable.

+
----
region = ts_var('region_var')
----
+
----
country = ts_var('country_var')
----
+
The formula is then used as a filter, so only the rows that match the specified condition are displayed to the user.

RLS rules with multiple variables::

The RLS rules support the `AND` operator, which means that you can combine multiple conditions in a single RLS rule, so that a row is accessible only if all specified conditions are met.

----
Country = ts_var('country_var') AND Department = ts_var('dept_var')
----

----
Region = ts_var('region_var') AND product_type = ts_var('product_type_var')
----

Wildcard “show all” via variables::
In this example, if the user’s region variable is set to `TS_WILDCARD_ALL`, they see all regions; otherwise, only their entitled region.

----
ts_var('region_var') = 'TS_WILDCARD_ALL' OR Region = ts_var('region_var')
----

Group override rule with variable-based check::
In this example, users in the "data developers" group see all data; others are filtered by their country entitlement.

----
'data developers' in ts_groups OR Country = ts_var('country_var')
----

Variables with numeric and Date data type::

----
Revenue <= to_double(ts_var('revenue_cap_var'))
----

----
if(date_column >= ts_var('start_date_var')) AND (date_column <= ts_var('end_date_var'))
----

[NOTE]
====
Formula variables with BOOLEAN and TIME data types are not supported.
====

== Create an ABAC token request with formula variables

To generate a token with formula variable attributes, send a `POST` request to the `POST /api/rest/2.0/auth/token/custom` API endpoint.

The variable attributes defined in the token request take effect only if they are referenced in an RLS rule. If the variables are not used in any formula or RLS rule, they will have no impact on data access. Before generating the request with variable attributes, ensure that the variables are referenced in the RLS rules on the Table.

==== Request parameters
[width="100%" cols="2,4"]
[options='header']
|=====
|Parameter|Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, a new user account will be created and added to ThoughtSpot.
|`secret_key`
|__String__. The secret key string provided by the ThoughtSpot server. ThoughtSpot generates this secret key xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled].
|`variable_values`  a| Array of formula variables and values for each variable. Define the following attributes for each variable:

* `name` - Name of the formula variable. The formula variable referenced on the token request must be available in ThoughtSpot.
* `values` - Variable values. Ensure that the assigned value matches the data type set for the variable during creation. For example, if you are adding a variable to filter by country, you can specify the string values. For example:

[source,cURL]
----
variable_values": [
    {
      "name": "country_var",
      "values": [
        "Japan",
        "Singapore",
        "Australia"
      ]
    }
  ]
----

For every variable you include in the request, you must assign a value, or a list of values. All values are passed into the token as *arrays of strings*, even if the column is a numeric, or date type in ThoughtSpot and the database. The column data type will be respected in the query issued to the database.

You can also use `TS_WILDCARD_ALL` option to grant access to oll. If `TS_WILDCARD_ALL` is set, ensure that the RLS rules are defined clearly on the Table to avoid unintended data exposure.

|`validity_time_in_sec` +
__Optional__| __Integer__. Token expiry duration in seconds. The default duration is 300 seconds.
|`org_id` +
__Optional__|__Integer__. If your instance has Orgs and want to create a token for a user in a specific Org, include the name or ID of the Org. If an Org ID is not specified, the token is generated for the Primary Org (Org 0).
|`persist_option` a| Specifies whether the rules should persist for user sessions. The following options are available:

* `APPEND` (default) +
Adds the attributes defined in the API request to the user properties. These properties will be applied to the current and future user sessions and for scheduled jobs until they are explicitly changed through a token update request.

* `REPLACE` +
Replaces existing variable assignments with the new values.

* `NONE` +
Not supported for variable values.

* `RESET` +
Not supported for variable values.

|`objects` +
__Optional__ a|__Array of strings__. An array of Model names or GUIDs to which you want to apply the security rules. The default object `type` `LOGICAL_TABLE`.

If no object is specified in the API request, the attributes will be applied to all `LOGICAL_TABLE` objects derived from the Table on which the RLS rules with formula variables are defined.

|`email` +
__Optional__ |__String__. Email address of the user. Use this parameter to add the email address of the user if `auto_create` is set to `true`.
|`display_name` +
__Optional__ |__String__. Display name of the user. Use this parameter if `auto_create` is set to `true.
|`auto_create` +
__Optional__|__Boolean__. Creates a user if the specified username is not already available in ThoughtSpot. The default value is `true`.
|=====

==== Example request
The following example shows the request body for generating a token with formula variable attributes:

[source,cURL]
----
 curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/custom'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "UserA",
  "validity_time_in_sec": 300,
  "persist_option": "APPEND",
  "auto_create": true,
  "secret_key": "f8aa445b-5ff1-4a35-a58f-e324133320d5",
  "variable_values": [
    {
      "name": "country_var",
      "values": [
        "Japan",
        "Singapore",
        "Australia"
      ]
    },
    {
      "name": "dept_var",
      "values": [
        "Sales",
        "Marketing"
      ]
    }
  ],
  "objects": [
    {
      "type": "LOGICAL_TABLE",
      "identifier": "35aa85fe-fbb4-4862-a335-f69679ebb6e0"
    }
  ]
}'
----

If the request is successful, ThoughtSpot generates a token and sends it in the API response.

To verify the assignment, use the `POST /api/rest/2.0/users/search` API call and check the variables values in user properties in the API response.

[source,JSON]
----
//...
{
  "variable_values": {
    "821119045": {
      "ALL": {
        "variable_values": [
          {
            "name": "country_var",
            "values": [
              "Japan",
              "Singapore",
              "Australia"
            ]
          },
          {
            "name": "dept_var",
            "values": [
              "Sales",
              "Marketing"
            ]
          }
        ]
      }
    }
  }
}
----

To verify the security entitlements, start a user session using the JWT and inspect the generated SQL for your query or visualization.

== Verify the entitlements
To verify the entitlements:

. Log in to ThoughtSpot and start the user session with the ABAC token.
. Access a Liveboard, Saved Answer, or start a new search query.
. Inspect the generated SQL for your query or visualization.
. Verify if only permitted rows are displayed.
. Check if data is returned if no variable values are defined.
. Repeat the steps for different variable assignments to confirm the RLS rule is enforced as expected for all scenarios.

== Limitations
The ABAC via tokens method requires xref:trusted-authentication.adoc[trusted authentication] setup.
For indexing recommendations, see xref:abac-user-parameters.adoc#_indexing[Indexing].

== Additional resources

* For information about variables and variable APIs, see https://docs.thoughtspot.com/cloud/latest/rls-variables-reference[:docs.thoughtspot.com] xref:variables.adoc[Variable APIs].
* For information about assigning security entitlements via ABAC tokens, see xref:abac-user-parameters.adoc[ABAC via tokens].
* For information about RLS rule definitions, see link:https://docs.thoughtspot.com/cloud/latest/security-rls[RLS rules documentation, window=_blank].
