= ABAC via token
:toc: true
:toclevels: 1

:page-title: ABAC via token
:page-pageid: abac-user-parameters
:page-description: Attribute-based access control pattern can be achieved via user parameters sent in the login token

Attribute Based Access Control (ABAC) is a pattern where security entitlements are sent in as lists of attributes at session creation time via the auth service.

The ABAC message to ThoughtSpot is encoded in JSON Web Token (JWT) format, using the existing ThoughtSpot V2.0 REST API Access Tokens (which are OAuth JWT tokens). The token can be used as a bearer token for Cookieless Trusted Auth or REST API access or as a sign-in token to create a ThoughtSpot session, in which case the ABAC user parameters should be *persisted*.

You can to pass in Runtime Filters and Parameters for a user via their login token. Both features work like the Runtime Filters and Parameters available within the Visual Embed SDK, but values set via token cannot be overriden by any user action within the ThoughtSpot UI.

== Token request

=== Persistence

== Implementing RLS with ABAC via tokens
You can to pass in Runtime Filters and Parameters for a user via the login token. 

Both features work like the Runtime Filters and Parameters available within the Visual Embed SDK, but values set via token cannot be overriden by any user action within the ThoughtSpot UI.

