= ABAC via RLS with variables
:toc: true
:toclevels: 2

:page-title: ABAC via tokens
:page-pageid: abac-via-rls-variables
:page-description: Attribute-based access control pattern with variable attributes referenced in Row-Level Security (RLS) rules on a given table.

In the ABAC via RLS rules implementation, administrators define RLS rules with variables on the Table from which objects such as Models, Liveboards, and Answers are derived. They can also assign variable values and pass these as user attributes and entitlements via a JWT token. This ensures that all derived objects inherit the data security rules from the Table and are filtered according to the user’s entitlements provided in the token.

[NOTE]
====
Formula variables are available on ThoughtSpot starting from 10.15.0.cl. If this feature is not enabled on your instance, contact ThoughtSpot Support.
====

== Overview

To implement data security for your application users, you can use the RLS rules with system variables such as `ts_username` or `ts_groups`. To provide dynamic and fine-grained access control that goes beyond what system variables can support, administrators can use formula variables in RLS rules. Formula variables allow you to define custom attributes and assign values at the user, Org, or Model level. This capability is useful if you want to enforce security policies that adapt to user context, such as region or department.

In embedded analytics scenarios, where each user may need different data access, you may want to assign security attributes and rules per user. The ABAC implementation with custom variables allows assigning variable attributes (`variable_values`) individually to users via JWT, and thus enforce user-specific data security rules and entitlements at session creation.

=== Implementation steps
The ABAC implementation with formula variables and RLS rules involves the following steps:

* xref:abac_rls-variables.adoc#_create_formula_variables[Creating formula variables] +
To generate tokens with variable attributes, the variable must be created and available on ThoughtSpot. To create variables, use the xref:variables.adoc#_create_a_variable[Variable REST API].
* xref:abac_rls-variables.adoc#_define_rls_rules_with_formula_variable[Adding RLS rules with formula variables to Tables] +
When defining an RLS rule with variables, use the `ts_var` function. These RLS rules will apply to the Models, Liveboards, and other objects derived from that Table.
* xref:abac_rls-variables.adoc#_define_values_and_scope_for_variables[Creating a token request with variable attributes] +
To generate a JWT token, use the `/api/rest/2.0/auth/token/custom` REST API endpoint. Your token generation request must include the variable attributes that will be used for RLS evaluation, to enable per‑user entitlements and data filters across all the objects derived from the Table.
* xref:abac_rls-variables.adoc#_verify_entitlements[Verifying entitlements] +
To ensure that data security rules are enforced dynamically and accurately, verify user entitlements and check whether they are translated into rules during query generation.

=== Limitations
The ABAC via tokens method requires the xref:trusted-authentication.adoc[trusted authentication] setup.
For indexing recommendations, see xref:abac-user-parameters.adoc#_indexing[Indexing].


////
=== Mandatory token filters

The `is_mandatory_token_filter: true` setting in object TML enforces that a filter rule must be provided for a specific column. When this attribute is set on a column in a Model, ThoughtSpot will deny all data access for users who do not have a corresponding filter rule for that column in their ABAC token.

When setting filter rules within the token, you must place the `is_mandatory_token_filter: true` property on every column in a Model where a filter rule is expected. This setting will deny any access to data if a user has not been assigned values for the expected set of fields.

[#column-name-warning]
The filter rules require passing the *exact* column name as defined in the Model. Otherwise, the values will not bind to any column. You must coordinate between the team that maintains the data objects and the team that builds the xref:trusted-auth-token-request-service.adoc[token request service] to know if any changes will be made to a Model and to ensure column names remain consistent. +
For this reason, end users of an embedded app must not be granted edit access to any Model using ABAC rules via tokens. Setting the `is_mandatory_token_filter: true` property on every column where a filter rule is expected ensures that no data is returned for users when column names change.

[NOTE]
====
If a column is set with both `is_hidden: true` and `is_mandatory_token_filter: true`, and filter conditions for that column are defined in the ABAC token, the filter will be applied as expected. The column will be hidden from the user interface, but the mandatory filter requirement will still be enforced, and data will be shown according to the filter values provided in the token.
====
////

== Create formula variables

To view the variables available on your instance, use the `POST /api/rest/2.0/template/variables/search` API call. If you want to create a new variable, use the `/api/rest/2.0/template/variables/create` API endpoint.

To configure formula variables for all Orgs on your instance or the Primary Org, cluster administration privileges are required. Org administrators can configure formula variables for their respective Orgs. Users with the `CAN_MANAGE_VARIABLES` (*Can manage variables*) role privilege can also create and manage variables for their Org context.

The `/api/rest/2.0/template/variables/create` API endpoint allows creating formula variables for the following data types:

* `VARCHAR`
* `INT32`
* `INT64`
* `DOUBLE`
* `DATE`
* `DATE_TIME`

During variable creation, specify the xref:variables.adoc#data_type[`data_type`].

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/]api/rest/2.0/template/variables/create' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "type": "FORMULA_VARIABLE",
  "name": "country_var",
  "is_sensitive": false,
  "data_type": "VARCHAR"
}'
----

The variable update API allows assigning variable values and setting the scope. For the ABAC implementation, administrators can set the variable values and scope when generating a JWT using the `/api/rest/2.0/auth/token/custom` API endpoint.

== Add RLS rules with variable references
To define RLS rules with variables for a Table:

. Navigate to the Data workspace and click the Table for which to define RLS rules.
. Click *Row security* and then click *+ Add row security*.
. In the *Row Security Editor*, define the rules. To reference the formula variable in the rule, use the `ts_var` function. For example, if you want to limit user access to data of a specific region, you can create a region-specific variable, assign values in the token request, and then add a rule on the underlying Table.

In this example, `country_var` is referenced in the RLS rule to limit user access to the country entitlement sent in the ABAC token.

----
country = ts_var('country_var')
----

The following examples show how to define RLS rules with formula  variables of different data types:

RLS rule with a single variable reference::

In the following examples, the formula references `region_var` and `country_var` variables. When the query is executed, the region will translate to the value defined for that variable, for example, West or EMEA. Similarly, `country_var` translates to the value specified for that variable.

+
----
region = ts_var('region_var')
----
+
----
country = ts_var('country_var')
----
+
The rule is translated to a filter, so only the rows that match the specified condition are displayed to the user.

RLS rules with multiple variables::

The RLS rules support the `AND` operator, which means that you can combine multiple conditions in a single RLS rule, so that a row is accessible only if all specified conditions are met.

----
Country = ts_var('country_var') AND Department = ts_var('dept_var')
----

----
Region = ts_var('region_var') AND Product_Type = ts_var('product_type_var')
----

Wildcard “show all” via variables::
In this example, if the user’s region variable is set to `TS_WILDCARD_ALL`, they see all regions; otherwise, only their entitled region.

----
ts_var('region_var') = 'TS_WILDCARD_ALL' OR Region = ts_var('region_var')
----

Group override rule with variable-based check::
In any security formula you build, you may want a clause that gives access to all data to certain groups. In the rule definition, you can include system variables, such as `ts_groups`, to build your preferred logic:

In this example, users in the "data developers" group see all data; others are filtered by their department entitlement.

----
'data developers' in ts_groups OR Department = ts_var('dept_var')
----

Variables with numeric and Date data type::

----
Revenue <= to_double(ts_var('revenue_cap_var'))
----

----
(date_column >= ts_var('start_date_var')) AND (date_column <= ts_var('end_date_var'))
----

[NOTE]
====
Formula variables with BOOLEAN and TIME data types are not supported.
====

== Create an ABAC token request with variable attributes

To generate a token with formula variable attributes, send a `POST` request to the `POST /api/rest/2.0/auth/token/custom` API endpoint.

The variable attributes defined in the token request take effect only if they are referenced in an RLS rule. If the variables are not used in any formula or RLS rule, they will have no impact on data access. Before generating the request with variable attributes, ensure the xref:abac_rls-variables.adoc#_add_rls_rules_with_formula_variables_to_tables[variables are added to the RLS rules] on the Table.

In the token request, include the following properties along with the `username`, xref:trusted-auth-secret-key.adoc[`secret_key`]:

* `variable_values`
* `persist_option`

Optionally, you can specify the `objects` and `org_identifier` to set the scope of access control.

=== Variable values

The `variable_values` array requires the following parameters:

* `name` +
_-String__. Name of the formula variable. The formula variable referenced on the token request must be available in ThoughtSpot and included in the RLS rule.
* `values` +
__Array of string or numeric values__. When assigning values, ensure that the value matches the data type set for the variable during creation. If you are adding a variable to filter by country, you can specify the string values as shown here:

[source,JSON]
----
variable_values": [
    {
      "name": "country_var",
      "values": [
        "Japan",
        "Singapore",
        "Australia"
      ]
    }
  ]
----

All values are passed into the token as *arrays of strings*, even if the column is a numeric or date type in ThoughtSpot and the database. The column data type will be respected in the query issued to the database.

==== Allow all values by default

To allow all values by default, specify `["TS_WILDCARD_ALL"]` as the variable value to grant access to all values in a given column.

A user might be entitled to all access for one variable, while for other variables, you can set values to apply restrictions.

[source,JSON]
----
"variable_values": [
    {
      "name": "country_var",
      "values": [
        "Japan",
        "Singapore",
        "Australia"
      ]
    },
    {
      "name": "dept_var",
      "values": [
        "Sales",
        "Marketing"
      ]
    },
    {
      "name": "product_type_var",
      "values": [
        "TS_WILDCARD_ALL"
      ]
    }
  ]
----

If `TS_WILDCARD_ALL` is set, ensure that the RLS rules are defined clearly on the Table to avoid unintended data exposure.

==== Deny all by default
For every variable you include in the request, you can assign a value or a list of values. If you do not assign a value for a variable, during query generation, the RLS rules for that variable will generate errors indicating that a mandatory variable has not been defined.

=== Persist options and session-based rules

Variable attributes must be *persisted* for them to apply to user sessions when using xref:trusted-authentication.adoc#cookie[cookie-based trusted authentication] or scheduled reports. To specify whether variable attributes and rules should persist for user sessions, you must define the `persist_option` parameter.

The ABAC implementation with formula variables and RLS does not support session-based ABAC rules, so we do not recommend setting the `persist_option` attribute to `NONE`.

To append or replace the attributes, use the following options:

* `APPEND`  +
Adds the attributes defined in the API request to the user properties. These properties will be applied to current and future user sessions and the scheduled reports, until they are explicitly changed through a token update request.

* `REPLACE` +
Replaces existing variable assignments with the new values.

 If you don’t want to append or replace any attributes, do not pass any variable values in the token update request.

[NOTE]
====
* If you don't want to append or replace any attributes, do not pass any variable values in the token update request.
* Passing an empty array does not reset the attributes.
* Resetting attributes via `"persist_option": "RESET"` is not supported.
====

=== Variable scope
To restrict the scope of the variable attributes and rules to a specific Org context and  object, define the `org_identifier` and `objects`.

==== Apply to specific objects
To apply variable entitlements to a specific object, specify the object IDs in the `objects` array as shown in this example:

[source,JSON]
----
"objects": [
   {
     // example of the format
     "type": "{OBJECT_TYPE}",
     "identifier": "{id or name of the object}"
   },
   {
     "type": "LOGICAL_TABLE",
     "identifier": "9b751df2-d344-4850-9756-18535797378c"
   }
]
----

[NOTE]
====
The only supported object types for data security are logical tables. By default, the API sets `LOGICAL_TABLE` as the `type`.
====

If the object ID is not specified, the variable values will be applied to the variables referenced in the RLS rules for all `LOGICAL_TABLE` objects derived from the Table on which the rules are defined, within the Org context for the user during token generation.

==== Apply to Org context
To limit the scope of the variable entitlements to the objects with an Org, specify the ID of the Org in the `org_identifier` attribute.

When Org ID is defined, the API sets the scope of the token and user entitlements to the specified Org context. For the variable attributes to take effect, the Table with RLS rules and the objects derived from the Table must also be available in the same Org context.

=== Example request body

The following example shows the request body for generating a token with formula variable attributes:

[source,cURL]
----
 curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/custom'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "UserA",
  "validity_time_in_sec": 300,
  "persist_option": "APPEND",
  "auto_create": true,
  "secret_key": "f8aa445b-5ff1-4a35-a58f-e324133320d5",
  "variable_values": [
    {
      "name": "country_var",
      "values": [
        "Japan",
        "Singapore",
        "Australia"
      ]
    },
    {
      "name": "dept_var",
      "values": [
        "Sales",
        "Marketing"
      ]
    },
    {
      "name": "product_type_var",
      "values": [
        "TS_WILDCARD_ALL"
      ]
    }
  ],
  "objects": [
    {
      "type": "LOGICAL_TABLE",
      "identifier": "35aa85fe-fbb4-4862-a335-f69679ebb6e0"
    }
  ]
}'
----

If the request is successful, ThoughtSpot generates a token and sends the  token details in the API response.

[NOTE]
====
ABAC details are sent in a JWT that can be used as a bearer token for cookieless trusted authentication, REST API calls, or as a sign-in token to start a session. JWTs are compressed by default to handle large payloads. It is recommended to keep the compression enabled to ensure all JWT tokens can get properly interpreted by the application regardless of their size, and to obfuscate the values passed in the JWT payload. If you want to disable it, contact ThoughtSpot Support.
====

=== Verify the variable assignment

To verify the variable assignment, use the `POST /api/rest/2.0/users/search` API call and check `variable_values` in the user properties in the API response.

[source,JSON]
----
//...
{
  "variable_values": {
    "821119045": {
      "ALL": {
        "variable_values": [
          {
            "name": "country_var",
            "values": [
              "Japan",
              "Singapore",
              "Australia"
            ]
          },
          {
            "name": "dept_var",
            "values": [
              "Sales",
              "Marketing"
            ]
          }
        ]
      }
    }
  }
}
----

To verify the security entitlements, start a user session using the JWT and inspect the generated SQL for your query or visualization.

== Verify the entitlements
To verify the entitlements:

. Log in to ThoughtSpot and start the user session with the ABAC token.
. Access a Liveboard, Saved Answer, or start a new search query.
. Inspect the generated SQL for your query or visualization.
. Verify if only permitted rows are displayed.
. Check if data is returned if no variable values are defined.
. Repeat the steps for different variable assignments to confirm the RLS rule is enforced as expected for all scenarios.

== Indexing
Several features within ThoughtSpot, such as autocompletion in Search on values within columns or the suggestions in *Explore* mode, use ThoughtSpot indexing. Due to the runtime nature of ABAC tokens, ThoughtSpot indexing will not be restricted by the values supplied in a token. This means the indexed columns may expose values in search suggestions or autocompletion that a user should not see, even if ABAC filters would block access to the underlying data. To prevent this, you can do one of the following:

* Disable indexing for columns and fields that must be restricted by ABAC. You may also want to disable indexing on all sensitive columns.
* Define an RLS rule on those fields, since RLS is enforced at the indexing layer and will secure suggestions and sample values.

== Additional resources

* For information about variables and variable APIs, see https://docs.thoughtspot.com/cloud/latest/rls-variables-reference and xref:variables.adoc[Variable APIs].
* For information about RLS rule definitions, see link:https://docs.thoughtspot.com/cloud/latest/security-rls[RLS rules documentation, window=_blank].
