= ABAC via token
:toc: true
:toclevels: 1

:page-title: ABAC via token
:page-pageid: abac-user-parameters
:page-description: Attribute-based access control pattern can be achieved via user parameters sent in the login token

Attribute Based Access Control (ABAC) is a pattern where security entitlements are sent in as lists of attributes at session creation time via the auth service.

[IMPORTANT]
====
[#beta-warning]
RLS using ABAC via tokens is a BETA feature. ThoughtSpot is working on improvements in upcoming releases that will change the best practice recommendations below, and will result in needed re-work of the security architecture of your deployment. We recommend reaching out to ThoughtSpot to discuss RLS best practices for your specific use case and deployment timelines.
====

Currently the ABAC via tokens method *requires using xref:trusted-authentication.adoc[trusted authentication]* and using link:https://docs.thoughtspot.com/cloud/latest/worksheet-create[worksheets, target=_blank] as data sources for Liveboards and answers, rather than individual table objects.

You can to pass in Runtime Filters and Parameters for a user via their login token. Both features work like the Runtime Filters and Parameters available within the Visual Embed SDK, but values set via token cannot be overriden by any user action within the ThoughtSpot UI.


== Token request
The ABAC message to ThoughtSpot is encoded in JSON Web Token (JWT) format, using the existing ThoughtSpot V2.0 REST API Access Tokens (which are OAuth JWT tokens). 

The token can be used as a bearer token for Cookieless Trusted Auth or REST API access or as a sign-in token to create a ThoughtSpot session, in which case the ABAC user parameters should be *persisted*.

=== ABAC capabilities
In ThoughtSpot 9.11+, three features are available to set via the login token:

1. *Runtime filters*: can filter *multiple values* of any data type. Binds to any Column in any Data Source with a matching Column Name (ThoughtSpot property, not underlying database table column name). 
2. *Parameters*: binds a *single value* to any Parameter in any Worksheet by Parameter Name and Type Match
3. *Runtime sorts*: overrides to sort order within columns

=== Request format
The ABAC request is sent using the `user_parameters` key of the link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Fget-full-access-token[V2.0 Full Access Token request, target=_blank]. 

There are three potential keys within `user_parameters`, each taking an array of objects:
[code,javascript]
----
...
"user_parameters": {
   "runtime_filters": [],
   "parameters" : [],
   "runtime_sorts": []
}
----

The format for the objects in each section follow the equivalent formats in the Visual Embed SDK for xref:runtime-filters.adoc[runtime filters], xref:runtime-parameters.adoc[runtime parameters] or xref:runtime-sort.adoc[runtime sorts]. 

There is a `persist` key to be added on each object that takes boolean `true` or `false`. This determines if the values are persisted at the user level beyond just the token itself, for features such as alerts and subscriptions that run outside of a user's session.

*You must persist values for them to apply when using xref:trusted-authenication.adoic#_cookie_based_vs_cookieless_authentication[cookie-based trusted authentication]*.

[code,javascript]
----
"user_parameters": {
   "runtime_filters": [
      {
        "column_name": "Region",
        "operator": "IN",
        "values": ["West", "Southwest"],
        "persist": false
      },
      {
        "column_name": "Product Type",
        "operator": "IN",
        "values": ["Shirts", "Swimwear"],
        "persist": true
      }
    ],
    "parameters": [
      {
        "name": "Secured",
        "values": ["rxzricmwfe87q7bh7jyg"],
        "persist": true
      }
    ]
  }
----

== Implementing RLS with ABAC via tokens
The best practice pattern for RLS using ABAC via tokens is *runtime filters + a shared secret 'check parameter'*. 

To make sure that no data shows if a properly-built token is not used to start the user session, you need to send a 'check parameter' along with the runtime filters. If the 'check parameter' value from the token does not match the value defined in the worksheet formula (the *shared secret*), the formula + filter combination blocks any data from showing for the user.

Parameters are currently single-value, so you'll need to use Runtime Filters to restrict on multiple values on a given field.

However, the way to set a runtime filter to *show all values* is to not send in any runtime filter at all for that column. Without additional information, it's impossible to know if the lack of a runtime filter is intentionally or the filter was not set via the token at all.

=== Building the ABAC token request
Two parts to the ABAC request:

1. Runtime filters defining multi-value conditions on columns
2. The *shared secret* to go into the 'check parameter' 

==== Creating runtime filter definitions
The value of the ABAC pattern is that you can send different combinations of filters for different types of users.

*Runtime filters match on the name property of a column*

==== Setting the 'check parameter' to the shared secret
The *shared secret* is just a long string value that cannot be easily guessed or determined programmatically. You can generate these values randomly - and the end user will never see it, only the worksheet editor if they look at the formula.

The description for how to set up the appropriate set of worksheet parameters, formulas and filters for the 'check parameter' to provide security are in the section below.

All that is required within the token request service is that the same *shared secret* defined within the worksheet formula is being sent with the appropriate 'check parameter' name.

If the parameter is named `Secured` and the *shared secret* value is `rxzricmwfe87q7bh7jyg`, then the `parameters` section of the token request will look like:

[code,javascript]
----
"parameters": [
   {
     "name": "Secured",
     "values": ["rxzricmwfe87q7bh7jyg"],
     "persist": true
   }
]
----

=== Using parameters to filter a worksheet
The basic pattern for using a parameter to filter a worksheet is:

1. Create link:https://docs.thoughtspot.com/cloud/latest/parameters-create[parameter, target=_blank] in worksheet
2. Make link:https://docs.thoughtspot.com/cloud/latest/formulas[formula, target=_blank] that evaluates the parameter's default value and the expected values from the token
3. Make link:https://docs.thoughtspot.com/cloud/latest/filters#_worksheet_filters[worksheet filter, target=_blank] based on the formula, set to *true*

link:https://docs.thoughtspot.com/cloud/latest/parameters-create[Parameters, target=_blank] are defined at the worksheet level within ThoughtSpot. Parameters have a data type and a default value set by the worksheet author.

To use a parameter, you'll make a link:https://docs.thoughtspot.com/cloud/latest/formulas[formula, target=_blank] on the worksheet. 

link:https://docs.thoughtspot.com/cloud/latest/filters#_worksheet_filters[Worksheet filters, target=_blank] can reference worksheet formulas once they have been created, which creates the security layer out of the result of the formula.


==== Defining the 'check parameter'
The simplest 'check parameter' pattern is a shared key string that is stored in both the xref:trusted-auth-token-request-service.adoc[token request service] and the *worksheet formula* used for the *worksheet filter*.

Parameters are always visible in the UI, even though a parameter set via a token can never be overridden by any action in the UI or using the Visual Embed SDK.

Thus the 'check parameter' and its default value should be named something that looks pleasant to end users. For example, if the parameter name is "Secured", you can set the default value to "✔️" or "true" or "yes" (any Unicode value is allowed, including emojis):

<<<image from Nico's workflow>>>

This will display on Liveboards and answers as:

<<<image from Nico's workflow>>>

==== Creating the 'worksheet security formula'
A parameter doesn't do anything on its own - you need a formula to evaluate the parameter's value.

The simplest formula for a 'check parameter' with shared key looks like:

`if ( check_parameter_name ) = 'shared-key-value' then true else false`

For example, if the 'check parameter' is called `Secured`, and the secret key value is a long-encoded string like `rxzricmwfe87q7bh7jyg`, the worksheet formula will be (parameter name are always lower-cased in formulas):

<<< image from Nico's workflow >>>

==== Setting a worksheet filter on the worksheet security formula


== Indexing
Several features within ThoughtSpot, such as autocompletion in Search on values within columns or the suggestions in Explore, use ThoughtSpot indexing. 

Due to the runtime nature of ABAC via tokens, ThoughtSpot indexing will not be restricted by the values supplied in a token. 

*You should turn of indexing for any field that needs to be restricted by RLS* when using ABAC via tokens for RLS.

