= ThoughtSpot REST APIs
:toc: true

:page-title: ThoughtSpot REST APIs
:page-pageid: rest-apis
:page-description: ThoughtSpot REST API provides service endpoints for administration, embedding, and data management.

The ThoughtSpot REST API framework lets you create, access, edit, and manage objects and resources in the ThoughtSpot system programmatically.

ThoughtSpot REST API supports several resource collections and operations in two distinct versions:

* REST API v1
+
The legacy framework with several endpoints to create, edit, administer and manage ThoughtSpot objects and data.

* REST API v2.0
+
The REST API v2.0 framework provides enhanced functionality and improved API experience with an interactive Playground.

For more information about the differences between these two REST API versions, see xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison].

== REST API Playground

ThoughtSpot users with Developer or Administrator privileges can access the REST API v1 and v2.0 endpoints in the *Develop* tab. The portal provides a separate Playground for each REST API version and lets you explore the API endpoints, request and response workflows.

* To try out the xref:rest-api-v1.adoc[REST API v1 endpoints], click **REST Playground v1**. +
* To access the xref:rest-api-v2.adoc[REST API v2 Playground], click **REST Playground v2.0**.

== Rate limits for API requests
To ensure API stability, optimize resource usage, and maintain service quality for all users, ThoughtSpot limits the number of public API requests allowed per client to prevent excessive requests from reaching application servers.

By default, on instances running 26.2.0.cl and later, a global rate limit of 100 requests per second per client IP is enforced at the cluster level for all public APIs. This limit is applied per client IP across all public APIs combined, not per endpoint. If a client IP exceeds this combined rate limit, a burst of 10 additional API requests is allowed before rejecting the requests with the 'HTTP 429: Too Many Requests' error.

For async status endpoints such as `/api/rest/2.0/metadata/tml/async/status`, up to 100 requests per minute per client IP are allowed, with a burst of 100 requests before requests are rejected with an HTTP 429 error.

These rate limits are enforced by default on all ThoughtSpot instances. Currently, rate limits are applied at the cluster level; Org-level rate limits are not supported.

ThoughtSpot administrators can monitor logs, add or update rate limits via TSCLI, and adjust these settings for different environments (dev or prod)  as required.

==  API endpoints
For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following reference pages:

* xref:rest-api-reference.adoc[REST API v1 Reference]
* xref:rest-api-v2-reference.adoc[REST API v2.0 Reference]

