= Access control and sharing
:toc: true
:toclevels: 1

:page-title: Access control and sharing
:page-pageid: access-control-sharing
:page-description: Access to content is controlled via sharing

Access control in ThoughtSpot is accomplished via *sharing* of content *authored* by one user to other users and groups.

In practice, administrators create specific *access control groups* to grant either *read-only* or *edit* access to content, then add users to the appropriate groups. This can be done via UI, but most often is automated via REST API or JIT provisioning during SSO.

Group membership also controls which users can see each other when sharing, through a property called *shareability*.

== Sharing model overview
The user who creates content always has access to the content they authored. Other users can only view and access content if it has been *shared* to a group they belong to, or to the user directly.

Ownership of content can be transferred by an administrator.


Users do not see the group that provides them access to a given piece of content (the same content could be shared to multiple groups they belong to, or to them directly as well).


ThoughtSpot users can share objects such as Liveboards, answers, tables, worksheets, and table columns. Users can set either `read-only` or `edit` permissions at the individual object level when sharing an object with another user or a user group. A user can automatically share objects with anyone else in the groups to which they belong.

When an object is shared, users can view all the data regardless of the permissions set at the parent object level. For example, a user can view a shared Liveboard without having access to its underlying Worksheet or table from which the visualizations in the Liveboard are built.

[NOTE]
====
If your application instance has classic Answer Experience enabled, administrators can restrict user access to Liveboards by selecting the *Cannot create or update Liveboards*  checkbox in the admin UI. Note that this feature is deprecated on clusters on which the New Answer Experience is enabled. ThoughtSpot recommends that you use the `disabledActions` and `hiddenActions` parameters in the Visual Embed SDK to define granular access. For more information, see xref:embed-actions.adoc[Show or hide actions].
====

== Sharing visibility

The Sharing visibility configuration allows users and groups to be set as *SHAREABLE* or *NOT SHAREABLE*.

For example, if _UserA_ is marked as *SHAREABLE*, other users can view _UserA_ in the *Share* dialog when they try to share an object.

Similarly, if a user group is set as *NOT SHAREABLE*, it does not appear in the *Share* dialog when a user tries to share an object.

[NOTE]
====
Avoid using the same group for sharing permissions and other privileges. Because a user can share with anyone in a group they belong to, they can potentially share restricted data.
====

== Sharing via UI
== Sharing via REST API
== Auditing access control

== Transferring content ownership

