= Audit logs
:toc: true
:toclevels: 2

:page-title: Audit logs
:page-pageid: audit-logs
:page-description:  Fetch a log of security audit events to detect potential threats

ThoughtSpot cloud deployments allow you to collect security audit events and .
ThoughtSpot Cloud logs events related to user activities, account authentication, and CRUD operations. Administrators can use thi event log detect potential security threats or compromised user accounts in an organization.

To fetch security events from ThoughtSpot, you can link:https://docs.thoughtspot.com/cloud/latest/audit-logs#_push_to_your_siem_server[push the logs to your Security information and event management (SIEM) server, window=_blank], or xref:audit-logs.adoc#_fetch_logs_via_api[pull the logs via audit logs REST API].


== Contents of a security audit event

Audit events in the security logs capture the following information.

* `type` +
Type of the action audited. For example, `LOGIN_FAILED`
* `desc` +
Description of the event. For example, `User login failed`.
* `ts` +
Timestamp of the event
* `id` +
ID of the event
* client +
A map of key-value pairs that show client information such as `userName`, `userGUID`, and `cIP`.
Name and GUID of the user that initiated the action audited in the log.
* `data` +
A collection of string key value pairs which are specific to the action. +

** For events related login and authentication, the `data` string includes the username of the user.
`{"data":{"userName":"UserA"}`
** For events related to CRUD operations on objects, the object ID and name are included in the data string. +
`{"data":{"modifiedPrivileges":["AUTHORING"],"currentPrivileges":[],"groupIdentity":{"id":{"id":"f60c79e9-2be0-4321-959c-fe1c09590780"},"name":"testGroup","owner":{"id":"f60c79e9-2be0-4321-959c-fe1c09590780"},"type":"UserGroup"}}`
+
`{"data":{"pinboardIds":"[\"f9ab90a9-b895-41f4-a244-8dce3f48d24a\"]"}`

** For events related to errors, the data string shows the error code and message. +
`{"data":{"error":"Error Code: WEAK_PASSWORD_CANNOT_USE_FIRST_LAST_NAME Incident Id: 51a9474b-f13c-44ab-8c48-e35c773a5911\
Error Message: Cannot use first or last name in the password.","userId":"e3dc4950-0677-45f9-9b2d-ffb16501c359"}`
* `orgId` +
Org ID if your ThoughtSpot application instance has Orgs.

== Security events list

include::{path}/security-events.adoc[]

== Fetch logs via API
To fetch logs via REST API, you need `ADMINISTRATION` privileges. You can use any of the following APIs:

* xref:logs-api.adoc[GET /tspublic/v1/logs/topics/{topic}] (REST API v1)
* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Flog%2Ffetch-logs">POST /api/rest/2.0/logs/fetch</a>+++ (REST API v2)

On Orgs-enabled clusters, the API fetch security logs for the current Org text. However, the administrator of the primary Org (Org 0) can fetch logs not just for the primary Org, but also for all other Orgs if the `get_all_logs` parameter to `true` in the API request.
