= REST API v2.0 authentication
:toc: true
:toclevels: 3

:page-title: User authentication and session management
:page-pageid: api-authv2
:page-description: REST v2 APIs support basic and token-based authentication methods.

The REST API v2.0 framework supports the following types of authentication:

Token-based authentication::
In this method, the REST clients obtain an authentication token from ThoughtSpot and use this token in their subsequent API calls to authorize their requests.
The token authentication endpoints allow REST client to generate a token with either a `username` and `password`, or a `username` and `secret_key`. For trusted authentication and custom tokens for ABAC, use the `username` and `secret_key` parameters. For more information, see xref:authentication.adoc#_token_generation_endpoints[Token generation endpoints].

Basic authentication/Local authentication::
In this method, the REST client sends an API request to the xref:restv2-basic-auth.adoc[`api/rest/2.0/auth/session/login`] endpoint with the `username` and `password`. +
This method also referred to as cookie-based authentication, because the client session is assigned a cookie upon successful login. This session cookie is used to authenticate the client in subsequent API calls.

Multi-factor authentication;;
ThoughtSpot supports link:https://docs.thoughtspot.com/cloud/latest/authentication-local-mfa[multifactor authentication (MFA), window=_blank] for environments using local authentication with Identity and Access Management (IAMv2).
+
If MFA is enabled on your ThoughtSpot instance, API requests with `username` and `password` parameters to the login and authentication endpoints will return an error. With MFA enabled, users must provide the additional authentication factor to log in to ThoughtSpot. Currently, there is no mechanism to pass the second factor via the standard API login endpoint, therefore the API request will not be successful. For login assistance and further guidance, contact link:https://community.thoughtspot.com/customers/s/login/?ec=302&startURL=%2Fcustomers%2Fs%2Fcontactsupport[ThoughtSpot Support, window=_blank].
+
If you are using the login API endpoint in your ThoughtSpot Embedded application workflow, consider switching to token-based authentication method such as `AuthType.TrustedAuthTokenCookieless`.

//Non-embedded users calling REST APIs authenticating to ThoughtSpot with only `username` and `password` will return an error. Users must provide the additional authentication factor as configured. Contact https://community.thoughtspot.com/customers/s/login/?ec=302&startURL=%2Fcustomers%2Fs%2Fcontactsupport[ThoughtSpot Support] for assistance.


//Users can also xref:authentication.adoc#_basic_authentication[Basic authentication]. In this method, a REST client sends the `username` and `password` to authenticate to ThoughtSpot and obtains a token.

== Token-based authentication

ThoughtSpot provides different REST API endpoints for developers and administrators to issue authentication tokens to end users. Each endpoint helps developers achieve slightly different use cases:

[cols="2,4", options="header"]
|=====
|Token type|Purpose and API endpoint
|Full access token| **API endpoint**: `POST /api/rest/2.0/auth/token/full` +

**Use case**: Authenticates users with standard row level security(RLS) rules and object permissions, administered via the user's properties and their group memberships. +

**Example**:
Authenticate a user via Trusted Auth, without any particular need for RLS.
|Custom access token|**Use case**: Assigns variable values to users when authenticating them, enabling ABAC via RLS rules when logging users in ThoughtSpot. +

**API endpoint**:`POST /api/rest/2.0/auth/token/custom` +

**Example**: Authenticate a user, and define RLS values on tables such that the user can only access data for specific regions in ThoughtSpot on when logged in to ThoughtSpot using the token. +

|Object access token | **Use case**: Assigns a subset of objects to a user for a given session. This object list is intersected with the list of the objects that the user has been permitted to view or edit via group membership. +

**API endpoint**: `POST /api/rest/2.0/auth/token/object` +

**Example** : Authenticate a user who usually can see Liveboards A, B, and C, but for the context of that session, solely give access to liveboard “A”.
|=====

=== Recommendations

* ThoughtSpot recommends using the `Full Access Token` for users, unless there is a need to set up ABAC via RLS, in which case, custom JWT token is required.
* For centralized control of object access and to restrict user access to specific objects, ThoughtSpot recommends using the link:https://docs.thoughtspot.com/cloud/10.15.0.cl/security-data-object#object_security[Object security, window=_blank] method.

==== Important points to consider
ThoughtSpot also allows developers to pass context, or update the experience of an end user via the Visual Embed SDK. Updating the context of the embedded object is not data security.

For example, a developer may choose to restrict data access for a user so they only see data for `country="United States"`. This is row-level security rule which should be implemented via the RLS feature. If needed, values passed for RLS can be updated via a custom access token.

However, this user may need to be shown data for `state = California`, or `product category = jeans` in ThoughtSpot, so the analysis conducted in ThoughtSpot matches the context of the host application. To accommodate this use case, developers can update the xref:filters_overview.adoc[Liveboard filters, runtime filters, or parameters] via the SDK. For more information on filters, see xref:filters_overview.adoc[Filters overview].

A clear distinction must be made between RLS and context update via HostEvents, runtime filters, and parameter updates.

[cols="2,2,2", options="header"]
|===
|RLS, and ABAC via RLS through a custom access token |Programmatically set Liveboard filter, runtime filter, or Parameter values |

| Security feature
| ✅
| ❌ (These filtering mechanisms are NOT secure)

| Appropriate for context updates
| ❌ (Once the security rules are set, they are fixed for at least that user’s session. As a result, this is not adapted to quickly updating a user’s context throughout a session.)
| ✅
|===

=== Generate a full access token
To generate a full access token, send a `POST` request to the `/api/rest/2.0/auth/token/full` API endpoint with the required attributes.

You can generate a token by providing a `username` and `password`, or by using a `secret_key`. To generate a `secret_key`, the administrator must enable xref:trusted-auth-secret-key.adoc[trusted authentication] on the **Develop** > **Customizations** > **Security Settings** page.

After ThoughtSpot issues an authentication token, the user must include the token in the `Authorization` header of their subsequent API requests.

[NOTE]
====
* When both `password` and `secret_key` are included in the API request, `password` takes precedence.
* If link:https://docs.thoughtspot.com/cloud/latest/authentication-local-mfa[Multi-Factor Authentication (MFA), window=_blank] is enabled on your instance, the API login request with `username` and `password` returns an error. You can switch to token-based authentication with  `secret_key` or contact ThoughtSpot Support for assistance.
====

==== API request with username and password
To get an access token that grants full access to ThoughtSpot, send a `POST` request with `username`, `password`, and other attributes to the `/api/rest/2.0/auth/token/full` endpoint:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|`username`
|__String__. Username of the ThoughtSpot user.
|`password`
|__String__. Password of the user account.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If no value is specified, the token is generated for the Primary Org (Org 0).
|`validity_time_in_sec` +
__Optional__|__Integer__. Token validity duration in seconds. By default, the token is valid for 5 minutes. You can set the token expiry duration to a higher value. API requests with an expired or invalid token result in an error. In such cases, REST clients must obtain a new token from ThoughtSpot and use it in their subsequent API calls.
||
|=====

===== Example request

.cURL
[sourc,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/full' \
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "password": "Guest123!",
  "org_id": 1,
  "validity_time_in_sec": 86400
}'
----

===== Example response
If the API request is successful, ThoughtSpot returns the authentication token that grants full application access.

[source,JSON]
----
{
  "token": "{AUTH_TOKEN}",
  "creation_time_in_millis": 1675129264089,
  "expiration_time_in_millis": 1675129564089,
  "scope": {
    "access_type": "FULL",
    "org_id": 1,
    "metadata_id": null
  },
  "valid_for_user_id": "59a122dc0-38d7-43e7-bb90-86f724c7b602",
  "valid_for_username": "tsUserA"
}
----

[#trusted-auth-v2]
=== API request with username and secret key
To obtain an authentication token for a user, include `username` and `secret_key` in the API request. In trusted authentication implementation, you can request tokens on behalf of users who require access to the ThoughtSpot content embedded in a third-party application.

To request a token on behalf of another user, you need administrator privileges and a `secret key` that allows you to securely pass the authentication details of an embedded application user. The `secret key` is generated xref:trusted-authentication.adoc#trusted-auth-enable[when Trusted authentication is enabled on a ThoughtSpot instance].

//The token issued from ThoughtSpot can be used to log in a user. By default, the token is valid for 300 seconds and the token expiration duration is configurable. Note that the token is necessary only during the login process, after which any request to ThoughtSpot will include session cookies identifying the signed-in user.

To get a trusted authentication token that grants full access to ThoughtSpot, send a `POST` request with `username`, `secret_key`, and other attributes to the `/api/rest/2.0/auth/token/full` endpoint:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|  Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, you can set the `auto_create` parameter to `true` to create a user just-in-time(JIT).
|`secret_key`
|__String__. The secret key string generated for your ThoughtSpot instance. The secret key is created xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled] on your instance.
|`validity_time_in_sec` +
__Optional__| __Integer__. Token expiry duration in seconds. The default duration is 300 seconds. You can set the token expiry duration to a higher value. API requests with an expired or invalid token result in an error. In such cases, REST clients must obtain a new token from ThoughtSpot and use it in their subsequent API calls.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If no value is specified, the token is generated for the Primary Org (Org 0).
|=====

===== Example request

The following example shows the request body with `username` and `secret_key`:

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://stage-grapes-champagne.thoughtspotstaging.cloud/api/rest/2.0/auth/token/full'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "org_id": 1,
  "validity_time_in_sec": 300,
  "auto_create": false,
  "secret_key": "2657f6f9-6aa9-4432-99f2-bf0d70f240ac"
}'
----

===== Example response
If the API request is successful, ThoughtSpot returns the authentication token that grants access to the metadata object specified in the request.

[source,JSON]
----
{
   "token":"{AUTH_TOKEN}",
   "creation_time_in_millis":1675163671270,
   "expiration_time_in_millis":1675163971270,
   "scope":{
      "access_type":"FULL",
      "org_id":1,
      "metadata_id":null
   },
   "valid_for_user_id":"fd873d1e-11cc-4246-8ee2-78e78d2b5840",
   "valid_for_username":"tsUserA"
}
----

=== Get object access token
The object access token grants read-only access to a specific ThoughtSpot metadata object, as defined by the `object_id` property in the request. This token can be used to authorize API requests that need access only to that particular object, not the full application.

You can obtain a token that grants read-only access to a ThoughtSpot metadata object via a `POST` request to the `/api/rest/2.0/auth/token/object` endpoint.

==== API request with username and password
To get a token that grants read-only access to a ThoughtSpot metadata object, send a `POST` request with `username`, `password`, `object_id`, and other attributes to the `/api/rest/2.0/auth/token/object` endpoint:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|  Description
|`username`
|__String__. Username of the ThoughtSpot user.
|`password`
|__String__. Password of the user account.
|`object_id`
|__String__. GUID of the ThoughtSpot object.
The token obtained from this API request grants `Read-Only` access to the specified object.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If no value is specified, the token is generated for the Primary Org (Org 0).
|`validity_time_in_sec` +
__Optional__|__Integer__. Token validity duration in seconds. By default, the token is valid for 5 minutes.
|=====

===== Example request

.cURL
[sourc,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/object' \
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "org_id": 1,
  "validity_time_in_sec": 86400,
  "auto_create": false,
  "password": "Guest123!"
  "object_id": "fa68ae91-7588-4136-bacd-d71fb12dda69"
}'
----

===== Example response
If the API request is successful, ThoughtSpot returns the authentication token that grants access to the metadata object specified in the request.

[source,JSON]
----
{
  "token": "{AUTH_TOKEN}",
  "creation_time_in_millis": 1675129264089,
  "expiration_time_in_millis": 1675129564089,
  "scope": {
    "access_type": "REPORT_BOOK_VIEW",
    "org_id": 1,
    "metadata_id": "e65d7d3b-c934-4a59-baa1-d5cb7b679cc9"
  },
  "valid_for_user_id": "59a122dc0-38d7-43e7-bb90-86f724c7b602",
  "valid_for_username": "tsUserA"
}
----

==== API request with username and secret key

To get a token that grants a `READ-ONLY` access to a specific metadata object, send a `POST` request with `username`, `secret_key`, `object_id`, and other attributes to the `/api/rest/2.0/auth/token/object` endpoint:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, you can set the `auto_create` parameter to `true` to create a user just-in-time (JIT).

|`secret_key`
|__String__. The secret key string generated for your ThoughtSpot instance. The secret key is created xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled] on your instance.

|`object_id`
|__String__. GUID of the ThoughtSpot object.
The token obtained from this API request grants `Read-Only` access to the specified object.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If no value is specified, the token is generated for the Primary Org (Org 0).
|`validity_time_in_sec` +
__Optional__| __Integer__. Token expiry duration in seconds. The default duration is 300 seconds.
|=====

===== Example request

The following example shows the request body with `username`, `secret_key`, and `object_id`:

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/object' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "org_id": 1,
  "object_id": "061457a2-27bc-43a9-9754-0cd873691bf0",
  "secret_key": "69fb6d98-1696-42c0-9841-22b078c04060",
}'
----

===== Example response
If the API request is successful, ThoughtSpot returns the authentication token that grants access to the metadata object specified in the request.

[source,JSON]
----
{
   "token":"{AUTH_TOKEN}",
   "creation_time_in_millis":1675162190374,
   "expiration_time_in_millis":1675162490374,
   "scope":{
      "access_type":"REPORT_BOOK_VIEW",
      "org_id":1,
      "metadata_id":"061457a2-27bc-43a9-9754-0cd873691bf0"
   },
   "valid_for_user_id":"fd873d1e-11cc-4246-8ee2-78e78d2b5840",
   "valid_for_username":"tsUserA"
}
----






===== Response codes

[width="100%" cols="2,4"]
[options='header']
|=====
|HTTP status code|Description
|**204**
|Successful logon
|**400**
|Bad request +
Invalid parameter
|**401**
|Unauthorized success
|**403**
|Forbidden access
|**500**
|Operation failed
|=====






Trusted authentication allows an authenticator service to request tokens on behalf of users who require access to the ThoughtSpot content embedded in a third-party application.

The token issued from ThoughtSpot can be used to log in a user. By default, the token is valid for 300 seconds and the token expiration duration is configurable. Note that the token is necessary only during the login process, after which any request to ThoughtSpot will include session cookies identifying the signed-in user.

To request a token on behalf of another user, you need administrator privileges and a `secret key` that allows you to securely pass the authentication details of an embedded application user. The `secret key` is generated xref:trusted-authentication.adoc#trusted-auth-enable[when Trusted authentication is enabled on a ThoughtSpot instance].

==== Get a token for full access

To get an access token that grants full access to ThoughtSpot, send a `POST` request with `username`, `secret_key`, and other attributes to the `/api/rest/2.0/auth/token/full` endpoint:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|  Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, you can set the `auto_create` parameter to `true` to create a user just-in-time(JIT).
|`secret_key`
|__String__. The secret key string generated for your ThoughtSpot instance. The secret key is created xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled] on your instance.
|`validity_time_in_sec` +
__Optional__| __Integer__. Token expiry duration in seconds. The default duration is 300 seconds.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If no value is specified, the token is generated for the Primary Org (Org 0).
|=====

===== Example request

The following example shows the request body with `username` and `secret_key`:

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://stage-grapes-champagne.thoughtspotstaging.cloud/api/rest/2.0/auth/token/full'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "org_id": 1,
  "validity_time_in_sec": 300,
  "auto_create": false,
  "secret_key": "2657f6f9-6aa9-4432-99f2-bf0d70f240ac"
}'
----

===== Example response
If the API request is successful, ThoughtSpot returns the authentication token that grants access to the metadata object specified in the request.

[source,JSON]
----
{
   "token":"{AUTH_TOKEN}",
   "creation_time_in_millis":1675163671270,
   "expiration_time_in_millis":1675163971270,
   "scope":{
      "access_type":"FULL",
      "org_id":1,
      "metadata_id":null
   },
   "valid_for_user_id":"fd873d1e-11cc-4246-8ee2-78e78d2b5840",
   "valid_for_username":"tsUserA"
}
----

===== Response codes
[width="100%" cols="2,4"]
[options='header']
|=====
|HTTP status code|Description
|**204**
|Successful logon
|**400**
|Bad request +
Invalid parameter
|**401**
|Unauthorized success
|**403**
|Forbidden access
|**500**
|Operation failed
|=====

[#_get_tokens_with_custom_rules_and_filter_conditions]
== Generate a custom token for ABAC implementation
To get a token with security entitlements encoded in JSON Web Token (JWT) format for a user, use the `/api/rest/2.0/auth/token/custom` API endpoint. This API allows administrators to generate a token with a specific attributes such as variable values for the formula variables referenced in Row-level security (RLS) rules, and thus allow ThoughtSpot administrators and developers to implement Attribute-Based Access Control(ABAC) via RLS.

For more information about the API requests and ABAC implementation, see xref:abac_rls-variables.adoc[Attribute-Based Access Control(ABAC) via RLS].

////
==== API request parameters

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, a new user account will be created and added to ThoughtSpot.
|`password`
a|__String__. Password of the user account. If using `secret_key` to generate the token, do not specify the `Password`. +
If MFA is enabled on your ThoughtSpot instance then API call with only `username` and `password` will return an error.
|`secret_key`
|__String__. The secret key string provided by the ThoughtSpot server. ThoughtSpot generates this secret key xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled].
|`validity_time_in_sec` +
__Optional__| __Integer__. Token expiry duration in seconds. The default duration is 300 seconds.
|`org_id` +
__Optional__|__Integer__. If the Orgs feature is enabled on your instance, specify the ID of the Org for which you want to generate the authentication token. If an Org ID is not specified, the token is generated for the Primary Org (Org 0).
|`persist_option` a| Indicates if the filter rules and Parameter attributes defined in the API request should persist for user sessions initiated with the token obtained from this API call. The following options are available:

* `APPEND` +
Adds the attributes defined in the API request to the user properties. These properties will be applied to user sessions and for scheduled jobs if any.

* `NONE` +

Does not update the existing user properties. The attributes defined in the API request will be applied to the token, but do not persist when the token expires.

* `REPLACE` +
Available from 10.5.0.cl. Replaces existing user properties of the user with the new attributes assigned to the token in the API request.

* `RESET` +
Resets the existing user properties upon token generation and adds the new attributes defined in the request. By default, `"persist_option": "RESET"` resets all attributes



|`filter_rules`  a|__Array of filter rules__. An array of runtime filter conditions to pass via token. Each rule in the array must include the following information:

* `column_name` +
Name of the column in the data source object (Model).
* `operator` +
Filter operator to use. For a complete list of supported operators, see xref:runtime-filters.adoc#rtOperator[filter operators].
* `values` +
The values to filter on. To get all records, use `TS_WILDCARD_ALL` .

[source,JSON]
----
  "filter_rules": [
    {
      "column_name": "Customer ID",
      "operator": "EQ",
      "values": [
        "492810"
      ]
    },
    {
      "column_name": "Item type",
      "operator": "EQ",
      "values": [
        "Jackets"
      ]
    }
  ]
----

|`parameter_values` a| __Array of Parameter values__. Parameter rules to apply. Each rule in the array must include the following attributes:

* `name` +
Name of the column in the data source object (Model)
* `value` +
The values to use.

[source,JSON]
----
"parameter_values": [
    {
      "name": "Discount",
      "values": ["20"]
    },
    {
      "name": "DATE,
      "values": ["1656914873"]
    }
  ]
----
|`objects` +
__Optional__ a|__Array of strings__. An array of object names or GUIDs to which you want to apply the security rules. The object `type` is mandatory if the object `name` is specified as the `identifier`. Specify the object type as `LOGICAL_TABLE`.

If no object is specified in the API request, the filter and Parameter rules will be applied to all `LOGICAL_TABLE` objects that the user has access to.

[NOTE]
====
The `LIVEBOARD` and `ANSWER` object types are not supported.
====

|`email` +
__Optional__ |__String__. Email address of the user. Use this parameter to add the email address of the user if `auto_create` is set to `true`.
|`display_name` +
__Optional__ |__String__. Display name of the user. Use this parameter if `auto_create` is set to `true.
|`auto_create` +
__Optional__|__Boolean__. Available from 10.5.0.cl. Creates a user if the specified username is not already available in ThoughtSpot. The default value is `true`.
|`groups` +
__Optional__|__Array of Strings__. GUIDs or names of the groups to assign the user to. This attribute can be used in conjunction with `auto_create` to dynamically assign groups and privileges to a user.
|=====



//unless a specific `reset_option` is defined.

|`reset_option` a|__Array of strings__. Allows you to define the type of attributes to reset upon token generation. The following options are available:

* `FILTER_RULES` +
Resets filter attributes.

* `PARAMETERS`
Resets only Parameters.

* `GROUPS`
Resets group assignments


==== Example request

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/custom'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "UserA",
  "validity_time_in_sec": 300,
  "persist_option": "APPEND",
  "auto_create": true,
  "filter_rules": [
    {
      "column_name": "Item type",
      "operator": "EQ",
      "values": [
        "Jackets","Bags"
      ]
    },
    {
      "column_name": "Customer ID",
      "operator": "EQ",
      "values": [
        "412870"
      ]
    }
  ],
  "parameter_values": [
    {
      "name": "Discount",
      "values": [
        "20"
      ]
    }
  ],
  "objects": [
    {
      "type": "LOGICAL_TABLE",
      "identifier": "4c55ff63-d03e-497a-8ec6-1be083f160ee"
    }
  ],
  "email": "UserA@thoughtspot.com",
  "display_name": "User A",
  "groups": [
    {
      "identifier": "a71d5d1f-6e02-4ee1-a6e9-e158af844367"
    }
  ],
  "org_identifier": "0",
  "secret_key": "4c55ff63-d03e-497a-8ec6-1be083f160ee"
}'
----

==== API response
If the API request is successful, ThoughtSpot returns a token with the security rules and attributes applied.

[source,JSON]
----
{
  "id": "58185cfd-4c04-4570-8bab-63bc8dad2c98",
  "token": "{AUTH_TOKEN}",
  "org": {
    "id": 0,
    "name": "Primary"
  },
  "user": {
    "id": "00000845-7688-795c-c4a1-857dc78d799d",
    "name": "userA"
  },
  "creation_time_in_millis": 1763654650210,
  "expiration_time_in_millis": 1763654949981
}
----

===== Response codes

[options="header", cols="1,4"]
|====
|HTTP status code|Description
|**204**|Successful token revocation
|**400**|Invalid request
|**401**|Unauthorized access
|**403**|Forbidden access
|**500**|Failed operation or unauthorized request
|====


////

== Just-in-time provisioning

If you are generating an authentication token for a new user in ThoughtSpot, you can use the create `auto_create` option to provision a user and obtain a token for this user. Creating a new user requires the assertion containing the username, email address, display name, groups, and Org details.

Users created via JIT provisioning are identical to users created in the UI or via user creation API, except they do not have passwords in ThoughtSpot, and they cannot access ThoughtSpot other than through the SSO method. You can assign a password to any user later through the UI or a REST API call.

The following APIs in ThoughtSpot support Just-in-time (JIT) provisioning:

- REST API v2:
- POST /api/rest/2.0/auth/token/full
- POST /api/rest/2.0/auth/token/object
- POST /api/rest/2.0/auth/token/custom

- REST API v1:
- POST /tspublic/v1/session/auth/token

These endpoints allow you to create a user at the time of authentication if the user does not already exist, by setting the appropriate auto_create (or autocreate) parameter and providing required user details such as display_name and email. JIT provisioning is also supported via SAML and OIDC SSO flows, where users can be created and assigned to groups/orgs upon first login through SSO if configured accordingly.



All token endpoints support on-demand user creation and group/org assignment during token generation, without any manual pre-provisioning steps

The API request Users created via JIT provisioning do not have a password  cannot log in directly; they can only access via the authentication method used for provisioning (e.g., SSO or trusted authentication

If the `username` does not exist in the ThoughtSpot system, you can provision a new user and assign privileges using `auto_create` and `group_identifiers` attributes. For xref:just-in-time-provisioning.adoc[Just-in-time provisioning], include the following attributes along with `username` and `secret_key` in the `POST` request body:

[NOTE]
====
When provisioning new users via `POST /api/rest/2.0/auth/token/custom` API endpoint, note that the user will be added if `auto_create` is set to `true` and the username specified in the API request does not exist in ThoughtSpot. Unlike the other token API endpoints (`POST /api/rest/2.0/auth/token/full` and `POST /api/rest/2.0/auth/token/object`), the user properties such as the display name, email, Org and group assignment will not be updated with new values.
====

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|`username`
|__String__. Username of the ThoughtSpot user. If the user is not available in ThoughtSpot, you can set the `auto_create` parameter to `true` to create a user just-in-time (JIT).
|`secret_key`
|__String__. The secret key string provided by the ThoughtSpot server. ThoughtSpot generates this secret key xref:trusted-authentication.adoc#trusted-auth-enable[when trusted authentication is enabled].
|`email` +
__Optional__ |__String__. Email address of the user. Use this parameter to add the email address of the user during JIT provisioning.
|`display_name` +
__Optional__ |__String__. Display name of the user. Use this parameter when adding a user  just-in-time (JIT).
|`auto_create` +
__Optional__|__Boolean__. Creates a user if the specified username is not already available in ThoughtSpot. The default value is `false`.
|`group_identifiers` +
__Optional__|__Array of Strings__. GUIDs or names of the groups to assign the user to. This attribute can be used in conjunction with `auto_create` to dynamically assign groups and privileges to a user.
|=====

==== Example requests

The following sample shows the request format to provision a new user just-in-time and get an authentication token that grants access to ThoughtSpot:

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/full' \
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "object_id": "061457a2-27bc-43a9-9754-0cd873691bf0",
  "secret_key": "69fb6d98-1696-42c0-9841-22b078c04060",
  "org_id": 2
  "email": "userA@example.com",
  "display_name": "User A"
  "auto_create": true,
  "group_identifiers": [
    "DataAdmin",
    "Analyst"
  ]
}'
----

The following sample shows the request format to provision a new user just-in-time and get an authentication token that grants access to a specific metadata object in ThoughtSpot:

.cURL
[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/object' \
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "tsUserA",
  "object_id": "061457a2-27bc-43a9-9754-0cd873691bf0",
  "secret_key": "69fb6d98-1696-42c0-9841-22b078c04060",
  "org_id": 2
  "auto_create": true,
  "group_identifiers": [
    "DataAdmin",
    "Analyst"
  ]
}'
----

[NOTE]
====
The `auth/token/custom` API endpoint also allows you to automatically create a user during token generation. For more information, see xref:authentication.adoc#_get_tokens_with_custom_rules_and_filter_conditions[Get a token with custom rules and filter conditions for ABAC implementation].
====

== Get token details

To get the authentication token assigned to the current session of the logged-in user, send a request to `/api/rest/2.0/auth/session/token`. You can also this API to get the token issued for the logged-in user for trusted authentication.

=== Example request

.cURL
[source,cURL]
----
curl -X GET \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/auth/session/token' \
  -H 'Accept: application/json'
----

=== Example response

[source,JSON]
----
 {
    "token": "{AUTH_TOKEN}"
    "creation_time_in_millis":1704471154477
    "expiration_time_in_millis":1704557554477
    "valid_for_user_id":"59481331-ee53-42be-a548-bd87be6ddd4a"
    "valid_for_username":"tsadmin"
 }
----

== Revoke a token

To revoke a token, send a `POST` request with the following attributes to the `/api/rest/2.0/auth/token/revoke` endpoint.

===== Request parameters

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|  Description
|`user_identifier`
|__String__. GUID or name of the ThoughtSpot user.
|`token`
|__String__. Token issued for the user specified in `user_identifier`.
|=====

===== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/auth/token/revoke' \
  -H 'Authorization: Bearer {AUTH_TOKEN}'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "user_identifier": "tsUserA,
  "token": {access_token_user}
}'
----

===== Example response

If the API request is successful, the access token is revoked, and the current user session becomes invalid. Before making another API call, you must obtain a new token.

===== Response codes

[options="header", cols="1,4"]
|====
|HTTP status code|Description
|**204**|Successful token revocation
|**400**|Invalid request
|**401**|Unauthorized access
|**403**|Forbidden access
|**500**|Failed operation or unauthorized request
|====

== View session information

To get details of the session object for the currently logged-in user, send a `GET` request to the `GET /api/rest/2.0/auth/session/user` endpoint.


=== Example request

.cURL
[source, cURL]
----
curl -X GET \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/auth/session/user' \
  -H 'Authorization: Bearer {AUTH_TOKEN}'\
  -H 'Accept: application/json'
----

=== Example response

If the API request is successful, ThoughtSpot returns the following response:

[source, JSON]
----
{
   "id":"658a4b35-d021-4009-bf16-c66504dee6a4",
   "name":"tsUserZ",
   "display_name":"tsUserZ",
   "visibility":"SHARABLE",
   "author_id":"59481331-ee53-42be-a548-bd87be6ddd4a",
   "can_change_password":true,
   "complete_detail":true,
   "creation_time_in_millis":1675163378622,
   "current_org":{
      "id":0,
      "name":"Primary"
   },
   "deleted":false,
   "deprecated":false,
   "account_type":"REMOTE_USER",
   "account_status":"ACTIVE",
   "email":"testUser1@thoughtspot.com",
   "expiration_time_in_millis":1675171235,
   "external":false,
   "favorite_metadata":[

   ],
   "first_login_time_in_millis":1675170739789,
   "group_mask":4,
   "hidden":false,
   "home_liveboard":null,
   "incomplete_details":[

   ],
   "is_first_login":false,
   "modification_time_in_millis":1675170835628,
   "modifier_id":"59481331-ee53-42be-a548-bd87be6ddd4a",
   "notify_on_share":true,
   "onboarding_experience_completed":false,
   "orgs":[
      {
         "id":0,
         "name":"Primary"
      }
   ],
   "owner_id":"658a4b35-d021-4009-bf16-c66504dee6a4",
   "parent_type":"USER",
   "privileges":[
      "AUTHORING",
      "USERDATAUPLOADING",
      "DATADOWNLOADING",
      "DEVELOPER"
   ],
   "show_onboarding_experience":true,
   "super_user":false,
   "system_user":false,
   "tags":[

   ],
   "tenant_id":"982d6da9-9cd1-479e-b9a6-35aa05f9282a",
   "user_groups":[
      {
         "id":"0b531ff7-2a5e-45ee-a954-43fbd25c4c92",
         "name":"DATAMANAGEMENT"
      },
      {
         "id":"4fa3f1ca-337a-4fb3-9e7c-dc85da8e6b8e",
         "name":"A3ANALYSIS"
      },
      {
         "id":"ed7435bc-cab4-40c2-ab2e-87e517eb3640",
         "name":"Developer"
      },
      {
         "id":"1cf05016-988c-422a-aae6-bf0ac9f106b7",
         "name":"USERDATAUPLOADING"
      }
   ],
   "user_inherited_groups":[
      {
         "id":"ed7435bc-cab4-40c2-ab2e-87e517eb3640",
         "name":"Developer"
      },
      {
         "id":"1cf05016-988c-422a-aae6-bf0ac9f106b7",
         "name":"USERDATAUPLOADING"
      },
      {
         "id":"4fa3f1ca-337a-4fb3-9e7c-dc85da8e6b8e",
         "name":"A3ANALYSIS"
      },
      {
         "id":"0b531ff7-2a5e-45ee-a954-43fbd25c4c92",
         "name":"DATAMANAGEMENT"
      }
   ],
   "welcome_email_sent":false
}
----

=== Response codes

[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful retrieval of session information
|**400**|Invalid request
|**401**|Unauthorized request
|**500**|Failed operation
|===

== Log out of a session

To log out of your current session, send a `POST` request to the `/api/rest/2.0/auth/session/logout` API endpoint.


=== Example request

.cURL
[source, cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/auth/session/logout'  \
  -H 'Authorization: Bearer {AUTH_TOKEN}'
----

=== Example response

If the API request is successful, ThoughtSpot returns the 204 response code and ends the user session.

=== Response codes

[options="header", cols="2,4"]
|===
|HTTP status code|Description
|**204**|The user is logged out of ThoughtSpot
|**500**|Failed operation
|===
