= Best practices and recommendations
:toc: true
:linkattrs:
:sectanchors:

:page-title: Best practices and recommendations
:page-pageid: best-practices
:page-description: Getting Started


For performance optimization, the following best practices are recommended

Use the recommended SDK version::

Always use the recommended SDK version. +
ThoughtSpot publishes a new version of the SDK for every major ThoughtSpot Cloud release. Make sure you review the xref:api-changelog.adoc[changelog] to know about the new features and enhancements, breaking changes, bug fixes, and deprecated features.

Use the appropriate embed package::

The SDK provides different packages for embedding ThoughtSpot components in your app. Choose the appropriate package that suits your requirement. For example, if you need to embed multiple visualizations, consider adding them to a Liveboard and embed that Liveboard in your app.

+
To avoid page scroll as visualizations load on a Liveboard, you can set the `fullHeight` property to `true` in the `LiveboardEmbed` code.

Call init early::

Call the `init` method as early as possible and complete authentication on application load.


Prefetch and cache resources::

Use the `prefetch` method in the SDK to xref:prefetch-and-cache.adoc[prefetch and cache] static resources required for loading the embedded components. Make sure you call the `prefetch` method before calling `init` and cache static assets as early as possible.

Cache query results::

To cache query results, tune the underlying data warehouse.


////
== Block access to non-embedded ThoughtSpot instance

The SDK allows you to prevent embed application users from accessing or navigating to ThoughtSpot application pages outside the context of your host app. The `blockNonEmbedFullAppAccess` property in the SDK allows you to block embed application users from accessing ThoughtSpot application pages in the non-embed mode. By default, the `blockNonEmbedFullAppAccess` property is set to `true`.

[source,javascript]
----
init({
   // ...
    blockNonEmbedFullAppAccess: true,
});
----

You can also enable the *Block non-embed full app access* feature on the *Develop* > *Customizations* > *Security Settings* page to block user access. However, the `blockNonEmbedFullAppAccess` setting in the SDK takes precedence over the *Block non-embed full app access* setting in the UI.

== Render the embedded application

Render the embedded application.

[source,JavaScript]
----
appEmbed.render();
----

== Related resources

* xref:VisualEmbedSdk.adoc[Visual Embed SDK Reference Guide]
* link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/README.md[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
