= Authorization
:toc: true
:toclevels: 2

:page-title: User access to embedded objects
:page-pageid: embed-object-access
:page-description: You can define user access to view or edit embedded objects and related workflows.

Authorization is the question of "what can the user do?", while authentication is concerned with who the user is and if they can sign-in at all. 

Often both authentication and authorization details are provided via the single sign-on (SSO) mechanism, but the capabilities themselves are separate within ThoughtSpot.

ThoughtSpot divides authorization into several distinct concepts:

* xref:privileges-and-roles.adoc[Privileges]: What system capabilities can you do?
** Roles: groupings of privileges
** Runtime granular control of buttons and menu actions in the embedded app (applicable to embedded ThoughtSpot instances)
* xref:access-control-sharing.adoc[Access Control] - What objects can you see/edit?
** Sharing
* xref:data-security.adoc[Data Security] - In a data source, what will be returned by the query?
** Row Level Security
** Column Level Security




