= Connection configuration
:toc: true
:toclevels: 2

:page-title: Data connection configuration APIs
:page-pageid: connection-config
:page-description: The connection API endpoints allow you to query multiple data configurations per connection used for live query services on a ThoughtSpot instance

ThoughtSpot supports multiple configurations per connection feature allowing developers to define and manage several distinct connection configurations under a single data connection object in ThoughtSpot. This is supported for Snowflake, Databricks, and BigQuery, and requires an Embrace license.

This article describes the procedures for setting and managing data connections through the REST APIs. For information about how to set up a data connection, see link:https://docs.thoughtspot.com/cloud/latest/connections[Data Connections in ThoughtSpot, window=_blank].

== Data Connection Configuration APIs
The connection configuration API endpoints allow you to create, edit, delete, and search connection configuration for an existing data connection on a ThoughtSpot cluster.

=== Required permissions

You must have data management permissions to create, search, update, and  delete connection configuration objects. Make sure your user account has the `DATAMANAGEMENT` privilege.

If xref:roles.adoc[Role-Based Access Control (RBAC)] is enabled on your ThoughtSpot cluster, the `CAN_CREATE_OR_EDIT_CONNECTIONS` *(Can create/edit Connections)* privilege is required.

=== Create connection configuration

To create a connection configuration to an existing data connection object in ThoughtSpot, send a `POST` request to the `POST /api/rest/2.0/connection-configurations/create` API endpoint.

=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description

|name a|__String__. Required. Name of the connection configuration.
|description a|__String__. Optional. Description of the connection configuration.
|connection_identifier a|__String__. Required. Unique ID of the connection for which the configuration will be created.
|authentication_type a|__String__. Required. Type of authentication used for the connection. Default value is `SERVICE_ACCOUNT`.
|configuration a|__String__. Required. A JSON map of the connection configuration attributes. For example, +
"configuration": {"accountName":"thoughtspot_partner","user":"DEV_USER","password":"th0ughtSp0t","role":"DEV","warehouse":"DEV_WH"},
|policy_type a|__String__. Optional. Policy type in connection configuration APIs determines how a specific configuration is assigned and used. The main policy types are:

* *No Policy:* The configuration is saved but not assigned to any users, groups, or processes. +
* *Principals:* The configuration is assigned to specific users and groups, allowing only them to use this configuration. +
* *Processes:* The configuration is assigned for use by specific processes, such as search indexing or row count statistics jobs.
|=====

=== Search a connection configuration
To create a connection configuration to an existing data connection object in ThoughtSpot, send a `POST` request to the `POST /api/rest/2.0/connection-configurations/search` API endpoint.

=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|connection_identifier a|__String__. Required. Unique ID of the connection. To get a list of all configurations available in the ThoughtSpot system, send the API request with only the connection name or GUID in the request body.
|configuration_identifier a|__String__. Optional. Unique ID of the configuration. Specify the configuration object name or GUID to fetch the details for it.
|policy_type a|__String__. Optional. The type of policy associated with the configuration object.
|=====

=== Update a connection configuration
To update an existing connection configuration in ThoughtSpot, send a `POST` request to the `POST /api/rest/2.0/connection-configurations/{configuration_identifier}/update` API endpoint.

=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|configuration_identifier a|__String__. Required. Unique ID of the configuration to be updated.
|connection_identifier a|__String__. Required. Unique ID of the connection object.
|name a|__String__. Optional. The name of the configuration.
|description a|__String__. Optional. The description for the configuration.
|authentication_type a|__String__. Required. Type of authentication used for the connection.
|policy_type a|__String__. Optional. The type of policy associated with the configuration object.
|disable a|__Boolean__. Optional. Indicates whether a configuration is enabled or disabled.
|=====

=== Delete connection configuration
To delete an existing connection configuration from ThoughtSpot, send a `POST` request to the `POST /api/rest/2.0/connection-configurations/delete' API endpoint.

=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description
|configuration_identifier a|__String__. Required. Unique ID of the configuration to be deleted.
|connection_identifier a|__String__. Required. Unique ID of the connection object for the configuration to be deleted.
|=====
