= URL actions
:toc: true
:toclevels: 1

:page-title: Send data to a URL using a custom action
:page-pageid: custom-action-url
:page-description: You can add a custom action to send data to a specific URL target

ThoughtSpot allows you to add a custom action to trigger a data payload to a specific URL target. For example, you may search in ThoughtSpot for specific data and want to programmatically deliver this data to an external application or web page. ThoughtSpot Developer portal allows developers to add a custom menu item in the visualization pages and trigger a data push workflow when a user clicks the action.


[div boxDiv boxFullWidth]
--
+++<h5>Feature highlights</h5>+++

* Any ThoughtSpot user with admin or developer privileges can create URL custom actions in the Developer portal.
* URL actions are available on both embedded and standalone ThoughtSpot instances and do not require ThoughtSpot Embedded Edition license.
* Developers can set a URL action as a global or local action.
* Developers can limit custom action access to a specific user group. 
* To access a URL action, users must have the **New Answer Experience** enabled.
* For URL actions to work in the embedded mode, you must add the URL domain to the CORS and CSP connect-src allowlist.
* Only ThoughtSpot users with edit permissions to a Worksheet or visualization can add a URL action to a Worksheet, visualization, or saved Answer.
--

== Initiate a URL action

To initiate a URL action:

. Navigate to a Liveboard visualization or saved Answer page, and click the URL action.
+
Custom actions appear as disabled on unsaved charts and tables. If you have generated a chart or table from a new search query, you must save the Answer to use the custom action.

. When you click the action, a POST request is sent to the specified URL target with the Answer or visualization data.
