= URL actions
:toc: true
:toclevels: 1

:page-title: Send data to a URL using a custom action
:page-pageid: custom-action-url
:page-description: You can add a custom action to send data to a specific URL target

ThoughtSpot allows you to add a custom action to trigger a data payload to a specific URL target.

== Overview
URL actions appear in ThoughtSpot even without using the Visual Embed SDK within an embedded application.

For URL actions to work in the embedded mode, you must add the URL domain to the CORS and CSP connect-src allowlist.

[NOTE]
====
URL actions do not display any feedback to the user when they are triggered. For custom actions that can provide user feedback within an embedded app, please use xref:custom-actions-callback.adoc[callback custom actions].
====

== Trigger a URL action

To trigger a URL action:

. Navigate to a Liveboard visualization or saved Answer page, and click the URL action.
+
Custom actions appear as disabled on unsaved charts and tables. If you have generated a chart or table from a new search query, you must save the Answer to use the custom action.

. When you click the action, a POST request is sent to the specified URL target with the Answer or visualization data.
