= Customize navigation experience
:toc: true
:toclevels: 2

:page-title: Customize navigation experience
:page-pageid: customize-nav-controls
:page-description: Customize the the navigation panel and menu items in full application embedding using the settings in the Visual Embed SDK

You can customize the navigation experience and the visibility  of navigation menu elements using the customization settings available in the Visual Embed SDK.

[div announcementBlock]
--
[IMPORTANT]
The V1 classic experience and V2 experience modes will be deprecated in an upcoming release in 2026. Therefore, ThoughtSpot recommends that you start upgrading your full app embedding implementation to the V3 UI experience.
--

== Navigation experience

The navigation structure in ThoughtSpot UI varies based on the UI experience mode set in your embed view.

[width="100%", cols="2,4"]
[options='header']
|====
|UI experience| Navigation options
|V1 classic experience a|A standard top navigation bar with the following components: +

* A horizontal application menu
* Help and user profile icons
* Org switcher

|V2 experience  a|
* Simplified top navigation structure. Includes the following components: +
** Object search bar
** The application selector to switch between different application contexts
** Help and profile icons
** Org switcher to switch between Orgs on instances with Orgs
* A left navigation panel for each application context.
|V3 experience
a|
* Top navigation bar with a modern look and feel. Includes the following components:
** A hamburger icon for the sliding navigation overlay
** Object search bar
** Help and profile icons +
The user profile includes *Admin settings* option. Visible to users with administration privileges
** Org switcher
* Left navigation
** A sliding left navigation panel controlled via hamburger icon
** Persona-based app selection icons in the panel header
** Left navigation menu that adjusts its contents according to the application context.
|====

== Customize the top navigation bar
The following customization settings are available for the top navigation panel.

[width="100%", cols="2,2,2,2"]
[options='header']
|====
| SDK property
| V1 classic experience
| V2 experience
| V3 experience
|`showPrimaryNavbar` +
To show or hide the navigation experience.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideApplicationSwitcher` +
To show or hide the application switcher
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported +
In V2 experience, hides the app selector in top navigation menu.
| [tag greenBackground tick]#✓#  Supported +
In the V3 experience, hides the app selection icons on the left navigation panel and the *Admin settings*  option in the User profile menu.
| `disableProfileAndHelp` +
To show or hide the help and user profile icons on the top navigation menu
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported +
In the V3 experience, hides user profile icon, including the *Admin settings* menu.

| `hideOrgSwitcher` +
To show or hide the Org switcher
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideNotification` +
To show or hide the notification (bell) icon
| [tag redBackground tick]#x# Not supported
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported

| `hideObjectSearch` +
To show or hide the object search bar in the top navigation menu
| __Not applicable__ +
The object search bar is hidden by default.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideHamburger` +
To show or hide the hamburger icon in the top navigation bar.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported +
Hides the hamburger icon available on pages where the left navigation panel is hidden by default.
|====

== Customize the left navigation panel on home page
In the V2 and V3 experience modes, the SDK provides the `hideHomepageLeftNav` property to hide the left navigation panel only on the home page.

If you want to include the left navigation on the home page and show or hide a specific section of the *Insights* panel, specify these menu items in the `hiddenHomeLeftNavItems` array. The allowed values for `hiddenHomeLeftNavItems` are listed in the following table.

[width="100%", cols="2,2,2,2"]
[options='header']

|===
|Allowed values
| V1 Experience
| V2 Experience
| V3 Experience

| `HomeLeftNavItem.Create` +
To show or hide the `+` icon that allows creating a Liveboard or Answer in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Home` +
To show or hide the *Home* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Spotter` +
To show or hide the  *Spotter* menu item in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SearchData` +
To show or hide the *Search Data* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Liveboards` +
To show or hide the *Liveboards* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Answers` +
To show or hide the *Answers* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.LiveboardSchedules` +
To show or hide the *LiveboardSchedules* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.MonitorSubscription` +
To show or hide the *Monitor subscriptions* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SpotIQAnalysis` +
To show or hide the *SpotIQ analyses* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Favorites` +
To show or hide the `Favorites` section in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
|===

== Examples
The following sections show code samples for customizing the default left navigation panel in the *Insights* section and the home page.

=== V3 experience

[source,JavaScript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    HomePage, // Enum for home page experience setting
    PrimaryNavbarVersion, // Enum for navigation bar version
    HomeLeftNavItem, // Enum for left navigation items
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    discoveryExperience: {
        primaryNavbarVersion: PrimaryNavbarVersion.Sliding, // Enables V3 sliding navigation
        homePage: HomePage.ModularWithStylingChanges, // Enables V3 home page experience
    },
    // Show navigation bar
    showPrimaryNavbar: true,
    hideApplicationSwitcher: true,
    // Hide Help and User Profile icons in top navigation
    disableProfileAndHelp: true,
    // Hide the alert icon in top navigation
    hideNotification: true,
    //Show left navigation panel on the home page
    hideHomepageLeftNav: false,
    hiddenHomeLeftNavItems: [
        HomeLeftNavItem.Home,
        HomeLeftNavItem.Liveboards
    ], // Hide Home and Liveboards from the left navigation panel
});
----

=== V2 experience

[source,JavaScript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    HomeLeftNavItem, // Enum for left navigation items
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    // Enable the V2 navigation experience
    modularHomeExperience: true,
    // Set the top navigation bar in the embedded view
    showPrimaryNavbar: true,
    // Hide the app selector in top navigation bar
    hideApplicationSwitcher: true,
    // Hide the left navigation panel on the home page
    hideHomepageLeftNav: true,
    // Hide the profile and help icons in top navigation
    disableProfileAndHelp: true,
    // Hide specific items from left navigation panel
    hideHomepageLeftNav: false,
    hiddenHomeLeftNavItems: [
        HomeLeftNavItem.MonitorSubscription,
        HomeLeftNavItem.SpotIQAnalysis
    ], // Hide Home and Liveboards from the left navigation panel
    //... other view config attributes
});
----

== Help menu customization
If you want to include the help menu and link:https://docs.thoughtspot.com/cloud/latest/customize-help[add custom links, window=_blank] to it, ensure that the top navigation bar is visible and `disableProfileAndHelp` is set to `false`.

By default, the help menu in the embedded view shows the legacy information center controlled using Pendo. To enable the new information center and add custom links, set `enablePendoHelp` to `false`.

To add custom links to the help menu, use the customization settings available on the **Admin settings** > **Help customization** page. For more information, see link:https://docs.thoughtspot.com/cloud/latest/customize-help[ThoughtSpot Product Documentation].

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    // Display the top navigation bar
    showPrimaryNavbar: true,
    // Show the profile and help icons in the navigation bar.
    disableProfileAndHelp: false,
    // Use the new ThoughtSpot information center for help and support.
    enablePendoHelp: false,
    // ... other view config attributes
});
----

== Additional resources
See also:

* xref:full-app-customize.adoc[Customize full application embed]
* xref:full-embed.adoc[Embed full application]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Actions]
