= Customize navigation experience
:toc: true
:toclevels: 2

:page-title: Customize navigation experience
:page-pageid: customize-nav-controls
:page-description: Customize the the navigation panel and menu items in full application embedding using the settings in the Visual Embed SDK

Navigation customization in full application embedding allows you to control the visibility and layout of navigation elements, such as the top navigation bar, application menu selector, and left navigation panel experience for Insights page.

== Navigation experience

The navigation structure in ThoughtSpot UI varies based on the UI experience settings.

[width="100%", cols="2,4"]
[options='header']
|====
|UI experience| Navigation options
|V1 classic experience a| Standard top navigation bar with the following components:
* A horizontal application menu
* Help and user profile icons
* Org switcher

|V2 experience a| * Simplified top navigation structure. Includes the  following components:
** Object search bar
** App switcher to switch between different application contexts
** Help and profile icons
** Org switcher
* Left navigation panel with dynamic menu items for each application context
|V3 experience
a|
* Top navigation bar with a modern look and feel. Includes the following components:
** Hamburger icon for sliding left navigation panel
** Object search bar
** Help and profile icons +
The user profile includes *Admin settings* option. Visible to users with administration privileges
** Org switcher
* Left navigation
** Sliding panel controlled via hamburger icon
** Persona-based app selection icons in the panel header
** Separate left navigation panel with dynamic menu items for each context.
|====

== Customize top navigation bar
If the navigation panels are hidden by default and you want to include these in the embedded view, set `showPrimaryNavbar: true` in the Visual Embed SDK.
For additional customization control, use the properties in the SDK.

[width="100%", cols="2,2,2,2"]
[options='header']
|====
| SDK property
| V1 classic experience
| V2 experience
| V3 experience
|`showPrimaryNavbar` +
Control the visibility of navigation experience.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideApplicationSwitcher` +
Show or hide the application switcher
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported +
In V2 experience, hides the app selector in top navigation menu.
| [tag greenBackground tick]#✓#  Supported +
In V3 experience, hides the app selection icons on the left navigation panel and the *Admin settings*  option in the User profile menu.
| `disableProfileAndHelp` +
Show or hide the help and user profile icons on the top navigation menu
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported +
In V3 experience, hides user profile icon, including the *Admin settings* menu.

| `hideOrgSwitcher` +
Show or hide the Org switcher
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideNotification` +
Show or hide the notification (bell) icon
| [tag redBackground tick]#x# Not supported
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported

| `hideObjectSearch` +
Show or hide the object search bar in the top navigation menu
| Not applicable. The object search bar is hidden by default.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideHamburger` +
Hides the hamburger icon in the top navigation bar.
| [tag greyBackground tick]#—# Not applicable
| [tag greyBackground tick]#—# Not applicable
| [tag greenBackground tick]#✓#  Supported +
Hides the hamburger icon that appears when navigating between application pages. Not visible on List pages.
|====

== Customize left navigation panel on home page
In V2 and V3 experience, the SDK provides `hideHomepageLeftNav` property as an additional setting to hide the left navigation panel only on the home page.

If you want to include the left navigation on the home page and show or hide specific section or menu of the *Insights* panel, specify the menu items in the `hiddenHomeLeftNavItems` array. The allowed values are listed in the following table.

[width="100%", cols="2,2,2,2"]
[options='header']

|===
|Allowed values
| V1 Experience
| V2 Experience
| V3 Experience

| `HomeLeftNavItem.Answers` +
For *Answers* menu in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Create` +
For `+` icon that allows creating a Liveboard or Answer in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Favorites` +
For `Favorites` section in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Home` +
For *Home* menu in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.LiveboardSchedules`
For *LiveboardSchedules* menu in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Liveboards` +
For *Liveboards* menu in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.MonitorSubscription`
For *Monitor subscriptions* in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SearchData`
For *Search Data* in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SpotIQAnalysis`
For *SpotIQ analyses* in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Spotter`
For *Spotter* menu item in the *Insights* panel.
| [tag greyBackground tick]#-# Not applicable
| [tag greyBackground tick]#-# Not applicable
| [tag greenBackground tick]#✓#  Supported
|===

== Examples
The following examples show the customization settings for left navigation panel on the home page and *Insights* section.

=== V3 experience

[source,JavaScript]
----
const embed = new AppEmbed('#tsEmbed', {
  // Show navigation bar
  showPrimaryNavbar: true,
  discoveryExperience: {
    // Set V3 navigation experience
    primaryNavbarVersion: PrimaryNavbarVersion.Sliding,
    // Set the home page to use the modular layout with styling changes
    homePage: HomePage.ModularWithStylingChanges,
  },
  // Hide the application menu icons
  hideApplicationSwitcher: true,
  // Hide the Help and User Profile icons in the top navigation bar
   disableProfileAndHelp: true,
  // Show the left navigation panel on the home page
  hideHomepageLeftNav: false,
  // Hide the notification icon in the top navigation bar
  hideNotification: true,
  // Hide specific items (Create, Search Data) from the home page left navigation panel
  hiddenHomeLeftNavItems: [HomeLeftNavItem.Create, HomeLeftNavItem.SearchData],
  //... other view config attributes
});
----

=== V2 experience

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    // Enable the V2 navigation experience
    modularHomeExperience: true,
    // Set the top navigation bar in the embedded view
    showPrimaryNavbar: true,
    // Hide the app selector in the top navigation bar
    hideApplicationSwitcher: true,
    // Hide the left navigation panel on the home page
    hideHomepageLeftNav: true,
    // Hide the profile and help icons in the navigation bar
    disableProfileAndHelp: true,
    // Hide specific items (Monitor Subscription, SpotIQ Analysis) from the left navigation panel
    hiddenHomeLeftNavItems: [HomeLeftNavItem.MonitorSubscription, HomeLeftNavItem.SpotIQAnalysis],
    //... other view config attributes
});
----

== Help menu customization
If you want include the help menu and link:https://docs.thoughtspot.com/cloud/latest/customize-help[add custom links, window=_blank] to it, ensure that the top navigation bar is visible and `disableProfileAndHelp` is set to `false`.

By default, the help menu in the embedded view is set to show the legacy information center controlled via Pendo. To enable the new information center and add custom links, set `enablePendoHelp` to `false`.

To add custom links to help menu, use the customziation settings available on **Admin settings** > **Help customization** page. For more information, see link:https://docs.thoughtspot.com/cloud/latest/customize-help[ThoughtSpot Product Documentation].

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    // Display the top navigation bar
    showPrimaryNavbar: true,
    // Show the profile and help icons in the navigation bar.
    disableProfileAndHelp: false,
    // Use the new ThoughtSpot information center for help and support.
    enablePendoHelp: false,
    // ... other view config attributes
});
----

== Additional resources

* xref:full-app-customize.adoc[Customize full application embed]
* xref:full-embed.adoc[Embed full application]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Actions]
