= Customize email settings per Org

:page-title: Customize notification email settings per Org
:page-pageid: customize-email
:page-description: You can rebrand system-generated notifications and customize notification emails



To customize the email notifications per Org, ThoughtSpot has introduced the following REST APIs:

* `POST /api/rest/2.0/customization/email`
* `POST /api/rest/2.0/customization/email/{template_identifier}/delete`
* `POST /api/rest/2.0/customization/email/search`
* `POST /api/rest/2.0/customization/email/validate`

== Before you begin

* For REST API v2 operations, the Org context is determined based on the authentication token used in your API requests. Ensure you log in to the appropriate Org context from which you want to send API requests.
* Ensure that you have developer or administrator privileges for the Org.

These APIs support configuration of the following parameters as per your requirements:

* Custom Sender email
* Custom email footer
* Style customization like font and email color palette
* Whitelabel ThoughtSpot content
* Hide ThoughtSpot content where required
* Branding elements like company logo for branding and communication consistency

To understand the API endpoints for the email customizations, see xref:rest-api-v2-reference.adoc[REST APIs v2].

== Create an email customization
To customize the notification emails for your Org, send a `POST` request to the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Femail-customisation%2Fcreate-email-customisation"> /api/rest/2.0/customization/email </a>+++ API endpoint, with the following parameters in the request body.


=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description

|template_properties a|__String__. A JSON map of

* `value` __String__ +
The value for the variable. For the primary Org, you can define the variable value as `Primary`. For destination Orgs, specify a separate value, for example, `staging1`.
* `org_identifier` __String__ +
ID or name of the Org. For primary Org, specify `primaryOrg` or Org 0.
* `principal_type` and `principal_identifier`
Specify if the variable should be applied per user or user group. Based on the principal type, specify the ID or name of the user or user group.
* `priority` +
The priority assigned to this value. If there are two matching values, the one with a higher priority will be used.
|=====
