= Customize email settings

:page-title: Customize notification email settings per Org
:page-pageid: customize-email-apis
:page-description: You can rebrand system-generated notifications and customize notification emails



ThoughtSpot now provides public REST APIs that enable developers and administrators to programmatically customize the branding, content, and visibility of components in notification emails. These APIs support customizations at the Org level.

These APIs support configuration of the following parameters as per your requirements:

* Sender email address for system-generated notification emails ensuring all notification emails reflect the email address of your company.
* Branding elements like company logo for branding and communication consistency.
* Style customization like font and email color palette. This allows you to set the look and feel, including fonts and colors for a seamless product experience.
* Custom vocabulary (whitelabel) for notification emails. This allows you to replace ThoughtSpot specific terms like “ThoughtSpot,” “Liveboard,” “Answer,” “SpotIQ,” and “KPI alert” with your own product terminology.



== Before you begin

* For REST API v2 operations, the Org context is determined based on the authentication token used in your API requests. Ensure you log in to the appropriate Org context from which you want to send API requests.
* Ensure that you have developer or administrator privileges for the Org.



To try the API endpoints for the email customizations, see xref:rest-api-v2-reference.adoc[REST APIs v2].

== Create an email customization
To customize the notification emails for your Org, send a `POST` request to the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Femail-customisation%2Fcreate-email-customisation"> /api/rest/2.0/customization/email </a>+++ API endpoint, with the following parameters in the request body.


=== Request parameters
In your `POST` request body, include the following parameters:

[width="100%" cols="1,4"]
[options='header']
|=====
|Parameter|Description

|template_properties a|__String__. A JSON map of customizable elements of the email template.

|=====

== Delete an email customization
To remove an existing customization configuration for notification emails in your Org, send a `POST` request to the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Femail-customisation%2Fdelete-email-customisation"> /api/rest/2.0/customization/email/{template_identifier}/delete </a>+++ API endpoint, with the `template_identifier` in the request body.
Pass either the unique ID or the name of the customization you want to delete as the value for this parameter in your API call.

== Search email Customization
To search the email customization configuration set for the Org or the ThoughtSpot instance, send a  `POST` request to the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Femail-customisation%2Fsearch-email-customisation"> /api/rest/2.0/customization/email/search </a>+++ API endpoint.

== Validate Email Customization
To validate your email customization configuration in ThoughtSpot, send a `POST` request to the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Femail-customisation%2Fdelete-email-customisation">  /api/rest/2.0/customization/email/validate </a>+++ API endpoint.
This triggers a test email designed to reflect all the customizations you’ve configured. This allows you to confirm that customizations are applied as expected. You can adjust your configuration if needed and repeat the validation until done.

== Response Codes