= Customize navigation panels
:toc: true
:toclevels: 2

:page-title: Customize navigation panels
:page-pageid: customize-nav-controls
:page-description: Customize the the navigation panel and menu items in full application embedding using the settings in the Visual Embed SDK

You can customize the navigation experience and the visibility of navigation menu elements using the Visual Embed SDK.

[div announcementBlock]
--
[IMPORTANT]
The classic (V1) experience and V2 experience modes will be deprecated in an upcoming release in 2026. Therefore, ThoughtSpot recommends upgrading the UI experience of your full application embedding to the V3 experience.
--


== Navigation experience
The navigation structure in ThoughtSpot UI varies based on the UI experience mode set in your embed view.

[width="100%", cols="2,4"]
[options='header']
|====
|UI experience| Navigation options
|Classic (V1) experience a|A standard top navigation bar with the following components: +

* A horizontal application menu
* Help and user profile icons
* Org switcher

|V2 experience  a|
* Simplified top navigation structure. Includes the following components: +
** Object search bar
** The application selector to switch between different application contexts
** Help and profile icons
** Org switcher for instances with Orgs
* A left navigation panel for each application context.
|V3 experience
a|
* Top navigation bar with a modern look and feel. Includes the following components:
** A hamburger icon for the sliding navigation overlay
** Object search bar
** Help and profile icons +
The user profile includes *Admin settings* option, which is visible to users with administration privileges.
** Org switcher
* Left navigation
** A sliding left navigation panel controlled via the hamburger icon
** Persona-based app selection icons in the panel header
** Left navigation menu that adjusts its contents according to the application context.
|====

== Customize the top navigation bar
The following customization settings are available for the top navigation bar.

[width="100%", cols="2,2,2,2"]
[options='header']
|====
| SDK property
| Classic (V1) experience
| V2 experience
| V3 experience
|`showPrimaryNavbar` +
To show or hide the navigation experience.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideApplicationSwitcher` +
To show or hide the application switcher.
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported +
In V2 experience, hides the app selector in the top navigation bar.
| [tag greenBackground tick]#✓#  Supported +
In the V3 experience, hides the app selection icons on the left navigation panel and the *Admin settings*  option in the Profile menu.
| `disableProfileAndHelp` +
To show or hide the help and user profile icons in top navigation bar.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported +
Also hides or shows *Help* menu on the left navigation panel of the home page.
| [tag greenBackground tick]#✓#  Supported +
Also hides the *Admin settings* menu in the profile dropdown.

| `hideOrgSwitcher` +
To show or hide the Org switcher.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideNotification` +
To show or hide the notification (bell) icon.
| [tag redBackground tick]#x# Not supported
| [tag redBackground tick]#x# Not supported
| [tag greenBackground tick]#✓#  Supported

| `hideObjectSearch` +
To show or hide the object search bar in the top navigation bar.
| __Not applicable__ +
The object search bar is hidden by default.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideHamburger` +
To show or hide the hamburger icon in the top navigation bar.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported +
Hides the hamburger icon available on pages where the left navigation panel is hidden by default.
|====

=== Example

The following example hides the icons in the top navigation and the application selection menu:

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    //... V3 experience attributes 
    // Show navigation bar
    showPrimaryNavbar: true,
    hideApplicationSwitcher: true,
    // Hide Help and User Profile icons in top navigation
    disableProfileAndHelp: true,
    // Hide object search bar in top navigation
    hideObjectSearch: true,
    // Hide the alert icon in top navigation
    hideNotification: true,
    //... other attributes
});
----

== Customize the left navigation panel on the home page
In the V2 and V3 experience modes, the left navigation panel on the *Insights* > *Home* page includes menu items such as *Answers*, *Liveboards*, *SpotIQ Analysis*, *Monitor Subscriptions*, and more. You can hide this navigation panel by setting the `hideHomepageLeftNav` property to `true` in the SDK. Note that this attribute hides the left navigation only on the home page. 

If you want to include the left navigation, but hide only a specific section in the *Insights* panel, use the `hiddenHomeLeftNavItems` property and specify the menu items to hide. The allowed values for `hiddenHomeLeftNavItems` are listed in the following table:

[width="100%", cols="2,2,2,2"]
[options='header']

|===
|Allowed values
| Classic (V1) experience
| V2 experience
| V3 experience

| `HomeLeftNavItem.Create` +
To show or hide the `+` icon that allows users to create a Liveboard or Answer in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Home` +
To show or hide the *Home* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Spotter` +
To show or hide the  *Spotter* menu item in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SearchData` +
To show or hide the *Search Data* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Liveboards` +
To show or hide the *Liveboards* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Answers` +
To show or hide the *Answers* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.LiveboardSchedules` +
To show or hide the *LiveboardSchedules* menu in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.MonitorSubscription` +
To show or hide the *Monitor subscriptions* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SpotIQAnalysis` +
To show or hide the *SpotIQ analyses* in the *Insights* panel.
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Favorites` +
To show or hide the `Favorites` section in the *Insights* panel.
| __ Not applicable__
| __ Not applicable__
| [tag greenBackground tick]#✓#  Supported
|===

== Examples
The following sections show code samples for customizing the default left navigation panel in the *Insights* section and the home page.

=== V3 experience

[source,JavaScript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    HomePage, // Enum for home page experience setting
    PrimaryNavbarVersion, // Enum for navigation bar version
    HomeLeftNavItem, // Enum for left navigation items
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    discoveryExperience: {
        primaryNavbarVersion: PrimaryNavbarVersion.Sliding, // Enables V3 sliding navigation
        homePage: HomePage.ModularWithStylingChanges, // Enables V3 home page experience
    },
    // Show navigation bar
    showPrimaryNavbar: true,
    hideHomepageLeftNav: false,
    hiddenHomeLeftNavItems: [
        HomeLeftNavItem.Favorites,
        HomeLeftNavItem.SpotIQAnalysis
    ], // Hide SpotIQ analysis and Favorites
    //... other view configuration attributes
});
----

=== V2 experience

[source,JavaScript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    HomeLeftNavItem, // Enum for left navigation items
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    // Enable the V2 navigation experience
    modularHomeExperience: true,
    // Hide specific items from left navigation panel
    hideHomepageLeftNav: false,
    hiddenHomeLeftNavItems: [
        HomeLeftNavItem.MonitorSubscription,
        HomeLeftNavItem.SpotIQAnalysis
    ], // Hide SpotIQ analysis and Monitor subscriptions from the left navigation panel
    //... other view configuration attributes
});
----

== Customize the Help menu

If you want to include the help menu and link:https://docs.thoughtspot.com/cloud/latest/customize-help[add custom links, window=_blank] to it, ensure that the top navigation bar is visible and `disableProfileAndHelp` is set to `false`.

By default, the help menu in the embedded view shows the legacy information center controlled using Pendo. To enable the new information center and add custom links, set `enablePendoHelp` to `false`.

To add custom links to the help menu, use the customization settings available on the **Admin settings** > **Help customization** page. For more information, refer to the link:https://docs.thoughtspot.com/cloud/latest/customize-help[ThoughtSpot Product Documentation].

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    // Display the top navigation bar
    showPrimaryNavbar: true,
    // Show the profile and help icons in the top navigation bar.
    disableProfileAndHelp: false,
    // Use the new ThoughtSpot information center for help and support.
    enablePendoHelp: false,
    // ... other view configuration attributes
});
----

== Additional resources
See also:

* xref:full-app-customize.adoc[Customize full application embed]
* xref:full-embed.adoc[Embed full application]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Actions]
