= Customize text strings
:toc: true
:toclevels: 2

:page-title: Customize text strings
:page-pageid: customize-text
:page-description: Customize text strings on ThoughtSpot application interface

You can customize text strings on the ThoughtSpot application interface via `customizations` object in the SDK.

== Example

[source,JavaScript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    customizations: {
        content: {
            strings: {
                "Liveboard": "Dashboard",
                "Edit": "Modify",
                "Show underlying data": "Show source data",
                "SpotIQ": "Insights",
                "Monitor": "Alerts",
                "Worksheets": "Data model"
            }
        }
    }
});
----

== Limitations
Note the following limitations: +

* The text strings are case-sensitive.
* Customization of user-defined text strings such as object names, titles, or description text is not supported.
* Note the order of strings and substring definitions when customizing text. +
For example, if the `Liveboard` text string is defined as `Dashboard`, all instances of `Liveboard` will be updated as `Dashboard` in the UI. If you want to customize `Pin to Liveboard` text string, you must specify the next substring as `Pin to Dashboard` instead of `Pin to Liveboard` as shown here.

+
[source,JavaScript]
----
customizations: {
        content: {
            strings: {
              "Liveboard": "Dashboard",
              "Pin to Dashboard": "Save",
            }
        }
    }
----
+

However, if the `Pin to Livebaord` string precedes the `"Liveboard": "Dashboard"` string, specify the substring as `Pin to Livebaord` as shown in this example.
+
[source,JavaScript]
----
customizations: {
        content: {
            strings: {
              "Pin to Liveboard": "Save",
              "Liveboard": "Dashboard",

            }
        }
    }
----

* If you want to customize a text phrase, which contains strings that are already defined for customization, use the custom text string in substring definitions. For example, customizing `Search` as `Analyze your metrics` updates all instances of `Search` in the UI, which means that the `Search data` button text will show as "Analyze your metrics data". To change the `Search data` button text, specify the substring as `Analyze your metrics data`.
+
[source,JavaScript]
----
customizations: {
    content: {
        strings: {
            "Search": "Analyze your metrics",
            "Analyze your metrics data": "Build query"
        }
    }
}
----

* To override some text strings such as phrases and sentences, you may need to break the text into substrings. If the phrase or sentence contains text, for example `Liveboard`, which is already defined or needs to be defined as a separate substring, you can break the text string as shown in this example:

+
[source,JavaScript]
----
customizations: {
    content: {
      strings: {
        "Request access for this": "Get access to this",
        "Liveboard": "Dashboard"
      }
    }
  }
----


+++ <a href="{{previewPrefix}}/playground/fullApp" target="_blank">Try it out </a> +++ in the Visual Embed Playground to preview the customization.