= Customize text strings
:toc: true
:toclevels: 2

:page-title: Customize text strings
:page-pageid: customize-text
:page-description: Customize text strings on ThoughtSpot application interface

You can customize text strings on the ThoughtSpot application interface via `customizations` object in the SDK.

== Example

[source,JavaScript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    customizations: {
        content: {
            strings: {
                "Liveboard": "Dashboard",
                "Edit": "Modify",
                "Show underlying data": "Show source data",
                "SpotIQ": "Insights",
                "Monitor": "Alerts",
                "Worksheets": "Data model"
            }
        }
    }
});
----

+++ <a href="{{previewPrefix}}/playground/fullApp" target="_blank">Try it out </a> +++ in the Visual Embed Playground to preview the customization.

== Limitations
Note the following limitations: +

* The text strings are case-sensitive.
* Customization of user-defined text strings such as object names, title, or description text is not supported.
* The latest entry in the `strings` object takes precedence over other substring overrides. For example, if the `Liveboard` text string is defined as `Dashboard` and the next substring `Pin to Liveboard` is defined as `Save`, all  instances of `Liveboard` will change to `Dashboard`, but `Pin to Liveboard` will be customized as `Save`.

+
[source,JavaScript]
----
customizations: {
        content: {
            strings: {
              "Liveboard": "Dashboard",
              "Pin to Liveboard": "Save",
            }
        }
    }
----
+

However, if the order of the string changes as shown in the following example, the later string customization entry will take precedence; which means that the second entry `"Liveboard": "Dashboard"` will drive the original copy in ThoughtSpot’s user interface `Pin to Liveboard` to be customized as `Pin to Dashboard`, and the string customization `"Pin to Liveboard": "Save"` will be ignored.

+
[source,JavaScript]
----
customizations: {
        content: {
            strings: {
              "Pin to Liveboard": "Save",
              "Liveboard": "Dashboard",

            }
        }
    }
----
