= Customize navigation panels
:toc: true
:toclevels: 2

:page-title: Customize navigation panels
:page-pageid: customize-nav-controls
:page-description: Customize the navigation panel and menu items in full application embedding using the settings in the Visual Embed SDK

You can customize the navigation experience and the visibility of navigation menu elements using the Visual Embed SDK.


== Navigation experience
The navigation experience in a full application embed includes the following elements:

* Top navigation bar with a modern look and feel. Includes the following components:
** A hamburger icon for the sliding navigation overlay
** Object search bar
** Help and profile icons
** Org switcher
* Left navigation
** A sliding left navigation panel controlled via the hamburger icon
** Persona-based app selection icons in the panel header
** Left navigation menu that adjusts its contents according to the application context


== Customize the top navigation bar

The following customization settings are available for the top navigation bar.

[width="100%", cols="3,^2,^2"]
[options="header"]
|====
| SDK property
| Sliding navigation with modular homepage +
| Sliding navigation with focused homepage +

| `showPrimaryNavbar` +
To show or hide the navigation experience.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported
| `hideApplicationSwitcher` +
To show or hide the application switcher.
| [tag greenBackground tick]#✓#  Supported +
Hides the app selection icons on the left navigation panel.
| [tag greenBackground tick]#✓#  Supported +
Hides the app selection icons on the left navigation panel.
| `disableProfileAndHelp` +
To show or hide the help and user profile icons in the top navigation bar.
| [tag greenBackground tick]#✓#  Supported +
Also hides or shows the *Help* menu on the left navigation panel of the home page.
| [tag greenBackground tick]#✓#  Supported

| `hideOrgSwitcher` +
To show or hide the Org switcher.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideNotification` +
To show or hide the notification (bell) icon.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideObjectSearch` +
To show or hide the object search bar in the top navigation bar.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `hideHamburger` +
To show or hide the hamburger icon in the top navigation bar.
| [tag greenBackground tick]#✓#  Supported +
Hides the hamburger icon available on pages where the left navigation
panel is hidden by default.
| [tag greenBackground tick]#✓#  Supported
|====

=== Example

The following example hides the icons in the top navigation and the application selection menu:

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    //... modular home page experience attributes
    showPrimaryNavbar: true,
    hideApplicationSwitcher: true,
    disableProfileAndHelp: true,
    hideObjectSearch: true,
    hideNotification: true,
    //... other attributes
});
----

== Customize the left navigation panel on the home page
In the modular and focused experience modes, the left navigation panel on the *Insights* > *Home* page includes menu items such as *Spotter*, *Answers*, *Liveboards*, *SpotIQ Analysis*, *Monitor Subscriptions*, and more. You can hide this navigation panel by setting the `hideHomepageLeftNav` property to `true` in the SDK. Note that this attribute hides the left navigation only on the home page.

If you want to include the left navigation, but hide only a specific section in the *Insights* panel, use the `hiddenHomeLeftNavItems` property and specify the menu items to hide. The allowed values for `hiddenHomeLeftNavItems` are listed in the following table:

[width="100%", cols="3,^2,^2"]
[options="header"]
|====
| Allowed values
| Sliding navigation with modular homepage
| Sliding navigation with focused homepage

| `HomeLeftNavItem.Create` +
To show or hide the `+` icon that allows users to create a
Liveboard or Answer in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Home` +
To show or hide the *Home* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported


| `HomeLeftNavItem.Spotter` +
To show or hide the *Spotter* menu item in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.SearchData` +
To show or hide the *Search Data* in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Liveboards` +
To show or hide the *Liveboards* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Answers` +
To show or hide the *Answers* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.MonitorAlerts` +
To show or hide the *Monitor* > *Alerts* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported


| `HomeLeftNavItem.MonitorSubscriptions` +
To show or hide the *Monitor* > *Subscriptions* menu in the
*Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported


| `HomeLeftNavItem.SpotIQAnalysis` +
To show or hide the *SpotIQ Analysis* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag redBackground tick]#x# Not supported


| `HomeLeftNavItem.Learning` +
To show or hide the *Learning* menu in the *Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported


| `HomeLeftNavItem.LiveboardSchedules` +
To show or hide the *Scheduled Liveboards* section in the
*Insights* panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

| `HomeLeftNavItem.Collections` +
To show or hide the *Collections* menu item in the *Insights* left navigation panel.
| [tag greenBackground tick]#✓#  Supported
| [tag greenBackground tick]#✓#  Supported

|====


== Command palette availability in embed
In ThoughtSpot application, users can open the link:https://docs.thoughtspot.com/cloud/latest/thoughtspot-homepage#command-palette[command palette] by pressing kbd:[Cmd+K] on macOS or kbd:[Ctrl+K] on Windows to quickly navigate to objects and perform actions. However, when you embed ThoughtSpot, this feature is disabled and embedded pages include only the standard object search experience.


== Related resources

* xref:full-app-customize.adoc[Customize full application embedding]
* xref:customize-homepage-full-embed.adoc[Customize home page experience]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Actions]

