= Customize onboarding settings

:page-title: Customize email settings and onboarding experience
:page-pageid: customize-emails
:page-description: You can rebrand system-generated notifications and customize onboarding experience

To customize the welcome email text, product name, and sender email addresses for welcome emails and scheduled notifications, use the  customization settings on the *Admin* > *Onboarding* page of your ThoughtSpot instance.

[IMPORTANT]
====
* If you want your ThoughtSpot instance to send email notifications with a custom domain name and a specific sender ID, contact ThoughtSpot Support.
* To send emails from a specific email account, you must update the *Custom admin email* and *From ID* on the *Admin* > *Application settings* > *Onboarding* page. To customize these parameters, contact ThoughtSpot Support.
//* If your instance has Orgs, note that customizing email settings per Org is not supported. To modify the email settings for all Orgs on your instance, you will need cluster administrator privileges.
====

To customize email settings and the onboarding experience, follow these steps:

. Log in to ThoughtSpot as an admin user.
. Go to *Admin* > *Application settings* > *Onboarding*.
. Click *Edit*.
. Configure the following parameters as per your requirements.

Welcome email::
Enables or disables welcome emails. When enabled, ThoughtSpot sends welcome emails to all new users.

Company name::
Your company name. The default value is `Your Company`.  

Custom admin email::
Email address of the administrator of your ThoughtSpot instance. You can add an email address of your choice. However, to enable this setting, you must contact ThoughtSpot Support.

From ID:: 
Email address from which the welcome emails are sent to new ThoughtSpot users. By default, ThoughtSpot uses `TS Admin <\no-reply@customer.thoughtspot.com>` to send email notifications. To change this setting, contact ThoughtSpot Support.

Support email ID::
Email address of your company's Support contact. This email address appears only in welcome emails sent to the new users of your ThoughtSpot instance.

Learn More link::
A website URL that allows users to learn more about ThoughtSpot or your organization’s implementation of ThoughtSpot. The default link is `\https://docs.thoughtspot.com`.

Product name::
The name of the product to use in email notifications; for example, Liveboard sharing, Liveboard job schedule, or Liveboard subscription notifications. If you specify a product name, these email notifications will show the product name as shown here:

+
----
Visit <product-name> to view this Liveboard.
----

+
If the product name is not defined, the email notifications will show `ThoughtSpot` as the product name.

Get started link::
A website link that allows users to get started with the product. By default, this link points users to the ThoughtSpot instance to which they are added.

Custom message::
The text to use in the email messages.
+
////
Signup experience::
The signup experience for new ThoughtSpot users. To customize the sign-up experience, turn on the *Signup* toggle and configure the following parameters: 

Signup button text;;
Specify the text for the sign-up button.

Signup button link;;
Enter the URL that you want to use as a sign-up button link.  
////

+ 
. Click *Save changes*.
. To reset the email and onboarding settings to the application default, click *Reset configuration*.



