= Customize navigation panels
:toc: true
:toclevels: 2

:page-title: Customize navigation panels
:page-pageid: customize-nav-controls
:page-description: Customize the navigation panel and menu items in full application embedding using the settings in the Visual Embed SDK

You can customize the navigation experience and the visibility of navigation menu elements using the Visual Embed SDK.

== Navigation experience
The navigation experience in a full application embed includes the following elements:

* Top navigation bar with a modern look and feel. Includes the following components:
** A hamburger icon for the sliding navigation overlay
** Object search bar
** Help and profile icons
** Org switcher
* Left navigation
** A sliding left navigation panel controlled via the hamburger icon
** Persona-based app selection icons in the panel header
** Left navigation menu that adjusts its contents according to the application context

== Customize the top navigation bar
The following customization settings are available for the top navigation bar.

[width="100%", cols="3,2"]
[options="header"]
|====
| SDK property
|Description

| `showPrimaryNavbar`
|Show or hide the navigation panels.

| `hideApplicationSwitcher` +
|Show or hide the application switcher on the left navigation panel.

| `disableProfileAndHelp` +
|Show or hide the help and user profile icons in the top navigation bar.

| `hideOrgSwitcher` +
|Show or hide the Org switcher.

| `hideNotification` +
|Show or hide the notification (bell) icon.

| `hideObjectSearch` +
a|Show or hide the object search bar in the top navigation bar.

NOTE: The object search bar in the embed mode does not support the link:https://docs.thoughtspot.com/cloud/latest/thoughtspot-homepage#command-palette[keyboard commands, window=_blank], such as kbd:[Cmd+K] on macOS or kbd:[Ctrl+K] on Windows, in embedded view.

| `hideHamburger` +
|Show or hide the hamburger icon in the top navigation bar.
|====

=== Example

The following example hides the icons in the top navigation and the application selection menu:

[source,JavaScript]
----
const embed = new AppEmbed("#embed", {
    //... modular home page experience attributes
    showPrimaryNavbar: true,
    hideApplicationSwitcher: true,
    disableProfileAndHelp: true,
    hideObjectSearch: true,
    hideNotification: true,
    //... other attributes
});
----

== Customize the left navigation panel on the home page
In the modular and focused experience modes, the left navigation panel on the *Insights* > *Home* page includes menu items such as *Spotter*, *Answers*, *Liveboards*, *SpotIQ Analysis*, *Monitor Subscriptions*, and more.

You can hide this navigation panel by setting the `hideHomepageLeftNav` property to `true` in the SDK. Note that this attribute hides the left navigation only on the home page.

If you want to include the left navigation, but hide only a specific section in the *Insights* panel, use the `hiddenHomeLeftNavItems` property and specify the menu items to hide. The allowed values for `hiddenHomeLeftNavItems` are listed in the following table:

[width="100%", cols="3,2"]
[options="header"]
|====
| Enum | Description
| `HomeLeftNavItem.Create`
|Show or hide the `+` icon that allows users to create a Liveboard or Answer in the *Insights* panel.
| `HomeLeftNavItem.Home` +
|Show or hide the *Home* menu in the *Insights* panel.
| `HomeLeftNavItem.Spotter` +
|Show or hide the *Spotter* menu item in the *Insights* panel.
| `HomeLeftNavItem.SearchData` +
|Show or hide the *Search Data* in the *Insights* panel.
| `HomeLeftNavItem.Liveboards` +
|Show or hide the *Liveboards* menu in the *Insights* panel.
| `HomeLeftNavItem.Answers` +
|Show or hide the *Answers* menu in the *Insights* panel.
| `HomeLeftNavItem.MonitorSubscription` +
|Show or hide the *Monitor* > *Subscriptions* menu in the *Insights* panel.
| `HomeLeftNavItem.SpotIQAnalysis` +
|Show or hide the *SpotIQ Analysis* menu in the *Insights* panel.
| `HomeLeftNavItem.LiveboardSchedules` +
|Show or hide the *Scheduled Liveboards* section in the *Insights* panel.
| `HomeLeftNavItem.Favorites` +
|Show or hide the *Favorites* menu in the *Insights* panel.
| `HomeLeftNavItem.Collections` +
|Show or hide the *Collections* menu item in the *Insights* left navigation panel.
|====

[source,JavaScript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    HomeLeftNavItem, // Enum for left navigation items
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    // Show navigation bar
    showPrimaryNavbar: true,
    // Show left navigation on home page
    hideHomepageLeftNav: false,
    // Hide SpotIQ analysis and Favorites menu options
    hiddenHomeLeftNavItems: [
        HomeLeftNavItem.Favorites,
        HomeLeftNavItem.SpotIQAnalysis
    ],
    //... other embed view configuration attributes
});
----

== Related resources

* xref:full-app-customize.adoc[Customize full application embedding]
* xref:customize-homepage-full-embed.adoc[Customize home page experience]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events for app interactions]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Action IDs for menu customization]

