= Data APIs
:toc: true
:toclevels: 1

:page-title: data-apis
:page-pageid: data-api
:page-description: Data APIs

ThoughtSpot provides the following API endpoints to fetch data:

* `POST /api/rest/2.0/searchdata` to search data from a given data source.
* `POST /api/rest/2.0/metadata/liveboard/data` to get data from a Liveboard.
* `POST /api/rest/2.0/metadata/answer/data` to get data from a saved Answer.

== Search data API

The `/api/rest/2.0/searchdata` endpoint requires you to specify data source object ID and query string for a successful API call. You can also define additional parameters such as `runtime_filter`, `runtime_sort`, and `runtime_param_override` to apply runtime overrides on the data set.

=== Data source
To search data via API call, you require at least view access to the data source object. The data source object can be a Worksheet, View, or Table.

You can specify the data source object GUID in the `logical_table_identifier`. The search data endpoint doesn't support searching data from multiple Worksheets, Views, or Tables in a single API request.

To find the GUID of the Worksheet, View, or Table, use one of the following methods:

Get data object GUID via API::

Send an API request to the `/api/rest/2.0/metadata/search` endpoint with the following metadata parameters in the metadata array: +

+
[source,JSON]
----
 "metadata": [
    {
      "identifier": "my_worksheet",
      "type": "LOGICAL_TABLE"
    }
  ]
----

+
If you don't know the exact name of the data source object, you can search metadata by specifying the `type` as `LOGICAL_TABLE` and examine the API response and copy the GUID of the data object.

Find the GUID of the data object via UI::
. Log in to your ThoughtSpot application instance:
. Navigate to *Data*.
+
----
https://<your-thoughtspot-instance>/#/data/tables/
----
. On the **Data** > **Home** page, click on data source type. For example, if the data source object is a Worksheet, click **Worksheets** and open the Worksheet.
. In the address bar of the web browser, note the GUID of the data source object.  For example, in the following address string, the GUID is `9d93a6b8-ca3a-4146-a1a1-e908b71b963f`:
+
----
https://<your-thoughtspot-instance>/#/data/tables/9d93a6b8-ca3a-4146-a1a1-e908b71b963f
----
. Copy the GUID.

=== Search query

include::{path}/search-query-string.adoc[]

[source,JSON]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/searchdata' \
  -H 'Authorization: Bearer {access-token}
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "query_string": "[sales][store]",
  "logical_table_identifier": "cd252e5c-b552-49a8-821d-3eadaa049cca",
}'
----

== Fetch Liveboard API
To get data from a Liveboard object and its visualizations via `POST /api/rest/2.0/metadata/liveboard/data` endpoint, you require at least view access to the Liveboard.

The API request body must include the name or GUID of the Liveboard to fetch data. To get specific visualizations from a given Liveboard, add the names or GUIDs of the visualizations in the  `visualization_identifiers` array.

[source,JSON]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/metadata/liveboard/data' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata_identifier": "d084c256-e284-4fc4-b80c-111cb606449a",
  "data_format": "COMPACT",
  "visualization_identifiers": [
    "a9655c18-9855-4a73-9e7b-ff4fb6da334b",
    "bf4c9814-82c1-4ec4-b879-57eae2134cb4",
    "8c46d2b6-94c7-4ba7-a628-6e74e297f973",
    "f6ef5d1f-cddb-4547-8b66-af4d5f4da5ad"
  ]
}'
----

== Fetch Answer Data API
To get data from saved Answer object via `POST /api/rest/2.0/metadata/answer/data` endpoint, you require at least view access to the saved Answer.

The API request body must include the name or GUID of the saved Answer.

[source,JSON]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/metadata/answer/data' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata_identifier": "f605dbc7-db19-450b-8613-307118f74c3c",
}'
----

== Pagination settings for Data APIs

When you make REST API calls to some v2 Data endpoints to query data, the API may return many rows of data in response. By default, the following parameters are set in API requests to the v2 Data API endpoints:

[source,JSON]
----
{
  "data_format": "COMPACT",
  "record_offset": 0,
  "record_size": 10
}
----

For precise results, you set `record_size` to `-1` and `record_offset` to `0`.


`FormatType` is the JSON format type.

[source,JSON]
----
{
    "name": "formattype",
    "description": "FormatType: This sets the JSON format type. Values that are allowed are FULL and COMPACT.",
    "defaultValue": "COMPACT",
    "type": "string"
}
----

`COMPACT` is the default type, and is formatted as follows: `['col1', 'col2'] [1, 'a']`.
While `FULL` is formatted like this:
----
{'col1': 1 'col2': 'a'}
----

=== Runtime overrides in Data APIs
The Data API endpoints support the following runtime overrides:

* Runtime filters
* Runtime sorting of columns
* Runtime Parameters

==== Runtime filters
To add runtime filters, in the `runtime_filter` property, add the `col1`, `op1`, and `val1` parameters JSON key-value format:

[source,JSON]
----
"runtime_filter": {
    "col1": "type",
    "op1": "EQ",
    "val1": "roasted",
}
----

To add additional filters, increment the number at the end of each parameter for each filter: for example, col2, op2, val2, and so on.

[source,JSON]
----
"runtime_filter": {
    "col1": "type",
    "op1": "EQ",
    "val1": "roasted",
    "col2": "tea",
    "op2": "EQ",
    "val2": "barley"
}
----

Some operators such as allow more than one value in the `val` parameter:

[source,JSON]
----
 "runtime_filter": {
    "col1": "tea",
    "op1": "CONTAINS",
    "val1": [
      "barley",
      "mint"
    ],
    "col2": "type",
    "op2": "CONTAINS",
    "val2": [
      "roasted",
      "loose leaves"
    ]
}
----

For more information, see `xref:runtime-filters.adoc#rtOperator[Supported runtime filter operators] and xref:runtime-filters.adoc#_rest_api_v2_0_endpoints[Apply runtime filters via REST APIs].

=== Runtime parameters


== How to search data using the API

To query data using the API, follow these steps:

[#search-data-api-ref]
== Search data API reference

[NOTE]
====
The search data API allows you to pass the search query string as query parameters in the URL. Therefore, ThoughtSpot recommends that you append the query string to the URL, instead of using the `-d <data>` option to pass these parameters in your cURL requests.
====

==== Browser locale

The search data API supports the search query string or keywords in `en-US` language only. Due to this, your browser locale must be set to `en-US` for a successful API call. ThoughtSpot recommends that you set the locale to `en-US` in the HTTP header request.

----
Accept-Language: en-US
----

When making REST API call from a browser, you can set the Accept-Language header directly to override the browser locale for that request.

[source,javascript]
----
// Using XMLHttpRequest
var xhr = XMLHttpRequest();
xhr.setRequestHeader('Accept-Language', 'en-US');
// ...

// Using Fetch
const fetchOptions = {
    method: 'POST',
    headers: {
      'Accept-Language': 'en-US',
      'Content-Type': 'application/json',
      // ...
    },
    // ...
}
----

=== Resource URL
----
POST /tspublic/v1/searchdata
----

=== Request parameters

[width="100%", cols="2,2"]
[options='header']
|====================
| Query parameter | Description
|`query_string` |__String__. The data search query string. For more information, see xref:search-data-api.adoc#components[Components of a search query].

|`data_source_guid` |__String__.  The GUID of the data source, either a Worksheet, a View, or a table.

|`batchsize`  |__Integer__. The batch size for loading search objects.

The system default is -1.
| `pagenumber` | __Integer__. An alternate way to set offset for the starting point of the search results returned from the query. The default value is `-1`.

`indexingOffset = (pageNumber - 1) * batchSize`

| `offset` |__Integer__. Attribute to offset the starting point of the search results returned from the query.  Specify a 1-based offset. The default value is `-1`.

| `formattype` |__String__. The format of the data.

Valid values are `COMPACT` or `FULL` JSON. The default value is `COMPACT`.
|====================

=== Example requests

.cURL (COMPACT)
[source, cURL]
----
curl -X POST \
--header 'Accept-Language: en-US' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT'
----

.cURL (FULL)
[source, cURL]
----
curl -X POST \
--header 'Accept-Language: en-US' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=FULL’
----

.Request URL (COMPACT)
[source, html]
----
https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT
----

.Request URL (FULL)
[source,html]
----
https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=FULL
----

=== Example response

The data the API response contains four components:

. The `columnNames` array that contains a list of all column headers.
. The `data` array that contains a list of sub-arrays. Each sub-array represents a new row of data.
. A sampling ratio.
+
The sampling ratio tells you the percentage of total data returned.
A sampling ratio of `1` indicates that all the data in the Answer object was returned in the API response.

[source,JSON]
----
{
  "columnNames": [
    "Store Region",
    "Total Sales"
  ],
  "data": [
    [
      "east",
      18934491.05134509
    ],
    [
      "midwest",
      29157090.327609923
    ],
    [
      "south",
      25484693.074720126
    ],
    [
      "southwest",
      34241076.52103955
    ],
    [
      "west",
      30848491.458509445
    ]
  ],
  "samplingRatio": 1,
  "totalRowCount": 5,
  "rowCount": 5,
  "pageSize": 100000,
  "offset": 0
}
----

=== Response codes

[options="header", cols="1,2"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of data from the data source
|**400**|Invalid query/data source
|===



Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown:

[source,JSON]
----
{
  "record_offset" : 0,
  "record_size": 10
}
----

For precise results, you can set `record_size` to `-1` and `record_offset` to `0`.
