= Data security
:toc: true
:toclevels: 2

:page-title: Data security
:page-pageid: data-security
:page-description: Data security involves filtering the data queried by ThoughtSpot from the data warehouse

Data security involves filtering the data queried by ThoughtSpot from the data warehouse. It is the next layer of security after access control, which simlpy says if you can see and/or edit the ThoughtSpot object.

Data security in ThoughtSpot is divided into row-level and column-level security, of which row-level security is by far the most common.

== Row-level security (RLS)
Row Level Security (RLS) is the term for filtering down to rows of data based on a set of entitlements for a user. 

ThoughtSpot has three mechanisms for row-level security:

* RLS Rules applied to the ThoughtSpot table objects
* Attribute Based Access Control (ABAC) filters and parameters passed in via login token
* OAuth connections: Individualized login to the data warehouse connection using OAuth, where security rules have already been implimented for each user

== Column-level security (CLS)
