= Data security
:toc: true
:toclevels: 2

:page-title: Data security
:page-pageid: data-security
:page-description: Data security involves filtering the data queried by ThoughtSpot from the data warehouse

Data security involves filtering the data queried by ThoughtSpot from the data warehouse. It is the next layer of security after access control, which simlpy says if you can see and/or edit the ThoughtSpot object.

Data security in ThoughtSpot is divided into row-level and column-level security, of which row-level security is by far the most common.

== Row-level security (RLS)
Row Level Security (RLS) is the term for filtering down to rows of data based on a set of entitlements for a user. 

ThoughtSpot has three mechanisms for row-level security:

* xref:rls-rules.adoc[RLS Rules] applied to the ThoughtSpot table objects
* xref:abac-user-parameters.adoc[Attribute Based Access Control (ABAC)] filters and parameters passed in via login token
* link:https://docs.thoughtspot.com/cloud/latest/connections-snowflake-oauth[OAuth connections, _target=blank]: Individualized login to the data warehouse connection using OAuth, where security rules have already been implimented for each user

The OAuth workflow requires openning a new window or redirecting to the OAuth provider for the initial sign-in workflow, making it less seamless than using a service account and defining data security via ThoughtSpot. It tends to be used for non-embedded ThoughtSpot use cases or for embedded applications for an organization's internal users with existing indivdual data warehouse user accounts.

== Column-level security (CLS)
CLS restricts user access to specific columns of a table. When CLS is applied, users see only the columns that they are allowed to view. Object owners can configure CLS by sharing a relevant set of columns in a table with a specific user or user group. 

+
For more information, see link:https://cloud-docs.thoughtspot.com/admin/data-security/share-source-tables.html[Sharing tables and columns, window=_blank].
