= Deprecation announcements
:toc: true
:toclevels: 1

:page-title: Deprecation announcements
:page-pageid: deprecated-features
:page-description: This article lists features deprecated and no longer supported in ThoughtSpot Embedded

As ThoughtSpot applications evolve, some existing features will be deprecated and replaced with new and improved functionality. A deprecated feature may continue to be functional for a short period, but will not be maintained or supported with new workflows and functionality in subsequent releases.

== Deprecated features

[width="100%" cols="3,4,2,2"]
[options='header']
|=====
|Feature|Impacted interfaces and versions|Deprecation announcement date|Deprecation date
|xref:deprecated-features.adoc#classicExpDeprecation[Classic experience for Liveboards, Answers, and SpotIQ, window=_blank] a|Application UI +

* ThoughtSpot Cloud 10.1.0.cl
* ThoughtSpot Software 10.5.0.sw|August 2024| August 2024
|xref:deprecated-features.adoc#_application_background_customization_via_ui[Application Background style customization] a|Application UI +

* ThoughtSpot Cloud 10.2.0.cl
* ThoughtSpot Software 10.5.0.sw |July, 2024|September 2024
|xref:deprecated-features.adoc#_deprecation_of_customcssurl_parameter[*customCssUrl* parameter] a|ThoughtSpot Embedded interfaces +

* Visual Embed SDK version 1.30.0
* ThoughtSpot Cloud 10.0.0.cl
* ThoughtSpot Software 9.5.1.sw|June, 2024|July, 2024
a|xref:deprecated-features.adoc#_deprecated_parameter_in_rest_api_v2_0_authentication_token_endpoints[*jwt_user_options*] parameter a| REST API v2.0 authentication token endpoints +

* ThoughtSpot Cloud 9.12.0.cl
* ThoughtSpot Software 10.0.0.sw
|May, 2024 | June, 2024
|xref:deprecated-features.adoc#_deprecated_parameters_in_version_control_apis[*default_branch_name* and *guid_mapping_branch_name*] parameters a|REST API v2 version control APIs

* ThoughtSpot Cloud 9.10.5.cl
* ThoughtSpot Software 10.0.0.sw|March, 2014|April, 2014

|xref:deprecated-features.adoc#_deprecation_of_rest_api_v2_beta_endpoints[REST API v2 ^Beta^ endpoints]|REST API|September, 2022| January, 2023
||||
|=====

[#classicExpDeprecation]
== Classic experience for Liveboards, Answers, and SpotIQ
Starting from 10.1.0.cl, classic experience for Liveboards, Answers, and SpotIQ will no longer be available. On ThoughtSpot embedded instances, developers will no longer be able to switch to the Liveboard classic experience using the `liveboardV2` parameter in the Visual Embed SDK.

Effective from::
* ThoughtSpot Cloud 10.1.0.cl
* ThoughtSpot Software 10.5.0.sw

Recommended action::
If you are using Liveboards in the classic experience mode, note that the new experience will become the only available option when your instance is upgraded to 10.1.0.cl. On ThoughtSpot embedded instances, the `"liveboardv2":"false"` setting in the SDK becomes invalid as classic experience will no longer be available.

== Application background customization via UI

The application background customization option that is currently available on the **Admin** > **Style customization** and **Develop** > **Customizations** > **Styles** will be deprecated in the upcoming version.

Effective from::
* ThoughtSpot Cloud 10.2.0.cl
* ThoughtSpot Software 10.5.0.sw

Recommended action::
To customize the background color of ThoughtSpot application, use the `--ts-var-root-background` CSS variable available with the CSS customization framework and Visual Embed SDK. For more information, see xref:css-customization.adoc[CSS customization framework].

== Deprecation of customCssUrl parameter

The `customCssUrl` parameter in the xref:EmbedConfig.adoc#_customcssurl[EmbedConfig interface] in the Visual Embed SDK is deprecated and will not be supported in future release versions.

Effective from::
* Visual Embed SDK version 1.30.0
* ThoughtSpot Cloud 10.0.0.cl
* ThoughtSpot Software 9.5.1.sw

Recommended action::
If you are using the xref:css-customization.adoc[CSS variables and overrides] feature to rebrand or customize embedded pages, no action is required. However, if your implementation uses the `customCssUrl` parameter in the xref:EmbedConfig.adoc#_customcssurl[EmbedConfig interface] to point to a custom CSS file, ThoughtSpot recommends switching to the `customCSSUrl` property in the xref:CustomStyles.adoc#_customcssurl[customizations interface] in the `init` code as shown in this example:

[source,JavaScript]
----
init({
  thoughtSpotHost: "https://<ThoughtSpot-Host>",
  authType: AuthType.None,
  customizations: {
    style: {
       customCSSUrl: 'https://cdn.jsdelivr.net/cssfilename.css',
    },
  },
});
----

If you are embedding ThoughtSpot without the SDK, you can switch to Visual Embed SDK and use the customization framework, or contact ThoughtSpot Support to configure your embed to point to your custom CSS file.

== Deprecated parameter in REST API v2.0 authentication token endpoints

The `jwt_user_options` object property in `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` is deprecated.

Effective from::
* ThoughtSpot Cloud 9.12.0.cl
* ThoughtSpot Software 10.0.0.sw

Recommended action::
Use the `user_parameters` property available with the `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` endpoints to define security entitlements to a user session. +
For more information, see xref:abac-user-parameters.adoc[ABAC via token][beta betaBackground]^Beta^.

== Deprecated parameters in Version Control APIs

The `default_branch_name` and `guid_mapping_branch_name` parameters available with the  `/api/rest/2.0/vcs/git/config/create` and  `/api/rest/2.0/vcs/git/config/update` endpoints are deprecated.

Effective from::
* ThoughtSpot Cloud 9.10.5.cl
* ThoughtSpot Software 10.0.0.sw

Recommended action::

* `default_branch_name` is replaced by the `commit_branch_name` parameter.
* `guid_mapping_branch_name` is replaced by the `configuration_branch_name` parameter.

Use the new parameters to configure Git branches for version control. For more information, see xref:version_control.adoc[Git integration and version control].

== Deprecation of REST API v2 (Beta) endpoints

The REST API v2 [beta betaBackground]^Beta^ endpoints are deprecated from 8.10.0.cl release. These API endpoints will remain functional but will not be accessible from the REST API Playground page from 9.0.0.cl onwards.

Effective from::
* ThoughtSpot Cloud 8.10.0.cl
* ThoughtSpot Software 9.0.1.sw

Recommended action::
If your current deployment uses REST API v2 [beta betaBackground]^Beta^ endpoints, your implementation may continue to work. However, we recommend transitioning to the REST API v2.0 endpoints as and when ThoughtSpot rolls out the new APIs for production use cases and General Availability (GA).

==== REST API v2 SDK
The REST API v2 [beta betaBackground]^Beta^ SDK is deprecated from 8.8.0.cl onwards. ThoughtSpot does not recommend using REST API SDK to call REST API v2 [beta betaBackground]^Beta^ v2.0 endpoints.

Effective from::
* ThoughtSpot Cloud 8.8.0.cl
* ThoughtSpot Software 9.0.1.sw

Recommended action::
Use the new version of REST API v2.0 endpoints and SDK versions available for these endpoints. For more information, see xref:rest-api-sdk-libraries.adoc[REST API v2.0 SDKs].

==== Documentation
Starting from 9.0.0.cl, the API documentation for the REST API v2 [beta betaBackground]^Beta^ endpoints will not be accessible from the REST API Playground in ThoughtSpot.
For information about the REST API v2 [beta betaBackground]^Beta^ endpoints, see xref:rest-api-v2-reference-beta.adoc[REST API v2 ^Beta^ reference].

Recommended action::
For information about REST API v2.0 endpoints, refer to the following articles and visit the link:{{navprefix}}/restV2-playground?apiResourceId=http%2Fgetting-started%2Fintroduction[REST API v2 Playground].

* xref:rest-api-v2-getstarted.adoc[REST API v2.0]
* xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison]
