= Deprecation announcements
:toc: true
:toclevels: 1

:page-title: Deprecation announcements
:page-pageid: deprecated-features
:page-description: This article lists features deprecated and no longer supported in ThoughtSpot Embedded

As ThoughtSpot applications evolve, some existing features will be deprecated and replaced with new and improved functionality. A deprecated feature may continue to be functional for a short period, but will not be maintained or supported with new workflows and functionality in subsequent releases.

== Deprecated features

[width="100%" cols="4,5,4,4"]
[options='header']
|=====
|Feature|Impacted interface and release versions|Deprecation date |End of Support / removal from the product
a|xref:deprecated-features.adoc#SagePrivilegeDeprecation[`PREVIEW_THOUGHTSPOT_SAGE` privilege deprecation] a|ThoughtSpot Cloud 26.3.0.cl and later | March 2026 | May 2026
a|xref:deprecated-features.adoc#_answer_data_panel_classic_experience_deprecation[Answer Data panel classic experience] |ThoughtSpot Cloud 26.4.0.cl and later | April 2026 | August 2026
a|xref:deprecated-features.adoc#_worksheet_deprecation_and_removal[Worksheets] a| ThoughtSpot Cloud 10.4.0.cl and later
|November 2024 | September 2025

a|xref:deprecated-features.adoc#restApiPlayground[REST API v1 Playground] a| ThoughtSpot Cloud 10.14.0.cl and later
|November 2025 | November 2025

a|xref:deprecated-features.adoc#SageDeprecationNotice[Sage Search and Ask Sage] a|
* ThoughtSpot Cloud 10.13.0.cl and later
* Visual Embed SDK version 1.40.0 and later
| September 2025 | December 2025
a|xref:deprecated-features.adoc#connectionAPIs[Delete and update connection API v2 endpoints]

a|REST API v2 +

* ThoughtSpot Cloud 10.4.0.cl and later|November 2024 a| September 2025

|xref:deprecated-features.adoc#IAMv1[IAMv1] a|

* ThoughtSpot Cloud 10.8.0.cl and later

|November 2024 | June 2025 __(tentative)__

|xref:deprecated-features.adoc#_search_assist[Search Assist] a|
* Application UI and Visual Embed Playground +
** ThoughtSpot Cloud 10.1.0.cl and later
** ThoughtSpot Software 10.1.0.sw and later

* Visual Embed SDK version 1.35.0 and later
|September 2024 | November 2024

|xref:deprecated-features.adoc#classicExpDeprecation[Classic experience for Liveboards, Answers, and SpotIQ] a|Application UI +

* ThoughtSpot Cloud 10.1.0.cl and later
* ThoughtSpot Software 10.1.0.sw and later|February 2024| August 2024
|xref:deprecated-features.adoc#_page_title_customization[Page title customization] a|Application UI +

* ThoughtSpot Cloud 10.1.0.cl and later
* ThoughtSpot Software 10.1.0.sw and later|February 2024| August 2024
|xref:deprecated-features.adoc#_application_background_customization_via_ui[Application Background style customization] a|Application UI +

* ThoughtSpot Cloud 10.3.0.cl and later
* ThoughtSpot Software 10.7.0.sw and later |July 2024|September 2024
|xref:deprecated-features.adoc#_deprecation_of_customcssurl_parameter[*customCssUrl* parameter] a|ThoughtSpot Embedded interfaces +

* Visual Embed SDK version 1.30.0 and later
* ThoughtSpot Cloud 10.0.0.cl and later
* ThoughtSpot Software 9.5.1.sw and later|June 2024|July 2024
a|xref:deprecated-features.adoc#_deprecated_parameter_in_rest_api_v2_0_authentication_token_endpoints[*jwt_user_options*] parameter a| REST API v2.0 authentication token endpoints +

* ThoughtSpot Cloud 9.12.0.cl and later
* ThoughtSpot Software 10.1.0.sw and later
|May 2024 | June 2024
|xref:deprecated-features.adoc#_deprecated_parameters_in_version_control_apis[*default_branch_name* and *guid_mapping_branch_name*] parameters a|REST API v2 version control APIs

* ThoughtSpot Cloud 9.10.5.cl and later
* ThoughtSpot Software 10.1.0.sw and later|March 2024|April 2024

|xref:deprecated-features.adoc#_deprecation_of_rest_api_v2_beta_endpoints[REST API v2 ^Beta^ endpoints] a|REST API +

* ThoughtSpot Cloud 9.0.0.cl and later
* ThoughtSpot Software 9.0.1.sw and later
|September 2022| January 2023
||||
|=====

[#SagePrivilegeDeprecation]
== `PREVIEW_THOUGHTSPOT_SAGE` privilege deprecation
The `PREVIEW_THOUGHTSPOT_SAGE` privilege is renamed to `CAN_USE_SPOTTER` with the ThoughtSpot 26.3.0.cl release version.

Impact on your instance::
* Both privileges remain supported until the ThoughtSpot 26.5.0.cl release, at which point `PREVIEW_THOUGHTSPOT_SAGE` will be removed.
* For existing ThoughtSpot instances which have enabled RBAC before the 26.3.0.cl release, there will be no automatic changes to the roles created using the `PREVIEW_THOUGHTSPOT_SAGE` privilege. However, the underlying privilege associated with such roles will be renamed to `CAN_USE_SPOTTER`.

Recommended action::
For ThoughtSpot instances which have enabled RBAC before the 26.3.0.cl release, the admins will have to create a role in accordance with the newer privilege name.


== Answer Data panel classic experience deprecation
The classic Data panel experience in Search and Answer pages will be deprecated in ThoughtSpot 26.4.0.cl release version. The new data panel experience, which provides a more intuitive layout with improved organization of data elements and features such as query sets and custom groups, will be the default data panel experience on all ThoughtSpot Embedded instances using Visual Embed SDK v1.41.1 or later.

Recommended action::
If your instance is still using the classic experience, we recommend switching to the new experience, testing your rollout, and updating your application workflows for a seamless embedding experience. You can enable the new data panel experience using the xref:embed-search.adoc#_data_panel_experience_in_the_embedded_search_page[dataPanelV2] attribute in the Visual Embed SDK. +
For more information and migration assistance, contact ThoughtSpot Support.

== Worksheet deprecation and removal

Starting with 10.4.0.cl, Worksheets are deprecated and disabled by default in ThoughtSpot. In ThoughtSpot Cloud 10.12.0.cl and later versions, the ability to create new Worksheets will be removed, and all existing Worksheets will be automatically migrated to Models.

Impact on your instance::

All existing Worksheets on your instance will be migrated automatically to Models, and Worksheets will no longer be available in the ThoughtSpot UI after the 10.12.0.cl release. Note that even adding a dbt connection will result in the creation of a Model. However, if you are using Worksheets in Git workflows or CI/CD pipelines that rely on import or create, those will continue to work temporarily until 10.13.0.cl.
+
Starting with 10.13.0.cl, import of worksheet TMLs will be blocked. Any such operations will fail with an error, requiring users to convert Worksheets to Models before importing. You may want to update your CI/CD and Git workflows to use Model TMLs instead of Worksheets.

Recommended action::
* If your instance has Worksheets, verify whether they are replaced with Models after your instance is upgraded to 10.12.0.cl.
* If you are importing Worksheet TML, the import operation will fail. Therefore, ThoughtSpot recommends converting Worksheets to Models and then importing Model TMLs to ThoughtSpot.
* Update your CI/CD and Git workflows to use Model TMLs instead of Worksheets.
* In REST APIs, the subtypes of `LOGICAL_TABLE`  objects may still be referred to as Worksheet. However, these subtypes  imply Models. When you specify subtype `WORKSHEET`, the API will include Models in the response or operation.
* You may find the "Worksheet" terminology in the Visual Embed SDK configuration properties and feature flags; for example, the `worksheetId` property in Spotter embed. However, when configuring these settings, use the Model object and its associated properties.

[#restApiPlayground]
== REST API v1 Playground deprecation

The REST API v1 Playground experience that is currently available from the *Develop* page of the ThoughtSpot UI will be removed from the UI in the 10.14.0.cl release version.

Impact on your instance::
Only the REST API v1 Playground will be removed from the ThoughtSpot UI. However, the REST API v1 endpoints will still be available for API calls from client applications and will continue to function as usual.

Recommended action::
When the REST API v1 Playground is no longer available in the ThoughtSpot UI, use the xref:rest-api-reference.adoc[REST API v1 Reference Guide] for information about the REST API v1 endpoints, request and response flows. Additionally, ThoughtSpot recommends that you gradually migrate your application workflows to REST API v2 endpoints. The REST API v2 framework is regularly updated with new enhancements and bug fixes, and also offers a more standardized API experience.

[#SageDeprecationNotice]
== Sage and Ask Sage deprecation

The Sage Search (the legacy Natural Language Search interface) and *Ask Sage* features are deprecated from 10.11.0.cl and will be removed from the product in December 2025.
Along with this, the xref:SageEmbed.adoc[SageEmbed] library in the Visual Embed SDK will also be deprecated.

//with no new enhancements or bug fixes supported after July 2025.

Impact on your instance::
This change will impact all ThoughtSpot instances and applications that use the xref:embed-nls.adoc[Natural Language Search (legacy) interface embedded using the SageEmbed] library in Visual Embed SDK.

Recommended action::
Customers using the legacy Natural Language Search interface and *Ask Sage* in their embedding applications are advised to upgrade to Spotter. We recommend that you start using Spotter by the 10.11.0.cl release (July 2025), so that you have sufficient time to test your rollout. +
Spotter provides advanced natural language search capabilities and a conversational interface to allow users to interact with the AI analyst and ask follow-up questions. To know more about Spotter and learn how to embed Spotter in your embedding application, refer to the following documentation:

* link:https://www.thoughtspot.com/product/ai-analyst[About Spotter, window=_blank]
* xref:embed-spotter.adoc[How to embed Spotter]
* link:https://docs.thoughtspot.com/cloud/latest/spotter[How to use Spotter, window=_blank]
+
For additional queries and assistance, contact ThoughtSpot Support.

[#connectionAPIs]
== Delete and update connection API v2 endpoints
The following Connection API v2 endpoints are deprecated and will be removed from the product in September 2025: +

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fdelete-connection">POST /api/rest/2.0/connection/delete</a>+++
* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fupdate-connection">POST /api/rest/2.0/connection/update </a>+++

**Effective from** +
ThoughtSpot Cloud 10.4.0.cl

=== Recommended action
Use the following API endpoints to update and delete connection objects: +

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fupdate-connection-v2">POST /api/rest/2.0/connections/{connection_identifier}/update </a>+++
* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fdelete-connection-v2">POST /api/rest/2.0/connections/{connection_identifier}/delete </a>+++

Note that the `connection_identifier` in both these endpoints is a path parameter and must be included in the request URLs for update and delete operations.

[#IAMv1]
== IAMv1
Identity and Access Management (IAMv1) will be deprecated for all ThoughtSpot embedded customers tentatively in 10.8.0.cl. IAMv2 will be enabled on ThoughtSpot instances during maintenance windows from 10.4.0.cl onwards.

Effective from::
* ThoughtSpot Cloud 10.8.0.cl

=== Recommended action

* Ensure that you are ready for migration by reviewing and following the link:https://docs.thoughtspot.com/cloud/latest/okta-iam#_before_migrating_to_iam_v2[steps in the product documentation, window=_blank], so that there is no login disruption for your users after migration. +
For more information, see link:https://docs.thoughtspot.com/cloud/latest/okta-iam[Identity and Access Management V2, window=_blank].
* Accept in-product notifications for IAM updates.
* Contact link:https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support] for assistance.

== Search assist

The Search Assist feature in **Data workspace** > **Worksheets** is deprecated. Due to this, the **Enable Search Assist** checkbox in the Visual Embed Playground and `enableSearchAssist` property in the SDK may not show the intended result.

Effective from::
* ThoughtSpot Cloud 10.1.0.cl
* ThoughtSpot Software 10.1.0.sw

Recommended action::
The Search Assist feature for Worksheets and the **Enable Search Assist** checkbox in Search Embed Playground will be removed from ThoughtSpot application in 10.4.0.cl. If your embedding application uses the `enableSearchAssist` property, you may want to update your deployment.

[#classicExpDeprecation]
== Classic experience for Liveboards, Answers, and SpotIQ
Starting from 10.1.0.cl, classic experience for Liveboards, Answers, and SpotIQ will no longer be available. On ThoughtSpot embedded instances, developers will no longer be able to switch to the Liveboard classic experience using the `liveboardV2` parameter in the Visual Embed SDK.

Effective from::
* ThoughtSpot Cloud 10.1.0.cl
* ThoughtSpot Software 10.1.0.sw

=== Recommended action
If you are using Liveboards in the classic experience mode, note that the new experience will become the only available option when your instance is upgraded to 10.1.0.cl. On ThoughtSpot embedded instances, the `"liveboardv2":"false"` setting in the SDK becomes invalid as classic experience will no longer be available.

== Page title customization
The Page title customization option on the **Admin** > **Style customization** and **Develop** > **Customizations** > **Styles** page is deprecated and removed from the UI. The **Page title** customization setting allowed administrators and developers to customize the title of the browser tab for ThoughtSpot application pages. This setting is deprecated to allow administrators to use the **Product name** parameter in the **Admin** > **Onboarding** page as a single setting to customize product name for all purposes.

Effective from::
* ThoughtSpot Cloud 10.1.0.cl
* ThoughtSpot Software 10.1.0.sw

=== Recommended action
If you have customized the **Page title** setting, after your instance is upgraded to 10.1.0.cl, the browser tab loading ThoughtSpot application pages will display the title in the following format:

* Liveboard or Answer page - `<Object name> | <Product name>`
* Other application pages - `<Product name>`

Administrators can use the **Product name** parameter in the **Admin** > **Onboarding** page to customize the product name displayed in browser tab titles.

Note that this change will not impact full application embedding if your host application uses its own browser tab titles.

== Application background customization via UI

The application background customization option that is currently available on the **Admin** > **Style customization** and **Develop** > **Customizations** > **Styles** will be deprecated in the upcoming version.

Effective from::
* ThoughtSpot Cloud 10.3.0.cl
* ThoughtSpot Software 10.7.0.sw

=== Recommended action
To customize the background color of ThoughtSpot application, use the `--ts-var-root-background` CSS variable available with the CSS customization framework and Visual Embed SDK. For more information, see xref:css-customization.adoc[CSS customization framework].

== Deprecation of customCssUrl parameter

The `customCssUrl` parameter in the xref:EmbedConfig.adoc#_customcssurl[EmbedConfig interface] in the Visual Embed SDK is deprecated and will not be supported in future release versions.

Effective from::
* Visual Embed SDK version 1.30.0
* ThoughtSpot Cloud 10.0.0.cl
* ThoughtSpot Software 9.5.1.sw

=== Recommended action
If you are using the xref:css-customization.adoc[CSS variables and overrides] feature to rebrand or customize embedded pages, no action is required. However, if your implementation uses the `customCssUrl` parameter in the xref:EmbedConfig.adoc#_customcssurl[EmbedConfig interface] to point to a custom CSS file, ThoughtSpot recommends switching to the `customCSSUrl` property in the xref:CustomStyles.adoc#_customcssurl[customizations interface] in the `init` code as shown in this example:

[source,JavaScript]
----
init({
  thoughtSpotHost: "https://<ThoughtSpot-Host>",
  authType: AuthType.None,
  customizations: {
    style: {
       customCSSUrl: 'https://cdn.jsdelivr.net/cssfilename.css',
    },
  },
});
----

If you are embedding ThoughtSpot without the SDK, you can switch to Visual Embed SDK and use the customization framework, or contact ThoughtSpot Support to configure your embed to point to your custom CSS file.

== Deprecated parameter in REST API v2.0 authentication token endpoints

The `jwt_user_options` object property in `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` is deprecated.

Effective from::
* ThoughtSpot Cloud 9.12.0.cl
* ThoughtSpot Software 10.1.0.sw

=== Recommended action
Use the `user_parameters` property available with the `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` endpoints to define security entitlements to a user session. +
For more information, see xref:abac-user-parameters.adoc[ABAC via token][beta betaBackground]^Beta^.

== Deprecated parameters in Version Control APIs

The `default_branch_name` and `guid_mapping_branch_name` parameters available with the  `/api/rest/2.0/vcs/git/config/create` and  `/api/rest/2.0/vcs/git/config/update` endpoints are deprecated.

Effective from::
* ThoughtSpot Cloud 9.10.5.cl
* ThoughtSpot Software 10.1.0.sw

=== Recommended action

* `default_branch_name` is replaced by the `commit_branch_name` parameter.
* `guid_mapping_branch_name` is replaced by the `configuration_branch_name` parameter.

Use the new parameters to configure Git branches for version control. For more information, see xref:version_control.adoc[Git integration and version control].

== Deprecation of REST API v2 (Beta) endpoints

The REST API v2 [beta betaBackground]^Beta^ endpoints are deprecated from 8.10.0.cl release. These API endpoints will remain functional but will not be accessible from the REST API Playground page from 9.0.0.cl onwards.

Effective from::
* ThoughtSpot Cloud 8.10.0.cl
* ThoughtSpot Software 9.0.1.sw

=== Recommended action
If your current deployment uses REST API v2 [beta betaBackground]^Beta^ endpoints, your implementation may continue to work. However, we recommend transitioning to the REST API v2.0 endpoints as and when ThoughtSpot rolls out the new APIs for production use cases and General Availability (GA).

=== REST API SDK for v2 (Beta) endpoints
The REST API v2 [beta betaBackground]^Beta^ SDK is deprecated from 8.8.0.cl onwards. ThoughtSpot does not recommend using REST API SDK to call REST API v2 [beta betaBackground]^Beta^ v2.0 endpoints.

Effective from::
* ThoughtSpot Cloud 8.8.0.cl
* ThoughtSpot Software 9.0.1.sw

=== Recommended action
Use the new version of REST API v2.0 endpoints and SDK versions available for these endpoints. For more information, see xref:rest-api-sdk-libraries.adoc[REST API v2.0 SDKs].

==== Documentation
Starting from 9.0.0.cl, the API documentation for the REST API v2 [beta betaBackground]^Beta^ endpoints will not be accessible from the REST API Playground in ThoughtSpot.
For information about the REST API v2 [beta betaBackground]^Beta^ endpoints, see xref:rest-api-v2-reference-beta.adoc[REST API v2 ^Beta^ reference].

Recommended action::
For information about REST API v2.0 endpoints, refer to the following articles and visit the link:{{navprefix}}/restV2-playground?apiResourceId=http%2Fgetting-started%2Fintroduction[REST API v2 Playground].

* xref:rest-api-v2-getstarted.adoc[REST API v2.0]
* xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison]
