= Embed AI Search and Analytics
:toc: true
:toclevels: 3

:page-title: Embed AI Search and Analytics
:page-pageid: embed-ai-search-analytics
:page-description: To embed ThoughtSpot Spotter and conversational analytics experience in your app, you can use the `SpotterEmbed` or `SpotterAgentEmbed` SDK library.

ThoughtSpot Spotter provides an interactive AI-powered Search and conversation analytics experience for its application users. With ThoughtSpot Spotter, users can query data in plain language, ask follow-up questions, and get insights directly from their data. ThoughtSpot also provides an agentic version of Spotter for a more advanced experience with context-based conversations and responses for deeper analysis.

== Embed components
For embedding applications, ThoughtSpot provides two distinct SDK libraries to embed Spotter capabilities in their app:

* xref:embed-spotter.adoc[`SpotterEmbed`] +
To embed the full Spotter interface with a conversation panel that allows natural language text strings, data source selection, and interactions with AI generated Answers, use the `SpotterEmbed` component.
For more information, see xref:embed-spotter.adoc[Embed Spotter].
* xref:embed-spotter-agent.adoc[`SpotterAgentEmbed`] +
Also refer to as `bodyless` embed, the Spotter Agent embedding allows you to integrate natural language data search and analysis into your own applications or chatbot. Unlike the standard Spotter embed, which provides a ready-made search bar and interface, the `SpotterAgentEmbed` component is designed for deeper customization, allowing full control over the look and feel, and workflow of the embedded analytics experience. It allows you to build your own UI or agent experience, route user questions to ThoughtSpot, and receive structured answers and visualizations.

[NOTE]
====
* The `ConversationEmbed` and `BodylessConversation` components are deprecated and replaced with `SpotterEmbed` and `SpotterAgentEmbed` respectively in Visual Embed SDK v1.38.0 and later.
* If you are embedding full ThoughtSpot experience in your app via `AppEmbed`, you must enable new home page experience and set the home page search bar mode to `aiAnswer` to view Spotter components. For more information, see xref:full-app-customize.adoc#_include_spotter_interface[Customize full application embedding].
====

== Spotter embed and Spotted Agent embed comparison

[width="100%" cols="7,5,5"]
[options='header']

|=====
|
| Spotter embed
| Spotter Agent embed (Bodyless/Agent)

|Use case
|Use this method to integrate the built-in AI search and conversation analytics interface in your app.
|Use this method to embed Spotter Search capabilities in your chatbot, virtual agent or an app with your own interface elements and user-experience.

| Embedding component
| Use `SpotterEmbed` component in the Visual Embed SDK library
| Use `SpotterAgentEmbed` component in the Visual Embed SDK library

| Data context
a| * Supported data object is Model +
   * Allows data source selection
a| * Supported data object is Model
   * Data source is passed in the code. No explicit selection is allowed unless the embedding application UI allows it.

| Customization
| The SDK provides several props, object properties, CSS and text customization options for branding and styling, event handlers for host and embed app interaction, and menu action configuration
| The SDK provides limited customization options as the UI/UX controlled by host application.

| Sample Questions
| The SDK provides the ability to show or hide sample questions via `hideSampleQuestions`.
| Not applicable
|=====

== Customization options in the SDK

Visual Embed SDK provides several view configuration settings and customization options for customizing Spotter embeds:

* Configuration properties to enable or disable features.
For more information, see xref:_spotterembedviewconfig.adoc[SpotterEmbedViewConfig] and xref:SpotterAgentEmbedViewConfig.adoc[SpotterAgentEmbedConfig]
* Action customization framework to show or hide actions in the embedded view +
For more information, see xref:Action.adoc[Action] and xref:embed-action-ref.adoc[Action IDs in the SDK]
* Event handlers for host and embed app interaction +
For more information, see xref:EmbedEvent.adoc[Embed events], xref:HostEvent.adoc[Host events], and xref:embed-events.adoc[Events and app interactions]
* Style customization framework for customizing styles, text strings, and icons +
See xref:css-customization.adoc[style customization framework]


== Additional resources
* link:https://docs.thoughtspot.com/cloud/latest/spotter[Spotter Documentation]
* link:https://docs.thoughtspot.com/cloud/latest/spotter-agent[Spotter Agent Documentation]
