= Events and app interactions
:toc: true
:toclevels: 2

:page-title: Events and app integration
:page-pageid: events-app-integration
:page-description: Events allow the embedding application to send and receive messages from embedded ThoughtSpot components.

ThoughtSpot Visual Embed SDK library supports the following event objects:

* `EmbedEvent` +
Events emitted by ThoughtSpot to your host application to notify when an application event occurs inside the embed.
* `HostEvent` +
Events triggered by your host application to send a command into the embed and initiate an action.

You can configure your embed to listen to these events aand respond with appropriate actions. The embedded ThoughtSpot components emit events when they initialize, load, or when a user interaction or response is detected inside the embed. The host application can also trigger events to initiate specific actions in the embedded components, causing navigation, filter changes, alerts, or other actions.

Visual Embed SDK v1.46.0 and later also supports explicit and implicit context‑aware routing of host events, giving you precise control over host event behavior in multi‑layer UI scenarios.

== Next steps

* xref:event-embedEvents.adoc[Learn more about embed events]
* xref:events-hostEvents.adoc[Learn how to configure host events]
* xref:events-context-aware-routing.adoc[Learn how to configure context-aware host events]

////

Verify the text for accuracy. QueryChanged can be fired on SageEmbed and SpotterEmbed as well.

==  SearchEmbed Events
There are several events that fire only on the `SearchEmbed` component:

* `DataSourceSelected`
+
Fires when a change occurs in the data sources, including the initial load of the `SearchEmbed` component. Can be used to hide a loader screen. Return object contains an array of the selected column GUIDs (accessible using `LOGICAL_COLUMN` type within metadata REST API commands).

* `QueryChanged`
+
Fires when a change occurs in the search bar, including the initial load of the `SearchEmbed` component. The returned object includes a `data.search` property with the TML search query from the search box.
////

== Related resources

* See xref:EmbedEvent.adoc[EmbedEvent] and xref:HostEvent.adoc[HostEvent] SDK documentation.
* For information about triggering events on React components, see xref:react-components_lesson-04.adoc[Event listeners for React components].