= Feature matrix
:toc: true

:page-title: Feature matrix and license types
:page-pageid: license-feature-matrix
:page-description: Choose the license model as per your embedding requirements.

The following table lists the features available with ThoughtSpot Analytics and embedding licenses:

[div tableContainer]
--

[width="100%" cols="7,5,5,5,5,5"]
[options='header']
|=====
|Feature|ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license| ThoughtSpot Everywhere License +
|Free Trial account +

(Evaluation only) |Developer Playground on public instance +
(Evaluation only)

|Access to **Develop** tab +
__Requires developer or admin  privileges__ |[tag greenBackground tick]#✓# 2*| [tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#  |[tag greenBackground tick]#✓#
| Visual Embed Playground|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#| [tag greenBackground tick]#✓#
|REST API Playground |[tag greenBackground tick]#✓#  2*| [tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#
|Embedding with Visual Embed SDK +
|[tag greyBackground tick]#–# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#

5+|*Authentication and security* + |

|Basic authentication + |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#

|SAML SSO |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#|[tag greyBackground tick]#–#
|OIDC authentication |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#|[tag greyBackground tick]#–#
|Trusted authentication +
SAML redirect domain configuration |[tag greyBackground tick]#–#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#|[tag greyBackground tick]#–#

|CSP and CORS settings| [tag greenBackground tick]#✓# 2*| [tag greenBackground tick]#✓# | [tag greyBackground tick]#–# | [tag greyBackground tick]#–#

5+|*REST APIs* + |

a|Embedding Liveboards and charts using data APIs +
|[tag greyBackground tick]#–#  +
2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#  +
|[tag greyBackground tick]#–#

a|REST API v1 endpoints

|[tag greenBackground tick]#✓#  2*|[tag greenBackground tick]#✓#
| [tag greenBackground tick]#✓#  | [tag greyBackground tick]#–#

a|REST API v2.0 endpoints |[tag greenBackground tick]#✓#
 2*|[tag greenBackground tick]#✓#  + |[tag greenBackground tick]#✓#  |[tag greyBackground tick]#–#

5+|*REST API authentication options* + |

|Basic authentication + |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#
|Bearer token authentication (REST API v2.0 only)|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#
|Trusted authentication |[tag greyBackground tick]#–#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#|[tag greyBackground tick]#–#

5+|*Custom actions* + |
|URL-based custom actions|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#|[tag greyBackground tick]#–#
|Callback custom actions|[tag greyBackground tick]#–# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#|[tag greyBackground tick]#–#
5+|*Custom styles* + |
|Style customization via UI|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
|CSS customization |[tag greyBackground tick]#–# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
|CSP overrides for fonts, styles, and images|[tag greyBackground tick]#–#  2*| [tag greenBackground tick]#✓# | [tag greyBackground tick]#–# | [tag greyBackground tick]#–#
5+|*Link settings* + |
|Custom link format|[tag greyBackground tick]#–# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
|=====
--
////

a|Runtime filters

(Available on embedded ThoughtSpot instances only) | [tag greenBackground tick]#✓# REST APIs

(Basic authentication only)

|[tag greenBackground tick]#✓# REST APIs

[tag greenBackground tick]#✓#  Visual Embed SDK

|[tag greenBackground tick]#✓# REST APIs

[tag greenBackground tick]#✓#  Visual Embed SDK

(Basic authentication only)
| [tag greenBackground tick]#✓# REST APIs

[tag greenBackground tick]#✓#  Visual Embed SDK

(Basic authentication only)

////

== REST API v1 operations

[div tableContainer]
--
[width="100%" cols="8,4,4,4,4,4"]
[options='header']
|=====
|REST API v1 endpoints|ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license|ThoughtSpot Everywhere license|Free Trial account +

(Evaluation only) |API Playground on public instance +
(Evaluation only)

a| xref:user-api.adoc[Users] +
////
__Require `ADMINISTRATION` privilege__
////
2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#

a| xref:group-api.adoc[Groups] +
////
__Require `ADMINISTRATION` privilege__
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–# +

a|xref:session-api.adoc[Session] +

////
* __The API calls to `/tspublic/v1/session/auth/token` and  `/tspublic/v1/session/login/token` require ThoughtSpot Everywhere license__ +
* __The home Liveboard CRUD operations require view or edit access to Liveboard objects__
////
|[tag greenBackground tick]#✓# +

__The xref:api-auth-session.adoc#_obtain_a_token_for_trusted_authentication[`session/auth/token`] and xref:api-auth-session.adoc#_authenticate_and_log_in_with_a_token_trusted_authentication[`session/login/token`] endpoints are not available__ 2*|[tag greenBackground tick]#✓#
 |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# +

__Session information and home Liveboard APIs only__
a|xref:connections-api.adoc[Connections] +

////
__Require `DATAMANAGEMENT` privilege__
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#
a|xref:metadata-api.adoc[Metadata] +
////
* __Require at least view access to metadata objects__ +

* __ `POST` requests require edit access to metadata objects__
////

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#

__Query APIs only__

a|xref:tml-api.adoc[TML] +

////
__Require `DATAMANAGEMENT` privilege__
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#

a|xref:admin-api.adoc[System administration] +

////
* __Require `ADMINISTRATION` privilege__ +
* __Custom action APIs require `ADMINISTRATOR` or `DEVELOPER` privilege__ +
* __Custom action association requires at least edit access to the visualization or saved answer__ +
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#

a|xref:admin-api.adoc#_supported_operations[Custom actions] +

////
* __Require `ADMINISTRATION` privilege__ +
* __Custom action APIs require `ADMINISTRATOR` or `DEVELOPER` privilege__ +
* __Custom action association requires at least edit access to the visualization or saved answer__ +
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#

__Query APIs only__
a|xref:dependency-apis.adoc[Dependency] +

////
__Require view access to metadata objects__
////

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#
a|Data API endpoints +

* xref:search-data-api.adoc[Search data API] +
* xref:pinboarddata.adoc[Liveboard data API] +
* xref:pinboard-export-api.adoc[Liveboard Export API] +

////
__Require at least view access to metadata objects__
////
|
[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#

a|xref:security-api.adoc[Security] +

////
__Require edit access to metadata objects to share and view permission details__
////
|
[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#

a|xref:logs-api.adoc[Audit logs] +

////
__Requires `ADMINISTRATION` privilege__
////
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#|
|=====
--

== REST API v2.0 operations

[div tableContainer]
--
[width="100%" cols="6,8,4,4,4,4"]
[options='header']
|=====
|REST API v2.0 endpoints |ThoughtSpot Analytics license|ThoughtSpot Analytics with Embed Add-on license| ThoughtSpot Everywhere License|Free Trial account +
(Evaluation only) |API Playground on public instance +
(Evaluation only)
a|xref:rest-api-v2-reference.adoc#_authentication[Authentication] +

a|[tag greenBackground tick]#✓# +

__The token generation option with `username` and `secret_key` and the JIT user provisioning parameters in `auth/token/object` and `auth/token/full` endpoints require an embedding license__.

2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# +
__Session information API only__
a|xref:rest-api-v2-reference.adoc#_users[Users]

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_system[System]

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_orgs[Orgs]

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#  |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_tags[Tags]

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_groups[Groups]

|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_metadata[Metadata]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# +
__Query APIs only__

a|xref:rest-api-v2-reference.adoc#_reports[Reports]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# +
__Query APIs only__

a|xref:rest-api-v2-reference.adoc#_security[Security]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#

a|xref:rest-api-v2-reference.adoc#_data[Data]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#  |[tag greenBackground tick]#✓#

a|xref:rest-api-v2-reference.adoc#_data[Audit logs]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_connections[Connections]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#
a|xref:rest-api-v2-reference.adoc#_version_control_beta_betabackgroundbeta[Version control]
|[tag greenBackground tick]#✓# 2*|[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#
|=====
--


== REST API v2 [beta betaBackground]^Beta^ operations

Starting from 9.0.0.cl, the REST API v2 [beta betaBackground]^Beta^ API endpoints are deprecated and removed from the REST API v2 Playground. The APIs remain functional until further notice. However, we recommend using the new REST API 2.0 endpoints that are currently available in the REST API Playground.

////
=== Supported operations
[div tableContainer]
--
[width="100%" cols="8,4,4,4,4"]
[options='header']
|=====
|REST API v2.0 endpoints[beta betaBackground]^Beta^ |ThoughtSpot Enterprise Cloud Service|ThoughtSpot Everywhere Edition License|Free Trial account +
(Evaluation only) |Developer Playground on public instance +
(Evaluation only)
a|Session API endpoints +

* __The API calls to `/tspublic/rest/v2/session/gettoken` require ThoughtSpot Everywhere license__  +
* __The home Liveboard CRUD operations require view or edit access to Liveboard objects__
__Require view or edit access to Liveboard objects__|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#|[tag greenBackground tick]#✓#|[tag greyBackground tick]#–#
a|User API endpoints +
* __Require `ADMINISTRATION` privilege__ +
* __The `/tspublic/rest/v2/user/changepassword` endpoint is available to all users__.
|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a| Group API endpoints +
__Require `ADMINISTRATION` privilege__|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|Metadata API endpoints +

* __Require at least view access to metadata objects__ +
* __ `POST` and `PUT` requests require edit access to metadata objects__ +
* __The import and export TML API endpoints require `DATAMANAGEMENT` privilege.__  |
[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# +

(Query APIs only)
a|Connection API endpoints +
__Require `DATAMANAGEMENT` privilege__|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#
a|Data API endpoints +
__Require at least view access to metadata objects__ |
[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#
a|Report API endpoints +
__Require `DATADOWNLOADING` privilege__|
[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#
a|Admin API endpoints +
__Require `ADMINISTRATION` privilege__|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|Custom action API endpoints +

* __Require `ADMINISTRATION` or `DEVELOPER` privilege__ +
* __Require edit access to saved Answer or Liveboard visualization object to associate custom action__ |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#
a|Security API endpoints +
__Require edit access to metadata objects to share and view permission details__ |
[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓# |[tag greyBackground tick]#–#
a|Audit logs API endpoint +
__Requires `ADMINISTRATION` privilege__|[tag greenBackground tick]#✓# |[tag greenBackground tick]#✓#|[tag greyBackground tick]#–# |[tag greyBackground tick]#–#|
|=====
--
////



== Additional resources

* xref:get-started-tse.adoc[Get started with embedding]
* link:https://www.thoughtspot.com/pricing[License options and pricing, window=_blank]
