= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot provides multiple types of filters for various xref:intro-thoughtspot-objects.adoc[object types], which can be applied in a layered fashion.

== Order of filter layers
The behavior of each filter type and the mechanism for setting filters can differ widely.
There are different types of filters, which can be applied in the following order:

1. xref:rls-rulesl.adoc[RLS Rules]
2. xref:abac-user-parameters.adoc[Attribute-Based Access Control (ABAC) *user_parameter* filters]
3. xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime_parameters]
4. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters, window=_blank]
5. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filters, window=_blank]
6. link:https://docs.thoughtspot.com/cloud/latest/filters[Search query filters, window=_blank]

All types of filters result in some form of `WHERE` clause being applied to the resulting queries generated by ThoughtSpot, or no query being issued if the resulting logic is always false.

== RLS Rules
xref:rls-rulesl.adoc[RLS rules] are defined at the ThoughtSpot Table object level. 

Once in place, they always apply within the query generation layer. 

Multiple RLS Rules are appended to the query via `OR` logic, rather than `AND`.

== user_parameter filters
Filters and parameter values defined via xref:abac-user-parameters.adoc[ABAC token] that apply at the data model layer are locked-in and always apply until changed or removed by a new token request.

The `user_parameter` filters and runtime filters are converted into SQL with the same logic:

1. clauses are appended via `AND`
2. filters are applied to exact matching Worksheet Column names

Any data restrictions resulting from `user_parameter` or runtime filters will be seen in the visible filter UI of the Liveboard filters and search_query filters layers, but there is no visible filter UI directly related to these filtering layers.

=== Worksheet filters
Worksheet objects can have Parameters, formulas, and filters.

End users cannot affect the formulas or filters, which are always applied, but any Parameters that are used in a formula can be set by these other methods.

To create an adjustable formula-filter that is secure, use the `user_parameters` filtering layer to set the value of the parameter programmatically.

If the parameter can be user-editable, then use the runtime Parameters layer to set the parameter value.

== Runtime filters and Parameters
You can define xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime parameters] within the browser for a given object at load time.

The runtime filters layer applies to the link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig[LiveboardEmbed], link:https://developers.thoughtspot.com/docs/Interface_SearchViewConfig[SearchEmbed] and link:https://developers.thoughtspot.com/docs/Interface_SageViewConfig[SageEmbed] components, which have methods for setting values prior to load and events for interacting after load time.

Filters and parameters that are set in the `user_parameters` layer via ABAC token cannot be overridden by setting `runtime_filters` or runtime_parameters` in the browser.

=== Setting values and events
Runtime filters can be set prior to the load within the link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig#_runtimefilters[configuration object] of the loaded embed component:

[source,JavaScript]
----
const embed = new LiveboardEmbed('#embed-container', {
   ... // other options
   runtimeFilters: [
          {
            columnName: 'value',
             operator: RuntimeFilterOp.EQ,
            values: ['string' | 123 | true],
          },
      ],
})
----

After load time, runtime filters can be adjusted using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updateruntimefilters[HostEvent.UpdateRuntimeFilters]:

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {columnName: "state",operator: RuntimeFilterOp.EQ,values: ["michigan"]},
  {columnName: "item type",operator: RuntimeFilterOp.EQ,values: ["Jackets"]}
])
----

== Liveboard filters
link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters, window=_blank] display at the top of a Liveboard. When clicked, a modal filtering dialog appears with filter options appropriate for the data type.

The author of the Liveboard can set default values for any of the Liveboard filters and a number of other options on each filter when editing the Liveboard.

The entire header where the Liveboard filters display link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig#_hideliveboardheader[can be hidden] and then their interaction triggered via events:

[source,JavaScript]
----
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  hideLiveboardHeader:true,
});
----

=== Events
There is no programmatic way to adjust the filter values prior to loading the Liveboard, but there are events that can adjust the values as soon as the Liveboard is accessible.

=== OpenFilter event
If you have hidden the Liveboard header, you can trigger the opening of the filter modal dialog by using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_openfilter[HostEvent.OpenFilter]:

[source,JavaScript]
----
LiveboardEmbed.trigger(HostEvent.OpenFilter,
 { columnId: '<column-GUID>'})
----

=== UpdateFilters event
The link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatefilters[HostEvent.UpdateFilters] directly updates the values of the target Liveboard filter:

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["JULY","2023"],
        type: "MONTH_YEAR"
       }
   });
----

The Liveboard filter exists already on the Liveboard for the `HostEvent.UpdateFilters` to work.

For more information and examples, see xref:embed-pinboard.adoc#_filters[Liveboard filters].

=== GetFilters and GetParameters events
If you want to build your own filter UI within the embedding app, you can find out details of the Liveboard and runtime filters that are defined using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getfilters[HostEvent.GetFilters]. There is an equivalent link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getparameters[HostEvent.GetParameters] to get the currently set Parameter values:

[source,JavaScript]
----
const data = await liveboardEmbed.trigger(HostEvent.GetFilters);
    console.log('data', data);

liveboardEmbed.trigger(HostEvent.GetParameters).then((parameter) => {
 console.log('parameters', parameter);
});

----

Note that `HostEvent.GetFilters` and `HostEvent.GetParameters` return a promise directly rather than taking a callback function as their second argument.

=== FilterChanged and ParameterChanged events
You can also listen for the user's interactions with the filters using the link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_filterchanged[EmbedEvent.FilterChanged].

There is an equivalent EmbedEvent for Parameters called link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_parameterchanged[EmbedEvent.ParameterChanged].

== Liveboard cross filters
Liveboard users can apply filters across all visualizations based on the current selection using the *Filter* menu option from the contextual menu. For more information, see link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filter, window=_blank].

If the column already has a Liveboard filter and the user applies cross filters, the cross filter replaces the values in the currently applied Liveboard filter. If there is no Liveboard filter applied to a column and user applies a cross filter, a new filter chip with cross filter values is displayed in the header area. This filter chip is removed when the cross filter is cleared.

=== CrossFilterChanged event
Whenever any user action affects a cross filter, a link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_crossfilterchanged[EmbedEvent.CrossFilterChanged] fires, which can be listened to for register details about the action that happened.

=== UpdateCrossFilter event
You can programmatically trigger a cross filter to apply by trigger a link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatecrossfilter[HostEvent.UpdateCrossFilter]:

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateCrossFilter, {
     vizId: 'b535c760-8bbe-4e6f-bb26-af56b4129a1e',
     conditions: [
       { columnName: 'Category', values: ['mfgr#12','mfgr#14'] },
       { columnName: 'color', values: ['mint','hot'] },
   ],
});
----

== Search query filters
The lowest layer of filters are those that are defined as part of the search query for a given Answer or visualization on a Liveboard.

The link:https://docs.thoughtspot.com/cloud/latest/filters[filter terms, window=_blank] are saved as part of the `search_query` of the object, visible in TML.

When viewing an Answer or a visualization in the *Edit* mode, you will see the filter UI for `search_query` filters above the chart or table. These filters are not visible on a Liveboard.

=== Liveboard filters override search_query filters
When viewing a visualization on a Liveboard, any Liveboard filter on the same column as a `search_query`  filter will fully override the values.

=== Events
There is not a specific event for changes to `search_query filters` while in the SearchEmbed component or Edit mode of a Liveboard.

The link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_querychanged[EmbedEvent.QueryChanged] can be listened to and you can trigger the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_gettml[HostEvent.GetTML] to get the new form of the TML `search_query` string after any update.
