= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot provides multiple types of filters in the various xref:intro-thoughtspot-objects.adoc[object types], which can be thought of as applying in a layered fashion. 

== Order of filter layers
The behavior of each filter type with regards to the other layers of filters, as well as the mechanism for setting the filters, can differ widely.

The different filter types exist and apply in the following order:

1. *xref:rls-rulesl.adoc[RLS Rules]*: 
2. *xref:abac-user-parameters.adoc[user_parameter filters]* 
3. *xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime_parameters]* 
4. *link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters]* 
5. *link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filters]*
6. *link:https://docs.thoughtspot.com/cloud/latest/filters[search_query filters]*

All of the types of filters result in some form of *WHERE clause* being applied to the resulting queries ThoughtSpot generates (or no query being issued, if the resulting logic is always false).

== RLS Rules
xref:rls-rulesl.adoc[RLS rules] are defined at the ThoughtSpot Table object level. 

Once in place, they always apply within the query generation layer. 

Multiple RLS Rules are appended to the query via *OR* logic, rather than *AND*.

== user_parameter filters
Filters and parameter values defined via xref:abac-user-parameters.adoc[ABAC token] that apply at the Worksheet/Model layer are are locked-in and always apply until changed or removed by a new token request.

user_parameter filters and runtime filters are converted into SQL with the same logic: 

1. clauses are appended via *AND*
2. filters are applied to exact matching Worksheet Column names

Any data restrictions resulting from user_parameter or runtime filters will be seen in the visible filter UI of the Liveboard filters and search_query filters layers, but there is on visible filter UI directly related to these filtering layers.

=== Worksheet filters
Worksheet objects can have *parameters*, *formulas* and *filters*.

End users cannot affect the formulas or filters, which are always applied, but any *parameters* that are used in a formula can be set by these other methods.

To create an adjustable formula-filter that is *secure*, you'll need to use the *user_parameters* filtering layer to set the value of the parameter programmatically.

If the parameter can be user-editable, then use the *runtime parameters* layer (below) to set the parameter value.

== Runtime filters and parameters
xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime parameters] can be defined *within the browser* for a given object at load time.

The runtime filters layer applies to the link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig[LiveboardEmbed], link:https://developers.thoughtspot.com/docs/Interface_SearchViewConfig[SearchEmbed] and link:https://developers.thoughtspot.com/docs/Interface_SageViewConfig[SageEmbed] components, which have methods for setting values prior to load and events for interacting after load time.

Filters and parameters that are set in the *user_parameters* layer via ABAC token cannot be overriden by setting *runtime_filters* or *runtime_parameters* in the browser.

=== Setting values and events
Runtime filters can be set prior to the load within the *link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig#_runtimefilters[configuration object]* of the loaded embed component:

[code,javascript]
----
const embed = new LiveboardEmbed('#embed-container', {
   ... // other options
   runtimeFilters: [
          {
            columnName: 'value',
             operator: RuntimeFilterOp.EQ,
            values: ['string' | 123 | true],
          },
      ],
})
----

After load time, runtime filters can be adjusted using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updateruntimefilters[UpdateRuntimeFilters HostEvent]:

[code,javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {columnName: "state",operator: RuntimeFilterOp.EQ,values: ["michigan"]},
  {columnName: "item type",operator: RuntimeFilterOp.EQ,values: ["Jackets"]}
])
----

== Liveboard filters
link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters] display at the top of a Liveboard. When clicked, a modal filtering dialog appears with filter options appropriate for the data type.

The author of the Liveboard can set default values for any of the Liveboard filters, as well as a number of other options on each filter when editing the Liveboard.

The entire header where the Liveboard filters display link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig#_hideliveboardheader[can be hidden] and then their interaction triggered via events:

[code,javascript]
----
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  hideLiveboardHeader:true,
});
----

=== Events
There is no programmatic way to adjust the filter values prior to loading the Liveboard, but there are events that can adjust the values as soon as the Liveboard is accessible.

=== OpenFilter
If you have hidden the Liveboard header, you can trigger the opening of the filter modal dialog by using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_openfilter[OpenFilter HostEvent]:

[code,javascript]
----
LiveboardEmbed.trigger(HostEvent.OpenFilter,
 { columnId: '<column-GUID>'})
----

=== UpdateFilters
The *link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatefilters[UpdateFilters HostEvent]* directly updates the values of the target Liveboard filter:

[code,javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["JULY","2023"],
        type: "MONTH_YEAR"
       }
   });
----

The Liveboard filter exist already on the Liveboard for the *UpdateFilters* HostEvent to work.

=== GetFilters and GetParameters
If you want to build your own filter UI within the embedding app, you can find out details of the Liveboard and runtime filters that are defined using the *link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getfilters[GetFilters HostEvent]*. There is an equivalent *link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getparameters[GetParameters Host Event]* to get the currently set parameter values:

[code,javascript]
----
const data = await liveboardEmbed.trigger(HostEvent.GetFilters);
    console.log('data', data);

liveboardEmbed.trigger(HostEvent.GetParameters).then((parameter) => {
 console.log('parameters', parameter);
});

----

Note that *GetFilters* and *GetParameters* return a Promise directly rather than taking a callback function as their second argument.

=== FilterChanged and ParameterChanged
You can also listen for the user's interactions with the filters using the *link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_filterchanged[FilterChanged EmbedEvent]*

There is an equivalent EmbedEvent for parameters, which also have similar UI to Liveboard filters, called *link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_parameterchanged[ParameterChanged]*.

== Liveboard cross filters
ThoughtSpot allows a user to use the context menu on a value to become a *link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filter]*.

If there is an existing defined *Liveboard filter* on the column that a *cross filter* applies to, any configuration of the existing Liveboard filter will be used, and the cross filter will simply be setting the value of the exiting Liveboard filter.

If there is not a Liveboard filter, a new cross filter is applied, and the UI for the cross filter appears in the header area along with any other existing Liveboard filters and parameters. It will go away if the cross filter is cleared.

=== CrossFilterChanged event
Whenever any user action affects a cross filter, a *link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_crossfilterchanged[CrossFilterChanged EmbedEvent]* fires, which can be listened to for details about the action that happened.

=== UpdateCrossFilter event
You can programmatically trigger a cross filter to apply by trigger a *link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatecrossfilter[UpdateCrossFilter HostEvent]*:

[code,javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateCrossFilter, {
     vizId: 'b535c760-8bbe-4e6f-bb26-af56b4129a1e',
     conditions: [
     { columnName: 'Category', values: ['mfgr#12','mfgr#14'] },
     { columnName: 'color', values: ['mint','hot'] },
   ],
});
----

== search_query filters
link:https://docs.thoughtspot.com/cloud/latest/filters[filter terms] that are part of the underlying *search query* of a single Answer or visualization on a Liveboard 
