= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot provides multiple types of filters in the various xref:intro-thoughtspot-objects.adoc[object types], which can be thought of as applying in a layered fashion. 

== Order of filter layers
The behavior of each filter type with regards to the other layers of filters, as well as the mechanism for setting the filters, can differ widely.

The different filter types exist and apply in the following order:

1. *xref:rls-rulesl.adoc[RLS Rules]*: 
2. *xref:abac-user-parameters.adoc[user_parameter filters]* 
3. *xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime_parameters]* 
4. *link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters]* 
5. *link:https://docs.thoughtspot.com/cloud/latest/filters[search_query filters]*

All of the types of filters result in some form of *WHERE clause* being applied to the resulting queries ThoughtSpot generates (or no query being issued, if the resulting logic is always false).

== RLS Rules
xref:rls-rulesl.adoc[RLS rules] are defined at the ThoughtSpot Table object level. 

Once in place, they always apply within the query generation layer. 

Multiple RLS Rules are appended to the query via *OR* logic, rather than *AND*.

== user_parameter filters
Filters and parameter values defined via xref:abac-user-parameters.adoc[ABAC token] that apply at the Worksheet/Model layer are are locked-in and always apply until changed or removed by a new token request.

user_parameter filters and runtime filters are converted into SQL with the same logic: 

1. clauses are appended via *AND*
2. filters are applied to exact matching Worksheet Column names

Any data restrictions resulting from user_parameter or runtime filters will be seen in the visible filter UI of the Liveboard filters and search_query filters layers, but there is on visible filter UI directly related to these filtering layers.

=== Worksheet filters
Worksheet objects can have *parameters*, *formulas* and *filters*.

End users cannot affect the formulas or filters, which are always applied, but any *parameters* that are used in a formula can be set by these other methods.

To create an adjustable formula-filter that is *secure*, you'll need to use the *user_parameters* filtering layer to set the value of the parameter programmatically.

If the parameter can be user-editable, then use the *runtime parameters* layer (below) to set the parameter value.

== Runtime filters and parameters
xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime parameters] can be defined *within the browser* for a given object at load time.

The runtime filters layer applies to the link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig[LiveboardEmbed], link:https://developers.thoughtspot.com/docs/Interface_SearchViewConfig[SearchEmbed] and link:https://developers.thoughtspot.com/docs/Interface_SageViewConfig[SageEmbed] components, which have methods for setting values prior to load and events for interacting after load time.

Filters and parameters that are set in the *user_parameters* layer via ABAC token cannot be overriden by setting *runtime_filters* or *runtime_parameters* in the browser.

=== Setting values and events
Runtime filters can be set prior to the load within the *link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig#_runtimefilters[configuration object]* of the loaded embed component:

[code,javascript]
----
const embed = new LiveboardEmbed('#embed-container', {
   ... // other options
   runtimeFilters: [
          {
            columnName: 'value',
             operator: RuntimeFilterOp.EQ,
            values: ['string' | 123 | true],
          },
      ],
})
----

After load time, runtime filters can be adjusted using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updateruntimefilters[UpdateRuntimeFilters HostEvent]:

[code,javascript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {columnName: "state",operator: RuntimeFilterOp.EQ,values: ["michigan"]},
  {columnName: "item type",operator: RuntimeFilterOp.EQ,values: ["Jackets"]}
])
----

== Liveboard filters
link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters] display at the top of a Liveboard, with modal UI for filtering that appears when clicked

=== Events

== search_query filters
link:https://docs.thoughtspot.com/cloud/latest/filters[filter terms] that are part of the underlying *search query* of a single Answer or visualization on a Liveboard 
