= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot provides multiple types of filters in the various xref:intro-thoughtspot-objects.adoc[object types], which can be thought of as applying in a layered fashion. 

The behavior of each filter type with regards to the other layers of filters, as well as the mechanism for setting the filters, can differ widely.

== Filter layers
The different filter types exist and apply in the following order:

1. *RLS Rules*: xref:rls-rulesl.adoc[RLS rules] are defined at the ThoughtSpot Table object level
2. *user_parameter filters* : filters and parameter values defined via  xref:abac-user-parameters.adoc[ABAC token] that apply at the Worksheet/Model layer are are locked-in and always apply until changed or removed
3. *Runtime filters*: filters and parameter values can be defined within the browser for a given loaded object
4. *Liveboard filters*: visible filters that display at the top of a Liveboard
5. *search_query filters*: filter clauses that are part of the underlying search query of a single Answer or visualization on a Liveboard 
