= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot provides multiple types of filters in the various xref:intro-thoughtspot-objects.adoc[object types], which can be thought of as applying in a layered fashion. 

The behavior of each filter type with regards to the other layers of filters, as well as the mechanism for setting the filters, can differ widely.

The different filter types exist and apply in the following order:

1. *xref:rls-rulesl.adoc[RLS Rules]*: 
2. *xref:abac-user-parameters.adoc[user_parameter filters]* 
3. *xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime_parameters]* 
4. *link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters]* 
5. *link:https://docs.thoughtspot.com/cloud/latest/filters[search_query filters]*

All of the types of filters result in some form of *WHERE clause* being applied to the resulting queries ThoughtSpot generates (or no query being issued, if the resulting logic is always false).

== RLS Rules
xref:rls-rulesl.adoc[RLS rules] are defined at the ThoughtSpot Table object level. 

Once in place, they always apply within the query generation layer. 

Multiple RLS Rules are appended to the query via *OR* logic, rather than *AND*.

== user_parameter filters
Filters and parameter values defined via xref:abac-user-parameters.adoc[ABAC token] that apply at the Worksheet/Model layer are are locked-in and always apply until changed or removed.

user_parameter filters and runtime filters are converted into SQL with the same logic: 

1. clauses are appended via *AND*
2. filters are applied to exact matching Worksheet Column names

== Runtime filters and parameters
xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime parameters] can be defined *within the browser* for a given object at load time.

The runtime filters layer applies to the LiveboardEmbed, SearchEmbed and SageEmbed components.



=== Setting values and events
Runtime filters can be set prior to the load within the *configuration object* of the loaded embed component.

After load time, runtime filters can be adjusted using the UpdateRuntimeFilters HostEvent.

== Liveboard filters
link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters] display at the top of a Liveboard, with modal UI for filtering that appears when clicked

=== Events

== search_query filters
link:https://docs.thoughtspot.com/cloud/latest/filters[filter terms] that are part of the underlying *search query* of a single Answer or visualization on a Liveboard 
