= Filters overview
:toc: true
:toclevels: 2

:page-title: Filters overview
:page-pageid: filters-overview
:page-description: ThoughtSpot has several layers of filters which have an order of precedence and different events

ThoughtSpot Embedded provides a robust filtering framework for Liveboards, Answers, visualizations, and other ThoughtSpot objects with multiple filter types and layered application logic. Filters can be configured using the Visual Embed SDK events and parameters when embedding, applied at runtime, or via UI-driven workflows.

== Filter types and application layers
The behavior of each filter type and the mechanism for setting filters can differ widely.
There are different types of filters, which can be applied in the following order:

1. xref:rls-rules.adoc[**Row-level security (RLS) Rules**] +
Rules are defined at the table level and applied during query generation to all objects derived from that table. Rules can be defined based on the logged-in user, their group memberships, or custom variables. +
RLS rules secure data and cannot be altered by the logged-in user. +
RLS rules can also be used, along with custom variables and the JSON Web Token (JWT) generated for the user, to implement xref:abac_rls-variables.adoc[Attribute-Based Access Control (ABAC)].

2. **Data Model filters** +
Models can have parameters, formulas, and filters. +
Embedding application users cannot affect the formulas or filters, which are always applied, but Parameters used in a formula can be set by other methods. +
If the user can edit the parameter, use the runtime parameters layer to programmatically set its value.

3. xref:runtime-filters.adoc[Runtime filters] and xref:runtime-parameters.adoc[Runtime Parameters] +
You can define xref:runtime-filters.adoc[runtime filters] and xref:runtime-parameters.adoc[runtime parameters] within the browser for a given object at load time. Filters and parameters can be set using the Visual Embed SDK, REST API, or URL query parameters and updated via host events in the Visual Embed SDK.
+
[NOTE]
====
Runtime filters do not display as UI filter components.
====

4. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters, window=_blank] +
Liveboard filters apply to all visualizations on the Liveboard and are visible as UI components at the top of a Liveboard page. When a filter is clicked, a modal with filter options appropriate for the data type is displayed. +
Liveboard users can add or modify filters as needed. If you are embedding a Liveboard that includes preset filters, you can programmatically update, reset, or remove filters using the `HostEvent.UpdateFilters`.

5. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filters, window=_blank] +
Cross filters are ad-hoc filters based on user selection. These filters are used for brushing and linking Liveboard visualizations. +
Cross filters are supported only on attribute columns.

6. link:https://docs.thoughtspot.com/cloud/latest/filters[Search query filters, window=_blank] +
Set via the search query string in Answers and visualizations, not visible as UI filter components on a Liveboard, but can be viewed in **Explore** or *Edit* modes. +
The lowest layer of filters is defined in the search query for a given Answer or visualization on a Liveboard. +
The link:https://docs.thoughtspot.com/cloud/latest/filters[filter terms, window=_blank] are saved as part of the `search_query` of the object, visible in TML.

== Filter attributes
When specifying a column for filtering, you must use the exact column name as defined in the model. Filters can be applied to string, number, boolean, Date, Datetime, and time data types.
For the `DATE` and `DATE_TIME` data types, some filter types may require the date and time values to be specified in the Epoch time format.

All operations result in a `WHERE` clause being applied to the queries generated by ThoughtSpot, or no query being issued if the logic is always false.

A data filter object in ThoughtSpot typically includes the following attributes:

`column`, `columnName`, or `columnId`::
The name of the column to filter on. For example, `item type` or `product`. The column value must match the actual column name in the ThoughtSpot model. If the model uses column aliases, use the base column name, not the alias. This attribute is defined as `col1`, `col2`, `col3` in the object URLs and REST API requests, as `columnName` in the `runtimeFilters` array in the Visual Embed SDK. The filter object for host events in the SDK allows `column` or `columnName`.
+
If there are multiple columns with the same name, you can use the `WORKSHEET_NAME::COLUMN_NAME` format; for example, `"(Sample) Retail - Apparel::city"`.

`oper` or `operator`::
The supported operators include:
+
[width="80%" cols="1,2,2"]
[options='header']
|===
|Operator|Description|Number of Values

| `EQ`
| equals
| 1

| `NE`
| not equal to
| 1

| `LT`
| less than
| 1

| `LE`
| less than or equal to
| 1

| `GT`
| greater than
| 1

| `GE`
| greater than or equal to
| 1

| `CONTAINS`
| contains
| 2

| `BEGINS_WITH`
| begins with
| 1

| `ENDS_WITH`
| ends with
| 1

| `BW_INC_MAX`
| between inclusive of the higher value
| 2

| `BW_INC_MIN`
| between inclusive of the lower value
| 2

| `BW_INC`
| between inclusive
| 2

| `BW`
| between non-inclusive
| 2

|`IN`
|is included in this list of values
|multiple
|`NOT_IN`
|is not included in this list of values
|multiple
|===

values::
An array of one or more values to filter by. The values must match the data type of the column.

type::
Specifies the type for date filters. Supported types include `YESTERDAY`, `TODAY`, `TOMORROW`, `EXACT_DATE`, `EXACT_DATE_RANGE`, `LAST_N_PERIOD`, `NEXT_N_PERIOD`, `THIS_PERIOD`, `PERIOD_TO_DATE`, `YEAR_ONLY`, `MONTH_YEAR`, and `QUARTER_YEAR`.

[NOTE]
====
* To specify the exact date or date range, you can use the date format such as `YYYY-MM-DD`, `YYYY/MM/DD`. If using epoch format, ensure that they are specified as numbers and not as strings. For example, `[1743465599, 1754006399]`.
* For `PERIOD` filters, you must include the `datePeriod` attribute in the date filter object.
* For rolling date filters with **Last <N> <Period>** and **Next <N> <Period>**, you can specify whether to include or exclude the current period.
====

////
== Order of filter layers
The behavior of each filter type and the mechanism for setting filters can differ widely.
There are different types of filters, which can be applied in the following order:

1. xref:rls-rules.adoc[Row-level security (RLS) Rules]+
Tied to the logged-in user and their group memberships. Completely secure and cannot be altered by the logged-in user.
2. xref:abac-user-parameters.adoc[Attribute-Based Access Control (ABAC) filter rules] +
Filters and Parameter rules applied on a Model and assigned to a token.
3. xref:runtime-filters.adoc[Runtime filters] and xref:runtime-parameters.adoc[Runtime Parameters] +
Set via the Visual Embed SDK or URL query parameters. Runtime filters do not display as UI filter components.
4. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters[Liveboard filters, window=_blank] +
Visible as UI components at the top of a Liveboard, affecting all visualizations on the Liveboard.
5. link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filters, window=_blank] +
Filters used for brushing and linking Liveboard visualizations
6. link:https://docs.thoughtspot.com/cloud/latest/filters[Search query filters, window=_blank] +
Set via the search query string, not visible as UI filter components on a Liveboard, but can be viewed in **Explore** or *Edit* modes.

All types of filters result in some form of `WHERE` clause being applied to the resulting queries generated by ThoughtSpot, or no query being issued if the resulting logic is always false.
////


////
== ABAC filter rules
Filters and parameter values defined via xref:abac-user-parameters.adoc[ABAC token] that apply at the data model layer are locked-in and always apply until changed or removed by a new token request.

The ABAC filter rules and runtime filters are converted into SQL with the same logic:


1. clauses are appended via `AND`
2. filters are applied to exact matching Model Column names

Any data restrictions resulting from filter rules will be seen in the visible filter UI of the Liveboard filters and `search_query` filters layers, but there is no visible filter UI directly related to these filtering layers.
////

== Applying filters before and after load

* xref:runtime-filters.adoc[Runtime filters] can be applied at load via Visual Embed SDK, REST API, or URL parameters.
* Liveboard filters cannot be applied at load. However, they can be updated using `HostEvent.UpdateFilters` in the SDK.
* Search query filters can be applied at load by specifying them in the initial search query when embedding an Answer or Spotter session. For example, in Spotter embed, you can use the `searchQuery` property to set a pre-defined search (including filters) at load.
+
When you view an Answer or visualization in *Edit* mode, the filter UI for search query filters appears above the chart or table. These filters are not shown on a Liveboard. If a Liveboard filter is applied to the same column as a search query filter, the Liveboard filter will override the search query filter values.

=== Cross filters
Liveboard users can apply filters across all visualizations based on the current selection using the *Filter* menu option from the contextual menu. For more information, see link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters-cross[Liveboard cross filter, window=_blank].

If the column already has a Liveboard filter and the user applies cross filters, the cross filter replaces the values in the currently applied Liveboard filter. If there is no Liveboard filter applied to a column and the user applies a cross filter, a new filter chip with cross filter values is displayed in the header area. This filter chip is removed when the cross filter is cleared.

Whenever any user action affects a cross filter, a link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_crossfilterchanged[EmbedEvent.CrossFilterChanged] fires, which can then be used to trigger a specific action.

== Updating filters using host events
There is no programmatic way to adjust the filter values before loading the Liveboard, but there are events that can adjust the values after the Liveboard is rendered.

=== OpenFilter event
If you have hidden the Liveboard header, you can trigger the action of opening a filter modal dialog using link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_openfilter[HostEvent.OpenFilter]:

[source,JavaScript]
----
LiveboardEmbed.trigger(HostEvent.OpenFilter,
 { columnId: '<column-GUID>'})
----

=== UpdateFilters event
The link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatefilters[HostEvent.UpdateFilters] directly updates the values of the target of an existing filter that's currently applied on a Liveboard:

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["JULY","2023"],
        type: "MONTH_YEAR"
       }
   });
----

=== GetFilters and GetParameters events
If you want to build your own filter UI within the embedding app, you can find out details of the Liveboard and runtime filters that are defined using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getfilters[HostEvent.GetFilters]. There is an equivalent link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getparameters[HostEvent.GetParameters] to get the currently set Parameter values:

[source,JavaScript]
----
const data = await liveboardEmbed.trigger(HostEvent.GetFilters);
console.log('data', data);

liveboardEmbed.trigger(HostEvent.GetParameters).then((parameter) => {
    console.log('parameters', parameter);
});
----

Note that `HostEvent.GetFilters` and `HostEvent.GetParameters` return a promise directly rather than taking a callback function as their second argument.

=== FilterChanged and ParameterChanged events
You can also listen for the user's interactions with the filters using the link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_filterchanged[EmbedEvent.FilterChanged].

There is an equivalent EmbedEvent for Parameters called link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_parameterchanged[EmbedEvent.ParameterChanged].

=== UpdateCrossFilter event
You can programmatically trigger an action to update a cross filter using link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updatecrossfilter[HostEvent.UpdateCrossFilter]:

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateCrossFilter, {
     vizId: 'b535c760-8bbe-4e6f-bb26-af56b4129a1e',
     conditions: [
       { columnName: 'Category', values: ['mfgr#12','mfgr#14'] },
       { columnName: 'color', values: ['mint','hot'] },
   ],
});
----

== Updating date filters via host events
To update date filters in an embedded Liveboard, visualization, or saved answer, use `HostEvent.UpdateFilters`.

When updating filters using `HostEvent.UpdateFilters`, you must include the date filter `type` along with the time period to apply a rolling or fixed time windows.

[NOTE]
====
* For `PERIOD` filters, you must include the `datePeriod` attribute in the date filter object.
* To specify the exact date or date range, you can use the date format such as `YYYY-MM-DD`, `YYYY/MM/DD`. If using epoch format, ensure that they are specified as numbers and not as strings. For example, `[1743465599, 1754006399]`.
====

The following table lists the supported filter types and examples for each type:

[width="100%" cols="3,5,8"]
[options='header']
|=====
|Type| Description | Example

| `YESTERDAY`  | Specify the `type` as `YESTERDAY`. a|
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [""],
        type: "YESTERDAY"
       }
   });
----
| `TODAY` | Specify the `type` as `TODAY`. a|
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [""],
        type: "TODAY"
       }
   });
----
| `TOMORROW` | Specify the `type` as `TOMORROW`. a|

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [""],
        type: "TOMORROW"
       }
   });
----

|`EXACT_DATE` | Allows filtering column data to show details for the exact date, before or after the date. For example, to filter data for dates greater than `2023/07/31`, specify `2023/07/31` as value, with the filter operator as `GT`.  a| [source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "GT",
        values: ["2023-07-31"],
        type: "EXACT_DATE"
       }
   });
----
|`EXACT_DATE_RANGE` |Specify the start date and end date in the `values` array. Ensure that the start date is lower than the end date. For example, `"2023-01-31","2023-03-31"`. a|

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "BW_INC",
        values: ["2023-01-31","2023-03-31"],
        type: "EXACT_DATE_RANGE"
       }
   });
----

|`LAST_N_PERIOD` |Specify the period. You must include the `datePeriod` attribute based on the time period specified in the filter object. Valid values for `datePeriod` are `SECOND`, `MINUTE`, `HOUR`, `DAY`, `WEEK`, `MONTH`, `QUARTER`, and `YEAR`. For example, to filter column data by last 2 weeks, set `datePeriod` to `WEEK` and `values` to `2`.

a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [2],
        datePeriod: "WEEK",
        type: "LAST_N_PERIOD",
        includeCurrentPeriod: true,
      }
   });
----

|`NEXT_N_PERIOD` | Specify the period. You must include the `datePeriod` attribute based on the time period specified in the filter object. Valid values for `datePeriod` are `SECOND`, `MINUTE`, `HOUR`, `DAY`, `WEEK`, `MONTH`, `QUARTER`, and `YEAR`. For example, to filter column data by next 2 months, set `datePeriod` to `MONTH` and `values` to `2`.

a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [2],
        datePeriod: "MONTH",
        type: "NEXT_N_PERIOD",
        includeCurrentPeriod: false,
      }
   });
----

| `THIS_PERIOD` | Specify the period. You must include the `datePeriod` attribute based on the time period specified in the filter object. Valid values for `datePeriod` are `SECOND`, `MINUTE`, `HOUR`, `DAY`, `WEEK`, `MONTH`, `QUARTER`, and `YEAR`.

a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [""],
        datePeriod: "MONTH",
        type: "THIS_PERIOD"
      }
   });
----

| `PERIOD_TO_DATE` |Specify the period. You must include the `datePeriod` attribute based on the time period specified in the filter object. Valid values for `datePeriod` are `WEEK`, `MONTH`, `QUARTER`, and `YEAR`.

a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: [""],
        datePeriod: "QUARTER",
        type: "PERIOD_TO_DATE"
      }
   });
----
|`YEAR_ONLY` |Specify the year. For example, 2023.
a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["2023"],
        type: "YEAR_ONLY"
      }
   });
----

| `MONTH_YEAR` |Specify the month and year in the `values` array. For example, `"July","2023"`.
a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["July","2023"],
        type: "MONTH_YEAR"
      }
   });
----

|`QUARTER_YEAR` | Specify the quarter and year in the `values` array. For example, `"Q1","2023"`.

a|[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filter: {
        column: "date",
        oper: "EQ",
        values: ["Q1","2023"],
        type: "QUARTER_YEAR"
      }
   });
----
|=====

[#_override_filters]
=== Overriding filters in REST API workflows

The `override_filters` parameter on the Liveboard report API
(`POST /api/rest/2.0/report/liveboard`) lets you programmatically apply or replace
filters when exporting a Liveboard report. Filters specified here override any existing
filters on the same columns in the Liveboard.

[IMPORTANT]
====
This section describes how the `override_filters` field used in the REST API request. If you are building an embedded application and want to update filters using the
Visual Embed SDK, see xref:filters_overview.adoc#_updating_filters_using_host_events[Updating date filters].

The two interfaces share the same filter concepts but are structurally different:
The Visual Embed SDK uses a `values[]` array to pass date values and the filter attribute names are in camelCase; for example, `datePeriod`.
The REST API uses named fields (`epoch`, `number`, `date_range`) in
`UPPER_SNAKE_CASE` type names. Do not mix examples from the two pages.
====

==== Request format

The `override_filters` value is a JSON array of filter objects. Each object targets
one column.

[source,json]
----
"override_filters": [
  { ... },   // filter for column A
  { ... }    // filter for column B
]
----

===== Filter object structure
Each element in the array has the following top-level fields:

[cols="2,1,1,4", options="header"]
|===
|Field
|Type
|Required
|Description

|`column_name`
|__String__
|Yes
|Display name of the column to filter.

|`date_filter`
|Object
|Conditional
|Date filter definition. Use for columns with a date or date-time data type.
Mutually exclusive with `generic_filter` on the same object.

|`generic_filter`
|Object
|Conditional
|Attribute or measure filter definition. Use for non-date columns.

|`negate`
|boolean
|No
|When `true`, inverts the filter. For `date_filter`, see the negation notes in
<<rest-date-filter-negate>>.
|===

[IMPORTANT]
====
You may specify *at most one* filter object per date-type column. Providing two or more
filter objects that target the same date column returns an error:

 more than one filter objects are not allowed for date type column <column_name>

Non-date columns do not have this restriction.
====

[#rest-date-filter-object]
=== date_filter object

The `date_filter` object specifies a structured date filter. Its fields map directly
to the internal `DateFilterProto` representation.

[cols="2,1,1,4", options="header"]
|===
|Field
|Type
|Required
|Description

|`type`
|string
|Yes
|The date filter category. Must be one of the values in <<rest-date-filter-types>>.

|`datePeriod`
|string
|Conditional
|The time granularity for rolling filters. Required when `type` is `LAST_N_PERIOD`,
`NEXT_N_PERIOD`, `THIS_PERIOD`, `LAST_PERIOD`, `NEXT_PERIOD`, or `PERIOD_TO_DATE`.
See <<rest-date-period-values>>.

|`op`
|string
|Yes
|The comparison operator. Valid values depend on `type`.
See <<rest-valid-operators-per-type>>.

|`number`
|integer
|Conditional
|The period count. Required when `type` is `LAST_N_PERIOD` or `NEXT_N_PERIOD`.
Must be ≥ 0.

|`epoch`
|integer (int64)
|Conditional
|A specific point in time as a Unix epoch in *seconds*, in *server timezone*.
Required when `type` is `EXACT_DATE` and `op` is an inequality (`LT`, `LE`, `GT`,
`GE`, `NE`). For `op: EQ` with `EXACT_DATE`, `epoch` is also required.

|`date_range`
|object
|Conditional
|Required when `type` is `EXACT_DATE_RANGE`. Contains `low_epoch` and `high_epoch`,
both int64 Unix epochs in *seconds*, in *server timezone*.
`low_epoch` must be strictly less than `high_epoch`.

|`year_name`
|string
|Conditional
|The four-digit year as a string (e.g., `"2024"`). Required for `YEAR_ONLY`,
`QUARTER_YEAR`, and `MONTH_YEAR`. Year value must be ≥ 1000.

|`quarter_name`
|string
|Conditional
|The quarter identifier. Required for `QUARTER_YEAR`.
Valid values: `Q1`, `Q2`, `Q3`, `Q4`.

|`month_name`
|string
|Conditional
|The month name in uppercase. Required for `MONTH_YEAR`.
Valid values: `JANUARY`, `FEBRUARY`, `MARCH`, `APRIL`, `MAY`, `JUNE`,
`JULY`, `AUGUST`, `SEPTEMBER`, `OCTOBER`, `NOVEMBER`, `DECEMBER`.

|`include_current_period`
|boolean
|No
|For `LAST_N_PERIOD` and `NEXT_N_PERIOD` only. When `true`, includes the current
in-progress period in the filter range. Requires the *Include Current Period*
feature to be enabled on the cluster. Silently ignored if the feature is off.
|===

[WARNING]
====
Epoch values must be in *server timezone* and expressed in *seconds*, not
milliseconds. Passing millisecond values (for example, `1710460800000` instead of
`1710460800`) produces an incorrect date range with no error.
====

[#rest-date-filter-types]
=== Supported type values

[cols="2,4,3", options="header"]
|===
|`type` value
|Description
|Required companion fields

|`YESTERDAY`
|The full previous calendar day.
|`op: EQ` only

|`TODAY`
|The current calendar day.
|`op: EQ`

|`TOMORROW`
|The next calendar day. +
⚠️ May be suppressed on clusters with future date filters disabled.
|`op: EQ`

|`LAST_PERIOD`
|The last single period (for example, last week).
|`datePeriod`, `op ∈ {EQ, LE, LT, GE, GT}`

|`NEXT_PERIOD`
|The next single period (for example, next month).
|`datePeriod`, `op ∈ {EQ, LE, LT, GE, GT}`

|`THIS_PERIOD`
|The current period (for example, this quarter).
|`datePeriod`, `op ∈ {EQ, LE, LT, GE, GT}`

|`LAST_N_PERIOD`
|The last _N_ complete periods.
|`datePeriod`, `number ≥ 0`, `op ∈ {EQ, LE, LT, GE, GT}` +
Optional: `include_current_period`

|`NEXT_N_PERIOD`
|The next _N_ complete periods.
|`datePeriod`, `number ≥ 0`, `op ∈ {EQ, LE, LT, GE, GT}` +
Optional: `include_current_period`

|`PERIOD_TO_DATE`
|From the start of the current period to now.
|`datePeriod`, `op: EQ` only

|`EXACT_DATE`
|A specific calendar date, or an inequality relative to a date.
|`epoch` (required for inequality ops), `op ∈ {EQ, NE, LT, LE, GT, GE}`

|`EXACT_DATE_RANGE`
|A date range between two bounds (inclusive).
|`date_range.low_epoch`, `date_range.high_epoch`, `op: BW_INC` only

|`QUARTER_YEAR`
|A specific quarter in a specific year.
|`quarter_name`, `year_name`, `op: EQ` only

|`MONTH_YEAR`
|A specific month in a specific year.
|`month_name`, `year_name`, `op: EQ` only

|`YEAR_ONLY`
|An entire calendar year.
|`year_name`, `op: EQ` only
|===

==== Unsupported type values

The following `type` values exist in the underlying `DateFilterType` proto enum but are
*not supported* by the `override_filters` API. Passing any of these values returns an
`Unsupported date filter type` error:

* `EXACT_TIME`
* `EXACT_DATE_TIME`
* `NOW`
* `MONTH_ONLY`
* `WEEKDAY_ONLY`
* `QUARTER_ONLY`
* `N_PERIOD_AGO`
* `PERIOD_ONLY`

[#rest-date-period-values]
=== datePeriod values

[cols="1,3", options="header"]
|===
|`datePeriod` value |Description
|`DAY`     |Calendar day
|`WEEK`    |Calendar week
|`MONTH`   |Calendar month
|`QUARTER` |Calendar quarter
|`YEAR`    |Calendar year
|`HOUR`    |Hour (for datetime columns only)
|`MINUTE`  |Minute (for datetime columns only)
|`SECOND`  |Second (for datetime columns only)
|===

[NOTE]
====
`HOUR`, `MINUTE`, and `SECOND` are valid only for columns that contain a time
component. On clusters where `hideTimeBasedFilters` is active, sub-day periods
are silently suppressed in the UI, but the REST API does not enforce this at the
request level.
====

[#rest-valid-operators-per-type]
=== Valid operators per filter type

The `op` field accepts string values from the `CompareTypeProto` enum. Valid
values depend on the `type`. Providing an invalid combination returns an
`Invalid date filter proto` error.

[cols="3,4", options="header"]
|===
|`type` value(s)
|Valid `op` values

|`YESTERDAY`, `TODAY`, `TOMORROW`
|`EQ` only

|`LAST_PERIOD`, `NEXT_PERIOD`, `THIS_PERIOD`, +
`LAST_N_PERIOD`, `NEXT_N_PERIOD`
|`EQ`, `LE`, `LT`, `GE`, `GT`

|`PERIOD_TO_DATE`, `QUARTER_YEAR`, +
`MONTH_YEAR`, `YEAR_ONLY`
|`EQ` only

|`EXACT_DATE`
|`EQ`, `NE`, `LT`, `LE`, `GT`, `GE`

|`EXACT_DATE_RANGE`
|`BW_INC` only
|===

[#rest-date-filter-negate]
=== Negating a date filter

The top-level `negate` field in the filter object inverts the match when set to `true`.

[IMPORTANT]
====
`negate` in the REST API is set at the *filter object* level (a sibling of
`date_filter`), not inside the `date_filter` object.
====

[NOTE]
====
Old-style epoch-based date filters do not support `negate: true`. Attempting to negate
a legacy date filter returns:

 Negate not supported with old date filters
====

=== Examples

==== Yesterday

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "YESTERDAY",
    "op": "EQ"
  }
}
----

==== Last 3 months (rolling)

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "LAST_N_PERIOD",
    "datePeriod": "MONTH",
    "number": 3,
    "op": "EQ"
  }
}
----

==== Last 3 months including the current partial month

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "LAST_N_PERIOD",
    "datePeriod": "MONTH",
    "number": 3,
    "op": "EQ",
    "include_current_period": true
  }
}
----

NOTE: `include_current_period` requires the *Include Current Period* feature to be
enabled on the cluster. It is silently ignored if the feature flag is off.

==== This quarter

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "THIS_PERIOD",
    "datePeriod": "QUARTER",
    "op": "EQ"
  }
}
----

==== Month to date

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "PERIOD_TO_DATE",
    "datePeriod": "MONTH",
    "op": "EQ"
  }
}
----

==== Exact date — on March 15, 2024

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "EXACT_DATE",
    "op": "EQ",
    "epoch": 1710460800
  }
}
----

==== Exact date — after March 15, 2024

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "EXACT_DATE",
    "op": "GT",
    "epoch": 1710460800
  }
}
----

==== Exact date range — January 1 to December 31, 2024 (inclusive)

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "EXACT_DATE_RANGE",
    "op": "BW_INC",
    "date_range": {
      "low_epoch": 1704067200,
      "high_epoch": 1735689599
    }
  }
}
----

==== Specific month and year — March 2024

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "MONTH_YEAR",
    "op": "EQ",
    "month_name": "MARCH",
    "year_name": "2024"
  }
}
----

==== Specific quarter and year — Q1 2024

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "QUARTER_YEAR",
    "op": "EQ",
    "quarter_name": "Q1",
    "year_name": "2024"
  }
}
----

==== Specific year — 2024

[source,json]
----
{
  "column_name": "Order Date",
  "date_filter": {
    "type": "YEAR_ONLY",
    "op": "EQ",
    "year_name": "2024"
  }
}
----



==== Combining date and attribute filters in one request

[source,json]
----
"override_filters": [
  {
    "column_name": "Order Date",
    "date_filter": {
      "type": "LAST_N_PERIOD",
      "datePeriod": "MONTH",
      "number": 3,
      "op": "EQ"
    }
  },
  {
    "column_name": "Region",
    "generic_filter": {
      "op": "IN",
      "values": [{ "value": "West" }, { "value": "East" }]
    }
  }
]
----

[#rest-column-name-resolution]
=== Resolving column names

The `column_name` field accepts the display name of the column as it appears in the
Liveboard's underlying data source. Matching is case-insensitive.

When the same column name appears in more than one worksheet referenced by the
Liveboard, qualify the name using the `::` separator:

----
"worksheet_name::column_name"
----

For example:

[source,json]
----
{
  "column_name": "Sales Metrics::Order Date",
  "date_filter": { ... }
}
----

If a column name matches more than one column and is not qualified, the API returns:

 Unable to determine logical column from name <name> due to more than one matches

[IMPORTANT]
====
The REST API qualifier order is *`worksheet_name::column_name`* — worksheet first,
column second. This is the *opposite order* from the Visual Embed SDK's
`UpdateFilters` qualifier format, which is `column_name::datasource_name`.
See xref:filters-overview.adoc#column-name-resolution[Embed SDK: Resolving column names].
====

=== Comparison with Embed SDK date filter fields

If you are familiar with the Visual Embed SDK `UpdateFilters` date filter syntax,
the following table maps each SDK field to its REST API equivalent.

[cols="2,2,3", options="header"]
|===
|Embed SDK field
|REST API `date_filter` field
|Notes

|`type` (camelCase, e.g. `LastNPeriod`)
|`type` (UPPER_SNAKE_CASE, e.g. `LAST_N_PERIOD`)
|Different naming convention.

|`datePeriod` (e.g. `Month`)
|`datePeriod` (e.g. `MONTH`)
|Same concept, UPPER_SNAKE_CASE in REST API.

|`operator` (e.g. `EQ`)
|`op` (e.g. `EQ`)
|Different field name. Same value strings.

|`values[0]` (for `LastNPeriod`)
|`number`
|SDK carries N in the `values` array; REST API uses an explicit `number` field.

|`values[0]` (for `ExactDate`)
|`epoch`
|SDK carries epoch in `values`; REST API uses an explicit `epoch` field.

|`values[0]`, `values[1]` (for `ExactDateRange`)
|`date_range.low_epoch`, `date_range.high_epoch`
|SDK packs both bounds into `values`; REST API uses an explicit nested object.

|`values[0]` (for `MonthYear`)
|`month_name`
|SDK: `values: ['MARCH', '2024']`. REST API: `month_name: "MARCH"`, `year_name: "2024"`.

|`values[0]` (for `QuarterYear`)
|`quarter_name`
|SDK: `values: ['Q1', '2024']`. REST API: `quarter_name: "Q1"`, `year_name: "2024"`.

|`values[0]` (for `YearOnly`)
|`year_name`
|SDK: `values: ['2024']`. REST API: `year_name: "2024"`.

|`negate`
|`negate` (top-level sibling, not inside `date_filter`)
|Same semantics, different placement.

|`includeCurrentPeriod`
|`include_current_period`
|camelCase vs snake_case. Same semantics.

|`columnName`
|`column_name`
|Qualifier order is reversed: SDK uses `column::datasource`; REST API uses `worksheet::column`.
|===

== Updating runtime filters

For information about runtime filters update, see xref:runtime-filters.adoc#_adjust_runtime_filters_using_sdk_events[Runtime filters documentation].

== Removing filters
To remove a specific filter, pass the empty values array, as shown in the following examples:

*Runtime filters*
[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [{
    columnName: "item type",
    operator: RuntimeFilterOp.EQ,
    values: [] // set an empty array to clear runtime filters
}]);
----

*Liveboard filters*

[source,JavaScript]
----
liveboardEmbed.trigger(HostEvent.UpdateFilters, {
    filters: [{
        column: "state",
        oper: "EQ",
        values: [] // set an empty array to clear filters
       }]
   });
----

Setting empty values via `HostEvent.UpdateFilters` removes only the filter values; it does not remove or hide the filter chips from the Liveboard.


////
=== Events
There is no specific event to update `search_query filters` in the `SearchEmbed` component or the Liveboard edit mode.

You can set your app to listen to link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent#_querychanged[EmbedEvent.QueryChanged] and trigger the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_gettml[HostEvent.GetTML] event to get a new TML generated for the `search_query` string after an update.
