= Formula variables
:toc: true
:toclevels: 2

:page-title: Formual variables
:page-pageid: formula-variables
:page-description: Formula variables in ThoughtSpot are custom template variables that enable dynamic, context-aware logic in formulas, especially for Row Level Security (RLS) rules.

Formula variables are a type of template variable in ThoughtSpot that enable dynamic and context-aware logic in Row Level Security (RLS) rules.

== Overview
Formula variables can be configured at the Org, user, and data model levels to implement clear rule definitions for data security, dynamic assignment at runtime, and a more efficient SQL query generation.

You can use the formula variables in the following scenarios:

* In Attribute-Based Access Control (ABAC) implementation and the xref:rls-rules.adoc[RLS rules] to dynamically restrict access to data. For example, to filter data by region, department, or entitlement, with the value determined by the Org or user context.
* For personalized analytics with user-specific filtering and calculations without duplicating objects or hardcoding values.

Formula variables are available on ThoughtSpot application instances with 10.15.0.cl or later, and can be configured by administrators via REST APIs.

Administrators can restrict the scope of formula variables to Orgs, users, and Models. They can also implement a combination of Org, user, and Model-specific rules to enforce access control. For example, you can set rules to restrict access to columns in a data model for users from a specific Org. Variables defined in a primary Org are propagated to all Orgs, unless Org-specific overrides are configured by the Org administrators.

[IMPORTANT]
====
* Currently, the formula variables can be added and managed only via REST APIs.
* To configure formula variables for all Orgs on your instance or the Primary Org, cluster administration privileges are required. Org administrators can configure formula variables for their respective Orgs. Users with the `CAN_MANAGE_VARIABLES` (*Can manage variables*) role privilege can also create and manage variables for their Org context.
* The variable values are case-sensitive.
====

=== Configure formula variables

To create formula variables and assign values, use the xref:variables.adoc#_create_a_variable[variable creation] and xref:variables.adoc#_assign_values_and_update_properties_of_multiple_variables[update REST APIs].

The `/api/rest/2.0/template/variables/create` API endpoint allows creating formula variables with string, integer, decimal, and epoch values for date and date and time. During variable creation, you must specify the xref:variables.adoc#data_type [`data_type`]. When assigning values, you must ensure the assigned values match the data type configured for that variable.

The following example shows the API request body for creating a variable that allows string values:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/]api/rest/2.0/template/variables/create' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "type": "FORMULA_VARIABLE",
  "name": "region_var",
  "is_sensitive": false,
  "data_type": "VARCHAR"
}'
----

After creating variables, you must assign values. If you are using formula variables to implement ABAC via RLS, you can assign values via xref:abac-user-parameters.adoc#_abac_via_rls_with_formula_variables[ABAC token generation request].

You can also add or update variable values and set the scope using the xref:variables.adoc#_define_values_and_scope_for_variables[variable update] API endpoint.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/template/variables/update-values'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "variable_assignment": [
    {
      "variable_identifier": "region_var",
      "variable_values": [
        "EMEA"
      ],
      "operation": "ADD"
    },
  ],
  "variable_value_scope": [
    {
      "org_identifier": "Org_EMEA",
      "model_identifier": "80c969e7-3a36-48b7-923e-e2fb5c3fe88f",
      "principal_type": "USER",
      "principal_identifier": "tsuser"
    }
  ]
}'
----

=== Include formula variable rules in ABAC tokens
Formula variables in the JWT token or ABAC context are used as parameters whose values are set via the JWT token at session creation. You can include the variable name and values in your token generation request and apply rules to the authenticated user sessions.

For example, when the JWT token is generated with formula variables for region, country, or department-specific control, these values are used by data model filters and RLS rules to apply security entitlements to the user session.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/auth/token/custom'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  --data-raw '{
  "username": "UserA",
  "validity_time_in_sec": 300,
  "persist_option": "APPEND",
  "auto_create": true,
  "password": "{password}",
  "secret_key": "6c523cf9-c5c7-4cb2-a70b-9c5be2d7c0fe",
  "org_identifier": "Primary",
  "variable_values": [
    {
      "name": "department_var",
      "values": [
        "Sales",
        "Marketing"
      ]
    }
  ],
  "objects": [
    {
      "type": "LOGICAL_TABLE",
      "identifier": "cd252e5c-b552-49a8-821d-3eadaa049cca"
    }
  ],
  "email": "UserA@testOrg.com",
  "display_name": "User A",
  "groups": [
  ],
}'
----

The values can be set via  `POST /api/rest/2.0/auth/token/custom` API calls and included in the access control properties for the user for whom the token is generated. The variable values defined in the ABAC tokens cannot be overridden in the UI or reset using the `"persist_option": "RESET"` option. However, administrators can replace or append, or reset values via a new API request.

==== Setting variable value to TS_WILDCARD_ALL

If a variable value is set to `TS_WILDCARD_ALL`, all values are returned during SQL query generation, and the SQL removes the filters from the WHERE clause.

=== Add variable references in RLS rules
Before adding variable references in the formulas, make sure the variables are available in your Org context, with values assigned according to the data type configured during variable creation. To get a list of formula variables available in ThoughtSpot, use the `/api/rest/2.0/template/variables/search` API endpoint.

To add a variable reference:

. Navigate to the Data workspace and click the Table for which to define the RLS rules.
. Click *Row security* and then click *+ Add row security*.
. In the row security editor window, define the formulas with variable references. You must include the formula variable reference with the `ts_var` function.

==== Examples

The following examples show how to reference formula variables in RLS rules:

Formula variables with string values (VARCHAR)::

In the following examples, the formula references `region_var` and `country_var` variables. When the query is executed, the region will translate to the value defined for that variable, for example, West or EMEA. Similarly, `country_var` translates to the value specified for that variable.
+
----
region = ts_var('region_var')
----
+
----
country = ts_var('country_var')
----

Formula variables with integer values (Integer)::

In this example, the formula references the `min_quantity_var` variable that sets a threshold value. The formula specifies if the value in the `quantity_purchased` field is greater than the value of the `min_quantity_var` variable. If this condition is true, it returns the `sales_dollar_amount`; else it returns 0.

+
----
if(quantity_sold > ts_var('min_quantity_var')) then sales_dollar_amount else 0
----

Formula variables with decimal values (Double / Float)::

In this example, the formula calculates the gross margin percentage as `(gross_profit / sales) * 100` and compares it to value of the `margin_threshold_var` variable, for example, 25.0. If the gross margin percentage is greater than the threshold, it returns 'High'; Otherwise, it returns 'Low'. This is a conditional logic formula used to categorize records based on whether their gross margin exceeds a specified threshold.
+
----
if((gross_profit / sales) * 100 > ts_var('margin_threshold_var')) then 'High' else 'Low'
----

Formula variables with Date or Date_Time data type::

In this example, the formula sets a rule to include records where the `event_timestamp` is greater than or equal to the value specified by the `start_date_time_var` variable.
+
----
if(event_timestamp >= ts_var('start_date_time_var')) then value else 0
----
+
Similarly, you can apply rules for a specific date range:
+
----
if(date_column >= ts_var('start_date_var') and date_column <= ts_var('end_date_var')) then value else 0
----

=== Verify the rules
To verify the rules, inspect the generated SQL for your query or visualization.

== Additional resources

* For information about RLS rule definitions, see link:https://docs.thoughtspot.com/cloud/latest/security-rls[RLS rules documentation, window=_blank].
* For information about variable APIs, see xref:variables.adoc[Variable APIs].
* For information about assigning security entitlements via ABAC tokens, see xref:abac-user-parameters.adoc[ABAC via tokens].