= Customize your full application embed
:toc: true
:toclevels: 1

:page-title: Customize your full application embed
:page-pageid: full-app-customize
:page-description: Customize the home page and navigation for full application embedding

Use the full app embed configuration settings in the Visual Embed SDK to customize the visual experience and home page layout.

== Overview
The Visual Embed SDK supports the following customization options in full application embedding:

[width="100%", cols="5,^3"]
[options="header"]
|====
|Feature |Availability
|Left navigation panel customization
|[tag greenBackground tick]#✓# Supported
|Custom reordering of left nav items
|[tag greenBackground tick]#✓# Supported
|List page customization
|[tag greenBackground tick]#✓# Supported
|Reordering and hiding home page modules
|[tag greenBackground tick]#✓# Supported in modular home page experience +
[tag redBackground tick]#x# Not supported in focused home page experience
|====

== Navigation experience
In the embed mode, the default experience includes the top and left sliding navigation panels if the `showPrimaryNavbar` parameter is enabled in the SDK. You can customize these panels using the settings available in the SDK. For more information, see xref:customize-nav-full-embed.adoc[Customize navigation experience].

== Home page experience
ThoughtSpot application supports the following types of home page experience:

* *Modular homepage experience*: The default home page experience, which includes the left navigation panel, customizable modules, and styling changes.
* *Focused homepage experience*: A home page experience with a focused layout and customization options.

For information about the home page components and the related customization settings in the SDK, see xref:customize-homepage-full-embed.adoc[Customize home page experience].

== List page experience
A list page in ThoughtSpot refers to a page that displays a list of objects, such as Answers, Liveboards, and Liveboard schedules. The list pages include columns for sorting, filtering, tagging, sharing, or deleting objects.

The list layouts typically include columns such as *Name*, *Author*, *Favorites*, *Tags*, *Last Viewed*, and more.

For Liveboard lists, a *Verified* column is available to filter the list by verified objects. In addition to these columns, the list pages include the **Views** column and the following options:

* Sorting options for the **Name**, **Author**, and **Views** columns.
* Column-level filters by author, favorites, last viewed date, or last modified date.

=== Including or excluding columns
To customize the columns in list pages such as *Liveboards* and *Answers*, use the xref:AppViewConfig.adoc#_hiddenlistcolumns[hiddenListColumns] attribute with the following List page IDs:

* `ListPageColumns.Author` to show or hide the *Author* column.
* `ListPageColumns.DateSort` to show or hide the *Last modified* column.
* `ListPageColumns.Favorites` to show or hide the *Favorites* column.
* `ListPageColumns.Share` to show or hide the *Share* links in the column.
* `ListPageColumns.Tags` to show or hide the *Tags* column.
* `ListPageColumns.Verified` to show or hide the *Verified* column in Liveboard lists.

The following example hides specific columns using the `hiddenListColumns` array:

[source,javascript]
----
import {
    AppEmbed, // Main class to embed the full ThoughtSpot app
    ListPageColumns // Enum for columns on list pages
} from '@thoughtspot/visual-embed-sdk';

const embed = new AppEmbed("#embed", {
    // hide Author, Share, and Tags columns on Answers and Liveboards listing pages
    hiddenListColumns: [
        ListPageColumns.Author,
        ListPageColumns.Share,
        ListPageColumns.Tags
    ],
    //... other view config attributes

});
----

[NOTE]
====
The `hiddenListColumns: [ListPageColumns.Share]` hides the *Share* column, but doesn't remove the *Share* button that appears above the list on selecting an object. To hide both the column and the *Share* button, use xref:Action.adoc#_share[Action.Share] in the  `hiddenActions` array.
====

== Default loading page and navigation routes
In full application embedding, the home page is set as the default landing page when the embedded app loads. You can set the default landing page using the `pageId` or `path` attribute. For more information, see xref:set-default-page.adoc[customize the default landing page settings].

== Style customization controls
xref:css-customization.adoc[CSS customization] allows overriding default styles in ThoughtSpot application pages. You can also use xref:theme-builder.adoc[Theme Builder] to explore the available CSS variables.

If there is a page element you cannot hide using ThoughtSpot or Visual Embed SDK options, you can use a CSS selector to target the element and apply CSS properties such as `display: none`, `visibility: hidden`, or `height: 0px` to hide it from the UI. To find the appropriate selector, use your browser's *Inspect* tool to examine the style element in the *Elements* section of the browser's Developer Tools.

[source,css]
----
.bk-data-scope .left-pane .header-lt {
  display: none !important;
  visibility: hidden !important;
}
----

You can also declare direct selectors using the xref:css-customization.adoc#_css_rules_using_selectors[rules] property in the Visual Embed SDK configuration. This is useful for real-time testing, especially in the Visual Embed SDK playground. Note the required format for encoding CSS rules as JavaScript objects. An example of using direct selectors in a file is available in the link:https://github.com/thoughtspot/custom-css-demo/blob/main/complete.css[complete.css sample, window=_blank] on the ThoughtSpot GitHub repository.


== Additional resources

* xref:full-embed.adoc[Embed full application]
* xref:customize-nav-full-embed.adoc[Customize the navigation for full application embedding]
* xref:customize-homepage-full-embed.adoc[Customize the home page for full application embedding]
* xref:AppViewConfig.adoc[AppViewConfig reference page]
* xref:HostEvent.adoc[Host events for app interactions]
* xref:EmbedEvent.adoc[Embed Events]
* xref:Action.adoc[Action IDs for menu customization]
* link:https://docs.thoughtspot.com/cloud/latest/thoughtspot-homepage#_focused_home_page[ThoughtSpot Homepage experience, window=_blank]
