= Get Started with embedding
:toc: true
:linkattrs:
:sectanchors:


:page-title: Getting Started
:page-pageid: getting-started
:page-description: Getting Started

ThoughtSpot provides Visual Embed SDK to embed Search bar, Search page, Liveboard, visualizations, or the full ThoughtSpot experience in your web application or portal. Based on your embedding requirements and integration setup, you can use one of the following embedding methods:

* xref:getting-started.adoc#_get_started_with_visual_embed_sdk[Embed using Visual Embed SDK] (Recommended)
* xref:embed-without-sdk.adoc[iFrame embedding without SDK]

== Get started with Visual Embed SDK

ThoughtSpot Visual Embed SDK offers a JavaScript library that allows you to embed ThoughtSpot components in web pages. This section helps you get started with embedding a ThoughtSpot component in your app.

=== Before you begin

Adjust CORS and CSP settings::

Before embedding ThoughtSpot in your app, check if your application domain is added to the CSP and CORS allowlist on the *Develop* > *Customizations* > *Security Settings* page.
+
If you encounter any errors when using the Visual Embed SDK components, verify the xref:security-settings.adoc#csp-cors-hosts[CORS and CSP settings].

Enable Developer Portal access::
ThoughtSpot users can access Developer Portal via *Develop* tab in the UI.
+
Only administrators and users with `Developer` privilege can access the *Develop* tab. Please have your administrator add any users who will be developing embedded solutions to a ThoughtSpot group with *Has Developer privilege*.

////
For more information, see xref:user-roles.adoc[Developer access].
////

=== Install the Visual Embed SDK

The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package. Make sure the link:https://www.npmjs.com/get-npm[NPM is installed, window=_blank] in your environment.

The latest version of the Visual Embed SDK is available at link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk, window=_blank].

To install the SDK from NPM, execute the following command:

[source,console]
----
npm install @thoughtspot/visual-embed-sdk
----

=== Import embed package

The SDK is written in TypeScript and is also provided both as ES Module (ESM) and Universal Module Definition (UMD) modules, allowing you to use it in a variety of environments.

[source,JavaScript]
----
// ESM via NPM
import * as TsEmbedSDK from '@thoughtspot/visual-embed-sdk';
// OR
import { LiveboardEmbed } from '@thoughtspot/visual-embed-sdk';

// NPM <script>
<script src="https://cdn.jsdelivr.net/npm/@thoughtspot/visual-embed-sdk/dist/tsembed.js"></script>;
// Makes the SDK available on global namespace window.tsembed

// ES6 from web
import {
LiveboardEmbed,
AuthType,
init,
} from 'https://cdn.jsdelivr.net/npm/@thoughtspot/visual-embed-sdk/dist/tsembed.es.js';
----

Import one of the following modules into your app:

LiveboardEmbed::
Use the **LiveboardEmbed** component to embed a single visualization or a full Liveboard with multiple visualizations

+
++++
<a href="?pageid=embed-liveboard" id="preview-in-playground" target="_blank">Embed a Liveboard</a>
++++

AppEmbed::
Use the `AppEmbed` library to embed full ThoughtSpot application in your app.

+
++++
<a href="?pageid=full-embed" id="preview-in-playground" target="_blank">Embed full ThoughtSpot application</a>
++++

SearchEmbed::

Use the SearchEmbed package to embed the ThoughtSpot search page with a pre-selected data source. +

+
++++
<a href="?pageid=embed-search" id="preview-in-playground" target="_blank">Embed Search page</a>
++++

SearchBarEmbed::

Use the **SearchBarEmbed** component to embed only the ThoughtSpot Search bar and data panel.

+
++++
<a href="?pageid=embed-searchbar" id="preview-in-playground" target="_blank">Embed Search page</a>
++++

[#initSdk]
=== Initialize the SDK

After importing the package, specify the hostname or IP address of your ThoughtSpot application instance and the authentication type.

[source,JavaScript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.EmbeddedSSO,
});
----
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.

For other supported authentication methods, see xref:embed-authentication.adoc[Authentication].

=== Register events

Subscribe and listen to events triggered when the embedded object interacts with your app.

* xref:HostEvent.adoc[HostEvent]
* xref:EmbedEvent.adoc[EmbedEvent]

=== Render the embedded application

Render the embedded application.

[source,JavaScript]
----
liveboardEmbed.render();
----

=== Code sample
[source,Javascript]
----
// NPM
import { LiveboardEmbed, AuthType, init } from '@thoughtspot/visual-embed-sdk';
// or ES6
// import { LiveboardEmbed, AuthType, init } from 'https://cdn.jsdelivr.net/npm/@thoughtspot/visual-embed-sdk/dist/tsembed.es.js';

init({
    thoughtSpotHost: '<%=tshost%>',
    authType: AuthType.None,
});

const liveboardEmbed = new LiveboardEmbed(
    document.getElementById('ts-embed'),
    {
        frameParams: {
            width: '100%',
            height: '100%',
        },
        liveboardId: '<%=liveboardGUID%>',
        vizId: '<%=vizGUID%>',
    },
});

liveboardEmbed.render();

liveboardEmbed.on(EmbedEvent.LiveboardRendered, () => {
    liveboardEmbed.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2']);
});
----

////
=== Embed ThoughtSpot objects
After you initialize the SDK, create embed object classes and define object properties. +
For more information about embedding ThoughtSpot app or its objects using SDK, see the following pages: +

* xref:embed-search.adoc[Embed Search page]
* xref:embed-searchbar.adoc[Embed Search bar]
* xref:embed-pinboard.adoc[Embed a Liveboard]
* xref:embed-a-viz.adoc[Embed a Liveboard visualization]
* xref:full-embed.adoc[Embed full ThoughtSpot app]


////

== Related information

* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/README.md[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]

