= Embed ThoughtSpot
:toc: true
:linkattrs:
:sectanchors:

:page-title: Embed ThoughtSpot
:page-pageid: tsembed
:page-description: Getting Started

Based on your embedding requirements and integration setup, you can use one of the following methods:

* Embed using Visual Embed SDK (Recommended)
+
ThoughtSpot Visual Embed SDK offers a JavaScript library that allows you to embed ThoughtSpot components in web pages. This section helps you get started with embedding a ThoughtSpot component in your app.
* xref:embed-without-sdk.adoc[iFrame embedding without SDK]

The following sections describe how to embed a ThoughtSpot component using Visual Embed SDK.

== Before you begin

[IMPORTANT]
====
**Adjust CORS and CSP settings**

Before embedding ThoughtSpot in your app, check if your application domain is added to the CSP and CORS allowlist on the *Develop* > *Customizations* > *Security Settings* page.

If you encounter any errors when using the Visual Embed SDK components, verify the xref:security-settings.adoc#csp-cors-hosts[CORS and CSP settings].
====

**Get Developer access**

Only administrators and users with `Developer` privilege can access the *Develop* tab. Please have your administrator add any users who will be developing embedded solutions to a ThoughtSpot group with *Has Developer privilege*.

////
For more information, see xref:user-roles.adoc[Developer access].
////

== Embed using SDK

The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package. The latest version of the Visual Embed SDK is available at link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk, window=_blank].

To get started with embedding, install the SDK:

[source,console]
----
npm install @thoughtspot/visual-embed-sdk
----

=== Import embed package

The SDK is written in TypeScript and is also provided both as ES Module (ESM) and Universal Module Definition (UMD) modules, allowing you to use it in a variety of environments.

Import one of the following modules into your app:

* **LiveboardEmbed** +
Use the **LiveboardEmbed** component to xref:embed-a-viz.adoc[embed a single visualization] or a full Liveboard with multiple visualizations:

+
++++
<a href="?pageid=embed-liveboard" id="preview-in-playground" target="_blank">Embed a Liveboard</a>
++++

* **SageEmbed** +
Use the `SageEmbed` package to embed Natural Language Search interface.

+
++++
<a href="?pageid=embed-nls" id="preview-in-playground" target="_blank">Embed Natural Language Search</a>
++++

* **AppEmbed** +
Use the `AppEmbed` library to embed full ThoughtSpot application in your app.

+
++++
<a href="?pageid=full-embed" id="preview-in-playground" target="_blank">Embed full ThoughtSpot application</a>
++++

* **SearchEmbed** +
Use the `SearchEmbed`  package to embed the ThoughtSpot search page with a pre-selected data source.
+
++++
<a href="?pageid=search-embed" id="preview-in-playground" target="_blank">Embed Search page</a>
++++

* **SearchBarEmbed** +
Use the `SearchBarEmbed` component to embed only the ThoughtSpot Search bar and data panel.

+
++++
<a href="?pageid=embed-searchbar" id="preview-in-playground" target="_blank">Embed Search bar</a>
++++

==== Example

[source,JavaScript]
----
// ESM via NPM
import * as TsEmbedSDK from '@thoughtspot/visual-embed-sdk';
// OR
import { LiveboardEmbed } from '@thoughtspot/visual-embed-sdk';

// NPM <script>
<script src="https://cdn.jsdelivr.net/npm/@thoughtspot/visual-embed-sdk/dist/tsembed.js"></script>;
// Make the SDK available on global namespace window.tsembed

// ES6 from web
import {
    LiveboardEmbed,
    AuthType,
    init,
    EmbedEvent,
    HostEvent
} from 'https://cdn.jsdelivr.net/npm/@thoughtspot/visual-embed-sdk/dist/tsembed.es.js';
----

[#initSdk]
== Initialize the SDK

After importing the package, specify the hostname or IP address of your ThoughtSpot application instance and the authentication type. For other supported authentication methods, see xref:embed-authentication.adoc[Authentication].

[source,JavaScript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: <AuthType>,
    ... // other authType dependent properties.
});
----

=== Embed ThoughtSpot Component
Create an object instance and define object properties. This example shows the code sample for a Liveboard object:

[source,JavaScript]
----
const liveboardEmbed = new LiveboardEmbed(
    document.getElementById('ts-embed'),
    {
        frameParams: {
            width: '100%',
            height: '100%',
        },
        liveboardId: '<%=liveboardGUID%>',
    },
});
----

== Register events

Register events that your app can listen to and respond with appropriate actions.
The following example registers `LiveboardRendered` and `SetVisibleVizs` events. The `LiveboardRendered` embed event is emitted when the embedding application renders the Liveboard and triggers the `SetVisibleVizs` event to show specific visualizations on the Liveboard.

[source,JavaScript]
----
liveboardEmbed.on(EmbedEvent.LiveboardRendered, () => {
    liveboardEmbed.trigger(HostEvent.SetVisibleVizs, ['viz1', 'viz2']);
});
----

* xref:HostEvent.adoc[HostEvent]
* xref:EmbedEvent.adoc[EmbedEvent]


== Render the embedded object

Render the embedded application.

[source,JavaScript]
----
liveboardEmbed.render();
----

== Code sample
[source,Javascript]
----
import {
    LiveboardEmbed,
    AuthType,
    init,
    EmbedEvent,
    HostEvent
} from '@thoughtspot/visual-embed-sdk';

const lb = new LiveboardEmbed('#container', {
    frameParams: {
        width: '100%',
        height: '100%',
    },
    liveboardId: '<%=liveboardGUID%>',
    runtimeFilters: [],
});
// [Optional]: Register event listeners.
lb.on(EmbedEvent.LiveboardRendered, (e) => {
    /* handler */
});

// Do not forget to call render.
lb.render();

// [Optional]: Trigger events on the lb
lb.trigger(HostEvent.UpdateRuntimeFilters, [
    {
        columnName: 'col1',
        operator: RuntimeFilterOp.EQ,
        values: ['val1'],
    },
]);
----

`#container` is a selector for the DOM node which the code assumes is already attached to DOM. The SDK will render the ThoughtSpot component inside this container element.

== Embed in a React app
ThoughtSpot provides React components for embedding Search, Liveboard, and the full ThoughtSpot application in a React app. The following code sample shows how to embed a Liveboard component in a React app:

[source,TypeScript]
----
import { LiveboardEmbed } from '@thoughtspot/visual-embed-sdk/react';

const App = () => {
    const embedRef = useEmbedRef();
    const onLiveboardRendered = () => {
        embedRef.current.trigger(HostEvent.UpdateRuntimeFilters, [
            {
                columnName: 'col1',
                operator: RuntimeFilterOp.EQ,
                values: ['val1'],
            },
        ]);
    };
    return (
        <LiveboardEmbed
            ref={embedRef}
            liveboardId="<liveboard-guid>"
            onLiveboardRendered={onLiveboardRendered}
        />
    );
};
----

For more information, see xref:embed-ts-react-app.adoc[Embed ThoughtSpot in a React app].

////
=== Embed ThoughtSpot objects
After you initialize the SDK, create embed object classes and define object properties. +
For more information about embedding ThoughtSpot app or its objects using SDK, see the following pages: +

* xref:embed-search.adoc[Embed Search page]
* xref:embed-searchbar.adoc[Embed Search bar]
* xref:embed-pinboard.adoc[Embed a Liveboard]
* xref:embed-a-viz.adoc[Embed a Liveboard visualization]
* xref:full-embed.adoc[Embed full ThoughtSpot app]


////

== Related information

* xref:VisualEmbedSdk.adoc[Visual Embed SDK Reference Guide]
* link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/README.md[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Embedded Resources on GitHub, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials, window=_blank]
