= Get Started with embedding
:toc: true
:linkattrs:
:sectanchors:


:page-title: Getting Started
:page-pageid: getting-started
:page-description: Getting Started

ThoughtSpot provides Visual Embed SDK to embed Search bar, Search page, Liveboard, visualizations, or the full ThoughtSpot experience in your web application or portal. Based on your embedding requirements and integration setup, you can use one of the following embedding methods:

* xref:getting-started.adoc#_get_started_with_visual_embed_sdk[Embed using Visual Embed SDK] (Recommended)
* xref:embed-without-sdk.adoc[iFrame embedding without SDK]

== Get started with Visual Embed SDK

ThoughtSpot Visual Embed SDK offers a JavaScript library that allows you to embed ThoughtSpot components in web pages.

=== Before you begin

Prepare your project environment::

The Visual Embed SDK is available for installation as a Node Package Manager (NPM) package. Make sure the link:https://www.npmjs.com/get-npm[NPM is installed, window=_blank] in your environment.
+
You can also access Visual Embed SDK, including information about how to install from NPM or run from a web repository, in the link:https://github.com/thoughtspot/visual-embed-sdk[ThoughtSpot Visual Embed SDK GitHub repository, window=_blank].

Adjust CORS and CSP settings::

Before embedding ThoughtSpot in your app, check if your application domain is added to the CSP and CORS allowlist on the *Develop* > *Customizations* > *Security Settings* page.
+
If you encounter any errors when using the Visual Embed SDK components, verify the xref:security-settings.adoc#csp-cors-hosts[CORS and CSP settings].

Enable Developer Portal access::
ThoughtSpot users can access Developer Portal via *Develop* tab in the UI.
+
Only administrators and users with `Developer` privilege can access the *Develop* tab. Please have your administrator add any users who will be developing embedded solutions to a ThoughtSpot group with *Has Developer privilege*.

////
For more information, see xref:user-roles.adoc[Developer access].
////


=== Install the Visual Embed SDK
The latest version of the Visual Embed SDK is available at link:https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk[https://www.npmjs.com/package/@thoughtspot/visual-embed-sdk, window=_blank].

To install the SDK, run the following command at the command line:
[source,console]
----
npm install @thoughtspot/visual-embed-sdk
----

=== Import embed package

Based on integration requirements, import any of the following embed modules and build your code.

SearchEmbed::

Use this package to xref:embed-search.adoc[embed the ThoughtSpot search page components].
+
The **SearchEmbed** component allows you to embed the search bar and data panel. You can load it with a pre-selected data source and let your users define search keywords or show a set of example search tokens on load, either from a data source or an existing saved Answer. +
+
In all cases, the search bar will appear along with full capabilities to edit search tokens and the resulting chart or table.


SearchBarEmbed::

Use this package to xref:embed-searchbar.adoc[embed only the Search bar].
+
The **SearchBarEmbed** component allows you to embed only the ThoughtSpot Search bar and data panel. The embedded search bar is responsive and can be adjusted to fit the screen width of your app.

LiveboardEmbed::
Use this package to embed ThoughtSpot xref:embed-a-viz.adoc[visualizations] and xref:embed-pinboard.adoc[Liveboards].
+
You can use the **LiveboardEmbed** component to embed a full Liveboard with multiple answers, as well as a specific Answer on a Liveboard without the search bar. These answers are referred to as Liveboard visualizations. +
+
Although you can use a saved Answer as a data source in SearchEmbed, ThoughtSpot does not support embedding a saved Answer. However, you can embed a specific visualization from a Liveboard using the `liveboardId` and `vizId` properties of LiveboardEmbed.

AppEmbed::
Use this package to embed xref:full-embed.adoc[the full ThoughtSpot application].

[#initSdk]
=== Initialize the SDK

After importing the package, specify the hostname or IP address of your ThoughtSpot application instance and the authentication type.

[source,JavaScript]
----
init({
    thoughtSpotHost: "https://<hostname>:<port>",
    authType: AuthType.EmbeddedSSO,
});
----
thoughtSpotHost::
_String_. Hostname or IP address of the ThoughtSpot application.

For supported authentication methods, see xref:embed-authentication.adoc[Authentication].

=== Render the embedded application

Render the embedded application.

[source,JavaScript]
----
appEmbed.render();
----


////
=== Embed ThoughtSpot objects
After you initialize the SDK, create embed object classes and define object properties. +
For more information about embedding ThoughtSpot app or its objects using SDK, see the following pages: +

* xref:embed-search.adoc[Embed Search page]
* xref:embed-searchbar.adoc[Embed Search bar]
* xref:embed-pinboard.adoc[Embed a Liveboard]
* xref:embed-a-viz.adoc[Embed a Liveboard visualization]
* xref:full-embed.adoc[Embed full ThoughtSpot app]

////
== Related resources

* link:{{visualEmbedSDKPrefix}}/modules.html[Visual Embed SDK Reference Guide, window=_blank] 
* link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/README.md[Visual Embed SDK GitHub repository, window=_blank]
* link:https://github.com/thoughtspot/ts_everywhere_resources[ThoughtSpot Everywhere Resources on GitHub, window=_blank]
* link:https://developers.thoughtspot.com/guides[Visual Embed Tutorials]
