= Git provider integration
:toc: true
:toclevels: 2

:page-title: Git provider integration using TML APIs
:page-pageid: git-provider-integration
:page-description: Overview of using a Git provider to manage SDLC in ThoughtSpot

Git providers such as GitHub, GitLab, Azure DevOps and BitBucket can run scripts that use the ThoughtSpot REST API and TML modification capabilities. 

This allows the Git provider to become the centralized control service for deployment processes to ThoughtSpot.

[NOTE]
====
The legacy GitHub REST APIs are used through ThoughtSpot and are tied to GitHub exclusively. The Git provider integration pattern provides more flexibility and control.
====

== Overview
The Git provider integration pattern is based on storing the necessary secrets in the Git provider to allow ThoughtSpot REST API commands to be run by the Git provider when accomplishing tasks on demand or on a schedule.

All imports and exports of ThoughtSpot TML files to and from branches, along with the commits and merges are controlled entirely in git using the Git provider's capabilities.  

== Setup

== GitHub Actions example
