= Mobile Embed SDK Changelog
:toc: true
:toclevels: 2

:page-title: Changelog
:page-pageid: mobile-sdk-changelog
:page-description: Changes to the Mobile SDK and APIs

This changelog lists only the changes introduced in the Mobile Embed SDK. For information about the new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== React Native Embed SDK

=== Version 0.0.1, April 2025

The version 0.0.1 of the React Native Embed SDK [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in native mobile apps for both Android and iOS, using JavaScript and React.

The SDK provides several configuration settings and attributes to customize the embedded view.

For more information, see xref:mobilesdk-quick-start.adoc[Embed ThoughtSpot using React Native mobile SDK].

== Flutter Embed SDK

=== Version 0.0.1, May 2025

The version 0.0.1 of the Flutter Embed SDK [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in a Flutter app.

The SDK also provides several configuration settings and attributes to customize the embedded view.

For more information, see xref:mobile-embed-qs-flutter.adoc[Embed ThoughtSpot in a Flutter app].

== Swift Embed SDK

=== Version 0.0.1, May 2025

The version 0.0.1 of the Swift Embed SDK [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in an iOS native app.

The SDK also provides the following features and configuration settings to customize the embedded view.

For more information, see xref:mobile-embed-qs-swift.adoc[Embed ThoughtSpot in an iOS app].

== Android Embed SDK

=== Version 0.0.1, May 2025

The version 0.0.1 of the Android Embed SDK [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in an Android native app.

The SDK also provides the following features and configuration settings to customize the embedded view.

For more information, see xref:mobile-embed-android.adoc[Embed ThoughtSpot in an Android app].
