= Embed ThoughtSpot using React Native mobile SDK
:toc: true
:toclevels: 2

:page-title: Embed ThoughtSpot with mobile SDK
:page-pageid: embed-ts-mobile-react-native
:page-description: Using mobile SDK, you can now embed ThoughtSpot in your mobile apps

ThoughtSpot's Mobile Embed SDK enables developers to embed ThoughtSpot Analytics in their mobile apps. The Mobile Embed SDK is designed for the React Native framework to allow developers to build their mobile apps that operate on *iOS* and *Android* platforms, using native resources and a single codebase.

In its initial release, the Mobile SDK for React Native supports embedding ThoughtSpot’s Liveboard component and allows for customization of the Liveboard view within the mobile app.

To learn how to embed ThoughtSpot content in your mobile app using the React Native Mobile SDK, refer to the steps described in this Quick Start Guide.

== Before you begin

Before you get started, check the following:

* You have access to a ThoughtSpot instance with the necessary credentials.
* link:https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[NPM and Node.js are installed, window=_blank] on your system.
* Your link:https://reactnative.dev/docs/environment-setup[React Native environment, window=_blank] is set up.
* If you are using Expo to build your application:
** Ensure that the link:https://docs.expo.dev/tutorial/create-your-first-app/[Expo project is created, window=_blank] and imported into your development environment.
** Install the link:https://expo.dev/go[Expo Go, window=_blank] app on your mobile device (iOS or Android) to preview the app.

== Get started with embedding
This section provides a set of steps to quickly embed a ThoughtSpot xref:faqs.adoc#lbDef[Liveboard] in a mobile app.

=== Install the SDK

The latest version of the Mobile Embed SDK for React Native is available at link:https://www.npmjs.com/package/@thoughtspot/react-native-embed-sdk[https://www.npmjs.com/package/@thoughtspot/react-native-embed-sdk].

[source,console]
----
npm install @thoughtspot/react-native-embed-sdk
----

=== Import the SDK into your project

[source,JavaScript]
----
 // NPM
 import { LiveboardEmbed, AuthType, init } from '@thoughtspot/react-native-embed-sdk';
----

After you import, you can define the ThoughtSpot host URL from which you want to embed a Liveboard, authentication type and attributes, and the Liveboard ID.

In the link:https://snack.expo.dev/@git/github.com/thoughtspot/developer-examples:mobile/react-native-embed-sdk[Expo code sandbox, window=_blank], you'll notice that your mobile embed project has the following files:

* `Auth.ts` - For authentication with ThoughtSpot's REST API to get the authentication token.
* `App.tsx` - Contains the main app setup with React navigation for screen transitions.
* `Home.tsx` - In this file, the `tsHost`, `username`, `secretKey`, and Liveboard ID are defined.
* `LiveboardView.tsx` - Defines the interface configuration properties for the Liveboard embedded view.

You can use similar files or use an index file based on your project setup.

=== Initialize the SDK and set up authentication

To initialize the SDK, the following information is required:

* `thoughtSpotHost` +
The hostname of your ThoughtSpot application instance. For example, `team2.thoughtspot.cloud`. See xref:faqs.adoc#tsHostName[FAQs] to know how to find the hostname of your application instance.
* `authType` +
Authentication type. In the current version, mobile embedding supports only the Cookieless Trusted authentication method (`AuthType.TrustedAuthTokenCookieless`).

[source,TypeScript]
----
init({
    thoughtSpotHost: '<%=tshost%>',
    authType: AuthType.TrustedAuthTokenCookieless,
    getAuthToken: async () => Token,
});
----

=== Add the Liveboard component

[source,TypeScript]
----
const LiveboardEmbedView = () => {

    return (
        <LiveboardEmbed
            ref = {webViewRef}
            liveboardId={liveboardId}
        />
    )
}
----

=== Build your app and preview the embedded content

* Build your app:
+
[,bash]
----
$ npm run build
----

* If you are using Expo project:
+
. Build your project locally
+
[,bash]
----
expo start
----
. Scan the QR code with the *Expo Go* app to see the app with the embedded content.

== Customize your embedded page
Just like the Visual Embed SDK for web application embed, the Mobile Embed SDK provides the following customization options:

* Control the xref:embed-actions.adoc[visibility of menu actions on the embedded page]. +
By default, the SDK includes the following menu actions on the embedded Liveboard and its visualizations:


Action.AddFilter,Action.CrossFilter, Action.DrillDown, Action.PersonalisedViewsDropdown, Action.AxisMenuFilter, Action.AxisMenuEdit, Action.AxisMenuPosition,
Action.AxisMenuSort, Action.AxisMenuAggregate, Action.AxisMenuConditionalFormat, Action.AxisMenuGroup, Action.AxisMenuRemove,
Action.AxisMenuRename, Action.AxisMenuTimeBucket

[width="100%" cols="3,4"]
[options='header']
|====
||
|Action string in SDK a|Action label in the UI
|xref:Action.adoc#_addtofavorites[`Action.AddToFavorites`]| `LiveboardEmbed` +
`AppEmbed` | The *Favorites* (star) icon on a Liveboard page. +
Allows adding a Liveboard to the user's favorites list.
|xref:Action.adoc#_aihighlights[`Action.AIHighlights`]|`LiveboardEmbed` +
`AppEmbed` |  The AI highlights button on a Liveboard page. +
Displays quick insights on how top metrics changed in your Liveboard. +
To enable *AI Highlights*, ensure that the link:https://docs.thoughtspot.com/cloud/latest/time-series-anomaly[KPI anomaly detection, window=_blank] feature is enabled on your instance.
|xref:Action.adoc#_share[`Action.Share`]| `LiveboardEmbed` +
`AppEmbed`  |*Share* +
Allows sharing a Liveboard with another user or group.
|xref:Action.adoc#_edit[`Action.Edit`]| `LiveboardEmbed` +
`AppEmbed` | *Edit* +
Allows editing the contents of a Liveboard. Available only if you have edit privileges to the object.
|xref:Action.adoc#_requestaccess[`Action.RequestAccess`]| `LiveboardEmbed` +
`AppEmbed` | The *Request access* action for view-only Liveboards. Allows sending a request to the Liveboard owner to obtain edit permissions.
|xref:Action.adoc#_addfilter[`Action.AddFilter`] a| `LiveboardEmbed` +
`AppEmbed` |*Add filters* +
Adds filters to visualizations on a Liveboard.
|xref:Action.adoc#_configurefilter[`Action.ConfigureFilter`]
a| `LiveboardEmbed` +
`AppEmbed`
|The filter configuration options in the *Add Filters* modal. +
Applies filters and allows configuring filters applied to a visualization on a Liveboard.
|xref:Action.adoc#_addparameter[`Action.AddParameter`]|  `SearchBarEmbed` +
`AppEmbed`| The *Add Parameters* option in the top panel of the Liveboard +
Allows adding parameters to a Liveboard.

|xref:Action.adoc#_addtab[`Action.AddTab`]|`LiveboardEmbed` +
`AppEmbed` | The *Add Tab* action on a Liveboard. +
Allows adding a new tab to a Liveboard view.
|xref:Action.adoc#_changefiltervisibilityintab[`Action.ChangeFilterVisibilityInTab`]|`LiveboardEmbed` +
`AppEmbed` | Action ID to disable or hide the filter visibility on Liveboard tabs. Applicable if link:https://docs.thoughtspot.com/cloud/latest/liveboard-filters#_apply_filters_to_specific_visualizations_or_tabs[the filter visibility on tabs, window=_blank] feature is enabled on your instance. +
See also, xref:LiveboardViewConfig.adoc#_hideirrelevantchipsinliveboardtabs[hideIrrelevantChipsInLiveboardTabs].

|xref:Action.adoc#_disablechipreorder[`Action.DisableChipReorder`]|`LiveboardEmbed` +
`SearchEmbed` `AppEmbed` | Action ID for disabling filter chip reordering on a Liveboard.

|xref:Action.adoc#_save[`Action.Save`]|`LiveboardEmbed` +
`AppEmbed` | *Save* +
Saves Liveboard modifications.
|xref:Action.adoc#_makeacopy[`Action.MakeACopy`] | `LiveboardEmbed` +
`AppEmbed`| *Make a copy* +
Creates a copy of the Liveboard.
|xref:Action.adoc#_downloadaspdf[`Action.DownloadAsPdf`] |  `LiveboardEmbed` +
`AppEmbed`|*Download as PDF* +
Downloads the Liveboard as a PDF file.
|xref:Action.adoc#_present[`Action.Present`]| `LiveboardEmbed` +
`AppEmbed` | *Present* +
Presents a fullscreen Liveboard in the slideshow mode.
|xref:Action.adoc#_schedule[`Action.Schedule`]
xref:Action.adoc#_subscription[`Action.Subscription`]| `LiveboardEmbed` +
`AppEmbed` |**Schedule** +
Allows scheduling Liveboard notifications.
|xref:Action.adoc#_scheduleslist[`Action.SchedulesList`]| `LiveboardEmbed` +
`AppEmbed` | *Manage schedules* +
Allows you to manage scheduled Liveboard jobs.
Saves Liveboard modifications.

|xref:Action.adoc#_liveboardinfo[`Action.LiveboardInfo`]|`LiveboardEmbed` +
`AppEmbed` |  *Show Liveboard details* +
Displays information about the Liveboard.

|xref:Action.adoc#_renamemodaltitledescription[`Action.RenameModalTitleDescription`]|`LiveboardEmbed` +
`AppEmbed` | The *Rename* menu action on Liveboards. Allows editing the name of the Liveboard.
|xref:Action.adoc#_requestverification[`Action.RequestVerification`]|`LiveboardEmbed` +
`AppEmbed` | The *Request verification* menu action on Liveboards. Initiates a request for Liveboard verification.
|xref:Action.adoc#_verifiedliveboard[`Action.VerifiedLiveboard`]| `LiveboardEmbed` +
`AppEmbed` |The Liveboard verified banner text. +
Indicates the Liveboard is verified.
See also, xref:LiveboardViewConfig.adoc#_showliveboardverifiedbadge[showLiveboardVerifiedBadge].|

xref:Action.adoc#_personalisedviewsdropdown[`Action.PersonalisedViewsDropdown`]| `LiveboardEmbed` +
`AppEmbed` | The Liveboard personalized views drop-down. +
Available if personalized views are saved on the Liveboard.
Allows switching between the saved personalized views of a Liveboard.
|xref:Action.adoc#_markasverified[`Action.MarkAsVerified`] |`LiveboardEmbed` +
`AppEmbed` |
The *Approve* action visible to Liveboard verifiers. +
Marks the Liveboard as approved.
|xref:Action.adoc#_synctoslack[`Action.SyncToSlack`]| `LiveboardEmbed` +
`AppEmbed` | The *Sync to Slack* action on Liveboard visualizations. Allows sending data to third-party apps Slack.
|xref:Action.adoc#_synctoteams[`Action.SyncToTeams`]| `LiveboardEmbed` +
`AppEmbed` | The *Sync to Teams* action on Liveboard visualizations. Allows sending data to third-party apps Team.
//|xref:Action.adoc#_unsubscribeschedulehomepage[`Action.UnsubscribeScheduleHomepage`]|`LiveboardEmbed` +
//`AppEmbed` | Action ID to hide or disable the unsubscribe option for Liveboard schedules.

|xref:Action.adoc#_tml[`Action.TML`]| `LiveboardEmbed` +
`AppEmbed` |Action ID for the Parent TML action The parent action *TML* must be included to access TML-related options within the cascading menu.
|xref:Action.adoc#_exporttml[`Action.ExportTML`]|`AppEmbed` +
`LiveboardEmbed`| *Export TML* +
Exports the TML representation of a Liveboard object from ThoughtSpot. The parent action *TML* must be included to access TML-related options within the cascading menu.
|xref:Action.adoc#_updatetml[`Action.UpdateTML`]|`LiveboardEmbed` +
`AppEmbed` | *Update Liveboard* +
Allows importing the TML representation of a Liveboard object to ThoughtSpot. The parent action *TML* must be included to access TML-related options within the cascading menu.
|xref:Action.adoc#_edittml[`Action.EditTML`]|`LiveboardEmbed` +
`AppEmbed` | *Edit TML* +
Allows editing the ThoughtSpot Modelling Language (TML) representation of a Liveboard object loaded on the ThoughtSpot server. The parent action *TML* must be included to access TML-related options within the cascading menu.
|====







* Customize app interactions and enable custom workflows with xref:embed-events.adoc[Embed and Host events].
* Customize the styles and UI layout of the embedded view using ThoughtSpot's xref:css-customization.adoc[CSS customization framework].

In the following code sample, the embedded view is customized to show only Drill down (`Action.DrillDown`) and Add filters (`Action.AddFilter`) actions. This code also includes embed events that register event listeners to log data or trigger a response from the app.

[source,typescript]
----
import React, { useRef, useState } from 'react';
import { StyleSheet, View, Text, Alert, TouchableOpacity } from 'react-native';
import { Action, HostEvent, LiveboardEmbed } from '@thoughtspot/react-native-embed-sdk';

export const LiveboardView = ({ navigation, route }) => {
  const { viewConfig } = route.params;
  const [loading, setLoading] = useState(true);
  const webViewRef = useRef(null);

  const reloadView = () => {
    if (webViewRef?.current) {
      webViewRef.current.trigger(HostEvent.Reload);
    }
  };

  const goBack = () => {
    if (webViewRef?.current) {
      webViewRef.current.trigger(HostEvent.Share);
    }
  };

  return (
    <View style={styles.embedContainer}>
      <LiveboardEmbed
        ref={webViewRef}
        liveboardId={viewConfig.liveboardId}
        onAuthInit={() => setLoading(false)}
        onError={(error) => Alert.alert("Error", `Error: ${JSON.stringify(error)}`)}
        onLiveboardRendered={() => Alert.alert("Success", "Liveboard Rendered")}
        visibleActions={[Action.DrillDown, Action.AddFilter]}
        fullHeight={true}
      />
      {/* Optional buttons to reload or go back */}
      <TouchableOpacity onPress={reloadView} style={styles.button}>
        <Text>Reload View</Text>
      </TouchableOpacity>

      <TouchableOpacity onPress={goBack} style={styles.button}>
        <Text>Go Back</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  embedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#007bff',
    borderRadius: 5,
  },
});
----

== Test the app

Once the app is running, you can enter your ThoughtSpot credentials to authenticate. After successful authentication, it will navigate to the `LiveboardView`, where you can interact with the embedded Liveboard.

<Add screenshots of the Liveboard view and customized content>


== Known limitations

<List feature limitations, styles, events and action customization options that are not available /work as expected>.


== Additional resources

* link:https://github.com/@thoughtspot/react-native-embed-sdk[Mobile Embed SDK (React Native) GitHub Repository, window=_blank]
* link:https://snack.expo.dev/@git/github.com/thoughtspot/developer-examples:mobile/react-native-embed-sdk[Expo code sandbox, window=_blank]
