= Mobile Embed SDK Changelog
:toc: true
:toclevels: 1

:page-title: Changelog
:page-pageid: mobile-sdk-changelog
:page-description: Changes to the Mobile SDK and APIs

This changelog lists only the changes introduced in the Mobile Embed SDK. For information about the new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== React Native SDK

=== Version 0.0.1, April 2025

The version 0.0.1 of the React Native Embed SDK [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in native mobile apps for both Android and iOS, using JavaScript and React.

Along with the Liveboard component, the SDK provides the following features and configuration settings to  customize the embedded view:

* Liveboard and visualization xref:mobilesdk-quick-start.adoc#_customize_menu_actions[menu customization].
* Style, text string, and icon customization with xref:css-customization.adoc[CSS customization framework].
* App interactions and custom workflows with xref:EmbedEvent.adoc[Embed events] and xref:HostEvent.adoc[Host events].

For more information, see xref:mobilesdk-quick-start.adoc[Embed ThoughtSpot using React Native mobile SDK].
