= Mobile Embed SDK Changelog
:toc: true
:toclevels: 2

:page-title: Changelog
:page-pageid: mobile-sdk-changelog
:page-description: Changes to the Mobile SDK and APIs

This changelog lists only the changes introduced in the Mobile Embed SDK. For information about the new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== React Native Embed SDK

=== Version 1.0.0, December 2025

React Native Embed SDK is Generally Available (GA) with version 1.0.0.

=== Version 0.0.2, April 2025

The React Native Embed SDK v0.0.2 [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in native mobile apps for both Android and iOS, using JavaScript and React.

The SDK provides several configuration settings and attributes to customize the embedded view.

For more information, see xref:mobilesdk-quick-start.adoc[Embed ThoughtSpot using React Native mobile SDK].

== Flutter Embed SDK

=== Version 1.0.0, December 2025

Flutter Embed SDK is Generally Available (GA) with version 1.0.0.

=== Version 0.0.2, June 2025

The Flutter Embed SDK v0.0.1 [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in a Flutter app.

For information about how to install and use the SDK, see xref:mobile-embed-qs-flutter.adoc[Embed ThoughtSpot in a Flutter app].

== Swift Embed SDK

=== Version 1.0.0, December 2025

Swift Embed SDK is Generally Available (GA) with version 1.0.0.

=== Version 0.0.1, June 2025

The Swift Embed SDK v0.0.1 [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in an iOS native app.

For information about how to install and use the SDK, see xref:mobile-embed-qs-swift.adoc[Embed ThoughtSpot in an iOS app].

== Android Embed SDK

=== Version 1.0.0, December 2025

Swift Embed SDK is Generally Available (GA) with version 1.0.0.

=== Version 0.0.1, June 2025

The Android Embed SDK v0.0.1 [beta betaBackground]^Beta^ provides client libraries to embed a ThoughtSpot Liveboard in an Android native app.

For information about how to install and use the SDK, see xref:mobile-embed-android.adoc[Embed ThoughtSpot in an Android app].
