= Mobile Embed SDK Changelog
:toc: true
:toclevels: 1

:page-title: Changelog
:page-pageid: mobile-sdk-changelog
:page-description: Changes to the Mobile SDK and APIs

This changelog lists only the changes introduced in the Mobile Embed SDK. For information about the new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== React Native SDK

=== Version 1.0.0, April 2025

Version 1.0.0 is the initial release of the Mobile Embed SDK for React Native. The SDK provides the client libraries to embed a ThoughtSpot Liveboard in a mobile app using React Native framework.

This version of the SDK also supports the following customization options:

* Customization of menu options with xref:LiveboardViewConfig.adoc#_visibleactions[visibleActions], xref:LiveboardViewConfig.adoc#_disabledactions[disabledActions], and xref:LiveboardViewConfig.adoc#_hiddenActions[hiddenActions] arrays and xref:Action.adoc[Action IDs].
* Style customization with xref:css-customization.adoc[CSS customization framework].
* App interactions and custom workflow with xref:EmbedEvent.adoc[Embed events] and xref:HostEvent.adoc[HostEvent.adoc]

For more information about embedding ThoughtSpot Liveboard in a mobile app, see xref:mobilesdk-quick-start.adoc[Embed ThoughtSpot using React Native Mobile SDK].