= Org administration
:toc:
:toclevels: 2

:page-title: Org administration
:page-pageid: orgs-api-op
:page-description: You can administer Orgs on your mult-tenant cluster 

To administer and manage Orgs, you can use the link:https://docs.thoughtspot.com/cloud/latest/orgs-overview[UI workflows, window=_blank] or REST API endpoints. This article describes the REST API operations available for Org provisioning and management.

include::{path}/rest-apiv1-deprecation-note.adoc[]

== Get started with Orgs

. Configure your ThoughtSpot instance as a multi-tenant cluster. If the Orgs feature is enabled on your cluster, a Primary Org is created by default, and you will be logged in to the Primary Org context.
+
If you do not see the Orgs feature enabled on your instance, contact ThoughtSpot Support.
. Log in to your application instance as an administrator.

. Create Orgs in the *Admin* page of the UI or via #the link:{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Forgs%2Fcreate-org[`POST /api/rest/2.0/orgs/create`] endpoint#.
+
To create and manage Orgs, you must set the Org context to `All`. To do this, you can switch to the *All Orgs* tab in the Admin page of UI or pass the Org scope `ALL` in your API requests to Orgs API endpoints. #For more information, see <<_create_and_manage_orgs,Org management operations>>.#
. Create users and map the users to Orgs.
+
You can create an administrator profile for each Org and let these Org administrators manage users, groups, and role privileges in their respective Orgs.

+

Note that ThoughtSpot allows provisioning groups only within the context of an Org. You must ensure that ThoughtSpot users are mapped to appropriate Orgs and the groups within these Orgs for user access control and data security.

[#_create_and_manage_orgs]
== Org management operations

To create an Org on a multi-tenant ThoughtSpot instance, you need cluster administrator privileges. By default, ThoughtSpot sets the administrator of the `Primary Org` as a cluster administrator. Only cluster administrators are allowed to perform CRUD operations on Org objects.

=== REST API v2.0 endpoints

#For Orgs CRUD operations, use the following REST API v2.0 Org endpoints:#

* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/create-org" target="_blank"><code>/api/rest/2.0/orgs/create</code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/search-orgs" target="_blank"><code> /api/rest/2.0/orgs/search</code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/update-org" target="_blank"><code>/api/rest/2.0/orgs/{org_identifier}/update </code></a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/delete-org"  target="_blank"><code> /api/rest/2.0/orgs/{org_identifier}/delete</code></a>+++

#Note the following points about Org names and descriptions:#

* #The Org name must be unique and must not exceed 48 characters. The name can contain only letters (a-z, A-Z), digits (0-9), and hyphens (-). Spaces and other special characters are not supported.#
* #The Org description must not exceed 124 characters.#

=== #Deleting an Org#
[NOTE]
====
* #ThoughtSpot does not allow deleting the Primary Org (Org 0).#
* #When an Org is deleted, the Org and its objects become inaccessible immediately. However, the objects remain in the ThoughtSpot system for seven days from the deletion date.#
* #To restore a deleted Org, contact ThoughtSpot Support within seven days of deletion.#
* #To remove the objects of a deleted Org before the seven-day period ends, or to reuse a deleted Org name or object names immediately after deletion, contact ThoughtSpot Support.#
====

== Manage users and groups

On a multi-tenant instance, the cluster and Org administrators can create users and associate these users to Orgs and groups within these Orgs. The cluster administrator can perform CRUD operations on Org objects at the All Orgs level and assign users, whereas the Org administrator can create users and groups within the context of their Org workspace.

[NOTE]
====
#For REST API v2 operations, the Org context is determined based on the authentication token used by the user in their API requests. Users must log in to the appropriate Org context from which they want to send API requests.#
====

[width="100%" cols="5,15"]
[options='header']
|=====
|#Operation type#|#REST API v2 endpoints#

|Authentication a| **Basic authentication** +
To log in to a specific Org context with basic authentication, specify the Org ID in the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/login" target="_blank"> <code>/api/rest/2.0/auth/session/login </code> </a>+++ API request.

**Token-based authentication** +
Use the following API endpoints:

* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-object-access-token" target="_blank"> <code> /api/rest/2.0/auth/token/object </code> </a>+++
* +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/authentication/get-full-access-token" target="_blank"><code> /api/rest/2.0/auth/token/full </code></a>+++

These above endpoints also support just-in-time provisioning of users to Orgs and groups. For more information, see xref:authentication.adoc[REST API v2 authentication].

|User provisioning a|To create users and assign users to one or several Orgs, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/create-user" target="_blank"> <code> /api/rest/2.0/users/create </code> </a>+++ API endpoint. +

To assign an existing user to new Orgs or remove a user from an Org, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/update-user" target="_blank"> <code>/api/rest/2.0/users/{user_identifier}/update </code> </a>+++ API endpoint.

|Group provisioning a|To create a group in an Org, use the +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/groups/create-user-group" target="_blank"> <code>/api/rest/2.0/groups/create </code></a>+++ API endpoint.

|Fetching Orgs a| The REST API v2 endpoints allow you to perform query operations to get Org details:

* To get a list of all Orgs on the cluster, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/orgs/search-orgs" target="_blank"><code>/api/rest/2.0/orgs/search </code></a>+++  (Requires cluster administrator privileges)

* To get Org details for a user, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/search-users  target="_blank"><code>/api/rest/2.0/users/search</code></a>+++
* To get Org details for a group, use +++<a href="{{previewPrefix}}/api/rest/playgroundV2_0?apiResourceId=http/api-endpoints/users/search-users  target="_blank"><code>/api/rest/2.0/groups/search</code></a>+++
|=====
