= Privileges and roles
:toc: true
:toclevels: 1

:page-title: Privileges and roles
:page-pageid: privileges-and-roles
:page-description: Users are granted system features via privileges which are grouped into roles

System privileges determine the workflows and actions that users can perform within the ThoughtSpot application context. 

Prior to version 9.8, privileges were assigned directly to Thoughtspot groups.

In ThoughtSpot 9.8 and later, privileges are assigned via ThoughtSpot roles. The roles feature is not turned on automatically - if you do not see roles, please discuss with your ThoughtSpot account team to have it enabled.

== Privileges
ThoughtSpot allows you to define several types of privileges for a given user group:

* Role-specific privileges for administrators, developers, and other user personas.
* Data-related privileges to allow or prevent access to upload, download, or manage data.
* Workflow-specific privileges to enable or disable access to features such as SpotIQ analysis, scheduling Liveboards, or the experimental features available for evaluation and early adoption.
* Sharing privilege to control a user's or group's visibility in the *Share* dialog. 

For more information about system privileges, see  link:https://cloud-docs.thoughtspot.com/admin/users-groups/about-users-groups.html[Understand groups and privileges, window=_blank].

== Roles

== Granular control of menu actions within browser

If you are using Visual Embed SDK to embed ThoughtSpot objects and you want to restrict user access to certain menu actions, you can use the `visibleActions`, `disabledActions` or `hiddenActions` attributes. For more information, see xref:embed-actions.adoc[Show or hide UI actions].
