= Privileges and Roles
:toc: true
:toclevels: 1

:page-title: Privileges and roles
:page-pageid: privileges-and-roles
:page-description: Users are granted system features via privileges which are grouped into roles

System privileges determine the workflows and actions that users can perform within the ThoughtSpot application context. 

== Privileges
ThoughtSpot allows you to define several types of privileges:

* Role-specific privileges for administrators, developers, and other user personas.
* Data-related privileges to allow or prevent access to upload, download, or manage data.
* Workflow-specific privileges to enable or disable access to features such as SpotIQ analysis, scheduling Liveboards, or the experimental features available for evaluation and early adoption.

For more information about privileges, see  link:https://cloud-docs.thoughtspot.com/admin/users-groups/about-users-groups.html[Understand groups and privileges, window=_blank].

== Roles
In ThoughtSpot 9.8 and later, privileges are assigned via link:https://docs.thoughtspot.com/cloud/latest/rbac[ThoughtSpot roles, target=_blank], that are then linked to ThoughtSpot groups. 

The roles feature is not turned on automatically - if you do not see roles, please discuss with your ThoughtSpot account team to have it enabled.

Prior to version 9.8, link:https://docs.thoughtspot.com/cloud/latest/groups-privileges[privileges, target=_blank] were assigned directly to Thoughtspot groups.

== User and group shareability
*Shareable* is a property of a user or group which controls visibility in the *Share* dialog. 

A user will only appear in the Share dialog if the user is *Shareable* and belongs to a group that is *Shareable*, that the logged-in user also belongs to.

Admin users or those with the "Can share with all users" privilege will see all users and groups in their Share dialog.

== Granular control of menu actions within browser

If you are using Visual Embed SDK to embed ThoughtSpot objects and you want to restrict user access to certain menu actions, you can use the `visibleActions`, `disabledActions` or `hiddenActions` attributes. For more information, see xref:embed-actions.adoc[Show or hide UI actions].
