= Report APIs
:toc: true
:toclevels: 3

:page-title: report-apis
:page-pageid: report-apis
:page-description: Report APIs

ThoughtSpot provides the following REST API v2 endpoints to download or export data as a file:

* xref:#_liveboard_report_api[`POST /api/rest/2.0/report/liveboard`] +
Download a Liveboard and its visualizations in PDF, PNG, CSV, or XLSX file format.
* xref:#_answer_report_api[`POST /api/rest/2.0/report/answer`] +
Download data from a saved Answer in PDF, PNG, CSV, or XLSX file format.

[NOTE]
To retrieve data as JSON instead of downloading a file, see xref:data-apis-v2.adoc[Data APIs].

== Liveboard Report API

To download a Liveboard report via `/api/rest/2.0/report/liveboard` API, you need at least view access to the Liveboard specified in the API request.

In the `POST` request body, specify the GUID or name of the Liveboard as `metadata_identifier`. To download reports with specific visualizations, add GUIDs or names of the visualizations in the `visualization_identifiers`.

To download visualizations from a specific Liveboard tab, specify the name or GUID of the tab in the  `tab_identifiers` parameter.

To download a personalized view of the Liveboard, specify the view name in the `personalised_view_identifier` attribute.

[IMPORTANT]
====
* The downloadable file returned in API response file is extensionless. You need to rename the downloaded file by typing in the relevant extension.
* If the Liveboard includes Note tiles, ensure that you do not pass the GUID of Note tiles as `visualization_identifiers` in the API request. Attempting to do so will lead to an error, and the API will return 400 error code in response.
* Attempting to override existing filter values with runtime filters while exporting a Liveboard will result in an error.
* If Role-Based Access Control (RBAC) is enabled, `DATADOWNLOADING` (Can download Data) privilege is required for Liveboard exports.
* If the granular Role-Based Access Control (RBAC) is enabled, the `CAN_DOWNLOAD_DETAILED_DATA` (Can download detailed data) privilege is required to export in the XLSX or CSV formats, and the `CAN_DOWNLOAD_VISUALS` (Can download visuals) privilege is required for PDF or PNG exports. In this case the `DATADOWNLOADING` privilege ceases to exist.
====

=== File Formats

The default `file_format` is *CSV*.

[NOTE]
If you do not have .csv downloads enabled for your ThoughtSpot instance, select either `PDF` or `PNG` `file_format` to successfully download the report. Using any other format will cause the API to return an error.


For *CSV* downloads,

* Each visualization is exported as a separate .csv file.
* If multiple visualizations are selected, the downloaded report is a single compressed .zip file containing all .CSV files.
* It does not support any additional parameters to customize the page orientation and `include_cover_page`, `include_filter_page`, logo, footer text, and page numbers.
* Charts are exported as tabular data. Downloaded reports may include columns not seen in the visualization if they were used as tokens in the underlying search query.

==== Sample API payload for CSV downloads

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/liveboard' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Content-Type: application/json' \
--data-raw '{
"metadata_identifier": "416052fd-ad22-4d48-be0a-e43b53109957",
"file_format": "CSV",
"tab_identifiers": [
"bc6d6fb8-1e06-4617-b02f-51745e6933a6"
]
}'
----

For *XLSX* downloads,

* Visualization is exported as an Excel workbook (.xlsx).
* If multiple visualizations are selected, the downloaded report is a single Excel workbook (.xlsx) containing each visualization in their individual tab.
* A maximum of 255 tabs per .xlsx workbook are allowed.
* It does not support any additional parameters to customize the page orientation and `include_cover_page`, `include_filter_page`, logo, footer text, and page numbers.
* Charts are exported as tabular data. Downloaded reports may include columns not seen in the visualization if they were used as tokens in the underlying search query.
* New pivot tables generated in .xlsx workbooks using this API endpoint retain their complete visual formatting and structural integrity.

==== Sample API payload for XLSX downloads

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/liveboard' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Content-Type: application/json' \
--data-raw '{
"metadata_identifier": "416052fd-ad22-4d48-be0a-e43b53109957",
"file_format": "XLSX",
"visualization_identifiers": [
"254c6e30-680c-41ea-aa4d-bb059f745462"
]
}'
----

For *PDF* downloads, you can specify additional parameters to customize the page orientation and include or exclude the cover page, logo, footer text, and page numbers.

You can now also download continuous pdfs which matches the full length of your Liveboard, without breaking them into multiple A4 pages.

* `page_size = CONTINUOUS` Unlike the A4 format, which introduces forced page breaks between visualizations, this continuous flow maintains your exact design and intended layout.
+
When `page_size = CONTINUOUS`, the `include_filter_page` option works to show/hide the filter section in the PDF page (in a continuous PDF, there is no separate filter page, but the filters are included on the same page at the top).
* `zoom_level` offers various download size options to suit the viewer's screen dimensions, thereby enhancing legibility. This can be set only when `page_size = CONTINUOUS`. Valid values are integers in the range of 45 and 175.


==== Sample API payload for PDF downloads

[source,cURL]
----
curl -X POST 'https://{ThoughtSpot-Host}/api/rest/2.0/report/liveboard' \
--header 'Authorization: Bearer {access-token}' \
--header 'Content-Type: application/json' \
--data-raw '{
  "metadata_identifier": "416052fd-ad22-4d48-be0a-e43b53109957",
  "file_format": "PDF",
  "visualization_identifiers": [
    "254c6e30-680c-41ea-aa4d-bb059f745462"
  ],
  "pdf_options": {
    "page_size": "CONTINUOUS",
    "zoom_level": 105,
    "include_cover_page": true,
    "include_custom_logo": true,
    "include_filter_page": true,
    "include_page_number": true,
    "page_orientation": "PORTRAIT",
    "truncate_table": false,
    "page_footer_text": "Sample footer text"
  }
}'
----

For *PNG* downloads, you can now define

* `image_resolution`
* `image_scale`
* `include_header`

[IMPORTANT]
====
* If the above settings are enabled on your instance or you are using a ThoughtSpot release 10.9.0.cl or later,
** You will no longer be able to use the `include_cover_page`, `include_filter_page` within the `png_options`.
** PNG download will support exporting only one tab at a time. If the `tab_identifier` is not specified, the first tab will be downloaded.
* Due to UI limitations in the REST API Playground, you'll notice that some parameters are automatically included in the PNG options JSON. This may cause your API request to fail. As a workaround, click *View JSON* next to the `png_options`, review the parameters, remove additional parameters, and then click *Try it out*.

====

==== Sample API payload for PNG downloads

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/liveboard' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata_identifier": "416052fd-ad22-4d48-be0a-e43b53109957",
  "file_format": "PNG",
  "tab_identifiers": [
    "bc6d6fb8-1e06-4617-b02f-51745e6933a6"
  ],
  "png_options": {
    "include_cover_page": null,
    "include_filter_page": null,
    "personalised_view_id": null,
    "image_resolution": 1920,
    "image_scale": 100,
    "include_header": true
  }
}'
----

=== Override filters

If the Liveboard has filters applied, and you want to override the filters before downloading the Liveboard, you can specify the filters in the `override_filters` array.

[source,JSON]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/liveboard'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {access-token}' \
  --data-raw '{
  "metadata_identifier": "9bd202f5-d431-44bf-9a07-b4f7be372125",
  "file_format": "PNG",
  "override_filters": [
    {
      "column_name": "Color",
      "generic_filter": {
        "op": "IN",
        "values": [
          "almond",
          "turquoise"
        ]
      },
      "negate": false
    },
    {
      "column_name": "Commit Date",
      "date_filter": {
        "datePeriod": "HOUR",
        "number": 3,
        "type": "LAST_N_PERIOD",
        "op": "EQ"
      }
    },
    {
      "column_name": "Sales",
      "generic_filter": {
        "op": "BW_INC",
        "values": [
          "100000",
          "70000"
        ]
      },
      "negate": true
    }
  ],
  "png_options": {
    "include_cover_page": true,
    "include_filter_page": true
  }
}'
----

[#transient-lb-content-report]
=== Liveboard data with unsaved changes

include::{path}/transient-lb-content.adoc[]

==== Sample browser fetch request

[source,JavaScript]
----
< iframe src = "http://ts_host:port/" id = "ts-embed" > < /iframe>
< script src = "/path/to/liveboard.js" > < /script>
< script >
    const embed = new LiveboardEmbed("#embed", {
        frameParams: {},
    });
    async function liveboardData() {
    const transientPinboardContent = await embed.trigger(HostEvent.getExportRequestForCurrentPinboard);
    const liveboardDataResponse = await fetch("https://ts_host:port/api/rest/2.0/report/liveboard", {
        method: "POST",
        body: createFormDataObjectWith({
            "transient_content": transientPinboardContent,
        }),
    });
 }
< /script>
----

See also, link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_getexportrequestforcurrentpinboard[HostEvent.getExportRequestForCurrentPinboard].

== Answer Report API

To download Answer data via `/api/rest/2.0/report/answer` API, you need at least view access to the saved Answer.

In the request body, specify the GUID or name of the Answer object as `metadata_identifier`.

The API supports exporting saved Answers, pinned Answers from a Liveboard, and Spotter-generated Answers. You can download Answer data in `CSV`, `XLSX`, `PNG`, and `PDF` format. The default `file_format` is `CSV`.

[IMPORTANT]
====
* If Role-Based Access Control (RBAC) is enabled, `DATADOWNLOADING` (Can download Data) privilege is required for Answer exports.
* If the granular Role-Based Access Control (RBAC) is enabled, the `CAN_DOWNLOAD_DETAILED_DATA` (Can download detailed data) privilege is required to export in the PDF, XLSX or CSV formats, and the `CAN_DOWNLOAD_VISUALS` (Can download visuals) privilege is required for PNG exports. In this case the `DATADOWNLOADING` privilege ceases to exist.
====

=== Example

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/answer' \
  -H 'Authorization: Bearer {access-token}'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata_identifier": "9bd202f5-d431-44bf-9a07-b4f7be372125",
  "file_format": "PNG"
}'
----

[NOTE]
====
* Exported files are automatically named after the Answer title, with the file extension appended based on the selected format.
* HTML rendering is not supported for PDF exports of Answers with tables.
====

* `personalised_view_identifier` +
Optional parameter to specify the GUID of the personalised view of the `PINNED` Answer object that you want to download.
* `type` +
Used to distinguish between a saved answer and a pinned answer on a Liveboard. Setting this parameter to `PINNED` allows the API to
accept the guid of a pinned Answer directly as the `metadata_identifier`. When
exporting an Answer, all Liveboard-level filters, Runtime Filters, and Column
Security Rules (CSR) are automatically applied to the export output.

The `png_options` support the following properties:

[cols="1,1,3"]
|===
|Property |Type |Description

|`x_resolution`
|Number
|Width of the exported PNG in pixels. +
Valid range: `600px` to `3840px`.

|`y_resolution`
|Number
|Height of the exported PNG in pixels. +
Valid range: `600px` to `3840px`.

|`scaling`
|Integer
|Display scale percentage for objects rendered in the image. Adjusts the relative
size of visual elements without cropping the image. +
Valid range: `80%` to `500%`.
|===

You can now export the PNG of any Answer in any aspect ratio and any scaling or zoom level. Just configure, scale, and export exactly what you need.

[#exportSpotterData]
=== Export data generated from Spotter APIs
To export results generated from Spotter APIs such as  `/api/rest/2.0/ai/answer/create`, `/api/rest/2.0/ai/agent/converse/sse`, and `/api/rest/2.0/ai/conversation/{conversation_identifier}/converse`, include the session ID and generation number in the `POST` request body.

When downloading a Spotter-generated Answer, do not specify the metadata object ID, because you will be exporting the data generated from a conversation session with Spotter and not a saved Answer.

==== Request example

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/report/answer'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "file_format": "CSV",
  "session_identifier": "ee077665-08e1-4a9d-bfdf-7b2fe0ca5c79",
  "generation_number": 2
}'
----

* `session_identifier` refers to session ID returned in the Spotter API response.
* `generation_number` indicates the Answer generation number.
* `file_format`  specifies the format of the output. You can export the Spotter-generated data as PNG, CSV, XLSX, or PDF file. By default, the API exports this data in PNG file format.

==== API Response

If the API request is successful, ThoughtSpot returns the data in the specified file format. You can download the file to use it later or import it into your application environment.

////
==== Response codes
[width="100%" cols="2,4"]
[options='header']
|===
|HTTP status code|Description
|**200**| Successful operation
|**400**| Invalid parameter
|**401**| Unauthorized access
|**401**| Forbidden request
|**500**| Internal error
|===
////

== Pagination and runtime overrides

The Report API endpoints support the same runtime overrides as the Data API endpoints. For more information, see xref:data-apis-v2.adoc#_runtime_overrides[Runtime overrides].

For information about pagination, record size, and the maximum row limit that apply to the Data API endpoints, see xref:data-apis-v2.adoc#pagination[Pagination settings for Data APIs].
