= REST API v2.0 Reference
:toc: true

:page-title: REST API Reference Guide
:page-pageid: rest-apiv2-reference
:page-description: REST API Reference

This API Reference page lists the REST API v2.0 endpoints and provides basic information about the resource URLs and supported operations. If you want to try out these APIs, view detailed documentation, and download code samples, visit the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fgetting-started%2Fintroduction">REST API v2.0 Playground</a>+++.

[NOTE]
====
Access to ThoughtSpot data is controlled based on xref:api-user-management.adoc#group-privileges[user privileges] and xref:configure-user-access.adoc#_object_level_permissions[object-level permissions]. Some operations are available to all users and may require at least view access to the metadata object. ThoughtSpot users are assigned access privileges based on the group to which they belong. Additionally, object owners can control access to a metadata object using `MODIFY` (*Can edit*), `READ_ONLY` (*Can view*), or `NO_ACCESS` permission when sharing an object with other users and groups.
====

== Authentication

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`GET /api/rest/2.0/auth/session/user` +
Gets session information for the currently logged-in user. +

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software:__ 9.0.1.sw or later __ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Fget-current-user-info" id="preview-in-playground">Try it out</a>+++
|
`POST /api/rest/2.0/auth/session/login` +
Creates a login session for a ThoughtSpot user.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/authentication/login" id="preview-in-playground">Try it out</a>+++
|`GET /api/rest/2.0/auth/session/token` +
Gets the authentication token used by the currently logged-in user.

|ThoughtSpot Cloud: __9.4.0.cl or later__ +
ThoughtSpot Software: __9.5.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Fget-current-user-token" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/auth/token/object` +

Gets an authentication token that grants access only to the metadata object specified in the API request.
|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Fget-object-access-token" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/auth/token/full` +
Gets an authentication token from ThoughtSpot that grants access to a full application session.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Fget-full-access-token" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/auth/session/logout` +
Logs out the currently logged-in user.


|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Flogout" id="preview-in-playground">Try it out </a>+++
a|`POST /api/rest/2.0/auth/token/revoke` +
Revokes authentication token granted for a user.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fauthentication%2Frevoke-token" id="preview-in-playground">Try it out </a>+++
|=====
--

== Users

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/users/search` +
Gets details of one or several ThoughtSpot users.


|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fsearch-users" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/users/create` +
Creates a user.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fcreate-user" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/users/{user_identifier}/update` +
Updates the properties of a user object.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fupdate-user" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/users/{user_identifier}/delete` +

Deletes a user object from ThoughtSpot.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fdelete-user" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/users/import` +
Gets an authentication token from ThoughtSpot that grants access to a full application session.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fimport-users" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/users/change-password` +
Allows ThoughtSpot users to change the password of their account.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/users/change-user-password" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/users/reset-password` +
Resets the password of a user account.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/users/reset-user-password" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/users/force-logout` +
Logs out a users from their current sessions.


|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fforce-logout-users" id="preview-in-playground">Try it out </a>+++
a|`POST /api/rest/2.0/users/activate` +

Activates a deactivated user account.

|ThoughtSpot Cloud: __9.7.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Factivate-user" id="preview-in-playground">Try it out </a>+++

|`POST /api/rest/2.0/users/deactivate` +
Deactivates a user account.

|ThoughtSpot Cloud: __9.7.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fusers%2Fdeactivate-user" id="preview-in-playground">Try it out </a>+++
|=====
--

== System

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version| Playground link
a|`Get System Information` +
Gets system information of your current logged-in cluster.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/system/get-system-information" id="preview-in-playground">Try it out</a>+++

a|`GET /api/rest/2.0/system` +
Gets details of the current configuration running on your cluster.


|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/system/get-system-config" id="preview-in-playground">Try it out</a>+++

a|`GET /api/rest/2.0/system/config-overrides` +
Gets details of the configuration overrides on your cluster.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/system/get-system-override-info" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/system/config-update` +

Gets details of the current configuration running on your cluster.

a|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/system/update-system-config" id="preview-in-playground">Try it out </a>+++
|=====
--

== Orgs

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/orgs/search` +
Gets a list of Orgs configured on the ThoughtSpot system.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __Not Applicable__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Forgs%2Fsearch-orgs" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/orgs/create` +
Creates an Org object. +

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __Not Applicable__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Forgs%2Fcreate-org" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/orgs/{org_identifier}/update` +
Modifies the object properties of an Org.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __Not Applicable__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Forgs%2Fupdate-org" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/orgs/{org_identifier}/delete` +

Deletes an Org object from ThoughtSpot.

a|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __Not Applicable__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Forgs%2Fdelete-org" id="preview-in-playground">Try it out </a>+++
|=====
--

== Tags

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/tags/search` +
Gets details of tag objects from ThoughtSpot.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Fsearch-tags" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/tags/create` +
Creates a tag object in ThoughtSpot. +

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Fcreate-tag" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/tags/{tag_identifier}/update` +
Modifies the object properties of a tag.  +

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Fupdate-tag" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/tags/{tag_identifier}/delete` +

Deletes an Org object from ThoughtSpot.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Fdelete-tag" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/tags/assign` +
Assigns a tag to metadata objects.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Fassign-tag" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/tags/unassign` +

Removes the tag assigned to a metadata object.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Ftags%2Funassign-tag" id="preview-in-playground">Try it out </a>+++
|=====
--

== Groups

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/groups/search` +
Gets details of one or several Groups.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fsearch-user-groups" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/groups/create`

Creates a Group object.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fcreate-user-group" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/groups/{group_identifier}/update` +
Updates the object properties of a group. You can also use this API to add or remove users, sub-groups, and privileges.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fupdate-user-group" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/groups/{group_identifier}/delete` +

Removes a group object from ThoughtSpot.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fdelete-user-group" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/groups/import`

Imports group objects from external databases into ThoughtSpot.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fimport-user-groups" id="preview-in-playground">Try it out </a>+++
|=====
--

== Metadata

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/metadata/search` +
Gets details of metadata objects from ThoughtSpot.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fsearch-metadata" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/metadata/liveboard/sql` +

Gets SQL query data for the visualizations on a Liveboard.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Ffetch-liveboard-sql-query" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/metadata/answer/sql` +
Gets SQL query data for a saved Answer.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Ffetch-answer-sql-query" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/metadata/tml/import` +

Imports TML representation of the metadata objects into ThoughtSpot.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fimport-metadata-tml" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/metadata/tml/export`

Exports TML representation of the metadata objects from ThoughtSpot in JSON or YAML format.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fexport-metadata-tml" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/metadata/delete`

Removes a metadata object.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fdelete-metadata" id="preview-in-playground">Try it out </a>+++

|=====
--

== Reports

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/report/liveboard` +
Exports a Liveboard and its visualizations as a PDF, CSV, XLSX, or PNG file.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Freports%2Fexport-liveboard-report" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/report/answer` +

Downloads a saved Answer in PDF, CSV, PNG, or XLSX format.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Freports%2Fexport-answer-report" id="preview-in-playground">Try it out</a>+++
|=====
--

== Security

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/security/principals/fetch-permissions` +
Gets a list of objects that a user or group has access to. You can also specify the metadata type in the API request to fetch user permission details for Liveboards, Worksheets, or Answers.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fsecurity%2Ffetch-permissions-of-principals" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/security/metadata/fetch-permissions`

Gets access permission details for metadata objects. To get object access details for a user or group, specify the user or group identifiers.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fsecurity%2Ffetch-permissions-on-metadata" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/security/metadata/assign` +
Assigns a new author or changes the author of a metadata object.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fsecurity%2Fassign-change-author" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/security/metadata/share` +

Allows sharing metadata objects, such as Liveboards, saved Answers, and Worksheets with another user or group in ThoughtSpot.

a|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fsecurity%2Fshare-metadata" id="preview-in-playground">Try it out </a>+++
|=====
--

== Data

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/searchdata` +

Generates results for the search query specified in the API request.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdata%2Fsearch-data" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/metadata/liveboard/data`

Gets details of a Liveboard and its visualizations.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdata%2Ffetch-liveboard-data" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/metadata/answer/data` +

Gets Answer data from ThoughtSpot. You can fetch data for saved Answers only.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdata%2Ffetch-answer-data" id="preview-in-playground">Try it out </a>+++
|=====
--


== Audit logs

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/logs/fetch` +

Gets security audit logs from the ThoughtSpot system.

|ThoughtSpot Cloud: __9.0.0.cl or later__ +
ThoughtSpot Software: __9.0.1.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Flog%2Ffetch-logs" id="preview-in-playground">Try it out</a>+++

|=====
--

== Version control


[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a| `POST /api/rest/2.0/vcs/git/config/search` +
Gets Git repository connections configured on the ThoughtSpot instance.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fsearch-config" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/vcs/git/commits/search` +

Gets Git commit history for a given metadata object.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fsearch-commits" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/vcs/git/config/create` +
Connects your ThoughtSpot instance to a Git repository.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fcreate-config" id="preview-in-playground">Try it out </a>+++

a| `POST /api/rest/2.0/vcs/git/config/update` +

Updates the Git repository settings configured for a ThoughtSpot instance.

a|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fupdate-config" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/vcs/git/config/delete` +

Deletes the Git repository configuration.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fdelete-config" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/vcs/git/branches/commit`

Commits TML files to the Git branch configured on your instance.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fcommit-branch" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/vcs/git/commits/{commit_id}/revert`

Reverts to a previous commit in the Git branch.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Frevert-commit" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/vcs/git/branches/validate`

Validates the content of your source branch against the objects in your destination environment and identifies merge conflicts.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fvalidate-merge" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/vcs/git/commits/deploy`

Deploys commits to the destination environment (`Staging` or `Production`).

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fversion-control%2Fdeploy-commit" id="preview-in-playground">Try it out </a>+++
|=====
--

== Connections

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/connection/search` +

Gets connection objects from ThoughtSpot.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fsearch-connection" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/connection/create`

Creates a connection to the data warehouse specified in the API request.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fcreate-connection" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/connection/update` +

Updates a connection object.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fupdate-connection" id="preview-in-playground">Try it out </a>+++


a|`POST /api/rest/2.0/connection/delete` +

Deletes a connection object.

|ThoughtSpot Cloud: __9.2.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fconnections%2Fdelete-connection" id="preview-in-playground">Try it out </a>+++
|=====
--

== Roles [beta betaBackground]^Beta^

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/roles/search` +

Gets Role objects from ThoughtSpot.

|ThoughtSpot Cloud: __9.5.0.cl or later__ +
ThoughtSpot Software: __Not applicable__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Froles%2Fsearch-roles" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/roles/create`

Creates a Role with a defined set of privileges.

|ThoughtSpot Cloud: __9.5.0.cl or later__ +
ThoughtSpot Software: __Not applicable__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Froles%2Fcreate-role" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/roles/{role_identifier}/update` +

Updates a Role object.

|ThoughtSpot Cloud: __9.5.0.cl or later__ +
ThoughtSpot Software: __Not applicable__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Froles%2Fupdate-role" id="preview-in-playground">Try it out </a>+++


a|`POST /api/rest/2.0/roles/{role_identifier}/delete` +

Deletes a Role object.

|ThoughtSpot Cloud: __9.5.0.cl or later__ +
ThoughtSpot Software: __Not applicable__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Froles%2Fdelete-role" id="preview-in-playground">Try it out </a>+++
|=====
--


== Custom actions

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/customization/custom-actions/search` +

Gets custom action objects.

|ThoughtSpot Cloud: __9.6.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fcustom-action%2Fsearch-custom-actions" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/customization/custom-actions`

Creates a custom action and assigns it to a given metadata object.

|ThoughtSpot Cloud: __9.6.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fcustom-action%2Fcreate-custom-action" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/customization/custom-actions/{custom_action_identifier}/update` +

Updates the properties of a custom action object.

|ThoughtSpot Cloud: __9.6.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fcustom-action%2Fupdate-custom-action" id="preview-in-playground">Try it out </a>+++


a|`POST /api/rest/2.0/customization/custom-actions/{custom_action_identifier}/delete` +

Deletes a custom action.

|ThoughtSpot Cloud: __9.6.0.cl or later__ +
ThoughtSpot Software: __9.8.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fcustom-action%2Fdelete-custom-action" id="preview-in-playground">Try it out </a>+++
|=====
--

== Schedules

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/schedules/create` +

Creates a Liveboard schedule job.

|ThoughtSpot Cloud: __9.4.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fschedules%2Fcreate-schedule" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/schedules/search` +

Gets details of the scheduled Liveboard jobs.

|ThoughtSpot Cloud: __9.4.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__  a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fschedules%2Fsearch-schedules" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/schedules/{schedule_identifier}/update` +

Updates a Liveboard job schedule.

|ThoughtSpot Cloud: __9.4.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fschedules%2Fupdate-schedule" id="preview-in-playground">Try it out </a>+++


a|`POST /api/rest/2.0/schedules/{schedule_identifier}/delete`

Deletes a scheduled Liveboard job.

|ThoughtSpot Cloud: __9.4.0.cl or later__ +
ThoughtSpot Software: __9.5.0.sw or later__ a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fschedules%2Fdelete-schedule" id="preview-in-playground">Try it out</a>+++

|=====
--


== DBT

[div boxAuto]
--
[width="100%" cols="6,4,2"]
[options='header']
|=====
|API endpoint| Release version | Playground link
a|`POST /api/rest/2.0/dbt/dbt-connection` +

Creates a DBT connection object in ThoughtSpot.

|ThoughtSpot Cloud: __9.10.0.cl or later__ +
ThoughtSpot Software: __10.0.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdbt%2Fdbt-connection" id="preview-in-playground">Try it out</a>+++

a|`POST /api/rest/2.0/dbt/generate-tml` +

Creates TML for the given data objects and imports the TML data to ThoughtSpot.

|ThoughtSpot Cloud: __9.10.0.cl or later__ +
ThoughtSpot Software: __10.0.0.sw or later__    a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdbt%2Fgenerate-tml" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/dbt/generate-sync-tml` +

Resynchronizes the existing list of Models, Tables, and Worksheet TML content for the specified DBT connection object and imports these to Thoughtspot.

|ThoughtSpot Cloud: __9.10.0.cl or later__ +
ThoughtSpot Software: __10.0.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdbt%2Fgenerate-sync-tml" id="preview-in-playground">Try it out </a>+++

a|`POST /api/rest/2.0/dbt/search` +

Gets a list of DBT connection objects.

|ThoughtSpot Cloud: __9.10.0.cl or later__ +
ThoughtSpot Software: __10.0.0.sw or later__   a|
+++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdbt%2Fdbt-connection" id="preview-in-playground">Try it out </a>+++


a|`POST /api/rest/2.0/dbt/{dbt_connection_identifier}`

Updates a DBT connection object.

|ThoughtSpot Cloud: __9.10.0.cl or later__ +
ThoughtSpot Software: __10.0.0.sw or later__  a| +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fdbt%2Fupdate-dbt-connection" id="preview-in-playground">Try it out</a>+++
|=====
--