= REST API v2.0 changelog
:toc: true
:toclevels: 1

:page-title: Changelog
:page-pageid: rest-v2-changelog
:page-description: Changelog of REST APIs

This changelog lists the features and enhancements introduced in REST API v2.0. For a complete list of ThoughtSpot Everywhere features and enhancements, see xref:whats-new.adoc[What's New].

== Version 9.5.0.cl, Coming soon

=== New API endpoints for Role-Based Access Control

* `POST /api/rest/2.0/roles/search` +
Gets details of role objects available in the ThoughtSpot system.
* `POST /api/rest/2.0/roles/create` +
Creates a role and assigns privileges
* `POST /api/rest/2.0/roles/{role_identifier}/update` +
Updates the properties of a given role
* `POST /api/rest/2.0/roles/{role_identifier}/delete` +
Removes a role object from the ThoughtSpot system

[NOTE]
====
The roles APIs work only if the  Role-Based Access Control (RBAC) feature is enabled on your instance. The RBAC feature is in beta and turned off by default. To enable this feature, contact ThoughtSpot Support.
====

=== Enhancements and API modifications

Support for runtime parameter overrides::
The following data and report API endpoints support applying runtime parameter overrides:
* `POST /api/rest/2.0/searchdata` +
* `POST /api/rest/2.0/metadata/liveboard/data` +
* `POST /api/rest/2.0/metadata/answer/data` +
* `POST /api/rest/2.0/report/liveboard` +
* `POST /api/rest/2.0/report/answer`

Git integration support for Orgs::

The Version Control API endpoints support using Orgs as disparate deployment environments. You can create separate Orgs for `dev`, `staging`, and `prod` and integrate these environments with a GitHub repo.

== Version 9.4.0.cl, August 2023

=== API endpoints to schedule and manage Liveboard jobs

* `*POST* /api/rest/2.0/schedules/create` +
Creates a scheduled job for a Liveboard
* `*POST* /api/rest/2.0/schedules/{schedule_identifier}/update` +
Updates a scheduled job
* `*POST* /api/rest/2.0/schedules/search` +
Gets a list of Liveboard jobs configured on a ThoughtSpot instance
* `*POST* /api/rest/2.0/schedules/{schedule_identifier}/delete` +
Deletes a scheduled job.

For more information, see link:{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/schedules/search-schedule[REST API v2.0 Reference].

=== API to fetch authentication token

The `GET /api/rest/2.0/auth/session/token` API endpoint fetches the current authentication token used by the currently logged-in user.

=== Version Control API enhancements

* The following Version Control API endpoints support generating and maintaining a GUID mapping file on a Git branch connected to a ThoughtSpot instance:

** `*POST* /api/rest/2.0/vcs/git/config/create`
** `*POST* /api/rest/2.0/vcs/git/config/update`

=== User and group API enhancements

* The `**POST** /api/rest/2.0/users/{user_identifier}/update` and `**POST** /api/rest/2.0/groups/{group_identifier}/update` support specifying the type of operation API request. For example, if you are removing a property of a user or group object, you can specify the `operation` type as `REMOVE` in the API request.
* The `**POST** /api/rest/2.0/users/{user_identifier}/update` allows you to define locale settings, preferences, and other properties for a user object.

== Version 9.3.0.cl, June 2023

The following Version Control [beta betaBackground]^Beta^ API endpoints are now available for the  lifecycle management of content on your deployment environments:

* `*POST* /api/rest/2.0/vcs/git/config/search`
* `*POST* /api/rest/2.0/vcs/git/commits/search`
* `*POST* /api/rest/2.0/vcs/git/config/create`
* `*POST* /api/rest/2.0/vcs/git/config/update`
* `*POST* /api/rest/2.0/vcs/git/config/delete`
* `*POST* /api/rest/2.0/vcs/git/branches/{branch_name}/pull`
* `*POST* /api/rest/2.0/vcs/git/branches/commit`
* `*POST* /api/rest/2.0/vcs/git/commits/{commit_id}/revert`
* `*POST* /api/rest/2.0/vcs/git/branches/validate`
* `*POST* /api/rest/2.0/vcs/git/commits/deploy`

For more information, see xref:version_control.adoc[Version control and Git integration].

== Version 9.2.0.cl, May 2023

New endpoints::

* System
+
** `POST /api/rest/2.0/system/config-update` +
Updates system configuration
+
** `GET /api/rest/2.0/system/config-overrides` +
Gets system configuration overrides

* Connections
+
** POST /api/rest/2.0/connection/create +
Creates a data connection

** `POST /api/rest/2.0/connection/search` +
Gets a list of data connections

** `POST /api/rest/2.0/connection/update` +
Updates a data connection

** `POST /api/rest/2.0/connection/delete` +
Deletes a data connection

Enhancements::

* Support for runtime filters and runtime sorting of columns +
The following REST API v2.0 endpoints support applying xref:runtime-filters.adoc#_apply_runtime_filters_in_rest_api_v2_requests[runtime filters] and xref:runtime-sort.adoc[sorting column data]:
+
** `POST /api/rest/2.0/report/liveboard` +
** `POST /api/rest/2.0/report/answer`

* Search users by their favorites
+
The `/api/rest/2.0/users/search` API endpoint allows searching users by their favorite objects and home Liveboard setting.

* Ability to log in to a specific Org
+
The `/api/rest/2.0/auth/session/login` API endpoint now allows ThoughtSpot users to log in to a specific Org context.

== Version 9.0.0.cl, February 2023

The ThoughtSpot Cloud 9.0.0.cl release introduces the REST API v2.0 endpoints and Playground. For information about REST API v2.0 endpoints and Playground, see the following articles:

* xref:rest-api-v2.adoc[REST API v2.0]
* xref:rest-api-v2-getstarted.adoc[Get started with REST API v2.0]
* xref:rest-api-v2-reference.adoc[REST API v2.0 reference]
* xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison]



