= REST API v2.0 changelog
:toc: true
:toclevels: 1

:page-title: Changelog
:page-pageid: rest-v2-changelog
:page-description: Changelog of REST APIs

This changelog lists the features and enhancements introduced in REST API v2.0. For information about new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== Version 10.15.0.cl, January 2026
For information about the new features and enhancements introduced in this release, see the link:https://developers.thoughtspot.com/docs/10.15.0.cl?pageid=rest-v2-changelog[10.15.0.cl Developer Documentation, window=_blank].

== Version 10.14.0.cl, November 2025

=== New API endpoints

System::
This release introduces the following endpoints for configuring communication channel preference.

* `POST /api/rest/2.0/system/preferences/communication-channels/configure` [beta betaBackground]^Beta^  +
Sets a communication channel preference for all Orgs at the cluster level or at the indiviudal Org level.
* `POST /api/rest/2.0/system/preferences/communication-channels/search` [beta betaBackground]^Beta^ +
Gets details of the communication channel preferences configured on ThoughtSpot.
+
For more information, see xref:webhooks-lb-schedule.adoc#_configure_a_webhook_communication_channel_for_the_liveboard_schedule_event[Configure  communication channel settings].

Webhook::
The following APIs are introduced for webhook CRUD operations:
* `POST /api/rest/2.0/webhooks/create`
Creates a webhook.
* `POST /api/rest/2.0/webhooks/{webhook_identifier}/update`
Updates the properties of a webhook
* `POST /api/rest/2.0/webhooks/search`
Gets a list of webhooks configured in ThoughtSpot or a specific Org in ThoughtSpot
* `POST /api/rest/2.0/webhooks/delete`
Deletes the webhook.
+
For more information, see xref:webhooks-lb-schedule.adoc[Webhooks for Liveboard schedule events].

Column security rules::

* `POST /api/rest/2.0/security/column/rules/update` +
Updates column security rules for a given Table.

* `POST /api/rest/2.0/security/column/rules/fetch` +
Gets details of column security rules for the tables specified in the API request.

////
<TBD>
Spotter::
POST /api/rest/2.0/ai/agent/{conversation_identifier}/converse
////
=== Variable API enhancements

The variable API enhancements are listed in the following sections. For additional details, see xref:variables.adoc[Define variables].

==== Variable creation API

* The variable creation endpoint `/api/rest/2.0/template/variables/create` doesn't support assigning values to a variable. To assign values to a variable, use the `/api/rest/2.0/template/variables/update-values` endpoint.
* The `sensitive` parameter is renamed as `is_sensitive`.
//* You can define the data type for variables using the `data_type`property.
//* You can now create formula variables. To create a formula variable, use define the variable type as `FORMULA_VARIABLE` variable type in your API request .

==== Variables update APIs [tag redBackground]#BREAKING CHANGE#

The `/api/rest/2.0/template/variables/update` endpoint is deprecated and replaced with `/api/rest/2.0/template/variables/update-values`. +
To update the properties of a specific variable, use the `/api/rest/2.0/template/variables/{identifier}/update` endpoint and to assign values to one or several variables in a single API call, use the `POST /api/rest/2.0/template/variables/update-values` endpoint.

==== Variables search API

* The variables search API endpoint `/api/rest/2.0/template/variables/search` now includes the `value_scope` parameter that allows you to filter the API response by the objects to which the variable is mapped.
* Filtering API response by `EDITABLE_METADATA_AND_VALUES` output format is no longer supported.


=== User API enhancements
The following APIs now support `variable_values` parameter. The `variable_values` property can be used for user-specific customization.

* `POST /api/rest/2.0/users/create`
* `POST /api/rest/2.0/users/search`
* `POST /api/rest/2.0/users/activate`

=== DBT API enhancements
The `/api/rest/2.0/dbt/generate-tml` endpoint supports `model_tables` attribute to allow listing Models and its Tables.

////
<TBD>
=== Authentication API
Support for `variable_values` property in `/api/rest/2.0/auth/session/user` API calls.

////

== Version 10.13.0.cl, October 2025

=== New API endpoints

Spotter::

* `POST /api/rest/2.0/ai/agent/conversation/create` +
Creates a new AI-driven conversation session based on a specified data source. The resulting session sets the context for subsequent queries and responses.  +


* `POST /api/rest/2.0/ai/relevant-questions/` +
Breaks down a user-submitted query into a series of analytical sub-questions using relevant contextual metadata.

* `POST /api/rest/2.0/ai/agent/converse/sse` +
Allows sending a follow-up message or question to an ongoing conversation session and returns the AI agent's response, including answers, tokens, and visualization details.  +

//* `POST /api/rest/2.0/ai/data-source-suggestions` +
//Returns a list of relevant data sources, such as Models, based on a query and thus helping users and agents choose the most appropriate data source for analytics. +

For more information, see xref:spotter-apis.adoc[Spotter AI APIs].

Email customization::
`POST /api/rest/2.0/customization/email/update` +
Updates an existing email customization. For more information, see xref:customize-email-apis.adoc[Customize email template].

=== API enhancements
The following APIs were modified to include new parameters:

TML export::
The TML export API now supports the `export_with_column_aliases` parameter in `export_options` to indicate whether to export column aliases of the model.

Email customization::
The `/api/rest/2.0/customization/email/update` and `/api/rest/2.0/customization/email` APIs now include `company_privacy_policy_url` and `company_website_url` properties in template variables, and a new `org_identifier` parameter in the API request.

For more information, see xref:customize-email-apis.adoc[Customize email template].

=== Deprecated endpoints

Spotter::
The `POST /api/rest/2.0/ai/analytical-questions` Spotter AI API [beta betaBackground]^Beta^ is deprecated and replaced with the new API endpoint, `POST /api/rest/2.0/ai/relevant-questions/`.

Email customization::
The `POST /api/rest/2.0/customization/email/{template_identifier}/delete` email customization API is deprecated and replaced with the new API endpoint, `POST /api/rest/2.0/customization/email/delete`.


////
=== Deprecated endpoints
The following Spotter AI APIs [beta betaBackground]^Beta^ are deprecated and replaced with the new xref:spotter-apis.adoc[AI APIs].

* `POST /api/rest/2.0/ai/conversation/create`
* `POST /api/rest/2.0/ai/analytical-questions`
* `POST /api/rest/2.0/ai/conversation/{conversation_identifier}/converse`
////

== Version 10.12.0.cl, September 2025

=== New API endpoints

The following API endpoints are now available:

Custom calendar::
* `POST /api/rest/2.0/calendars/create` +
Creates a custom calendar.
* `POST /api/rest/2.0/calendars/generate-csv` +
Exports a custom calendar in the CSV format.
* `POST /api/rest/2.0/calendars/search` +
Gets custom calendars for the connection ID specified in the API request.
* `POST /api/rest/2.0/calendars/{calendar_identifier}/delete` +
Deletes a custom calendar.
* `POST /api/rest/2.0/calendars/{calendar_identifier}/update` +
Updates a custom calendar.

Connection configuration::
* `POST /api/rest/2.0/connection-configurations/create` +
Creates an additional configuration to an existing connection to a data warehouse.
* `POST /api/rest/2.0/connection-configurations/search` +
Gets the required connection configuration objects.
* `POST /api/rest/2.0/connection-configurations/{configuration_identifier}/update` +
Updates an existing connection configuration object.
* `POST /api/rest/2.0/connection-configurations/delete` +
Deletes the connection configuration object.

=== Enhancements to APIs

Export API endpoint::

* Answer TML: +
The `POST /api/rest/2.0/metadata/tml/export` API endpoint now allows fetching TML for Answer objects that do not have an ID or name assigned. The `session_identifier` and `generation_number` parameters allow you to define the session ID and the Answer generation number in the API request. These optional attributes can be used for unsaved Answers generated from Spotter queries.

* Table TML: +
The `POST /api/rest/2.0/metadata/tml/export` API request allows exporting column security rules for Table TML objects. This attribute will export column security rules only if the object specified in the API request has column security applied and when `export_associated` is set to `true`.

== Version 10.11.0.cl, July 2025

=== Search metadata API enhancements
The search metadata (`/api/rest/2.0/metadata/search`) API includes the following enhancements:

* The `liveboard_reponse_version` parameter. It allows you to specify the xref:rest-api-v2-metadata-search.adoc#_response_format_for_liveboards[response format for Liveboard objects].
* The `subtypes` attribute to specify the sub-type for the `LOGICAL_TABLE` metadata type. The `LOGICAL_TABLE` type allows to fetch objects such as Tables, Models, and Views. The `subtypes` parameter allows you to filter API response by specifying subcategories of the object type.
* The `include_only_published_objects` attribute to specify whether the search should should include xref:publish-api.adoc[published objects].


=== System API
The API response generated from the `GET /api/rest/2.0/system/config-overrides` requests now returns the overrides in the `config_override_info` object.

=== TML API
The API response for the `POST /api/rest/2.0/metadata/tml/async/import` and `POST /api/rest/2.0/metadata/tml/async/status` now includes the `author_display_name` property. This property shows the display name of user that initiated the asynchronous TML import request.

=== REST API Java SDK

The REST API Java SDK library artifacts are now available in the `com.thoughtspot` Maven namespace. If you are using Maven Central to import the REST API SDK artifacts, update the group ID in your `pom.xml` file to `com.thoughtspot` and the artifact ID to `rest-api-sdk`.

For more information, see xref:rest-api-java-sdk.adoc#_import_the_sdk_to_your_application_environment[REST API Java SDK].

== Version 10.10.0.cl, July 2025

=== Email template customization APIs:
This release introduces the following new endpoints for email template customization:

* `POST /api/rest/2.0/customization/email` +
Allows you to personalize the ThoughtSpot notification emails content.
* `POST /api/rest/2.0/customization/email/{template_identifier}/delete` +
Removes the customizations done for the ThoughtSpot notification emails.
* `POST /api/rest/2.0/customization/email/search` +
Allows searching the email customization configuration if any set for ThoughtSpot.
* `POST /api/rest/2.0/customization/email/validate` +
Validates the email customization configuration if any set for ThoughtSpot.

=== Group API

The `/api/rest/2.0/groups/search` endpoint now supports the following new options in group search API requests:

* `include_users` +
When set to `true`, it includes user details in the group search API response.
* `include_sub_groups` +
When set to `true`, it includes sub-groups in the group search response.

=== Schedule API
You can now specify the `personalised_view_id` of a Liveboard in API requests to the following schedule APIs:

* `POST /api/rest/2.0/schedules/create`
To schedule a job for a personalized view of the Liveboard, specify the `personalised_view_id`.
* `POST /api/rest/2.0/schedules/{schedule_identifier}/update`
To update schedule details for a specific view of the Liveboard, specify the `personalised_view_id`.

== Version 10.9.0.cl, June 2025

=== Metadata parameterization and content publishing across Orgs

This release introduces the following new endpoints for metadata parameterization [beta betaBackground]^Beta^ and content publishing [beta betaBackground]^Beta^ across Orgs. To enable the content publishing feature and the related API operations on your instance, contact ThoughtSpot Support.

* `POST /api/rest/2.0/metadata/parameterize` [beta betaBackground]^Beta^ +
Allows you to parameterize fields in metadata objects.
* `POST /api/rest/2.0/metadata/unparameterize` [beta betaBackground]^Beta^ +
Allows removing parameterization from fields in metadata objects
* `POST /api/rest/2.0/security/metadata/publish` [beta betaBackground]^Beta^ +
Publish metadata objects to one or several Orgs on an instance.
* `POST /api/rest/2.0/security/metadata/unpublish` [beta betaBackground]^Beta^ +
Removes published metadata objects from the Orgs specified in the API request.
* `POST /api/rest/2.0/template/variables/create` [beta betaBackground]^Beta^ +
Allows creating a template variable which can be used to parameterize fields in a metadata object.
* `POST /api/rest/2.0/template/variables/search` [beta betaBackground]^Beta^ +
Allows searching template variables
* `POST /api/rest/2.0/template/variables/{identifier}/update` [beta betaBackground]^Beta^ +
Allows updating properties of a template variable.
* `POST /api/rest/2.0/template/variables/update` [beta betaBackground]^Beta^ +
Allows you to add, remove, or replace properties of one or several template variables.
* `POST /api/rest/2.0/template/variables/{identifier}/delete` [beta betaBackground]^Beta^ +
Deletes a template variable.

If your metadata objects are parameterized, you can use the `show_resolved_parameters` to filter the API response from `/api/rest/2.0/connection/search` and `/api/rest/2.0/metadata/search` endpoints to get only the objects with resolved parameterized values.

=== Liveboard Report API
The Liveboard Report API now allows you to define the following properties:

* `tab_identifiers` +
Optional parameter to specify the name or GUID of a Liveboard tab to export only the visualizations in that tab.
* `personalised_view_identifier` +
Optional parameter to specify the GUID of the Liveboard personalized view that you want to download.

In addition to these parameters, you can also define the following properties for PNG downloads:

* `image_resolution`
* `image_scale`
* `include_header`

For more information, see xref:data-report-v2-api.adoc#_liveboard_report_api[Liveboard Report API].

=== REST API Java SDK

The REST API Java SDK enables developers to interact programmatically with ThoughtSpot REST APIs from Java applications. It provides a client library with Java methods and classes that map to API endpoints, handle authentication, send API requests, and allow creating and modifying ThoughtSpot resources and objects.

For information about how to install and use the SDK, see xref:rest-api-java-sdk.adoc[Java SDK for REST APIs].


== Version 10.8.0.cl, April 2025

=== New API endpoints

This version introduces the following endpoints:
////
* `POST /api/rest/2.0/ai/analytical-questions` +
Allows using an existing ThoughtSpot Answer or Liveboard, and include content to improve query response.
////

* `POST /api/rest/2.0/metadata/update-obj-id` +
Update object IDs for given metadata objects. +

[NOTE]
====
An object ID is a user-defined ID assigned to a ThoughtSpot object in addition to the system-generated GUID.
Note that the object ID generation for metadata objects is disabled by default. If this feature is enabled on your instance, you can use the `POST /api/rest/2.0/metadata/update-obj-id` to assign or update the object ID.
====

=== Metadata API

* The `POST /api/rest/2.0/metadata/search` endpoint now supports the following parameters:

** `include_discoverable_objects` +
Allows including Answers and Liveboards that are marked as discoverable by the object owner.
** `metadata_obj_id` +
Filters metadata objects by the user-defined object ID. This parameter returns data only if the user-defined object ID feature is enabled on your instance.

=== TML APIs

* The `all_orgs_context` parameter in TML import APIs (` /api/rest/2.0/metadata/tml/import` and `/api/rest/2.0/metadata/tml/async/import`) is deprecated and removed from the Playground. Use `all_orgs_override` to define the Org context in your API requests.

* The TML export API now allows exporting TML content with user feedback received for objects such as AI-generated Answers. The `export_with_associated_feedbacks` attribute is set to `false` by default.

=== Report APIs
The Liveboard export API (`/api/rest/2.0/report/liveboard`) now allows overriding filters applied to a Liveboard. The `override_filters` array allows specifying several types of filters and updates the Liveboard data during export.

For more information, see xref:data-report-v2-api.adoc#_override_filters[Override filters].

== Version 10.6.0.cl, March 2025

=== New metadata API endpoints

* `POST /api/rest/2.0/metadata/headers/update` +
Updates metadata header for a given list of objects.
* `POST /api/rest/2.0/metadata/worksheets/convert` +
Converts a Worksheet object to a Model.

=== Report APIs
[tag redBackground]#BREAKING CHANGE#

Downloading Liveboard reports in the CSV and XLSX file format via `POST /api/rest/2.0/report/liveboard` API endpoint is not supported. The CSV and XLSX `file_format` options have been removed because they were not functioning in the expected manner.

==== Parameters for regional settings

The `/api/rest/2.0/report/answer` and `/api/rest/2.0/report/liveboard` now allow users to define the following `regional_settings` attributes:

* `currency_format`
* `user_locale`
* `number_format_locale`
* `date_format_locale`

////
=== Custom authentication token API

The `/api/rest/2.0/auth/token/custom` API endpoint now allows you to define the `reset_option` to specify if the attributes assigned to the token should persist or be reset.
////

=== Custom object ID in TML and Metadata APIs

The following API endpoints allow you to specify a custom object ID (`obj_identifier`) in the metadata object properties:

* `POST /api/rest/2.0/metadata/search`
* `POST /api/rest/2.0/metadata/headers/update`
* `POST /api/rest/2.0/metadata/tml/export` +

=== TML import API

The `/api/rest/2.0/metadata/tml/async/import` and `POST /api/rest/2.0/metadata/tml/import` endpoints allow skipping diff check when processing TMLs for imports. The `skip_diff_check` attribute is disabled by default and can be enabled to avoid importing objects that do not have any changes.

=== API response changes

The 200 and 201 response body from `POST /api/rest/2.0/ai/answer/create` and `POST /api/rest/2.0/ai/conversation/{conversation_identifier}/converse` API calls now includes the `display_tokens` property.


== Version 10.5.0.cl, December 2024

=== Custom access token API
The `/api/rest/2.0/auth/token/custom` API endpoint allows setting the following attributes in API requests:

* `auto_create` +
Creates a user if username specified in the API request is not available in ThoughtSpot. By default, the `auto_create` is set to `true`.
* `REPLACE` enum for `persist_option` +
Allows replacing persisted values with new attributes defined in the token generation API request. For more information, see xref:abac-user-parameters.adoc[ABAC via tokens].

=== TML import APIs

TML async import::

The `/api/rest/2.0/metadata/tml/async/import` supports setting the following properties via API requests:
+
* `import_policy` +
Allows you specify if all objects should be imported during the TML import operation. Valid values are:

** `PARTIAL_OBJECT` (default)
** `PARTIAL`
** `VALIDATE_ONLY`
** `ALL_OR_NONE`

* `enable_large_metadata_validation` +
Indicates if the TMLs with large and complex metadata should be validated before the import.
+
For more information about these attributes, see xref:tml.adoc#_import_tml_objects_asynchronously[Import TML objects asynchronously].

////
* `skip_diff_check` +
Allows skipping checks that find differences in TML content before processing TML objects for import.
////

TML import API::

The `/api/rest/2.0/metadata/tml/import` API also supports setting the `enable_large_metadata_validation` attribute for large and complex metadata objects during TML import.

TML export API::

The `/api/rest/2.0/metadata/tml/export` endpoint now allows you to include additional attributes when exporting TML for an object from ThoughtSpot. The `export_options` allows you to include the following optional attributes:

* `include_obj_id_ref` +
Specifies whether to export `user_defined_id` of the referenced object. This setting is valid only if the `UserDefinedId` property in TML is enabled.
* `include_guid` +
Specifies whether to export the GUID of the object. This setting is valid only if the `UserDefinedId` property in TML is enabled.
* `include_obj_id` +
Specifies whether to export the `user_defined_id` of the object. This setting is valid only if the `UserDefinedId` property in TML is enabled.


Share metadata::

The `email` attribute is now optional in the `POST` request body sent to the `/api/rest/2.0/security/metadata/share` API endpoint.

Role API::

The `/api/rest/2.0/roles/create` API endpoint now allows setting `read_only` attribute to specify if the role is read only. A read-only role cannot be updated or deleted.

== Version 10.4.0.cl, November 2024

=== New API endpoints

Spotter AI APIs [beta betaBackground]^Beta^ ::

* `POST /api/rest/2.0/ai/conversation/create` +
Creates a conversation session.
* `POST /api/rest/2.0/ai/conversation/{conversation_identifier}/converse` +
Generates responses for user queries and follow-up questions.
* `POST /api/rest/2.0/ai/answer/create` +
Generate an Answer from a Natural Language Search query

Authentication::
The `/api/rest/2.0/auth/token/custom` API endpoint is now available to generate an authentication token with custom rules and filter conditions for a user.

+
ThoughtSpot recommends using the custom token API endpoint to generate tokens for the Attribute-Based Access Control (ABAC) implementation. For more information, see xref:authentication.adoc#_get_tokens_with_custom_rules_and_filter_conditions[REST API v2 authentication] and xref:abac-user-parameters.adoc[ABAC via tokens].

Connections::
The following new API endpoints are available for updating and deleting a connection object:

* `POST /api/rest/2.0/connections/{connection_identifier}/update`
* `POST /api/rest/2.0/connections/{connection_identifier}/delete`

+
ThoughtSpot recommends using these APIs instead of `POST /api/rest/2.0/connection/update` and `POST /api/rest/2.0/connection/delete`.

TML::
The following API endpoints are available for asynchronous TML import:

* `POST /api/rest/2.0/metadata/tml/async/import` +
Validates and imports TML objects asynchronously. Use this API endpoint when importing large metadata objects.
* `POST /api/rest/2.0/metadata/tml/async/status` +
Fetches task status for the async TML import operations.

For more information, see xref:tml.adoc#_import_tml_objects_asynchronously[Import TML objects asynchronously].

=== API enhancements

User session::

* The 200 API response for the `/api/rest/2.0/auth/session/user` and `/api/rest/2.0/users/search` is modified to show `access_control_properties`.

* You can now manage account activation status for IAMv2 users using the following API endpoints:

** `POST /api/rest/2.0/users/create` +
** `POST /api/rest/2.0/users/{user_identifier}/update`

////
TML import API::
You can specify the following attributes in TML import requests to `/api/rest/2.0/metadata/tml/import`:

* `skip_cdw_validation_for_tables` +
Indicates if the Cloud Data Warehouse (CDW) validation for table imports should be skipped.
////

Report API::

The `POST /api/rest/2.0/report/answer` API endpoint supports downloading an Answer generated by the Spotter AI APIs:

* `session_identifier`  +
Session ID returned in API response by the `/api/rest/2.0/ai/answer/create` or `/api/rest/2.0/ai/conversation/create` endpoint.
* `generation_number` +
Number assigned to the Answer session with Spotter.
+
If you are downloading an Answer generated by Spotter, you must specify the session ID. The `metadata_identifier` property is not required.

=== Deprecated features

Connection APIs::

The following connection API endpoints are deprecated:

* `POST /api/rest/2.0/connection/delete`
* `POST /api/rest/2.0/connection/update`

+
Use `POST /api/rest/2.0/connections/{connection_identifier}/update` and `POST /api/rest/2.0/connections/{connection_identifier}/delete` APIs to update and delete a connection object respectively.

Authentication::

The `user_parameters` property in  `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` APIs is deprecated.
+
ThoughtSpot recommends using `/api/rest/2.0/auth/token/custom` API endpoint with `filter_rules` and `parameter_values` to configure user properties for ABAC via tokens.

== Version 10.3.0.cl, October 2024

=== New API endpoint

You can now create a copy of a Liveboard or Answer object using `/api/rest/2.0/metadata/copyobject` API endpoint.

== Version 10.1.0.cl, August 2024

=== New API endpoints

* `POST /api/rest/2.0/metadata/tml/export/batch` +
Exports a batch of TML for user, user group, or Role objects.

=== Security APIs
The `/api/rest/2.0/security/metadata/fetch-permissions` API endpoint supports the following parameters:

* `record_offset` +
Specifies the starting record number from which the records for each metadata type will be included in the API response.
* `record_size` +
Specifies the number of records that should be included for each metadata type in the API response.
* `permission_type` +
Specifies the type of permission. Valid values are:
** `EFFECTIVE` - If user permission to the metadata objects is granted by the privileges assigned to the groups to which they belong.
** `DEFINED` - If a user or user group received access to metadata objects via object sharing by another user.

== Version 10.0.0.cl, July 2024

=== Roles

You can now assign the `CAN_MANAGE_VERSION_CONTROL` role using any of the following API endpoints:

* `POST /api/rest/2.0/roles/create`
* `POST /api/rest/2.0/roles/{role_identifier}/update`

The `CAN_MANAGE_VERSION_CONTROL` Role privilege is required for Git integration with ThoughtSpot.

////
=== Connections

The following API endpoints available for data connections:

* `POST /api/rest/2.0/connections/update/{connection_identifier}`
* `POST /api/rest/2.0/connections/delete/{connection_identifier}`
////

== Version 9.12.0.cl, May 2024

==== New features

Authentication API::

*  `/api/rest/2.0/auth/token/validate` +
Validates the authentication token of the logged-in user.

TML API::
The export TML API requests now support the following parameters:
+
* `export_schema_version` +
Specifies the schema version for datasets during TML export. By default, the API request uses v1 schema for Worksheet TML export. For Models, set `export_schema_version` to `v2`. +
* `export_dependent` +
Allows exporting dependent Tables while exporting a Connection.
* `export_connection_as_dependent` +
Specifies if a Connection can be exported as a dependent object when exporting a Table, Worksheet, Answer, or Liveboard. This parameter works only when `export_associated` is set to `true` in the API request.

==== Deprecated features

Token authentication APIs::

The `jwt_user_options` object property in `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` is deprecated. Use the `user_parameters` property to define security entitlements to a user session. For more information, see xref:abac-user-parameters.adoc[ABAC via token][beta betaBackground]^Beta^.

== Version 9.10.5.cl, April 2024

=== New features

Authentication::

The `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` API endpoints support generating JWT token for Attribute-Based Access Control. The `user_parameters` object allows you to define security entitlements for a given user.

For more information, see xref:abac-user-parameters.adoc[ABAC via tokens].

Roles::

The `/api/rest/2.0/roles/create` and `/api/rest/2.0/roles/{role_identifier}/update` API endpoints support assigning the following privileges to a Role for granular data access control and management:

* `CAN_MANAGE_CUSTOM_CALENDAR`
* `CAN_CREATE_OR_EDIT_CONNECTIONS`
* `CAN_MANAGE_WORKSHEET_VIEWS_TABLES`

DBT::

You can now use `file_content` to upload DBT Manifest and Catalog artifact files as a ZIP file in your API requests to the `/api/rest/2.0/dbt/dbt-connection`, `/api/rest/2.0/dbt/generate-tml`, `/api/rest/2.0/dbt/generate-sync-tml`, and `/api/rest/2.0/dbt/update-dbt-connection` endpoints. Required if the  `import_type` parameter is set to `'ZIP_FILE`.

Connections::

* `/api/rest/2.0/connections/fetch-connection-diff-status/{connection_identifier}` +
Validates the differences in Connection metadata between Cloud Data Warehouse and ThoughtSpot.
* `/api/rest/2.0/connections/download-connection-metadata-changes/{connection_identifier}` +
Downloads the connection metadata differences identified between Cloud Data Warehouse and ThoughtSpot.

Logs::
The `/api/rest/2.0/logs/fetch` API endpoint allows fetching all logs in a single API request. To get all logs, set `get_all_logs` to `true`.

Share metadata::

The `/api/rest/2.0/security/metadata/share` API supports the following new properties:

* `notify_on_share` +
Sends a share notification to the email addresses specified in the API request.
* `has_lenient_discoverability` +
Sets the shared metadata object as a discoverable object. Applies to Saved Answers and Liveboards only.

Users::
The `trigger_activation_email` property allows you to specify if an activation email must be sent to the user's email address in the user creation request to the `/api/rest/2.0/users/create` endpoint.

=== Deprecated features

Version Control APIs::

The following parameters in the `/api/rest/2.0/vcs/git/config/create` and  `/api/rest/2.0/vcs/git/config/update` are deprecated from 9.10.5.cl onwards:

* `default_branch_name` +
Replaced by `commit_branch_name`
* `guid_mapping_branch_name` +
Replaced by `configuration_branch_name`

For more information, see xref:version_control.adoc[Git integration and version control].

== Version 9.10.0.cl, March 2024

=== New API endpoints

DBT::

* `POST /api/rest/2.0/dbt/dbt-connection` +
Creates a DBT connection.
*  `POST /api/rest/2.0/dbt/generate-tml` +
Generates Worksheets and Tables for a given DBT connection.
* `POST /api/rest/2.0/dbt/generate-sync-tml` +
Synchronizes the existing TML of data models and Worksheets and import them to Thoughtspot.
* `POST /api/rest/2.0/dbt/search` +
Gets a list of DBT connection objects for a given user or Org.
* `POST /api/rest/2.0/dbt/{dbt_connection_identifier}` +
Updates a DBT connection.

System::

`GET api/rest/2.0/system/banner` +
Gets cluster maintenance status and banner text.

+
For more information, see xref:tse-eco-mode.adoc#_cluster_status_during_upgrade[Cluster maintenance and upgrade].

== Version 9.8.0.cl, January 2024

The `deploy_policy` property in the `/api/rest/2.0/vcs/git/commits/deploy` endpoint now supports the `VALIDATE_ONLY` option, which allows you to compare and validate TML content on the destination environment against the content in the main branch before deploying commits.

== Version 9.7.0, November 2023

=== Version Control APIs

This release introduces the following enhancements to the Version Control API endpoints:

==== Git connection creation and update APIs

The `POST /api/rest/2.0/vcs/git/config/create` and `POST /api/rest/2.0/vcs/git/config/update` API endpoints include the following enhancements:

New parameters::

* `commit_branch_name` +
Allows configuring a commit branch for Git connections on your ThoughtSpot instance. ThoughtSpot recommends using `commit_branch_name` instead of `default_branch_name` in the API calls to prevent users from committing changes to the default deployment branch.
* `configuration_branch_name` +
Allows configuring a separate Git branch for storing and maintaining configuration files, such as GUID mapping and commit tracking files. If the `configuration_branch_name` property is defined, the `guid_mapping_branch_name` parameter is not required.

Modified parameters::
The `enable_guid_mapping` parameter is enabled by default.

Separate branches for Orgs::
If you are using Orgs and want to move content between these Orgs using version control APIs, ensure that you set a separate Git branch for each Org. If two Orgs are connected to the same Git `repository_url`, the `POST /api/rest/2.0/vcs/git/config/create` and `POST /api/rest/2.0/vcs/git/config/update` API endpoints do not support configuring the same branch name for these Orgs.

Deprecation notice::

The `default_branch_name` and `guid_mapping_branch_name` parameters will be deprecated from version 10.0.0.cl and later releases.

For more information, see xref:version_control.adoc#connectTS[Connect your ThoughtSpot environment to the Git repository].

==== Commit API

The `POST /api/rest/2.0/vcs/git/branches/commit` API endpoint allows the following new attribute in the request body:

* `delete_aware`
+
When set to true, the system runs a check between the objects and files in the Git branch and destination environment or Org. If an object exists in the Git branch, but not the destination environment or Org, it will be deleted from the Git branch during the commit operation.

For more information, see xref:version_control.adoc#_commit_files_and_changes[Commit files].

==== Deploy API

Note the following changes:

* The `branch_name` attribute is now mandatory in the `POST /api/rest/2.0/vcs/git/commits/deploy` API requests. Ensure that you specify the name of the Git branch from which the commits can be picked and deployed on the destination environment or Org.

* After a successful deployment, a tracking file is generated with the `commit_id` and saved in the Git branch that is used for storing configuration files. The `commit_id` recorded in the tracking file is used for comparing changes when new commits are pushed in the subsequent API calls.

For more information, see xref:version_control.adoc#_deploy_commits[Deploy commits].

=== User API

The following new API endpoints are introduced for user account management:

* `POST /api/rest/2.0/users/activate` +
Activates an inactive user account.

* `POST /api/rest/2.0/users/deactivate` +
Deactivates a user account.

=== Support for sorting of columns at runtime
The following data API endpoints now support runtime sorting of columns:

* `POST /api/rest/2.0/searchdata` +
* `POST /api/rest/2.0/metadata/liveboard/data` +
* `POST /api/rest/2.0/metadata/answer/data` +

For more information, see xref:runtime-sort.adoc[Runtime sorting of columns].

== Version 9.6.0.cl, October 2023

=== New API endpoints

* `POST /api/rest/2.0/customization/custom-actions/search` +
Gets custom action objects
* `POST /api/rest/2.0/customization/custom-actions` +
Creates a custom action
* `POST /api/rest/2.0/customization/custom-actions/{custom_action_identifier}/update` +
Updates the properties of a custom action object.
* `POST /api/rest/2.0/customization/custom-actions/{custom_action_identifier}/delete` +
Deletes a custom action

=== SDK for TypeScript

ThoughtSpot provides TypeScript SDK to help client applications call REST APIs using TypeScript. You can download the SDK from the link:https://www.npmjs.com/package/@thoughtspot/rest-api-sdk?activeTab=readme[NPM site, window=_blank].

== Version 9.5.0.cl, September 2023

=== New API endpoints for Role-Based Access Control [beta betaBackground]^Beta^

* `POST /api/rest/2.0/roles/search` +
Gets details of role objects available in the ThoughtSpot system.
* `POST /api/rest/2.0/roles/create` +
Creates a role and assigns privileges
* `POST /api/rest/2.0/roles/{role_identifier}/update` +
Updates the properties of a given role
* `POST /api/rest/2.0/roles/{role_identifier}/delete` +
Removes a role object from the ThoughtSpot system

For more information, see xref:roles.adoc[Role-based access control].

[NOTE]
====
The roles APIs work only if the Role-Based Access Control (RBAC) [beta betaBackground]^Beta^ feature is enabled on your instance. The RBAC feature is turned off by default. To enable this feature, contact ThoughtSpot Support.
====

=== Enhancements and API modifications

Support for runtime parameter overrides::
The following data and report API endpoints support applying runtime parameter overrides:
* `POST /api/rest/2.0/searchdata` +
* `POST /api/rest/2.0/metadata/liveboard/data` +
* `POST /api/rest/2.0/metadata/answer/data` +
* `POST /api/rest/2.0/report/liveboard` +
* `POST /api/rest/2.0/report/answer`

Git integration support for Orgs::

The Version Control API endpoints support using Orgs as disparate deployment environments. You can create separate Orgs for `dev`, `staging`, and `prod` and integrate these environments with a GitHub repo.

+
For more information, see xref:version_control.adoc[Git integration and version control].

=== Response code change [tag redBackground]#BREAKING CHANGE#

The following endpoints now return the 204 response code instead of 200. The 204 code doesn't return a response body. This change may affect your current implementation, so we recommend that you update your code to avoid issues.

* `POST /api/rest/2.0/connection/delete`
* `POST /api/rest/2.0/connection/update`
* `POST /api/rest/2.0/users/{user_identifier}/update`
* `POST /api/rest/2.0/users/{user_identifier}/delete`
* `POST /api/rest/2.0/users/change-password`
* `POST /api/rest/2.0/users/reset-password`
* `POST /api/rest/2.0/users/force-logout`
* `POST /api/rest/2.0/groups/{group_identifier}/update`
* `POST /api/rest/2.0/groups/{group_identifier}/delete`
* `POST /api/rest/2.0/metadata/delete`
* `POST /api/rest/2.0/orgs/{org_identifier}/update`
* `POST /api/rest/2.0/orgs/{org_identifier}/delete`
* `POST /api/rest/2.0/schedules/{schedule_identifier}/delete`
* `POST /api/rest/2.0/schedules/{schedule_identifier}/update`
* `POST /api/rest/2.0/security/metadata/assign`
* `POST /api/rest/2.0/security/metadata/share`
* `POST /api/rest/2.0/system/config-update`
* `POST /api/rest/2.0/tags/{tag_identifier}/update`
* `POST /api/rest/2.0/tags/{tag_identifier}/delete`
* `POST /api/rest/2.0/tags/assign`
* `POST /api/rest/2.0/tags/unassign`
* `POST /api/rest/2.0/vcs/git/config/delete`
* `POST /api/rest/2.0/auth/session/login`
* `POST /api/rest/2.0/auth/session/logout`
* `POST /api/rest/2.0/auth/token/revoke`


== Version 9.4.0.cl, August 2023

=== API endpoints to schedule and manage Liveboard jobs

* `*POST* /api/rest/2.0/schedules/create` +
Creates a scheduled job for a Liveboard
* `*POST* /api/rest/2.0/schedules/{schedule_identifier}/update` +
Updates a scheduled job
* `*POST* /api/rest/2.0/schedules/search` +
Gets a list of Liveboard jobs configured on a ThoughtSpot instance
* `*POST* /api/rest/2.0/schedules/{schedule_identifier}/delete` +
Deletes a scheduled job.

For more information, see link:{{navprefix}}/restV2-playground?apiResourceId=http/api-endpoints/schedules/search-schedule[REST API v2.0 Reference].

=== API to fetch authentication token

The `GET /api/rest/2.0/auth/session/token` API endpoint fetches the current authentication token used by the currently logged-in user.

=== Version Control API enhancements

* The following Version Control API endpoints support generating and maintaining a GUID mapping file on a Git branch connected to a ThoughtSpot instance:

** `*POST* /api/rest/2.0/vcs/git/config/create`
** `*POST* /api/rest/2.0/vcs/git/config/update`

=== User and group API enhancements

* The `**POST** /api/rest/2.0/users/{user_identifier}/update` and `**POST** /api/rest/2.0/groups/{group_identifier}/update` support specifying the type of operation API request. For example, if you are removing a property of a user or group object, you can specify the `operation` type as `REMOVE` in the API request.
* The `**POST** /api/rest/2.0/users/{user_identifier}/update` allows you to define locale settings, preferences, and other properties for a user object.

== Version 9.3.0.cl, June 2023

The following Version Control [beta betaBackground]^Beta^ API endpoints are now available for the  lifecycle management of content on your deployment environments:

* `*POST* /api/rest/2.0/vcs/git/config/search`
* `*POST* /api/rest/2.0/vcs/git/commits/search`
* `*POST* /api/rest/2.0/vcs/git/config/create`
* `*POST* /api/rest/2.0/vcs/git/config/update`
* `*POST* /api/rest/2.0/vcs/git/config/delete`
* `*POST* /api/rest/2.0/vcs/git/branches/commit`
* `*POST* /api/rest/2.0/vcs/git/commits/{commit_id}/revert`
* `*POST* /api/rest/2.0/vcs/git/branches/validate`
* `*POST* /api/rest/2.0/vcs/git/commits/deploy`

For more information, see xref:version_control.adoc[Version control and Git integration].

== Version 9.2.0.cl, May 2023

New endpoints::

* System
+
** `POST /api/rest/2.0/system/config-update` +
Updates system configuration
+
** `GET /api/rest/2.0/system/config-overrides` +
Gets system configuration overrides

* Connections
+
** POST /api/rest/2.0/connection/create +
Creates a data connection

** `POST /api/rest/2.0/connection/search` +
Gets a list of data connections

** `POST /api/rest/2.0/connection/update` +
Updates a data connection

** `POST /api/rest/2.0/connection/delete` +
Deletes a data connection

Enhancements::

* Support for runtime filters and runtime sorting of columns +
The following REST API v2.0 endpoints support applying xref:runtime-filters.adoc#_apply_runtime_filters_in_rest_api_v2_requests[runtime filters] and xref:runtime-sort.adoc[sorting column data]:
+
** `POST /api/rest/2.0/report/liveboard` +
** `POST /api/rest/2.0/report/answer`

* Search users by their favorites
+
The `/api/rest/2.0/users/search` API endpoint allows searching users by their favorite objects and home Liveboard setting.

* Ability to log in to a specific Org
+
The `/api/rest/2.0/auth/session/login` API endpoint now allows ThoughtSpot users to log in to a specific Org context.

== Version 9.0.0.cl, February 2023

The ThoughtSpot Cloud 9.0.0.cl release introduces the REST API v2.0 endpoints and Playground. For information about REST API v2.0 endpoints and Playground, see the following articles:

* xref:rest-api-v2.adoc[REST API v2.0]
* xref:rest-api-v2-getstarted.adoc[Get started with REST API v2.0]
* xref:rest-api-v2-reference.adoc[REST API v2.0 reference]
* xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison]



