= REST API v2.0 groups/search endpoint
:toc: true
:toclevels: 2

:page-title: Using REST API V2.0 groups/search endpoint
:page-pageid: rest-apiv2-groups-search
:page-description: Many use cases are possible with the V2.0 groups/search endpoint

== Overview
`link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fsearch-user-groups[/groups/search, target=_blank]` is used to retrieve details about ThooughtSpot groups (often referred in the API as user groups or with the `USER_GROUP` value), with many specific filtering capabilities for answering a number of relevant questions about groups.

You can search for the `USER_GROUP` type using `metadata/search`, but `groups/search` provides considerably more control.

The overall structure of `groups/search` request is link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fapi-rest-20-groups-search-request[described as a combination of objects, target=_blank].

Remember: many parameters in the request are *optional*, and leaving the parameter name out entirely has a different effect from including the parameter and specific values.

Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown: 

[source,javascript]
----
{
  "record_offset" : 0,
  "record_size": 100000
}
----

== Response format
The response from any call to `groups/search` will resemble the following:

[source,javascript]
----
[
  {
    "author_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "complete_detail": true,
    "content": NULL,
    "creation_time_in_millis": 1354006445722,
    "default_liveboards": [],
    "deleted": false,
    "deprecated": false,
    "description": NULL,
    "display_name": "System Management Group",
    "external": false,
    "generation_number": 867825,
    "hidden": false,
    "id": "179d8867-cf36-4a8d-a019-63a226fd3196",
    "index": 3,
    "index_version": 867825,
    "metadata_version": 0,
    "modification_time_in_millis": 1354006445722,
    "modifier_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "name": "System",
    "orgs": NULL,
    "owner_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "parent_type": "GROUP",
    "privileges": [],
    "sub_groups": [],
    "system_group": true,
    "tags": [],
    "type": "LOCAL_GROUP",
    "users": [
      {
        "id": "67e15c06-d153-4924-a4cd-ff615393b60f",
        "name": "nick.cooper"
      },
      ...
    ],
    "visibility": "SHARABLE",
    "roles": null
  }
...
]
----

== Lists of metadata
`/groups/search` performs listing functions when you do not send specific object IDs as part of your request. Note you must send some request in the body of the POST, even if this is only `{ }`.

The basic metadata selectors are placed in the `metadata` parameter as an array of link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-list-item-input[Metadata List objects, target=_blank]. 

For example, to see *all groups*, you can simply send the `record_offset` and `record_size` parameters:

[source,javascript]
----
{
  "record_offset": 0,
  "record_size": 100000
}
----

== Retrieve specific objects
There are several parameters that allow referencing a user object directly. 
  
`group_identifier` takes either the **group name** or **group GUID**:

[source,javascript]
----
{
 "group_identifier" : 'Marketing Team'
}
----

`display_name` instead checks against the visible display name that shows within the ThoughtSpot UI.

`description` is also available as a filtering parameter.

== Filtering and sorting

=== sort_options
The `sort_options` parameter takes a link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fenumerations%2Ffield-name[Users Search Sort Options, target=_blank] object allowing for sorting on one field of the metadata response either **ASC** or **DESC**:

[source,javascript]
----
{
 "sort_options" : {
  "field_name": "DISPLAY_NAME",
  "order": "ASC" 
 }
}
----

If you need multiple levels of sorting, you'll have to parse the response programmatically and apply a sorting algorithm on the properties within each response item.

=== user_identifiers
You can filter responses based on which users belong to a group.

The `user_identifiers` parameter takes an array of strings of either **username** or **user GUID**. Note that users have a `display_name` property separate from **username** that cannot be used in the `user_identifiers` array.

[source,javascript]
----
{
 "user_identifiers" : [
    "Developers"
  ]
}
----

As with other filters that take arrays, the query treats multiple items as a logical OR operation. If you need to identify groups with an exact set of users, you'll need to process the result and inspect the `users` array of each returned group object.

=== privileges
Responses can be filtered based on **privileges** assigned to the user. Privileges are assigned through groups directly or via roles on ThoughtSpot instances with the newer roles feature enabled.

The array of privileges works as an OR condition, returning any group with any of the privileges listed. If you need find a group with a set of privileges, you'll have to check the `privileges` array for each group object in the response.

[source,javascript]
----
{
 "privileges": [
    "DEVELOPER",
    "DATADOWNLOADING"
  ]
}
----

=== visibility
Every group has a `visibility` property which can either be `SHARABLE` or `NON_SHARABLE`. A `SHARABLE` group can have content shared by users who belong to the same sharable group.

You can list out groups with a specific visibility setting by specifiying the `visibility` property in the request:

[source,javascript]
----
{
 "visibility": "SHARABLE"
}
----

=== user_identifiers
You can filter responses based on which users belong to a group.

The `user_identifiers` parameter takes an array of strings of either **username** or **user GUID**. Note that users have a `display_name` property separate from **username** that cannot be used in the `user_identifiers` array.

[source,javascript]
----
{
 "user_identifiers" : [
    "Developers"
  ]
}
----

=== type 
The `type` property tracks which SSO method was used to create a given group. The two options are `LOCAL_GROUP` and `LDAP_GROUP`. 

[source,javascript]
----
{
 "type": "LDAP_GROUP"
}
----

=== sub_group_identifiers
Groups in ThoughtSpot can belong to other groups. The `sub_group_identifiers` parameter takes an an array of strings of either **group name** or **group GUID** and returns a list of groups with those sub-groups. 


[source,javascript]
----
{
 "sub_group_identifiers" : [
    "A Sub Group Name"
  ]
}
----


=== default_liveboard_identifiers
The `default_liveboard_identifiers` parameter filters to groups with the specified Liveboards set as default Liveboards set for any user who belongs to that group. The value can take the GUID of a Liveboard or its name, but because Liveboard names are not guaranteed to be unique, it is best to use the GUIDs of any specific Liveboards when using this filtering parameter:

[source,javascript]
----
{
 "default_liveboard_identifiers": 
    ["a1fdcb4d-9cf9-466b-b866-22c53db9b1ac"]
}
----

=== org_identifiers
On a ThoughtSpot instance where orgs has been enabled, a user can belong to multiple orgs. 

The `org_identifiers` parameter takes an array of strings representing either org names or the string version of the org_id, which is an integer.

As with other filtering parameters that take arrays, the list of identifiers is handled as a logical OR, returning any users who belong to any of the provided identifiers. To filter to a user with a particular set of orgs, you will need to do additional processing on the result set to confirm the full set of orgs matches:

[source,javascript]
----
{
 "org_identifiers": [
   "Dev",
   "UAT"
 ]
}
----

The `orgs` key of each user item in the response contains the details of the orgs, which can be read and compared to the set of orgs you want to match for that user:

[source,javascript]
----
...
"orgs":[
  {
    "id": 1568202965,
    "name": "Dev"
  }, 
  {
    "id": 2004448319,
    "name": "Secondary"
  }
]
...
----

Note that the org `id` is an integer in this portion of the response. 

=== role_identifiers
On ThoughtSpot instances with roles enabled, you can use the `role_identifiers` parameter to send an array of either GUID or name of the roles that a group has been assigned to.





