= TypeScript SDK
:toc: true
:toclevels: 1

:page-title: REST API SDK
:page-pageid: rest-api-sdk-typescript
:page-description: ThoughtSpot provides REST API SDK with TypeScript client libraries.

The REST API SDK library for TypeScript is available on the link:https://www.npmjs.com/package/@thoughtspot/rest-api-sdk[NPM site, window=_blank].

== SDK version

Note the version recommendations for your ThoughtSpot clusters:

[width="100%" cols="1,4"]
[options='header']
|====
|SDK version|Minimum required version on ThoughtSpot cluster
|v2.0.2 a| ThoughtSpot Cloud 9.6.0.cl +
ThoughtSpot Software 9.8.0.sw

If your cluster is upgraded to a later version, please browse through the xref:rest-apiv2-changelog.adoc[API changelog] and note the breaking changes.
|====

== Get started

Before you begin, check if your setup meets the following prerequisites:

* You have a ThoughtSpot instance with the necessary credentials
* Node.js version 18 or later is installed on your machine +
You can also use the ThoughtSpot React demo application to interact with a ThoughtSpot instance using the TypeScript SDK.

=== Setup and usage

. Install the SDK in your local directory.
+
----
npm install @thoughtspot/rest-api-sdk --save
----

. Build your app locally.

+
----
npm run build
----

. Open the `src/App.tsx` file and update the following constants with your ThoughtSpot server information:
+
* `BASE_URL` +
The URL of your ThoughtSpot instance.
* `USERNAME` +
Username of your ThoughtSpot account.
* `PASSWORD` +
Password of your ThoughtSpot account.

. Start the application:
+
----
npm run start
----

=== Authentication
After you install the SDK, set up authentication and make an API request. For basic authentication, specify the `username` and `password` as shown in this example:

[source,TypeScript]
----
import { createBearerAuthenticationConfig, AuthenticationApi, GetFullAccessTokenRequest } from '@thoughtspot/rest-api-sdk';

const configuration = createBearerAuthenticationConfig("CLUSTER_SERVER_URL", {
    username: "YOUR_USERNAME",
    password: "YOUR_PASSWORD",
});
const apiInstance = new AuthenticationApi(configuration);

apiInstance.getFullAccessToken(
  // GetFullAccessTokenRequest
  {
    username: "UserA",
    password: "{PASSWORD}",
    secret_key: "",
    validity_time_in_sec: 300,
    org_id: 0,
    email: "email_example",
    display_name: "display_name_example",
    auto_create: false,
    group_identifiers: [
      "group_identifiers_example",
    ],
  }
).then((data:any) => {
  console.log('API called successfully. Returned data: ' + data);
}).catch((error:any) => console.error(error));
----

=== Make an API call
To test your implementation, make an API call. For example, call the `searchUsers` method to get a list of ThoughtSpot users.

----
import {
  ThoughtSpotRestApi,
  createBearerAuthenticationConfig
} from "@thoughtspot/rest-api-sdk";

const BASE_URL = "CLUSTER_URL";

const main = async () => {
  // getting the token
  const config = createBearerAuthenticationConfig(BASE_URL, {
    username: "YOUR_USERNAME",
    password: "YOUR_PASSWORD",
  });

  // create a thoughtspot client
  const tsRestApiClient = new ThoughtSpotRestApi(config);

  try {
    const users = await tsRestApiClient.searchUsers();
    console.log("Users on the cluster : ");
    users.forEach((user) => {
      console.log(user.name, user.email);
    });
  } catch (e) {
    console.log(e);
  }
};

main();
----

== SDK documentation

For a complete list of methods to use for API calls and examples, see the following resources:

[width="100%" cols="2,4"]
[options='header']
|====
|SDK version|Documentation
|ThoughtSpot Cloud 9.6.0.cl a| link:https://github.com/thoughtspot/rest-api-sdk/blob/release/sdks/typescript/ThoughtSpotRestApi.md[REST API SDK library for TypeScript, Window=_blank]
|====



