= REST API v2.0 search endpoints
:toc: true
:toclevels: 2

:page-title: Using REST API V2.0 search endpoints
:page-pageid: rest-apiv2-search
:page-description: Many use cases are possible with the very flexible REST API v2.0 search endpoints

The V2 endpoints that end in `/search` have very flexible request formats that solve a number of use cases. 

Some capabilities that have separate endpoints in the V1 REST API are done using the correct request on the smaller subset of `/search` endpoints in V2.0.

Remember: many parameters in the requests are *optional*, and leaving the parameter name out entirely has a different effect from including the parameter and specific values.

Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown: 

[source,javascript]
----
{
  "record_offset" : 0,
  "record_size": 100000
}
----

= /metadata/search
The `/metadata/search` endpoint in the V2 REST API replaces a large set of distinct endpoints in REST API V1. 

Please see the xref:rest-api-v2-metadata-search.adoc[/metadata/search endpoint documentation] for all of the many use cases of this API.

= users/search
You can use `metadata/search` with the `type` set to `USER` to get a basic listing, but `users/search` endpoint provides many more filtering options that are specific to properties of user objects.

Please see the xref:rest-api-v2-users-search.adoc[/users/search endpoint documentation] for all of the many use cases of this API.

= groups/search
You can use `groups/search` with the `type` set to `USER_GROUP` to get a basic listing, but `groups/search` endpoint provides many more filtering options that are specific to properties of user group objects.

Please see the xref:rest-api-v2-groups-search.adoc[/groups/search endpoint documentation] for all of the many use cases of this API.

= tags/search
The `tags/search` V2 endpoint allows you request a filterd list of the tag objects in the ThoughtSpot system. 

Searches for which content tags are assigned to are performed using the `xref:rest-api-v2-metadata-search.adoc[metadata/search]` endpoint.

== List all tags
The simplest request to `tags/search` is an empty body, which retrieves all tags in the system. Note that you do need to send an empty object `{ }` in the body of the request, otherwise it will not work:

[source,javascript]
----
{}
----

The response will be an array of tag header objects, with various properties of each tag:

[source,javascript]
----
[
  {
    "name":"RetailJP"
    "id":"000a240f-3029-4d2a-9d60-5fc3885f7bc7"
    "color":"#63c9ea"
    "deleted":false
    "hidden":false
    "external":false
    "deprecated":false
    "creation_time_in_millis":1607307160738
    "modification_time_in_millis":1607307160974
    "author_id":"59481331-ee53-42be-a548-bd87be6ddd4a"
    "modifier_id":"59481331-ee53-42be-a548-bd87be6ddd4a"
    "owner_id":"000a240f-3029-4d2a-9d60-5fc3885f7bc7"
    },
    ...
]
----
`name`, `color` and `id` are the most essential tag properties

== Filter to specific tags
You can specify a particular tag using the `tag_identifier` parameter in the request, which takes either the tag name or GUID:

[source,javascript]
----
{ 
 "tag_identifier" : "Marketing Tag"
}
----

You can also search for tags by assigned color with the `color` parameter, which takes a string of the 6 digit hex code of the color (using lowercase letters):
[source,javascript]
----
{ 
 "color" : "#63c9ea"
}
----

= orgs/search

= schedules/search

= roles/search

