= REST API v2.0 changelog
:toc: true
:toclevels: 3

:page-title: Changelog
:page-pageid: rest-v2-changelog
:page-description: Changelog of REST APIs

This changelog lists the features and enhancements introduced in REST API v2.0. For information about new features and enhancements available for embedded analytics, see xref:whats-new.adoc[What's New].

== Version 10.10.0.sw, September 2025

=== REST API Java SDK

The REST API Java SDK enables developers to interact programmatically with ThoughtSpot REST APIs from Java applications. It provides a client library with Java methods and classes that map to API endpoints, handle authentication, send API requests, and allow creating and modifying ThoughtSpot resources and objects.

For information about how to install and use the SDK, see xref:rest-api-java-sdk.adoc[Java SDK for REST APIs].

=== New API endpoints

==== Metadata APIs

Metadata parameterization and content publishing across Orgs::

This release introduces the following new endpoints for metadata parameterization [beta betaBackground]^Beta^ and content publishing [beta betaBackground]^Beta^ across Orgs. To enable the content publishing feature and the related API operations on your instance, contact ThoughtSpot Support.

* `POST /api/rest/2.0/metadata/parameterize`   +
Allows you to parameterize fields in metadata objects.
* `POST /api/rest/2.0/metadata/unparameterize`  +
Allows removing parameterization from fields in metadata objects
* `POST /api/rest/2.0/security/metadata/publish`  +
Publish metadata objects to one or several Orgs on an instance.
* `POST /api/rest/2.0/security/metadata/unpublish`  +
Removes published metadata objects from the Orgs specified in the API request.
* `POST /api/rest/2.0/template/variables/create`   +
Allows creating a template variable which can be used to parameterize fields in a metadata object.
* `POST /api/rest/2.0/template/variables/search` +
Allows searching template variables
* `POST /api/rest/2.0/template/variables/{identifier}/update`  +
Allows updating properties of a template variable.
* `POST /api/rest/2.0/template/variables/update`  +
Allows you to add, remove, or replace properties of one or several template variables.
* `POST /api/rest/2.0/template/variables/{identifier}/delete`  +
Deletes a template variable.

+
If your metadata objects are parameterized, you can use the `show_resolved_parameters` to filter the API response from `/api/rest/2.0/connection/search` and `/api/rest/2.0/metadata/search` endpoints to get only the objects with resolved parameterized values.

Object IDs::

* `POST /api/rest/2.0/metadata/update-obj-id` +
Update object IDs for given metadata objects. +
+
An object ID is a user-defined ID assigned to a ThoughtSpot object in addition to the system-generated GUID.
Note that the object ID generation for metadata objects is disabled by default. If this feature is enabled on your instance, you can use the `POST /api/rest/2.0/metadata/update-obj-id` to assign or update the object ID.

Metadata header::

* `POST /api/rest/2.0/metadata/headers/update` +
Updates metadata header for a given list of objects.

Worksheet to Model conversion::
* `POST /api/rest/2.0/metadata/worksheets/convert` +
Converts a Worksheet object to a Model.

Copy and create new object::

* `/api/rest/2.0/metadata/copyobject` +
Creates a copy of a Liveboard or Answer object using API endpoint.

==== Authentication
The `/api/rest/2.0/auth/token/custom` API endpoint is now available to generate an authentication token with custom rules and filter conditions for a user.

ThoughtSpot recommends using the custom token API endpoint to generate tokens for the Attribute-Based Access Control (ABAC) implementation. For more information, see xref:authentication.adoc#_get_tokens_with_custom_rules_and_filter_conditions[REST API v2 authentication] and xref:abac-user-parameters.adoc[ABAC via tokens].

===== Connections
The following new API endpoints are available for updating and deleting a connection object:

* `POST /api/rest/2.0/connections/{connection_identifier}/update`
* `POST /api/rest/2.0/connections/{connection_identifier}/delete`

ThoughtSpot recommends using these APIs instead of `POST /api/rest/2.0/connection/update` and `POST /api/rest/2.0/connection/delete`.

===== TML APIs
The following API endpoints are available for asynchronous TML import:

* `POST /api/rest/2.0/metadata/tml/async/import` +
Validates and imports TML objects asynchronously. Use this API endpoint when importing large metadata objects.
* `POST /api/rest/2.0/metadata/tml/async/status` +
Fetches task status for the async TML import operations.

For more information, see xref:tml.adoc#_import_tml_objects_asynchronously[Import TML objects asynchronously].

==== Email template customization APIs
This release introduces the following new endpoints for email template customization:

* `POST /api/rest/2.0/customization/email` +
Allows you to personalize the ThoughtSpot notification emails content.
* `POST /api/rest/2.0/customization/email/{template_identifier}/delete` +
Removes the customizations done for the ThoughtSpot notification emails.
* `POST /api/rest/2.0/customization/email/search` +
Allows searching the email customization configuration if any set for ThoughtSpot.
* `POST /api/rest/2.0/customization/email/validate` +
Validates the email customization configuration if any set for ThoughtSpot.

=== API enhancements

==== Group API

The `/api/rest/2.0/groups/search` endpoint now supports the following new options in group search API requests:

* `include_users` +
When set to `true`, it includes user details in the group search API response.
* `include_sub_groups` +
When set to `true`, it includes sub-groups in the group search response.

==== Schedule API
You can now specify the `personalised_view_id` of a Liveboard in API requests to the following schedule APIs:

* `POST /api/rest/2.0/schedules/create`
To schedule a job for a personalized view of the Liveboard, specify the `personalised_view_id`.
* `POST /api/rest/2.0/schedules/{schedule_identifier}/update`
To update schedule details for a specific view of the Liveboard, specify the `personalised_view_id`.

==== Liveboard Report API

The Liveboard export API (`/api/rest/2.0/report/liveboard`) now allows overriding filters applied to a Liveboard. The `override_filters` array allows specifying several types of filters and updates the Liveboard data during export.

For more information, see xref:data-report-v2-api.adoc#_override_filters[Override filters].

[tag redBackground]#BREAKING CHANGE#

*  Downloading Liveboard reports in the CSV and XLSX file format via `POST /api/rest/2.0/report/liveboard` API endpoint is not supported. The CSV and XLSX `file_format` options have been removed because they were not functioning in the expected manner.

* The Liveboard Report API now allows you to define the following properties:
+
** `tab_identifiers` +
Optional parameter to specify the name or GUID of a Liveboard tab to export only the visualizations in that tab.
** `personalised_view_identifier` +
Optional parameter to specify the GUID of the Liveboard personalized view that you want to download.
+
In addition to these parameters, you can also define the following properties for PNG downloads: +
** `image_resolution`
** `image_scale`
** `include_header`

For more information, see xref:data-report-v2-api.adoc#_liveboard_report_api[Liveboard Report API].

==== Parameters for regional settings in Report APIs

The `/api/rest/2.0/report/answer` and `/api/rest/2.0/report/liveboard` now allow users to define the following `regional_settings` attributes:

* `currency_format` +
* `user_locale` +
* `number_format_locale` +
* `date_format_locale`

////

The `POST /api/rest/2.0/report/answer` API endpoint supports downloading an Answer generated by the Spotter AI APIs:

* `session_identifier`  +
Session ID returned in API response by the `/api/rest/2.0/ai/answer/create` or `/api/rest/2.0/ai/conversation/create` endpoint.
* `generation_number` +
Number assigned to the Answer session with Spotter.
+
If you are downloading an Answer generated by Spotter, you must specify the session ID. The `metadata_identifier` property is not required.
////

==== User APIs

* The 200 API response for the `/api/rest/2.0/auth/session/user` and `/api/rest/2.0/users/search` is modified to show `access_control_properties`.

* You can now manage account activation status for IAMv2 users using the following API endpoints:

** `POST /api/rest/2.0/users/create` +
** `POST /api/rest/2.0/users/{user_identifier}/update`

////
TML import API::
You can specify the following attributes in TML import requests to `/api/rest/2.0/metadata/tml/import`:

* `skip_cdw_validation_for_tables` +
Indicates if the Cloud Data Warehouse (CDW) validation for table imports should be skipped.
////

==== Metadata API

* The `POST /api/rest/2.0/metadata/search` endpoint now supports the following parameters:

** `include_discoverable_objects` +
Allows including Answers and Liveboards that are marked as discoverable by the object owner.
** `metadata_obj_id` +
Filters metadata objects by the user-defined object ID. This parameter returns data only if the user-defined object ID feature is enabled on your instance.

* The following API endpoints allow you to specify a custom object ID (`obj_identifier`) in the metadata object properties:

** `POST /api/rest/2.0/metadata/search`
** `POST /api/rest/2.0/metadata/headers/update`
** `POST /api/rest/2.0/metadata/tml/export` +

===== Share metadata objects

The `email` attribute is now optional in the `POST` request body sent to the `/api/rest/2.0/security/metadata/share` API endpoint.

==== TML APIs

////
* `skip_diff_check` +
Allows skipping checks that find differences in TML content before processing TML objects for import.
////

TML import API::

The `/api/rest/2.0/metadata/tml/import` API also supports setting the `enable_large_metadata_validation` attribute for large and complex metadata objects during TML import.

TML export API::

The `/api/rest/2.0/metadata/tml/export` endpoint now allows you to include additional attributes when exporting TML for an object from ThoughtSpot. The `export_options` allows you to include the following optional attributes:

* `include_obj_id_ref` +
Specifies whether to export `user_defined_id` of the referenced object. This setting is valid only if the `UserDefinedId` property in TML is enabled.
* `include_guid` +
Specifies whether to export the GUID of the object. This setting is valid only if the `UserDefinedId` property in TML is enabled.
* `include_obj_id` +
Specifies whether to export the `user_defined_id` of the object. This setting is valid only if the `UserDefinedId` property in TML is enabled.



=== Deprecated features

Connection APIs::

The following connection API endpoints are deprecated:

* `POST /api/rest/2.0/connection/delete`
* `POST /api/rest/2.0/connection/update`

+
Use `POST /api/rest/2.0/connections/{connection_identifier}/update` and `POST /api/rest/2.0/connections/{connection_identifier}/delete` APIs to update and delete a connection object respectively.

Authentication::

The `user_parameters` property in  `/api/rest/2.0/auth/token/full` and `/api/rest/2.0/auth/token/object` APIs is deprecated. Use the `/api/rest/2.0/auth/token/custom` API endpoint with `filter_rules` and `parameter_values` attributes to configure user properties for ABAC via tokens.

=== API response changes

The 200 and 201 response body from `POST /api/rest/2.0/ai/answer/create` and `POST /api/rest/2.0/ai/conversation/{conversation_identifier}/converse` API calls now includes the `display_tokens` property.



