
= REST API v2.0 metadata endpoints
:toc: true
:toclevels: 1

:page-title: Using REST API V2.0 metadata endpoints
:page-pageid: rest-apiv2-metadata
:page-description: Many use cases are possible with the very flexible REST API v2.0 metadata endpoints

The metadata endpoints, in particular those that end in `/search`, have very flexible request formats that solve a number of use cases. 

Some capabilities that have separate endpoints in the V1 REST API are done using the correct request on the smaller subset of metadata `/search` endpoints in V2.0.

Remember: many parameters in the requests are *optional*, and leaving the parameter name out entirely has a different effect from including the parameter and specific values.

Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown: 

[source,javascript]
----
{
  "record_offset" : 0,
  "record_size": 100000
}
----

== /metadata/search
`link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fsearch-metadata[/metadata/search, target=_blank]` is the most versatile of all of the metadata endpoints. It can be used to search for lists, or to retrieve back very detailed information about specific objects.

It replaces `metadata/list`, `metadata/listobjectheaders`, `metadata/details` from REST API V1.

The overall structure of `metadata/search` request is link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fapi-rest-20-metadata-search-request[described as a combination of objects, target=_blank].

=== Lists of metadata
`/metadata/search` performs listing functions when you do not send specific object IDs as part of your request. 

The basic metadata selectors are placed in the `metadata` parameter as an array of link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-list-item-input[Metadata List objects, target=_blank]. 

For example, to see *all liveboards*, you only send the a single Metadata List object with `type` parameter set to `LIVEBOARD`:

[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD"
    }
  ]
{
----

To match names against a pattern, you can use the `name_pattern` parameter, including % for wildcard purposes:
[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD",
      "name_pattern": "Standard %"
    }
  ]
}
----
You may still want to process the result set further within your programming language.

=== Retrieve specific objects
The `identifier` parameter allows referencing an object by name or by object GUID. 
  
Specific objects can be retrieved via the object GUID without specifying `type`:

[source,javascript]
----
{
 "metadata": [
    {
      "identifier" : "009d8d6c-5026-47a9-96d7-9e0f84896d17"
    }
  ]
}
----

You can specify one item by name using `identifier`, but you must include the `type` in this request:
[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD",
      "identifier" : "My Great Liveboard"
    }
  ]
}
----
