= REST API v2.0 changelog
:toc: true
:toclevels: 1

:page-title: Changelog
:page-pageid: rest-v2-changelog
:page-description: Changelog of REST APIs

This changelog lists the features and enhancements introduced in REST API v2.0. For a complete list of ThoughtSpot Everywhere features and enhancements, see xref:whats-new.adoc[What's New].

== Version 9.1.0.cl, Coming soon

The 9.1.0.cl release introduces the following features and enhancements:

New API endpoints::
+
* `POST /api/rest/2.0/system/config-update`
+
Updates system configuration

+
* `GET /api/rest/2.0/system/config-overrides`
+
Gets system configuration overrides

Enhancements to Search user API endpoint::

The `POST /api/rest/2.0/users/search` API endpoint allows searching users by their favorite objects and home Liveboard setting.

== Version 9.0.0.cl, February 2023

The ThoughtSpot Cloud 9.0.0.cl release introduces the REST API v2.0 endpoints and Playground. For information about REST API v2.0 endpoints and Playground, see the following articles:

* xref:rest-api-v2.adoc[REST API v2.0]
* xref:rest-api-v2-getstarted.adoc[Get started with REST API v2.0]
* xref:rest-api-v2-reference.adoc[REST API v2.0 reference]
* xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison]



