= REST API v2.0 SDKs
:toc: true
:toclevels: 1

:page-title: REST API SDKs
:page-pageid: rest-api-sdk
:page-description: Use REST API SDKs to call APIs in a language-specific way.

ThoughtSpot provides native SDK libraries to help client applications call REST APIs in a specific language format.

Currently, the REST API client libraries are available for xref:rest-api-sdk-typescript.adoc[TypeScript] and xref:rest-api-java-sdk.adoc[Java]. These SDKs provide language-specific client libraries to call APIs from client applications.

== Additional resources

For more information about REST APIs, use the following resources:

* For information about supported authentication types, see xref:authentication.adoc[REST API v2 authentication].
* Browse through the +++<a href="{{navprefix}}/restV2-playground">REST API v2 Playground</a>+++ before you start constructing your API requests. The playground offers an interactive portal with comprehensive information about the API endpoints, request and response workflows.
* For information about supported API endpoints, see xref:rest-api-v2-reference.adoc[REST API v2 reference].
* For information about new and deprecated features and enhancements, see xref:_rest_api_v2_0_changelog[REST API v2 Changelog].
