= REST API v2 SDK
:toc: true
:toclevels: 1

:page-title: REST API SDK
:page-pageid: rest-api-sdk
:page-description: ThoughtSpot provides REST API SDK with TypeScript client libraries.

ThoughtSpot provides native SDK libraries to help client applications call REST APIs in a specific language format.

Currently, the REST API client libraries are available for TypeScript. This client library includes classes that correspond to the resource elements and data types that the API uses when processing requests and responses.

For more information about the TypeScript SDK and its usage, see xref:rest-api-sdk-typescript.adoc[TypeScript SDK].


== Additional resources

For more information about REST APIs and REST API SDK, use the following resources:

* For information about supported authentication types, see xref:authentication.adoc[REST API v2 authentication].
* Browse through the  +++<a href="{{navprefix}}/restV2-playground">REST API v2 Playground</a>+++ before you start constructing your API requests. The playground offers an interactive portal with comprehensive information about the API endpoints, request and response workflows.
* For information about supported API endpoints, see xref:rest-api-v2-reference.adoc[REST API v2 reference].
* For REST API SDK libraries, go to the link:hhttps://github.com/thoughtspot/rest-api-sdk[REST API SDK GitHub repository, window=_blank].
* For information about new and deprecated features and enhancements, see xref:_rest_api_v2_0_changelog[REST API v2 Changelog].

