= REST API v2.0 groups/search endpoint
:toc: true
:toclevels: 2

:page-title: Using REST API V2.0 groups/search endpoint
:page-pageid: rest-apiv2-groups-search
:page-description: Many use cases are possible with the V2.0 groups/search endpoint

== Overview
`link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fgroups%2Fsearch-user-groups[/groups/search, target=_blank]` is used to retrieve details about ThooughtSpot groups (often referred in the API as user groups or with the `USER_GROUP` value), with many specific filtering capabilities for answering a number of relevant questions about groups.

You can search for the `USER_GROUP` type using `metadata/search`, but `groups/search` provides considerably more control.

The overall structure of `groups/search` request is link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fapi-rest-20-groups-search-request[described as a combination of objects, target=_blank].

Remember: many parameters in the request are *optional*, and leaving the parameter name out entirely has a different effect from including the parameter and specific values.

Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown: 

[source,javascript]
----
{
  "record_offset" : 0,
  "record_size": 100000
}
----

== Response format
The response from any call to `groups/search` will resemble the following:

[source,javascript]
----
[
  {
    "author_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "complete_detail": true,
    "content": NULL,
    "creation_time_in_millis": 1354006445722,
    "default_liveboards": [],
    "deleted": false,
    "deprecated": false,
    "description": NULL,
    "display_name": "System Management Group",
    "external": false,
    "generation_number": 867825,
    "hidden": false,
    "id": "179d8867-cf36-4a8d-a019-63a226fd3196",
    "index": 3,
    "index_version": 867825,
    "metadata_version": 0,
    "modification_time_in_millis": 1354006445722,
    "modifier_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "name": "System",
    "orgs": NULL,
    "owner_id": "59481331-ee53-42be-a548-bd87be6ddd4a",
    "parent_type": "GROUP",
    "privileges": [],
    "sub_groups": [],
    "system_group": true,
    "tags": [],
    "type": "LOCAL_GROUP",
    "users": [
      {
        "id": "67e15c06-d153-4924-a4cd-ff615393b60f",
        "name": "nick.cooper"
      },
      ...
    ],
    "visibility": "SHARABLE",
    "roles": null
  }
...
]
----

== Lists of metadata
`/groups/search` performs listing functions when you do not send specific object IDs as part of your request. Note you must send some request in the body of the POST, even if this is only `{ }`.

The basic metadata selectors are placed in the `metadata` parameter as an array of link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-list-item-input[Metadata List objects, target=_blank]. 

For example, to see *all groups*, you can simply send the `record_offset` and `record_size` parameters:

[source,javascript]
----
{
  "record_offset": 0,
  "record_size": 100000
}
----

== Retrieve specific objects
There are several parameters that allow referencing a user object directly. 
  
`group_identifier` takes either the **group name** or **group GUID**:

[source,javascript]
----
{
 "group_identifier" : 'Marketing Team'
}
----

`display_name` instead checks against the visible display name that shows within the ThoughtSpot UI.

`description` is also available as a filtering parameter.

== Filtering and sorting

=== sort_options
The `sort_options` parameter takes a link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fenumerations%2Ffield-name[Users Search Sort Options, target=_blank] object allowing for sorting on one field of the metadata response either **ASC** or **DESC**:

[source,javascript]
----
{
 "sort_options" : {
  "field_name": "DISPLAY_NAME",
  "order": "ASC" 
 }
}
----

If you need multiple levels of sorting, you'll have to parse the response programmatically and apply a sorting algorithm on the properties within each response item.

=== group_identifiers
You can filter responses based on which groups the user belongs to.

This replaces some of the individual `groups` endpoints in the V1 REST API, such as the xref:group-api.adoc#get-users-group[get a list of users assigned to a group] endpoint. 

The `group_identifiers` parameter takes an array of strings of either **group name** or **group GUID**. Note that groups have a `display_name` property separate from **group_name** that cannot be used in the `group_identifiers` array.

[source,javascript]
----
{
 "group_identifiers" : [
    "Developers"
  ]
}
----

=== privileges
Responses can be filtered based on **privileges** assigned to the user. Privileges are assigned through groups or roles rather than directly to a user, but the `users/search` endpoint is able to search the set of privileges the user currently has.

The array of privileges works as an OR condition, returning any user with any of the privileges listed. If you need know who has a set of privileges, you'll have to check the `privileges` array for each user object in the response.

[source,javascript]
----
{
 "privileges": [
    "DEVELOPER",
    "DATADOWNLOADING"
  ]
}
----

=== visibility
Every user has a `visibility` property which can either be `SHARABLE` or `NON_SHARABLE`. A `SHARABLE` user can have content shared directly to them by other users who belong to the same sharable group. In multi-tenanted situations, it is most common to have users set to `NON_SHARABLE` so that individual usernames are never revealed to any other users.

You can list out users with a specific visibility setting by specifiying the `visibility` property in the request:

[source,javascript]
----
{
 "visibility": "SHARABLE"
}
----

=== account_type and account_status
The `account_type` property tracks which SSO method was used to create a given user. There are many values, but the main options are `LOCAL_USER`, `SAML_USER` and `OIDC_USER`. 

The response can be filtered to just users created from a particular method using the `account_type` parameter on the request:

[source,javascript]
----
{
 "account_type": "SAML_USER"
}
----

The `account_status` parameter is also available for filtering, but the majority of users are listed as `ACTIVE` and the other avaialble states are not relevant at this time.

=== home_liveboard_identifier
The `home_liveboard_identifier` parameter filters to users with a specific Liveboard set as their "home" Liveboard. The value can take the GUID of a Liveboard or its name, but because Liveboard names are not guaranteed to be unique, it is best to use a GUID of a specific Liveboard when using this filtering parameter:

[source,javascript]
----
{
 "home_liveboard_identifier": "a1fdcb4d-9cf9-466b-b866-22c53db9b1ac"
}
----

=== org_identifiers
On a ThoughtSpot instance where orgs has been enabled, a user can belong to multiple orgs. 

The `org_identifiers` parameter takes an array of strings representing either org names or the string version of the org_id, which is an integer.

As with other filtering parameters that take arrays, the list of identifiers is handled as a logical OR, returning any users who belong to any of the provided identifiers. To filter to a user with a particular set of orgs, you will need to do additional processing on the result set to confirm the full set of orgs matches:

[source,javascript]
----
{
 "org_identifiers": [
   "Dev",
   "UAT"
 ]
}
----

The `orgs` key of each user item in the response contains the details of the orgs, which can be read and compared to the set of orgs you want to match for that user:

[source,javascript]
----
...
"orgs":[
  {
    "id": 1568202965,
    "name": "Dev"
  }, 
  {
    "id": 2004448319,
    "name": "Secondary"
  }
]
...
----

Note that the org `id` is an integer in this portion of the response. 

=== role_identifiers
On ThoughtSpot instances with roles enabled, you can use the `role_identifiers` parameter to send an array of either GUID or name of the roles that a user has access to.

=== Additional optional boolean filters
`notify_on_share`, `show_onboarding_experience` and `onboarding_experience_completed` are all available as boolean filters to see only users who either have or haven't used a given feature.

Note that the *absence* of the parameter is how you remove the filtering. If the parameter value is present as a key, the value must be set to `true` or `false` and thus the response will be filtered to only those users who match the condition.

== Additional response details
There are a number of parameters that add new data to the response, allowing the `metadata/search` endpoint to answer questions that required multiple endpoints in the V1 REST API.

=== include_favorite_metadata
The `user` object in the response always includes a `favorite_metadata` key, but it will always be an empty array unless the  `include_favorite_metadata` parameter is added to the request set to `true`:

[source,javascript]
----
{
 "user_identifier": "bryant.howell",
 "include_favorite_metadata": true
}
----

The response will now have metadata objects in the array for the `favorite_metadata` key if the user has favorited any content, contained the `id`, `name` and `type` of the content, which is enough to create a listing in an embedding web app's UI that can load the content:

[source,javascript]
----
"favorite_metadata":[
  {
    "id": "8838d9fc-e56d-4467-859f-1ab9364eb139"
    "name": "Procurement / Supplier 365"
    "type": "LIVEBOARD"
  }
  ...
]
----



