
= REST API v2.0 metadata endpoints
:toc: true
:toclevels: 1

:page-title: Using REST API V2.0 metadata endpoints
:page-pageid: rest-apiv2-metadata
:page-description: Many use cases are possible with the very flexible REST API v2.0 metadata endpoints

The metadata endpoints, in particular those that end in `/search`, have very flexible request formats that solve a number of use cases. 

Some capabilities that have separate endpoints in the V1 REST API are done using the correct request on the smaller subset of metadata `/search` endpoints in V2.0.

Remember: many parameters in the requests are *optional*, and leaving the parameter name out entirely has a different effect from including the parameter and specific values.

Throughout this article, requests and responses will be shown as JSON, without any of the code to send the requests. The V2.0 Playground generates requests that always include the default values for any parameters that have them, but this article excludes them. Assume every request you see has the following parameters in addition to what is shown: 

[source,javascript]
----
{
  "record_offset" : 0,
  "record_size": 100000
}
----

== /metadata/search
`link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fsearch-metadata[/metadata/search, target=_blank]` is the most versatile of all of the metadata endpoints. It can be used to search for lists, or to retrieve back very detailed information about specific objects.

It replaces `metadata/list`, `metadata/listobjectheaders`, `metadata/details` and `metadata/listvizheaders` from REST API V1.

The overall structure of `metadata/search` request is link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fapi-rest-20-metadata-search-request[described as a combination of objects, target=_blank].

=== Lists of metadata
`/metadata/search` performs listing functions when you do not send specific object IDs as part of your request. 

The basic metadata selectors are placed in the `metadata` parameter as an array of link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-list-item-input[Metadata List objects, target=_blank]. 

For example, to see *all liveboards*, you only send the a single Metadata List object with `type` parameter set to `LIVEBOARD`:

[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD"
    }
  ]
{
----

To match names against a pattern, you can use the `name_pattern` parameter, including % for wildcard purposes:
[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD",
      "name_pattern": "Standard %"
    }
  ]
}
----
You may still want to process the result set further within your programming language.

=== Retrieve specific objects
The `identifier` parameter allows referencing an object by name or by object GUID. 
  
Specific objects can be retrieved via the object GUID without specifying `type`:

[source,javascript]
----
{
 "metadata": [
    {
      "identifier" : "009d8d6c-5026-47a9-96d7-9e0f84896d17"
    }
  ]
}
----

You can specify one item by name using `identifier`, but you must include the `type` in this request:
[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD",
      "identifier" : "My Great Liveboard"
    }
  ]
}
----

The response to a `metadata/search` request takes the form of an array of link:https://try-everywhere.thoughtspot.cloud/v2/#/everywhere/api/rest/playgroundV2_0?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-search-response[Metadata Response Objects, target=_blank]:
[source,javascript]
----
"[
  {
    "metadata_id": "009d8d6c-5026-47a9-96d7-9e0f84896d17"
    "metadata_name": "New Liveboard"
    "metadata_type": "LIVEBOARD"
    "dependent_objects": null
    "incomplete_objects": null
    "metadata_detail": null
    "metadata_header": {...}
    "visualization_headers": null
    "stats": null
  },
  ...
]
----

The `metadata_header` key is always returned with values, regardless of the request. This section resembles the V1 REST API response from `metadata/list` and `metadata/listobjectheaders`.


=== Visualization headers from a Liveboard
The V1 REST API has an endpoint called `metadata/listvizheaders`, which receives the header details of all of the individual visualizations on a Liveboard.

In V2, the `include_visualization_headers` parameter adds the visualization headers to the response.

[source,javascript]
----
{
 "metadata": [
    {
      "identifier" : "009d8d6c-5026-47a9-96d7-9e0f84896d17"
    }
  ]
},
"include_visualization_headers": true
----

Note from above that the response to **every** request has the `visualization_headers` key, but the value will be `null` unless `include_visualization_headers` is `true` and the object type is `LIVEBOARD`.

`include_visualization_headers` adds the array of visualization headers for every element in the response, so you can request a list of all Liveboards and all the visualizations on those Liveboards all at once.

=== sort_options
The `sort_options` parameter takes a link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fmodels%2Fstructures%2Fmetadata-search-sort-options[Metadata Search Sort Options, target=_blank] object allowing for sorting on one field of the metadata response either **ASC** or **DESC**:

[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD"
    }
  ]
},
"include_visualization_headers": true,
"sort_options" : {
  "field_name": "LAST_ACCESSED",
  "order": "ASC"
}
----

If you need multiple levels of sorting, you'll have to parse the response programmatically and apply a sorting algorithm on the properties within each response item.

=== include_details
The V1 REST API has an endpoint called `metadata/details` for retrieving a very large and complex object containing as much detail as possible about the requested object and its relationships with other objects within ThoughtSpot.

The `include_details` parameter of `metadata/search` request adds the equivalent details object to each element retrieved by `metadata/search` to the response under the `metadata_detail` key.

[source,javascript]
----
{
 "metadata": [
    {
      "identifier" : "009d8d6c-5026-47a9-96d7-9e0f84896d17"
    }
  ],
 "include_details" : true
}
----

The details of each object type is a complex object that is unique to each object type within ThoughtSpot. 

=== tag_identifiers
Thoughtspot objects can be assigned multiple **tags**, and the `/metadata/search` endpoint allows you to filter for items with a set of tags using the `tag_identifiers` parameter. 

Including multiple tags behaves as a logical **OR** operation, retrieving all content with **any** of the listed tags. 

[source,javascript]
----
{
 "metadata": [
    {
      "type": "LIVEBOARD"
    }
  ]
},
"tag_identifiers": [

]

----
