= RLS rules
:toc: true
:toclevels: 2

:page-title: RLS rules
:page-pageid: rls-rules
:page-description: RLS rules define data security directly on ThoughtSpot table objects

ThoughtSpot link:https://cloud-docs.thoughtspot.com/admin/data-security/about-row-security.html[Row Level Security Rules, window=_blank] define how the user's username or the names of the groups they belong  into WHERE clauses on the SQL queries generated. 

The two basic patterns for RLS Rules are *direct RLS rules* that reference a column on the table the rule is placed on and *ACL table rules* that reference a separate table of entitlements within the same database.

If neither of these patterns is easily implemented, please consider the xref:abac-user-properties.adoc[ABAC via tokens] method of RLS, available starting in ThoughtSpot 9.11.

== RLS rules overview
*RLS rules* are defined on table objects, and automatically extend to all worksheets, saved answers, and Liveboards based on that table, every time.

RLS rules are defined using either the *ts_username* variable or *ts_groups* variable. The RLS rules translate into WHERE clauses in any SQL query generated from that table object, with the variables expanding into the details of the signed-in user. *ts_groups* turns into the set of *group name* properties of the ThoughtSpot groups the user belongs to.


== Direct RLS rules
Rules that directly filter on column(s) that exist on every table - for example a customer_id on every row in a multi-tenanted data warehouse. 

A common RLS rule type pattern for a multi-tenanted data warehouse involves each user belonging to a *ThoughtSpot group* names to match the values in a 'customer name' or 'tenant name' column on every table. Alternatively, *username* can be used if the data is stored at an individual rather than tenant level.

== Access control list (ACL) table rules
Rules that reference a separate Access Control List (ACL) table of 'entitlements' for that user or the groups they belong to, which is then JOINed to other tables. 

RLS rules on one table object can reference other tables objects that are joined within a given connection. This allows for more a more complex RLS pattern to be used, where an "access control list" or "entitlements" table (*ACL table*) exists in the database, with a JOIN in ThoughtSpot to the fact or dimension tables. 

The RLS rule is defined on the fact or dimension table, but will reference the ACL table, typically by comparing *ts_username* variable against a column in the ACL table, which filters the ACL table's rows to only those defined for the user. The JOIN defined between the ACL table and the other tables then reduces down the rows to only those that match the remaining rows in the ACL table.

ACL table pattern is two-step logically: 

1. The ACL table of entitlements filters down to just the apropriate rows for the user, by comparing the username or the user's group membership to one column of the ACL table
2. Any number of the columns in the now reduced ACL table are INNER JOINed to other tables within the data model. This serves to filter the rows on the other tables to only those that match the rows in the ACL table for the user

The description above is entirely logical - each data warehouse will process the query in its own optimized way.

=== Updating the ACL table
In the ACL table pattern, the embedding web application must define a process for updating the ACL table in the data warehouse with the correct entitlement rows for each user. This is a separate process that does not involve ThoughtSpot, although it can be combined with the xref:trusted-authentication#authenticator-service-back-end[authenticator service] used for Trusted Authentication.

== Additional resources
A link:https://community.thoughtspot.com/customers/s/article/How-to-secure-your-data-in-ThoughtSpot[comprehensive examples and best practices guide to RLS, window=_blank] data model setup is available on the ThoughtSpot Community.
 
