= Runtime overrides
:toc: true
:toclevels: 1

:page-title: Runtime overrides
:page-pageid: runtime-overrides
:page-description: ThoughtSpot allows applying filters, updating Parameters, and sorting columns of a visualization on a Liveboard or Saved Answer.

You can apply filters and adjust Parameter values on ThoughtSpot Liveboards and Answers at load time.

=== Runtime filters

The runtime filters layer allows setting filter rules on Liveboards and Answers prior to load.

Developers can set runtime filters in the Visual Embed SDK for the following embed components:

* link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig[LiveboardEmbed]
* link:https://developers.thoughtspot.com/docs/Interface_SearchViewConfig[SearchEmbed]
* link:https://developers.thoughtspot.com/docs/Interface_AppViewConfig[AppEmbed]

After the object loads, runtime filters can be adjusted using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updateruntimefilters[HostEvent.UpdateRuntimeFilters] event.

For more information and examples, see xref:runtime-filters.adoc[Runtime filters].

== Runtime Parameters
Parameters allow users to visualize data by running different scenarios with adjustable values. You can use Parameters within formulas when analyzing your data via Search, Liveboards, or Answers.

Like runtime filters, Parameters can be applied on ThoughtSpot Liveboards and Answers prior to load. Developers can set runtime Parameters in the Visual Embed SDK for the following embed components:

* link:https://developers.thoughtspot.com/docs/Interface_LiveboardViewConfig[LiveboardEmbed]
* link:https://developers.thoughtspot.com/docs/Interface_SearchViewConfig[SearchEmbed]
* link:https://developers.thoughtspot.com/docs/Interface_AppViewConfig[AppEmbed]

After the object loads, Parameter values can be adjusted using the link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent#_updateparameters[HostEvent.UpdateParameters] event.

For more information and examples, see xref:runtime-parameters.adoc[Runtime Parameters].

