= Runtime overrides
:toc: true
:toclevels: 1

:page-title: Runtime overrides
:page-pageid: runtime-overrides
:page-description: ThoughtSpot allows applying filters, updating Parameters, and sorting columns of a visualization on a Liveboard or Saved Answer.

You can apply filters and adjust Parameter values on ThoughtSpot Liveboards and Answers at load time.

=== Runtime filters

xref:runtime-filters.adoc[Runtime filters] allows setting filter rules on embedded objects dynamically at runtime.

Developers can set runtime filters in the Visual Embed SDK for the following embed components:

* xref:LiveboardViewConfig.adoc[LiveboardEmbed]
* xref:SpotterEmbedViewConfig.adoc[SpotterEmbed]
* xref:SearchViewConfig.adoc[SearchEmbed]
* xref:AppViewConfig.adoc[AppEmbed]

After the object loads, runtime filters can be xref:runtime-filters.adoc#_adjust_runtime_filters_using_sdk_events[adjusted using the SDK events].

WARNING: The SDK processes at most 49 entries per embed. Any objects at index 50 or
beyond are silently dropped without an error or warning. See
xref:runtime-filters.adoc#_maximum_filter_count[Runtime filter limit] for
more information.


== Runtime Parameters
Parameters allow users to visualize data by running different scenarios with adjustable values. You can use Parameters within formulas when analyzing your data via Search, Liveboards, or Answers.

Like runtime filters, xref:runtime-parameters.adoc[Parameters] can be applied on ThoughtSpot objects at runtime. Developers can set runtime Parameters in the Visual Embed SDK for the following embed components:

* xref:LiveboardViewConfig.adoc[LiveboardEmbed]
* xref:SpotterEmbedViewConfig.adoc[SpotterEmbed]
* xref:SearchViewConfig.adoc[SearchEmbed]
* xref:AppViewConfig.adoc[AppEmbed]

After the object loads, Parameter values can be link:runtime-parameters.adoc#_adjust_parameter_values_using_sdk_events[adjusted using the SDK events].


