= Search data API
:toc: true
:toclevels: 2

:page-title: Search Data API
:page-pageid: search-data-api
:page-description: Search Data API

To construct a search query string and retrieve data from ThoughtSpot programmatically, use the `/tspublic/v1/searchdata` REST API.

== Supported operations

include::{path}/search-api-list.adoc[]

== Required permissions

You must have view access to the data source objects to run a search query.

== Search query

include::{path}/search-query-string.adoc[]

== How to search data using the API

To query data using the API, follow these steps:

[#get-guid]
=== Determine the GUID of the data source

To find the GUID of the Model, View, or Table, use one of the following methods:

Get data object GUID via API::

Send an API request to the `/api/rest/2.0/metadata/search` v2 API endpoint with the following parameters in the metadata array: +

+
.**Example**
[source,JSON]
----
 "metadata": [
    {
      "identifier": "my_data_model",
      "type": "LOGICAL_TABLE"
    }
  ]
----

+
If you don't know the exact name of the data source object, specify the metadata `type` as `LOGICAL_TABLE` in your API request, and then copy the GUID of the data object from the API response.

Find the GUID of the data object via UI::
. Log in to your ThoughtSpot application instance:
. Navigate to *Data*.
+
----
https://<your-thoughtspot-instance>/#/data/tables/
----
. On the **Data** > **Home** page, select the data object. For example, if the data source object is a Model, click **Models** and then open the Model.
. In the address bar of the web browser, note the GUID of the data source object.  For example, in the following address string, the GUID is `9d93a6b8-ca3a-4146-a1a1-e908b71b963f`:
+
----
https://<your-thoughtspot-instance>/#/data/tables/9d93a6b8-ca3a-4146-a1a1-e908b71b963f
----
. Copy the GUID.

=== Run the search query

. In another browser, navigate to the following address:

+
----
https://<your-thoughtspot-instance>/external/swagger/#!/tspublic%2Fv1/searchData
----

. Click `**POST** /tspublic/v1/searchdata`

. Specify values for request parameters. For more information, see xref:search-data-api.adoc#search-data-api-ref[Search data API reference].

. Click **Try it out**, and note the results.

+
You can also verify if the query returns the same data when you run it in the ThoughtSpot UI search bar (with slightly different syntax).

[#search-data-api-ref]
== Search data API reference

[NOTE]
====
The search data API allows you to pass the search query string as query parameters in the URL. Therefore, ThoughtSpot recommends that you append the query string to the URL, instead of using the `-d <data>` option to pass these parameters in your cURL requests.
====

==== Browser locale

The search data API supports the search query string or keywords in `en-US` language only. Due to this, your browser locale must be set to `en-US` for a successful API call. ThoughtSpot recommends that you set the locale to `en-US` in the HTTP header request.

----
Accept-Language: en-US
----

When making REST API call from a browser, you can set the Accept-Language header directly to override the browser locale for that request.

[source,javascript]
----
// Using XMLHttpRequest
var xhr = XMLHttpRequest();
xhr.setRequestHeader('Accept-Language', 'en-US');
// ...

// Using Fetch
const fetchOptions = {
    method: 'POST',
    headers: {
      'Accept-Language': 'en-US',
      'Content-Type': 'application/json',
      // ...
    },
    // ...
}
----

=== Resource URL
----
POST /tspublic/v1/searchdata
----

=== Request parameters

[width="100%", cols="2,2"]
[options='header']
|====================
| Query parameter | Description
|`query_string` |__String__. The data search query string. For more information, see xref:search-data-api.adoc#components[Components of a search query].

|`data_source_guid` |__String__.  The GUID of the data source, either a Model, a View, or a table.

|`batchsize`  |__Integer__. The batch size for loading search objects.

The system default is -1.
| `pagenumber` | __Integer__. An alternate way to set offset for the starting point of the search results returned from the query. The default value is `-1`.

`indexingOffset = (pageNumber - 1) * batchSize`

| `offset` |__Integer__. Attribute to offset the starting point of the search results returned from the query.  Specify a 1-based offset. The default value is `-1`.

| `formattype` |__String__. The format of the data.

Valid values are `COMPACT` or `FULL` JSON. The default value is `COMPACT`.
|====================

=== Example requests

.cURL (COMPACT)
[source, cURL]
----
curl -X POST \
--header 'Accept-Language: en-US' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT'
----

.cURL (FULL)
[source, cURL]
----
curl -X POST \
--header 'Accept-Language: en-US' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'X-Requested-By: ThoughtSpot' \
'https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=FULL’
----

.Request URL (COMPACT)
[source, html]
----
https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT
----

.Request URL (FULL)
[source,html]
----
https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/searchdata?query_string=%5Bsales%5D%20%5Bstore%20region%5D&data_source_guid=06517bd1-84c0-4bc6-bd09-f57af52e8316&batchsize=-1&pagenumber=-1&offset=-1&formattype=FULL
----

=== Example response

The data the API response contains four components:

. The `columnNames` array that contains a list of all column headers.
. The `data` array that contains a list of sub-arrays. Each sub-array represents a new row of data.
. A sampling ratio.
+
The sampling ratio tells you the percentage of total data returned.
A sampling ratio of `1` indicates that all the data in the Answer object was returned in the API response.

[source,JSON]
----
{
  "columnNames": [
    "Store Region",
    "Total Sales"
  ],
  "data": [
    [
      "east",
      18934491.05134509
    ],
    [
      "midwest",
      29157090.327609923
    ],
    [
      "south",
      25484693.074720126
    ],
    [
      "southwest",
      34241076.52103955
    ],
    [
      "west",
      30848491.458509445
    ]
  ],
  "samplingRatio": 1,
  "totalRowCount": 5,
  "rowCount": 5,
  "pageSize": 100000,
  "offset": 0
}
----

=== Response codes

[options="header", cols="1,2"]
|===
|HTTP Code|Description
|**200**|Successful retrieval of data from the data source
|**400**|Invalid query/data source
|===
