= Security settings
:toc: true

:page-title: Security settings
:page-pageid: security-settings
:page-description: Security settings for embedding


The **Security Settings** page in ThoughtSpot UI allows administrators and developers to configure Content Security Policy (CSP), Cross-origin resource sharing (CORS), authentication, and access control settings.

[NOTE]
====
The following settings on the **Security Settings** page appear as locked for ThoughtSpot Analytics application users. These settings apply to ThoughtSpot embedding and require an embedding license:

* xref:security-settings.adoc#csp-viz-embed-hosts[CSP visual embed hosts]
* xref:security-settings.adoc#cors-hosts[CORS whitelisted domains]
* xref:security-settings.adoc#_block_access_to_non_embedded_thoughtspot_pages[Block non-embed full app access]
* xref:configure-saml.adoc#saml-redirect[SAML redirect domains]
* xref:trusted-authentication.adoc[Trusted authentication]
====

== Security settings for ThoughtSpot embedding

Most web browsers block cross-site scripting, cross-domain requests, and third-party cookies by default. Web browsers also have built-in security mechanisms like same-origin and content security policies. These policies restrict how applications and scripts from one origin (domain) can interact with the resources hosted on another origin (domain). For embedded content and data security and to provide seamless user experience, configure the settings described in this section.

=== Third-party cookies
When ThoughtSpot is embedded in another application, it is considered a third-party application in the host application context. As a result, cookies from ThoughtSpot are blocked by Web browsers.

To avoid this issue, ThoughtSpot recommends the following:

* Use cookieless authentication in your production environments. Developers can use either xref:embed-authentication.adoc#embedSSO[`AuthType.EmbeddedSSO`] or xref:trusted-auth-sdk.adoc[`AuthType.TrustedAuthTokenCookieless`] based on their embedding setup.
* If you are using a ThoughtSpot Cloud instance, set up your instance to the same domain as your host application. For more information, see link:https://docs.thoughtspot.com/cloud/latest/custom-domains[Custom domain configuration, window=_blank].
* If you are using authentication methods that rely on cookies, xref:_enable_partition_cookies[enable partition cookies].


== Add domains to CSP and CORS allowlists

To allow another application to embed ThoughtSpot, you must xref:security-settings.adoc#csp-viz-embed-hosts[add your host application domain as a CSP Visual Embed host].

To allow your embedding application to call ThoughtSpot, access its resources, and render embedded content, xref:security-settings.adoc#cors-hosts[add your host application domain URL as a trusted host for CORS].

To allow xref:security-settings.adoc#csp-connect-src[loading script interfaces and JavaScript events for custom actions], or xref:security-settings.adoc##csp-trusted-domain[to enable importing resources from other sites], add the source domain URLs as trusted hosts in the respective CSP allowlist.


[#csp-viz-embed-hosts]
=== Add CSP visual embed hosts
To allow your host domain to set the `frame-ancestors` CSP policy header and embed a ThoughtSpot object within your application frame, add your application domain as a CSP visual embed host.

. On your ThoughtSpot application instance, go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CSP visual embed hosts* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.

[NOTE]
====
Only users with a valid embed license can add Visual Embed hosts.
====

[#csp-connect-src]
=== Add URLs to CSP connect-src allowlist
If you plan to create custom actions with URL targets, you must add the domain names of these URLs to the `CSP connect-src` allowlist. This allows JavaScript events triggered by the custom action URLs.

. On your ThoughtSpot application instance, go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CSP connect-src domains* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.

=== Add trusted domains to CSP allowlists

To import images, fonts, and stylesheets from external sites, or load the content from an external site using an iFrame element, you must add the source URLs as trusted domains in the CSP allowlist.
For example, in the Liveboard Note tiles, if you want to insert an image from an external site or embed content from an external site in an iFrame, you must add domain URLs of these sites to the CSP allowList. Similarly, to import fonts and custom styles from an external source, you must add the source URL as a trusted domain in ThoughtSpot.

The following CSP settings are available on the ** Develop** > *Customizations* > *Security Settings* page:

* *CSP img-src domains* +
Add the domains from which you want to load images and favicons.
* *CSP font-src domains* +
Add the domains from which you want to load fonts.
* *CSP style-src domains* +
Add the domains from which you want to load stylesheets.
* *CSP frame-src domains* +
Add the iframe source URL domains.

[NOTE]
====
If your application instance has Orgs, the CSP settings can be configured only at the cluster level.
====

[#cors-hosts]
=== Enable CORS

The CORS configuration for your cluster controls which domains can access and modify your application content. To allow your application to call ThoughtSpot or its REST API endpoints, and request resources, you must add your application domain to the CORS allowlist. For example, if your website is hosted on the `example.com` domain and the embedded ThoughtSpot content is hosted on the `example.thoughtspot.com`, you must add the `example.com` domain to the CORS allowlist for cross-domain communication. You can also add `\http://localhost:8080` to the CORS allowlist to test your deployments locally. However, we recommend that you disable `localhost` access in production environments.

If you enable CORS for your application domain, ThoughtSpot adds the `Access-Control-Allow-Origin` header in its API responses when your host application sends a request to ThoughtSpot.

To add domain names to the CORS allowlist, follow these steps:

. On your ThoughtSpot application instance, go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CORS whitelisted domains* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.


[#csp-cors-hosts]
=== Domain name format for CSP and CORS configuration

[IMPORTANT]
====
[#port-protocol]
Note the following points if using port or protocol in the domain name string:

* The UI allows you to add a domain URL with or without the protocol (`http/https`) in the CSP allowlist. To avoid long URLs in the CSP header, we recommend that you don't include the protocol in the domain name string. However, for non-HTTPS domains, such as your local testing environment, do include `http` in the domain name string.
* Although you can add a domain URL with the protocol (`http/https`) to the CORS allowlist, ThoughtSpot ignores the protocol in the domain names of CORS hosts. Therefore, you can exclude the protocol in the domain name strings.
* If your domain URL has a non-standard port such as 8080, specify the port number in the domain name string.
* You can add multiple domain names to the CORS and CSP Visual Embed hosts list on the **Develop** > **Security Settings** page. Ensure that the CORS and CSP host allowlist does not exceed 4096 characters.
====

The following table shows the valid domain name strings for the CORS and CSP allowlists.

[div tableContainer]
--

[width="100%" cols="4,2,2,2,2"]
[options='header']
|====
|Domain name format|CSP Visual Embed host|CSP connect-src |CORS |CSP font-src +
CSP style-src +
CSP img-src

a|Domain URL strings without protocol


* `thoughtspot.com`
* `www.thoughtspot.com` +

|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported

a|Domain URL strings for localhost

* `localhost`
* `localhost:3000`
* `\http://localhost:3000`

|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported
a|Domain URL strings without port

* `thoughtspot.com`
* `mysite.com`

If your domain URL has a non-standard port, for example `mysite.com:8080`, make sure you add the port number in the domain name string.

|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported
|Wildcard (`*`) for domain URL|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported| [tag redBackground tick]#x# Not supported |[tag greenBackground tick]#✓# Supported
|Wildcard +++(*)+++ before the domain name extension +
`\https://*.com`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|Plain text string without the domain name extension. +

`thoughtspot`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|Domain name with wildcard (*) and a leading dot +

`+++.*.thoughtspot.com +++`

|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported a|[tag greenBackground tick]#✓# Supported +

__To avoid domain validation errors, make sure you add an escape character `\` after the wildcard in the domain URL string:__ +
`.*\.thoughtspot.com`
|[tag redBackground tick]#x# Not supported

a|Wildcard before the domain name +

`+++*+++.thoughtspot.com`

|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported |[tag redBackground tick]#x# Not supported|[tag greenBackground tick]#✓# Supported


a| Domain names with space, backslash (\), and wildcard (*).

* `www.+++*+++.+++*+++.thoughtspot.com` +
* `www.thoughtspot.com/*` +
* `thoughtspot  .com` +
|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|URLs with query parameters +
`\http://thoughtspot.com?2rjl6`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|URLs with path parameters +
`thoughtspot.com/products`|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported |[tag redBackground tick]#x# Not supported|[tag greenBackground tick]#✓# Supported
|URLs with path and query parameters +
`thoughtspot.com/products?id=1&page=2`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|IPv4 addresses +
`255.255.255.255`|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported
|Semicolons as separators +
`thoughtspot.com; thoughtspot.com;`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
|Comma-separated values +
`thoughtspot.com, thoughtspot.com`|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported
|`mail://xyz.com`|[tag redBackground tick]#x# Not supported|[tag redBackground tick]#x# Not supported 2*|[tag redBackground tick]#x# Not supported
a|+++Wildcard (*) for port+++

`thoughtspot:*`|[tag greenBackground tick]#✓# Supported|[tag greenBackground tick]#✓# Supported 2*|[tag greenBackground tick]#✓# Supported
|====
--

== Block access to non-embedded ThoughtSpot pages

If you have embedded ThoughtSpot content in your app, you may want your users to access only the ThoughtSpot pages embedded within the context of your host app.

If you have embedded ThoughtSpot using Visual Embed SDK v1.22.0 or later, the `blockNonEmbedFullAppAccess` property in the SDK is set to `true` by default. Due to this, your application users cannot access or navigate to the ThoughtSpot application experience outside the context of your app.

If you are not using Visual Embed SDK to embed ThoughtSpot, you can turn on the *Block non-embed full app access* feature on the *Develop* > *Customizations* > *Security Settings* page. This will restrict your users from opening non-embedded ThoughtSpot pages from their embedded app context. Note that this feature does not restrict ThoughtSpot users with administrator or developer privileges from accessing ThoughtSpot pages.

== Enable partitioned cookies
Many web browsers do not allow third-party cookies. If you are using authentication methods that rely on cookies, users will not be able to access the embedded content when browsers block third-party cookies. ThoughtSpot recommends using xref:trusted-auth-sdk.adoc[cookieless authentication] in production environments.

However, if your implementation uses cookie-based authentication or xref:embed-authentication.adoc#none[AuthType.None], ensure that you enable partitioned cookies:

. On your ThoughtSpot application instance, go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. Turn on the *Enable partitioned cookies* toggle switch.
. Click *Save changes*.

With partitioned cookies enabled, when a user logs in to ThoughtSpot and accesses embedded content on a host application, a cookie is set with the partitioned attribute. On browsers supporting partitioned cookies, the partitioned cookie will persist in the app after a successful login.

[IMPORTANT]
====
Safari blocks all third-party cookies and does not support partitioned cookies. You can switch to a different browser that supports partitioned cookies, or use cookieless authentication in your embedding implementation.
====

== Add permitted iFrame domains
Some features in ThoughtSpot, such as link:https://docs.thoughtspot.com/software/latest/liveboard-notes[Liveboard Note tiles, window=_blank], allow iFrame content. If you are planning to embed content from an external site, make sure the domain URLs of these sites are added to the iFrame domain allowlist:

. On your ThoughtSpot application instance, go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. In the *Permitted iFrame domains* text box, add the domain URL of the website or portal that you want to use for iFrame content.
. Click *Save changes*.

