= Security settings
:toc: true
:toclevels: 2

:page-title: Security settings
:page-pageid: security-settings
:page-description: Security settings for embedding

The **Security Settings** page in ThoughtSpot UI allows administrators and developers to configure allowlists for Content Security Policy (CSP) and Cross-origin Resource Sharing (CORS), authentication attributes, and access control settings.

== Overview
Most web browsers block cross-site scripting, cross-domain requests, and third-party cookies by default. Web browsers also have built-in security mechanisms such as same-origin and content security policies. These policies restrict how applications and scripts from one origin (domain) can interact with the resources hosted on another origin (domain). To ensure data security and a seamless user experience in embedding applications, configure the settings described in this section.

When ThoughtSpot is embedded in another application, it is considered a third-party application in the host application context. As a result, cookies from ThoughtSpot are blocked by Web browsers.

=== Third-party cookies
To avoid this issue, ThoughtSpot recommends the following:

* Developers can use either xref:embed-authentication.adoc#embedSSO[`AuthType.EmbeddedSSO`] or xref:trusted-auth-sdk.adoc[`AuthType.TrustedAuthTokenCookieless`] based on their embedding setup.
* If you are using a ThoughtSpot Cloud instance, set up your instance to the same domain as your host application. For more information, see link:https://docs.thoughtspot.com/cloud/latest/custom-domains[Custom domain configuration, window=_blank].
* If you are using authentication methods that rely on cookies, xref:_enable_partition_cookies[enable partition cookies].

== Security settings in ThoughtSpot

Users with administration privileges can configure security settings on the Security settings page of the ThoughtSpot UI. Note that the following settings on the **Security Settings** page will appear as locked for ThoughtSpot Analytics application users and will require an embedding license:

* xref:security-settings.adoc#csp-viz-embed-hosts[CSP visual embed hosts]
* xref:security-settings.adoc#cors-hosts[CORS whitelisted domains]
* xref:security-settings.adoc#_block_access_to_non_embedded_thoughtspot_pages[Block non-embed full app access]
* xref:configure-saml.adoc#saml-redirect[SAML redirect domains]
* xref:trusted-authentication.adoc[Trusted authentication]

=== Security settings for Orgs

On ThoughtSpot instances with Orgs, security settings can be managed at two levels:

* Global settings for all Orgs +
Cluster administrators can configure security settings globally for all Orgs. On ThoughtSpot instances with Orgs, the *Develop* page opens in the `Primary Org` context, unless you are accessing the Develop tab from a specific Org context. To configure settings for all Orgs, you must switch to *All Orgs* context.

* Org-level settings +
Cluster and Org administrators can configure security settings for a specific Org. Configuration modifications at the Org level do not affect other Orgs or the default settings applied at the All Orgs level.

The following table shows the settings available at the All Orgs and per-Org levels:

[width="100%" cols="5,7,7,7"]
[options='header']
|=====
||Configuration setting|All Orgs level |Per-Org level
.6+|CSP allowlists | **CSP visual embed hosts** a| [tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|**CSP connect-src domains** a| [tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|**CSP font-src domains**  a| [tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|**CSP img-src domains** a| [tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|**CSP style-src domains** a|[tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|**Permitted iFrame domains** a|[tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|CORS allowlist |**CORS whitelisted domains** a|[tag greenBackground tick]#Yes# a|
[tag greenBackground tick]#Yes#
|Embed access|**Block non-embed full app access** a|[tag greenBackground tick]#Yes# a|
[tag greenBackground tick]#Yes#
|Partitioned cookies | **Enable partitioned cookies** a|[tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|SAML SSO |**SAML redirect domains** a|[tag greenBackground tick]#Yes# a|
[tag redBackground tick]#No#
|Token-based authentication|**Trusted authentication** a|[tag greenBackground tick]#Yes# +
Can be used to authenticate users in any Org on the ThoughSpot instance. a|
[tag greenBackground tick]#Yes# +
Each Org can have a separate secret key, which can be used to authenticate users in that Org.
|=====


////
|**CSP frame-src domains** a| [tag greenBackground tick]#Yes# a| [tag redBackground tick]#No#
////

[NOTE]
====
* When security settings are defined at both levels, the Org-level settings take precedence over cluster-level settings within that Org.
* If the configuration settings are available at both levels and are configured only at the All Orgs level, the Orgs on the instance will inherit these settings.
* If the settings are not defined either at the All Orgs level or per Org, the system defaults will be applied.
====


== CSP allowlists

To allow another application to embed ThoughtSpot, you must xref:security-settings.adoc#csp-viz-embed-hosts[add your host application domain as a CSP Visual Embed host].

To allow xref:security-settings.adoc#csp-connect-src[loading script interfaces and JavaScript events for custom actions], or xref:security-settings.adoc##csp-trusted-domain[to enable importing resources from other sites], add the source domain URLs as trusted hosts in the respective CSP allowlist.

[NOTE]
====
If your instance has Orgs configured, note that the default Org on your instance is *Primary Org*. ThoughtSpot allows CSP settings only at the cluster level, so you must switch to the *All Orgs* context to configure CSP allowlists.
====

[#csp-viz-embed-hosts]
=== Add CSP visual embed hosts
To allow your host domain to set the `frame-ancestors` CSP policy header and embed a ThoughtSpot object within your application frame, add your application domain as a CSP visual embed host.

. On your ThoughtSpot application instance, go to *Develop* page.
. If your instance has Orgs, click the *All Orgs* tab.
. Go to *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CSP visual embed hosts* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.

[NOTE]
====
Only users with a valid embed license can add Visual Embed hosts.
====

[#csp-connect-src]
=== Add URLs to CSP connect-src allowlist
If you plan to use a custom action or webhook to send data to an external endpoint or application, you must add the domains of the target endpoints or applications to the `CSP connect-src` allowlist.

. On your ThoughtSpot application instance, go to *Develop* page.
. If your instance has Orgs, click the *All Orgs* tab.
. Go to *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CSP connect-src domains* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.

[#csp-trusted-domain]
=== Add other trusted domains

To import images, fonts, and stylesheets from external sites, or load the content from an external site using an iFrame element, you must add the source URLs as trusted domains in the CSP allowlist.
For example, in the Liveboard Note tiles, if you want to insert an image from an external site or embed content from an external site in an iFrame, you must add domain URLs of these sites to the CSP allowList. Similarly, to import fonts and custom styles from an external source, you must add the source URL as a trusted domain in ThoughtSpot.

. On your ThoughtSpot application instance, go to *Develop* page.
. If your instance has Orgs, click the *All Orgs* tab.
. Go to *Customizations* > *Security settings* and configure the settings: +

* *CSP img-src domains* +
Add the domains from which you want to load images and favicons.
* *CSP font-src domains* +
Add the domains from which you want to load fonts.
* *CSP style-src domains* +
Add the domains from which you want to load stylesheets.
* *CSP script-src domains*
Add the domains from which you want host scripts. For more information, see xref:3rd-party-script.adoc[Integrate third-party tools and allow custom scripts].

////
* *CSP frame-src domains* +
Add the iframe source URL domains.
////

=== Add permitted iFrame domains
Features such as link:https://docs.thoughtspot.com/software/latest/liveboard-notes[Liveboard Note tiles, window=_blank] and link:https://docs.thoughtspot.com/cloud/latest/chart-custom[custom charts, window=_blank] allow iFrame content. If you are planning to embed content from an external site, make sure the domain URLs of these sites are added to the iFrame domain allowlist:

. On your ThoughtSpot application instance, go to *Develop* page.
. If your instance has Orgs, click the *All Orgs* tab.
. Go to *Customizations* > *Security settings*.
. Click *Edit*.
. In the *Permitted iFrame domains* text box, add the domain URL of the website or portal that you want to use for iFrame content.
. Click *Save changes*.


[#cors-hosts]
=== Enable CORS

To allow your embedding application to call ThoughtSpot, access its resources, and render embedded content, add your host application domain URL as a trusted host for CORS.

The CORS configuration on your instance controls which domains can access and modify your application content. To allow your application to call ThoughtSpot or its REST API endpoints, and request resources, you must add your application domain to the CORS allowlist. For example, if your website is hosted on the `example.com` domain and the embedded ThoughtSpot content is hosted on the `example.thoughtspot.com`, you must add the `example.com` domain to the CORS allowlist for cross-domain communication. You can also add `\http://localhost:8080` to the CORS allowlist to test your deployments locally. However, we recommend that you disable `localhost` access in production environments.

If you enable CORS for your application domain, ThoughtSpot adds the `Access-Control-Allow-Origin` header in its API responses when your host application sends a request to ThoughtSpot.

To add domain names to the CORS allowlist, follow these steps:

. On your ThoughtSpot instance, navigate to the *Develop* page.
. If your instance has Orgs, you can configure CORS allowlists for all Orgs globally at the cluster-level or per Org. +

* For cluster-wide configuration, click the *All Orgs* tab.
* To configure settings at the Primary Org level, click the *Primary Org* tab.
* To configure CORS settings at the Org-level, switch the Org context via Org switcher in the top navigation bar.

. On *Develop* page, go to  *Customizations* > *Security settings*.
. Click *Edit*.
. In the *CORS whitelisted domains* text box, add the domain names. For valid domain name formats, See xref:security-settings.adoc#csp-cors-hosts[Domain name format for CSP and CORS configuration].
. Click *Save changes*.

[#csp-cors-hosts]
=== Domain name format for CSP and CORS configuration

[IMPORTANT]
====
[#port-protocol]

* You can add multiple domains to the CORS and CSP Visual Embed allowlists on the **Develop** **Customizations** > **Security Settings** page. Ensure that the CORS and CSP allowlists do not exceed 4096 characters.
* *Protocol in the domain URL*:
** CSP hosts — The UI allows adding a domain URL with or without the protocol (`http/https`). However, to avoid long URLs in the CSP header, you can exclude the protocol in the domain URL strings.
** CORS hosts — The UI allows adding a domain URL with the protocol (`http/https`). If the domain  URLs are using `https`, you can exclude the protocol in domain URL strings, because ThoughtSpot assigns `https` to the URLs by default.
** For localhost and non-HTTPS URLs — For non-HTTPs domains or localhost such as `localhost:3000`, if you add the domain without the protocol, the `https` protocol will be assigned to the URL by default. Due to this, the localhost domain with `http` (`\http://localhost:3000`) might result in a CSP or CORS error. Therefore, include the `http` protocol in the domain name strings for non-HTTPS domains and localhost.
* **Port**: If your domain URL has a non-standard port such as 8080, specify the port number in the domain name string.

====

The following table shows the valid domain name strings for the CORS and CSP allowlists.

[width="100%" cols="4,2,2,2,2"]
[options='header']
|====
|Domain name format|CSP Visual Embed host|CSP connect-src |CORS |CSP font-src +
CSP style-src +
CSP img-src

a|Domain URL strings without protocol

* `thoughtspot.com`
* `www.thoughtspot.com` +

|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported

a|Domain URL strings for localhost

* `localhost`
* `localhost:3000`
* `\http://localhost:8080`
* `\http://localhost:3000`

|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported
a|Domain URL strings without port

* `thoughtspot.com`
* `mysite.com`

If your domain URL has a non-standard port, for example `mysite.com:8080`, make sure you add the port number in the domain name string.

|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported
|Wildcard (`\*`) ,  (`.*`) for domain URL +
 |[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported a|[tag orangeBackground tick]#✓# Partial support +

__Supports only (`.*`)__ |[tag greenBackground tick]#✓# Supported
|Wildcard +++(*)+++ before the domain name extension +
`\https://*.com`|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  |[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported
|Plain text string without the domain name extension. +

`thoughtspot` |[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported# |[tag redBackground tick]#x# Not supported

|Domain name with wildcard (*) and a leading dot +

`+++.*.thoughtspot.com +++`

|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  a|[tag greenBackground tick]#✓# Supported  +

__To avoid domain validation errors, make sure you add an escape character `\` after the wildcard in the domain URL string:__ +
`.*\.thoughtspot.com`
|[tag redBackground tick]#x# Not supported

a|Wildcard before the domain name +

`+++*+++.thoughtspot.com`

|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  |[tag redBackground tick]#x# Not supported |[tag greenBackground tick]#✓# Supported


a| Domain names with space, backslash (\), and wildcard (*).

* `www.+++*+++.+++*+++.thoughtspot.com` +
* `www.thoughtspot.com/*` +
* `thoughtspot  .com` +
|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  2*|[tag redBackground tick]#x# Not supported
|URLs with query parameters +
`\http://thoughtspot.com?2rjl6`|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  2*|[tag redBackground tick]#x# Not supported
|URLs with path parameters +
`thoughtspot.com/products`|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  |[tag redBackground tick]#x# Not supported |[tag greenBackground tick]#✓# Supported
|URLs with path and query parameters +
`thoughtspot.com/products?id=1&page=2`|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  2*|[tag redBackground tick]#x# Not supported
|IPv4 addresses +
`255.255.255.255`|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported
|Semicolons as separators +
`thoughtspot.com; thoughtspot.com;`|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  2*|[tag redBackground tick]#x# Not supported
|Comma-separated values +
`thoughtspot.com, thoughtspot.com`|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported
|`mail://xyz.com`|[tag redBackground tick]#x# Not supported |[tag redBackground tick]#x# Not supported  2*|[tag redBackground tick]#x# Not supported
a|+++Wildcard (*) for port+++

`thoughtspot:*`|[tag greenBackground tick]#✓# Supported |[tag greenBackground tick]#✓# Supported  2*|[tag greenBackground tick]#✓# Supported
|====


== Block access to non-embedded ThoughtSpot pages
If you have embedded ThoughtSpot content in your app, you may want your users to access only the ThoughtSpot pages embedded within the context of your host app. ThoughtSpot allows administrators to restrict user access to non-embedded application pages from the embedding application context or selectively grant access to specific user groups. For information, see xref:selective-user-access.adoc[Control User Access].

== Enable partitioned cookies
Many web browsers do not allow third-party cookies. If you are using authentication methods that rely on cookies, users will not be able to access the embedded content when browsers block third-party cookies. Therefore, ThoughtSpot recommends using xref:trusted-auth-sdk.adoc[cookieless authentication] in production environments.

However, if your implementation uses cookie-based authentication or xref:embed-authentication.adoc#none[AuthType.None], ensure that you enable partitioned cookies:

. On your ThoughtSpot application instance, go to *Develop* page.
. If your instance has Orgs, click the *All Orgs* tab.
. Go to *Customizations* > *Security settings*.
. Click *Edit*.
. Turn on the *Enable partitioned cookies* toggle switch.
. Click *Save changes*.

With partitioned cookies enabled, when a user logs in to ThoughtSpot and accesses embedded content on a host application, a cookie is set with the partitioned attribute. On browsers supporting partitioned cookies, the partitioned cookie will persist in the app after a successful login.

[IMPORTANT]
====
Safari blocks all third-party cookies and does not support partitioned cookies. You can switch to a different browser that supports partitioned cookies, or use cookieless authentication in your embedding implementation.
====

== Trusted authentication
See xref:trusted-authentication.adoc[Trusted authentication] and xref:_secret_key_management[Secret key management].
