= Selective user access
:toc: true

:page-title: Selective user access
:page-pageid: selective-user-access
:page-description: Selective user access for TSE customers

With the current implementation, if you have embedded ThoughtSpot content in your app, your users can access only the ThoughtSpot pages embedded within the context of your host app.
There are cases when you want to give internal users the access to non-embedded content without giving them the admin or developer privilege. Selective user access facilitates this accessibility without posing any security risks.

The `blockNonEmbedFullAppAccess` property in the SDK is set to false by default. Once the flag is enabled, non-admins and non-developers won’t be able to log in into the ThoughtSpot cluster. Admins and developers will still be able to login.

To provide access to non-embed content for selective users:

. Go to *Security Settings*
. Click the *Edit* button > *Block non-embed full app access*
. Enable the *Block non-embed full app access* to true. It is false by default.
. Click on the now enabled *Advanced Settings*.
. Select the groups you want to allow access to ThoughtSpot pages through both the ThoughtSpot Cluster URL and the embedded context of your host app.
. Click *Save*
. Click *Save Changes*

Doing this will create a role for *Allow Full App Access* for the select group of users.

== Limitations
* This role is not visible via the *Admin* Section. Currently it cannot be edited through the APIs as well.
This role is only allowed to be assigned or removed through the *Security Settings* > *Block non-embed full app access* > *Advanced Settings*.

* If *Block non-embed full app access* is turned on in *All Orgs*, it will be applied to all the current orgs as well as to the newly created orgs.
// But the behavior won’t be toggled for the orgs for which this behavior was specifically changed.

* The *Advanced Settings* cannot be enabled at the *All Orgs* level. It is only visible inside the respective orgs.






