= Selective user access
:toc: true

:page-title: Selective user access
:page-pageid: selective-user-access
:page-description: Selective user access for TSE customers

If you have embedded ThoughtSpot content in your app, you may either want your users to access only the ThoughtSpot pages embedded within the context of your host app, or allow them to access the ThoughtSpot cluster without the administrator
 or developer privilege.

== Block access to non-embedded ThoughtSpot pages

If you have embedded ThoughtSpot using Visual Embed SDK v1.22.0 or later, the `blockNonEmbedFullAppAccess` property in the SDK is set to `true` by default. Due to this, your application users cannot access or navigate to the ThoughtSpot application experience outside the context of your app.

If you are not using Visual Embed SDK to embed ThoughtSpot, you can turn on the *Block non-embed full app access* feature on the *Develop* > *Customizations* > *Security Settings* page. This will restrict your users from opening non-embedded ThoughtSpot pages from their embedded app context. Note that this feature does not restrict ThoughtSpot users with administrator
or developer privileges from accessing ThoughtSpot pages.

== Challenge with complete access restriction
With the current implementation, if you have embedded ThoughtSpot content in your app, users can access only the ThoughtSpot pages embedded within the context of your host app.
Trying to give some users the ability to access the ThoughtSpot cluster requires to give every such user the administrator or developer privilege, which is not recommended.

There are cases when you want to give your internal users the access to embedded content via ThoughtSpot URL (not via embedded app) without giving them the administrator or developer privileges which pose security risks.
If a malicious user wants to access embed content via ThoughtSpot cluster (non-embedded route) they can check the iframe URL via network tab and access the content.

== Selective user access
With selective user access you can allow internal users to securely access non-embedded content without giving them the administrator or developer privilege. Users with administrator or developer privilege can add these users as part of groups only through the *Security Settings* page.

To provide access to non-embed content for selective users:

. Go to *Security Settings*
. Click the *Edit* button > *Block non-embed full app access*
. Enable the *Block non-embed full app access* to true. It is false by default.
. Click *Advanced Settings*.
. Select the groups you want to allow access to ThoughtSpot pages through both the ThoughtSpot Cluster URL and the embedded context of your host app.
. Click *Save*
. Click *Save Changes*

Doing this will create a role for *Allow Full App Access* for the select group of users. Users assigned this role via a group will be able to access the ThoughtSpot cluster even when `blockNonEmbedFullAppAccess = TRUE` in the SDK, just like the users with administrator or developer privilege.

== Limitations
* This role is not visible via the *Admin* Section. Currently it cannot be edited through the APIs as well.
This role is only allowed to be assigned or removed through the *Security Settings* > *Block non-embed full app access* > *Advanced Settings*.

* If *Block non-embed full app access* is turned on in *All Orgs*, it will be applied to all the current orgs as well as to the newly created orgs.
// But the behavior won’t be toggled for the orgs for which this behavior was specifically changed.

* The *Advanced Settings* cannot be enabled at the *All Orgs* level. It is only visible inside the respective orgs.






