== Integrating Spotter into your own Chatbot

In this article we will use ThoughtSpot's https://github.com/thoughtspot/visual-embed-sdk[visual embed SDK] to add analytics and interactive data visualizations to your own chatbot. The full code written below is available at https://codesandbox.io/p/sandbox/bodyless-sample-doc-5q3dwr[codesanbox].

=== Install Visual embed SDK

 $ npm i @thoughtspot/visual-embed-sdk

=== Configure security and authentication

. Allowlist the application which will embed thoughtspot visualizations. Basically adding the correct CORS and frame-ancestors CSP. More details on how to do that https://developers.thoughtspot.com/docs/security-settings[here].
. Configure the authentication scheme which works best for your use case. Read https://developers.thoughtspot.com/docs/embed-auth[this guide], to help you choose. For the purpose of this article we will use `AuthType.None` and assume you are logged into your instance in a different Tab, as setting up the other scehmes are covered in https://developers.thoughtspot.com/docs/embed-auth[this article].

=== Get the data model

For this guide we assume that you have already connected your database, and created a ThoughtSpot data model. Please log into your instance to get the `id` of the model you want to use. In this article we use a https://try-everywhere.thoughtspot.cloud/#/everywhere[demo] Thoughtspot instance with a sample data model.

=== Initialize the SDK

[,js]
----
import {
  BodylessConversation,
  init,
  AuthType,
} from "@thoughtspot/visual-embed-sdk";

init({
  thoughtSpotHost: "https://<your-instance>.thoughtspot.cloud",
  authType: AuthType.None, // Or your authentication scheme.
});
----

=== Create a new conversation

To use the spotter conversational analytics, you start by creating a new conversation. This conversation holds the context to all messages sent to ThoughtSpot by your bot. This enables a truly conversational experience for your users.

[,js]
----
const conversation = new BodylessConversation({
    worksheetId: "<data-model-id>",
  });
----

=== Send messages and get interactive visualizations in response

Once you have a conversation, you would use it to send user messages to ThoughtSpot Spotter AI which will evaluate and generate data on your data model and send back the visualization.

[,js]
----
// Get the response from ThoughtSpot Spotter
const { container } = await conversation.sendMessage(message);

// Create a new DOM element, to host the visualization returned above.
const div = document.createElement("div");

// Add any styling you might want to this element.
div.classList.add("viz");
// Add the container of the visualization as contents to this dom element.
div.append(container);
// insert the DOM into your application.
app.insertAdjacentElement("beforeend", div);
----

=== That's all folks!

And, thats it! Super quick start on how to leverage Spotter embed APIs to integrate with your own chatbot. Look at the full https://codesandbox.io/p/sandbox/bodyless-sample-doc-5q3dwr[codesandbox] to see it in action in a dummy chatbot we created.
