= Spotter APIs
:toc: true
:toclevels: 2

:page-title: Spotter APIs
:page-pageid: spotter-api
:page-description: You can use Spotter REST APIs to receive Answers for your analytical queries sent through the conversational experience with ThoughtSpot.

The Spotter APIs support natural-language-driven analytics, context-aware and guided data analysis, and integration with agentic systems.

The key capabilities of the Spotter APIs include the following:

* Initiating and managing conversational sessions
* Processing natural-language queries and interpreting user intent
* Generating analytical responses, insights, and visualizations
* Decomposing complex user queries

Spotter manages conversation sessions, context tracking, and response generation for user-submitted queries. The Spotter APIs are designed for use in Spotter-driven analytics and also for agentic interactions within an orchestrated agent framework.

Spotter API operations require `CAN_USE_SPOTTER` privilege and at least view-level access to the underlying metadata entities referenced in the response.

== Supported API operations

For information about supported API operations, see the following pages:

* xref:spotter-classic-apis.adoc[APIs for Spotter classic workflow]
* xref:spotter-agent-apis.adoc[APIs for Spotter agent workflows]
* xref:spotter-nl-instructions.adoc[APIs for Spotter coaching and NL instructions]
* xref:spotter-agent-instructions.adoc[APIs for Spotter agent instructions]

== Locale settings for API requests

When using the xref:spotter-classic-apis.adoc#_generate_a_single_answer[Single Answer] and xref:spotter-classic-apis.adoc#_send_a_query_to_a_conversation_session[Send message] APIs, the locale used for API requests depends on your application's locale settings:

* If your application is set to "Use browser language", the API will use this locale to generate responses. To override this setting, you must explicitly include the desired locale code in the `Accept-Language` header of your API request. To ensure consistent localization, set the `Accept-Language` header in your API requests when relying on browser language detection, or configure the locale explicitly in the user profile settings in ThoughtSpot.
* If you have set a specific locale in your ThoughtSpot instance or user profile, the API uses this locale to generate responses, overriding the browser or OS locale.

== Per-user API rate limits

The following rate limits apply to Spotter agent APIs per user:

* A maximum of 10 conversation creation requests per minute.
* A maximum of 30 query messages to a conversation session per minute.

[width="100%" cols="2,2"]
[options='header']
|=====
|API endpoint| Rate Limit (per user, per minute)
|`/api/rest/2.0/ai/agent/conversation/create` |	10
|`/api/rest/2.0/ai/agent/conversation/{conversation_identifier}/send`| 30
|`POST /api/rest/2.0/ai/agent/conversation/{conversation_identifier}/send/stream` | 30
|`/api/rest/2.0/ai/agent/{conversation_identifier}/converse` [.version-badge.deprecated]#Deprecated# | 30
|`/api/rest/2.0/ai/agent/converse/sse` [.version-badge.deprecated]#Deprecated# | 30
||
|=====

If you are integrating these APIs in your environment, consider implementing a retry logic to handle the rate limit errors.

== Additional resources

* Visit the +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fgetting-started%2Fintroduction">REST API v2.0 Playground</a>+++ to view the API endpoints and verify the request and response workflows.
* For information about embedding Spotter in your app, see xref:embed-spotter.adoc[Embed Spotter].
* For information about MCP server, see xref:mcp-integration.adoc[MCP server integration].
