= SpotterCode for IDEs
:toc: true
:toclevels: 2

:page-title: SpotterCode integration gude
:page-pageid: SpotterCode
:page-description: This document provides a comprehensive, step-by-step approach to integrating SpotterCode with your IDE and use its tools and skills to get help with embedding a ThoughtSpot object.

ThoughtSpot SpotterCode enables AI agents in your integrated development environments (IDEs) to discover documentation lookup skills and assist developers in embedding ThoughtSpot content in their applications. Using the SpotterCode extension, developers can rapidly generate and build deployment-ready code in their applications.

[IMPORTANT]
====
SpotterCode is an add-on feature available with the link:https://www.thoughtspot.com/pricing[ThoughtSpot Analytics and ThoughtSpot Embedded offerings, window=_blank].

////
To enable the SpotterCode in your environment, you must have an active subscription to one of the following ThoughtSpot license plans:

* Enterprise Edition of ThoughtSpot Analytics
* ThoughtSpot Embedded subscription
////
If you have an active subscription, and you want to enable SpotterCode integration on your IDE, contact your ThoughtSpot Sales representative or ThoughtSpot Support.
====

== Overview
SpotterCode is a server-side integration layer that connects IDEs to a ThoughtSpot-hosted MCP server. It exposes a set of tools and documentation lookup skills to the agentic systems and provides access to ThoughtSpot SDK, API documentation, and code samples within the IDE. Developers can leverage these capabilities to obtain relevant guidance and let the agent in their IDE scaffold code that fits their project’s context and structure.

=== Key features
When SpotterCode is integrated with your IDE, it offers the following advantages:

* Empowers your IDE with documentation lookup skills to get the necessary information and guidance required to embed ThoughtSpot content and integrate ThoughtSpot REST API workflows in your projects.
* Accelerate embedding and integration of ThoughtSpot analytics into applications by providing code generation, SDK skills, and custom styling directly in the IDE.
- Enables developers to build context-aware and deployment-ready code tailored to their project structure, thereby reducing manual effort and errors.
- Reduces operational strain on development teams by providing boilerplate code, agentic  for embedding ThoughtSpot in your application.

=== Supported tools and skills
When the SpotterCode MCP server is integrated with your IDE, it exposes the following tools and skills to the AI agent on your IDE:

* `get-visual-embed-sdk-reference` +
A documentation lookup skill that enables the AI Agent on your IDE to access ThoughtSpot Visual Embed SDK documentation and code samples for embedding ThoughtSpot content. This skill is used when responding to user queries related to embedding and the Visual Embed SDK. For example, supported embedded types, authentication options, configuration schemas, customization settings, event hooks, and code samples.

* `get-rest-api-reference` +
The REST API lookup skill that enables access to REST API specification and SDKs, endpoints, request and response formats, authentication flows, assistance with CRUD operations on ThoughtSpot objects and metadata, API documentation, and REST API TypeScript and Java SDK.

* `get-developer-docs-reference` +
A documentation lookup skill to find information about embedding, UI customization and theming, deployment guidelines, security settings, best practices, and more.


////
* `get-sdk-docs` +
Searches and retrieves documentation for ThoughtSpot SDKs, including Visual Embed SDK and REST API SDK. The agent on your IDE uses this skill to get responses for user questions related to embedding, authentication options, customization settings, and REST APIs.  For example, when a user sends a natural language question about embedding ThoughtSpot, the AI agent on your IDE programmatically determines the `query` string and documentation `type`, invokes the `get-sdk-docs` skill, and returns responses from the Visual Embed SDK documentation.

* `get-code-example` +
Retrieves code example from ThoughtSpot SDKs. For example, when a user asks question on embedding Liveboard, the AI agent on your IDE determines the context programmatically and invokes `get-code-example` skill to retrieve code examples for embedding a Liveboard.

* `get-style-customization` +
Provides theming, styling, and customization guidance for ThoughtSpot UI and embeds. Supports changing colors, fonts, backgrounds, branding, and other visual elements using CSS variables, theme JSON, or the Visual Embed SDK. The skill can generate official `CustomVariables` code and styling examples for LiveBoard, Search, and Visualization embeds. This skill supports text queries, branding guidelines in PDF, and design mockup image and PDF.
+
For example, when a user sends instructions to change the button or background color of the embedded page, the AI agent on your IDE invokes this `get-style-customization` skill to generate the code with variables supported in the ThoughtSpot's CSS customization framework. If the user's instruction is match your host app's style, the theme properties and values are extracted from your codebase and applied to your embed.
////
==== Input schema of the skills

The input schema for the SpotterCode skills consists of the following parameters. Note that the values for these parameters are context-driven and are programmatically added by the AI agent orchestrating the workflows in your IDE.

* `query` +
A free-form string describing the user's request or question. This is used to determine the context and intent of the skill invocation. For example, "How do I listen for filter events in a Liveboard embed?"
* `version` +
The SDK version. By default, the latest version is used for generating responses.
* `topK` +
Number of relevant documents to return. Default is 5.
* `symbolName` +
Symbol name, such as `CustomCssInterface`, to set the scope of search.
* `apiName` +
API node to return in response. Used when the API node is known. Gets the fastest path to the request/response schema.
* `additionalDocs` +
Additional documentation to use in response. Used when you also want the client SDK guidance for Java or TypeScript alongside the REST API information.

////
Quick “which knobs to turn” guide
Not finding the right thing: make query more specific, increase topK.
Too much noise: make query more specific, decrease topK, or use symbolName / apiName.
Version mismatch concerns: set version explicitly.
Need SDK-client context for an API: set additionalDocs.

* `appThemeContext` +
This parameter in the `get-style-customization` input schema is used when a user sends the instruction to match the app's theme. It is an optional object containing extracted theme values such as `computedStyles`, `cssVariables`, `designTokens`, and `additionalContext`.
////

=== How it works

. A user starts a chat session with the IDE and asks a question seeking information or help with a specific action related to ThoughtSpot embedding, REST APIs, or the SDKs.
. The AI agent in your IDE processes the natural language input, determines the intent,  and finds the appropriate skills required to generate a response.
. The AI agent sends a structured MCP request, setting the context and input parameters to fetch the relevant information.
. Using the MCP skill, the AI agent retrieves information and examples for generating the response and provides them to the model.
. The model generates and returns a final response to the user.

=== Supported IDEs

The initial version of SpotterCode supports the following IDEs:

* Cursor AI
* Visual Studio Code with GitHub Copilot
* Claude Code

=== Limitations

* SpotterCode’s capabilities are limited to the features and parameters exposed by the current Visual Embed SDK, REST API, and ThoughtSpot Developer documentation.
* SpotterCode helps in generating code samples for the most common use cases. Development scenarios that require deeper customization and have highly specialized use cases may require manual intervention or additional coding.

== Integrate SpotterCode with your IDE
Before getting started with SpotterCode integration, ensure your environment meets the following prerequisites:

* Ensure that your IDE supports AI agentic workflows and chats. Ensure that your environment has the latest version of the IDE installed, and the AI models are enabled for use in chat sessions.
* Access to the MCP server configuration settings with the ability to add or modify server URL and other relevant properties.
* Access to the ThoughtSpot MCP Server that enables SpotterCode integration. To obtain the SpotterCode MCP Server URL for integration with your IDE, contact your ThoughtSpot Sales representative or ThoughtSpot Support.
* Node.js is required to run the MCP server and enable communication between Cursor and SpotterCode. Ensure that Node.js is installed in your environment. #version recommendations if any?#
* Access to the ThoughtSpot instance and its resources that you want to embed or access via the REST API.

=== Integrate SpotterCode with Cursor

. To add the MCP server URL to your Cursor settings, go to **Cursor Settings** > **Tools and MCP**. Cursor opens the `mcp.json` file.
. Add the SpotterCode MCP Server URL as a remote MCP server. For information about MCP server configuration and setup, refer to the link:https://cursor.com/docs/context/mcp[Cursor Documentation, window=_blank].
+
[source,JSON]
----
{
  "mcpServers": {
    "SpotterCode": {
      "url": "{SpotterCode-MCP_Server URL}"
    }
  }
}
----
. Click *Save* and close the `mcp.json` file. This will install the SpotterCode MCP server and tools for the AI models on Cursor to execute.
+
If the configuration is valid and successful, you'll see the SpotterCode MCP server in the list of **Installed MCP Servers** on the **Tools & MCP** page.

. To view the MCP tools, on the **Tools & MCP** page, click **Installed MCP Servers**. As you hover over each skill, you can view the description of the skill and supported parameters for agentic queries. You can also disable the MCP skills that you don't want the AI model to use.

+
[div videoContainer]
--
video::./images/cursor_mcp-skills.mp4[width=100%,options="autoplay,loop"]
--

=== Integrate SpotterCode with Visual Studio Code

Although you can configure the MCP server in Visual Studio Code, to start a chat session with the AI agent, you'll need GitHub Copilot or a similar extension.

To add an MCP Server to Visual Studio Code, you can use the Extensions view, the `MCP: Add Server` command via command palette, or directly edit the `mcp.json` file in your workspace configuration.

[source,JSON]
----
{
  "servers": {
    "SpotterCode": {
      "url": "{SpotterCode-MCP_Server URL}",
      "type": "http"
    }
  }
}
----

After you add the MCP server URL, the SpotterCode MCP server will be available in the Extensions view. For more information about MCP server configuration in Visual Studio Code, see link:https://code.visualstudio.com/docs/copilot/customization/mcp-servers[Visual Studio Code Documentation, window=_blank].

=== Integrate SpotterCode with Claude Code
To enable SpotterCode in Claude Code, you can add the SpotterCode MCP server URL using the `claude mcp add` command via Claude CLI. If you are using Claude Desktop, you can add the URL directly to the Claude configuration JSON file:

[source,JSON]
----
{
  "mcpServers": {
    "SpotterCode": {
      "url": "{SpotterCode-MCP_Server URL}",
    }
  }
}
----

For more information about adding MCP servers to Claude Code, see link:https://code.claude.com/docs/en/mcp[Claude Code Documentation, window=_blank].

== Verify the integration

To verify the integration:

. Open your application project in your IDE.
. Initiate a chat session by selecting the AI model. In your prompt, send a request for getting information about REST APIs or embedding.
+
In the following example, a chat session with Cursor AI is initiated using the instruction, "I want to embed a ThoughtSpot Liveboard in my React application. Use the available tools to get this information and generate the embed code". Notice how the AI agent uses the SpotterCode skills to get the required information:
+
[div videoContainer]
--
video::./images/cursor-chat-session.mp4[width=100%,options="autoplay,loop"]
--
. Analyze the chat response and review the code. If the responses are not accurate, check for errors and verify whether the Spotter MCP server is accessible and the MCP tools and skills are available to the AI agent in your IDE.
+
The following example shows how Cursor AI scaffolds the embed code using the SpotterCode skills. Notice that the AI agent identifies and lists the minimum configuration settings, such as the ThoughtSpot host URL, Liveboard ID, and authentication attributes, required to complete the embedding.

+
[div videoContainer]
--
video::./images/cursor-chat-session2.mp4[width=100%,options="autoplay,loop"]
--
. If you are prompted to provide additional information, specify these details to continue with the embedding as shown in the following example:

+
[div videoContainer]
--
video::./images/cursor-lb-embed.mp4[width=100%,options="autoplay,loop"]
--
. Notice how the embedding view is produced in a few seconds.
. Try additional prompts to customize and style your embed view.
. Iterate until the integration meets your requirements.

== Best practices and recommendations

SpotterCode enriches your development environment with documentation lookup skills and integrates them into your coding experience and agentic workflows.

When interacting with the AI agent on your IDE, we recommend the following guidelines:

* Provide clear, direct, and specific instructions. If you want a code sample as the output and nothing else, specify this in your prompt.
* Avoid multiple task requests in a single prompt. Break down your questions and precisely explain what you want.
* For best results, use ThoughtSpot terminology such as Liveboards, Spotter, and so on. To receive specific answers and narrow down your request, mention the SpotterCode skill in instructions. For example, "How do I embed a ThoughtSpot page in my app? Use the available SpotterCode tools and skills to get this information".
* Provide contextual information when asking for information or help with a specific action. For example, describe the end goal of the task and the end goal of the task. If an action needs to be carried out in a sequential manner, use numbered lists or bullet points to ensure that the AI agent completes the given task in the exact way you want it to.
* Thoroughly review each response. For better results, use the advanced AI models.
* Do not expose sensitive data to AI models.
* Provide additional details and clarifications in the next prompt if you are not getting the desired response.
* Do not rely on SpotterCode to infer business logic that isn’t explicitly defined in the documentation or the SDK.

== Prompt examples

For accurate and consistent responses, improve your prompts.

=== Embedding
The following table show a list of vague and clear prompt examples for embedding-related questions and tasks.

[width="100%" cols="4,4"]
[options='header']
|=====
|Vague prompt|Clear prompt
|How do I embed ThoughtSpot?| I want to embed full ThoughtSpot application in my app. Use the available tools to get this information and generate the embed code.
|I want to use ThoughtSpot in my app.| I want to embed a ThoughtSpot Liveboard in my React application. Use the available tools to get this information and generate the embed code.
|Show me how to use the SDK. | I want to embed ThoughtSpot Spotter Search and AI analytics in my application. Use the 'get-visual-embed-sdk-reference' and 'get-developer-docs-reference' tools to get the information and code samples.
|Give me code for embedding analytics. | Provide an example of embedding the full ThoughtSpot application using AppEmbed.
|How do I add Search? | How do I use the SearchEmbed component to embed a search page with a pre-selected data source?
a|
Tell me how to start the SDK in my app.

Show me how to use the SDK | How do I initialize the ThoughtSpot Visual Embed SDK in a React application?
|What is the embed code for Liveboard? a| Use the SpotterCode tools and generate the embed code for a Liveboard in a React application +
Give me a code sample for embedding a ThoughtSpot Liveboard using the Visual Embed SDK.
|How do I add a chart in my app?| How do I embed a single chart or table from a ThoughtSpot Liveboard in my application?
|How do I use runtime filters? | Show a code example for embedding a Liveboard with two runtime filters: one for 'Region' set to 'Midwest' and one for 'item type' set to 'Jackets', using the Visual Embed SDK.
|Add an event hook to Liveboard. | Generate a React component that uses the ThoughtSpot embed SDK to display a Liveboard and add an event to trigger filter updates.
|Can I customize the embed?| Fetch the documentation for the LiveboardEmbed class and summarize the available customization options.
a|How do I update my code? +

Update to new version
|Update my embed code using the latest Visual Embed SDK version and highlight any breaking changes from the documentation.
a| Show me an example with filters +

Add filters to my embed
a|
* List all supported runtime filter operators and provide code examples for each using the SDK.
* Show how to apply an OR condition in runtime filters for product names containing 'bag' or 'jackets' in the embed code.
* Explain how to embed a Liveboard with a date filter using epoch time format, and show a code sample.
|Give me code for embedding analytics | Provide a code snippet to embed Spotter and pass a search query string as a prop
a| Change the Liveboard layout +
Make my embed dynamic
a| Show how to customize the Liveboard breakpoint width and explain the impact. +
Show me how to customize the layout of charts in the embedded Liveboard.
|Add custom styles to buttons| Change the background color of the Call To Action (CTA) buttons in the embed view to Cerulean blue (#2A52BE).
|=====

==== REST APIs
The following table show a list of vague and clear prompt examples for REST APIs.

[width="100%" cols="4,4"]
[options='header']
|===
|Vague prompt|Clear prompt
|How do I get the dashboards via API| How do I get a list of my Liveboards via ThoughtSpot REST API?
a| Show me how to connect to the API +

Show me how to use the API a|
Show a cURL example for authenticating to ThoughtSpot REST API v2.0 using OAuth +

Generate a POST request to /api/rest/2.0/metadata/search, including required headers and body.
|How do I add a user using API? a|
How do I create a new user with admin privileges via REST API? Provide the endpoint, method, and sample payload.
|Get data from a chart via API| Generate a REST API request example to fetch data from a specific chart in a Liveboard.
|What do I need to include in my API request? | What headers are required for a REST API call to ThoughtSpot? List and explain each.
|How do I see new actions in my app? | How do get a list of custom actions added in my embed via REST API?
|===









