= Theme builder
:toc: true
:toclevels: 2

:page-title: Theme builder
:page-pageid: theme-builder
:page-description: Understanding how to use the theme builder

Theme builder is the application built to provide developers the graphical control of the CSS customization options available with the Visual Embed SDK.


== Changing and loading styles
* Open the https://developers.thoughtspot.com/docs/theme-builder[Theme Builder] application.
* Choose the desired embed component from the dropdown on the left panel. Currently, you can choose from Liveboard, Visualizations, Search page, and the full application experience.

<image here>

* You can further choose from the list of style customizations available. Click on the fields to choose an input.
<image and example with explanation here>
* Click *Load Changes* in the top-right corner, to apply the selected style edits.
* Alternatively, you can also choose *Realtime loading* checkbox in the top-right corner. If you choose this,
the iframe refreshes automatically on each customization with your selected input.

== JSON
You can directly edit the styles in JSON format by collectively adding values to the CSS variables.

* Click *Paste JSON* on the bottom of the left panel.
* A modal in JSON format will popup withe CSS variables and their current values. Edit the values in the JSON file.
* Click *Submit*. If there are no errors, a success message appears at the bottom left and the iframe refreshes with the applied JSON.

If you want to keep this JSON as a reference for your ThoughtSpot embed application,

* Click *Download JSON*
* If you want to copy the CSS variables and their corresponding values to a clipboard, click *Copy JSON*.
* If you want to save the JSON file, click *Download JSON*.



