= TML
:toc: true
:toclevels: 2

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files
// SOURCE: SCAL-307283, SCAL-317357

ThoughtSpot Modeling Language (TML) is a scriptable format developed by ThoughtSpot for exporting, modifying, and migrating metadata objects such as Models, Views, Tables, Liveboards, and Answers. TML files allow you to manage and version control these objects outside the ThoughtSpot UI, supporting workflows like bulk changes, migration between environments, and programmatic edits via REST API. Users can use link:https://docs.thoughtspot.com/cloud/latest/tml[TML] to model data and build analytics content in the test environment in a flat-file format, and then import and deploy it in their environments.

== Structure of a TML file

To work with TML files for Models, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects as a flat file in `.TML` format, modify, and subsequently upload the TMLs either to the same or a different cluster.

The TML syntax varies per object type. However, all TMLs follow a general pattern that allows programmatic edits. ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules.

See the following pages for the detailed syntax of TML files for each object type: +

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-collections[TML for Collections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for Joins, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor Alerts, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for Tables, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for Models, window=_blank] +
//* link:https://docs.thoughtspot.com/cloud/10.11.0.cl/tml-worksheets[TML for Worksheets, window=_blank]  +

For TML modification tips and recommendations, see xref:modify-tml.adoc[TML modification].


////
[NOTE]
====
Worksheets are deprecated in ThoughtSpot and replaced by Models.
====
////


== TML import and export via REST API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

* xref:tml-import.adoc[Import TML]
* xref:tml-export.adoc[Export TML]

== TML modification

Visit this page for detailed information on xref:modify-tml.adoc[TML modification].

== Limitations of working with TML files
There are certain limitations to the changes you can apply by editing a ThoughtSpot object through TML. Visit link:https://docs.thoughtspot.com/cloud/latest/tml#_limitations_of_working_with_tml_files[Limitations of working with TML files, window=_blank] for detailed information.

== Deployment and version control of TML objects
For information about version control and TML deployment, see the following pages:

* xref:version_control.adoc[Git integration and version control]
* xref:development-and-deployment.adoc[TML files from development to testing and production environments]

////
When embedding or deploying a third-party application in their environments, most organizations use defined practices at various stages of their SDLC process. Users typically use a version control system and CI-CD pipeline to push their .

ThoughtSpot instances act as a constantly running service, so deployment only involves publishing ThoughtSpot content, in the form of ThoughtSpot Modeling Language (TML) files to a given ThoughtSpot instance. The three traditional steps to building an SDLC process with ThoughtSpot are:

* Exporting TML objects into a source control system (Git, etc.)
* Altering copies of the TML files for the next stage/environment
* Importing the TML files into the new environment

But this changed with the link:https://developers.thoughtspot.com/docs/git-integration[Git integration] feature. ThoughtSpot now allows you to connect your deployment instance to a Git repository, push TML files to CI/CD pipelines, and deploy commits from your Git repository to your production environment.
However, ThoughtSpot’s Git integration does not support moving objects within the same Org or application instance. For example, it does not support moving objects in an environment where xref:multitenancy-without-orgs[multi-tenancy is implemented using groups].
////
