= TML
:toc: true
:toclevels: 2

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files

ThoughtSpot developed its own scriptable approach for exporting, enhancing, and migrating Worksheets, views, tables, Liveboards, Monitor alerts, and Answers.
Use link:https://docs.thoughtspot.com/cloud/latest/tml[TML, window=_blank] (ThoughtSpot Modeling Language) to modify a ThoughtSpot object in a flat-file format. Users can model data and build out sophisticated dashboards in the test environment, before deploying to all users.

== Structure of a TML file

To work with TML files for Worksheets, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects as a flat file in `.TML` format, modify, and subsequently upload the TMLs either to the same or a different cluster.

The TML syntax varies per object type. However, all TMLs follow a general pattern that allows programmatic edits. ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules.

See the following pages for the detailed syntax of TML files for each object type: +

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for Joins, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor Alerts, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for Tables, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-worksheets[TML for Worksheets, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for Models, window=_blank] +

For TML modification tips and recommendations, see xref:modify-tml.adoc[TML modification].


== TML import and export via REST API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

[NOTE]
====
If using older versions of TML files for Liveboards, ensure that your TML file has the object name as `liveboard`. Replace any `pinboard` occurrences with `liveboard` before import.
====

== Import TML
To import a modified TML object, your account must have the `DATAMANAGEMENT` (*Can manage data*) or `ADMINISTRATION` (*Can administer ThoughtSpot*) privilege.

You can import single or multiple objects using the `tml/import` API. If you are importing TML files one at a time, include the `fqn` property to distinguish objects that have the same name. If you have multiple connections or tables with the same name and the Connection or Table you reference in your TML does not have a unique name, it can lead to invalid object references. Adding `fqn` helps ThoughtSpot differentiate a Table from another with the same name.

By default, the `fqn` parameter is not present in the TML file. However, you can export TML with FQNs and use it during the import.

To import TML representation of the metadata objects into ThoughtSpot, use one of  the following API endpoints:

* `link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fimport-metadata-tml[**POST** /api/rest/2.0/metadata/tml/import]` (REST API v2)
* `xref:tml-api.adoc#import[**POST** /tspublic/v1/metadata/tml/import]` (REST API v1)

//While the v1 API accepts a string containing a JSON array of TML objects to upload, in YAML or JSON format, the v2 accepts it only in the JSON format.

There are multiple kinds of imports possible:

* `PARTIAL` imports all objects that validate successfully, and ignores objects that do not validate successfully.
* `ALL_OR_NONE` imports the objects that validate successfully.
* `VALIDATE_ONLY` validates the objects but does not import them.

You can also specify additional parameters to skip validation and diff checks, and define Org context for the import operation.

[NOTE]
====
If you import only a Worksheet object, it may take some time for the Worksheet to become available in the ThoughtSpot system. You may need to wait for a few seconds to create answers and Liveboards.

However, if you import a Worksheet along with Liveboards, answers, and other dependent objects in a single API call, the imported objects will be immediately available for use.
====

== Import TML objects asynchronously
The REST v1 and v2  `metadata/tml/import` APIs import TML objects synchronously. When you try to import large and complex metadata objects, the synchronous import operation takes more time to process data and sometimes can result in a timeout error.

To allow mutually exclusive import tasks to run in parallel and process TML objects asynchronously,  ThoughtSpot provides the `POST /api/rest/2.0/metadata/tml/async/import`. The async TML import API allows you to create TML import tasks and fetch task status via `POST /api/rest/2.0/metadata/tml/async/status`.

=== Schedule import tasks

You can import TML objects asynchronously by scheduling TML import tasks via `POST` request to POST `/api/rest/2.0/metadata/tml/async/import` API endpoint. You can send the following parameters in the API request body:

[width="100%" cols="2,4,1"]
[options='header']
|====
|Form parameter|Description| Default
|`metadata_tmls` |__Array of strings__. GUIDs of the metadata TML objects to import. |__None__
|`create_new`  +
__Optional__ |__Boolean__. To create TML objects with new GUIDs during import, specify `true`. By default, ThoughtSpot updates the existing objects that have the same GUID as the objects you are importing. | `false`
|`all_orgs_context` +
__Optional__ |__Boolean__. Specify if import operation must be run for all Orgs on your instance.

__Requires Org administration privileges to access TML objects across all Orgs.__| `false`

|`import_policy`  a|__String__. Policy to follow during import. The allowed values are:

* `PARTIAL` +
Imports objects that validate successfully. Skips the objects that do not validate successfully and their dependent objects if any.
* `ALL_OR_NONE` +
Imports all objects that validate successfully. If the import fails for one object, no objects will be imported.
* `VALIDATE_ONLY` +
Validates the objects but does not import them.
* `PARTIAL_OBJECT` +
Imports objects that validate successfully and skips the objects that do not validate successfully. If the import fails for a visualization object in a Liveboard TML, the Liveboard will be imported without that visualization object. Similarly, if importing a relationship in a logical table fails, the table TML will be imported with warnings in the API response.
| `PARTIAL_OBJECT`

|`skip_cdw_validation_for_tables` +
__Optional__ |__Boolean__. Skips Cloud Data Warehouse validation for table TML imports. | `false`
|`skip_diff_check` +
__Optional__ |__Boolean__. Skips diff check before processing TMLs for imports. |`false`
|`enable_large_metadata_validation` +
__Optional__ |__Boolean__. Enables validation for large metadata objects. |`false`
|====

==== Example request

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/metadata/tml/async/import'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "metadata_tmls": [
    "fa68ae91-7588-4136-bacd-d71fb12dda69",
    "e26e5de0-3e4f-4786-b563-103eed06c0f6"
  ],
  "create_new": true,
  "all_orgs_context": false,
  "skip_cdw_validation_for_tables": true,
  "import_policy": "PARTIAL_OBJECT",
  "skip_diff_check": false,
  "enable_large_metadata_validation": true
}'
----

==== Example response

If the API request is successful, ThoughtSpot schedules an import task, and returns the task name and ID in the API response:

[source,JSON]
----
{
  "tenant_id": "default-tenant-id",
  "org_id": 0,
  "task_id": "c8c8c4da-0bc8-4460-8039-cfa7fd598335",
  "task_name": "ASYNC_TML_26:Nov:2024-06:06:24",
  "import_response": null,
  "task_status": "IN_QUEUE",
  "author_id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
  "import_policy": "PARTIAL_OBJECT",
  "created_at": null,
  "in_progress_at": null,
  "completed_at": null,
  "total_object_count": 2,
  "object_processed_count": null,
  "modified_at": null
}
----

===== Response codes

[options="header", cols="1,4"]
|====
|HTTP status code|Description
|**200**|Async TML Import Task submitted successfully
|**400**|Invalid request
|**401**|Unauthorized access
|**403**|Forbidden access
|**500**|Unexpected Error
|====

=== Fetch status of the TML import task

To fetch the status of a scheduled import task, send a `POST` request to the `POST /api/rest/2.0/metadata/tml/async/status` API endpoint.

In the request body, include the following attributes:

[width="100%" cols="2,4,1"]
[options='header']
|====
|Form parameter|Description| Default
|`task_ids` |__Array of strings__. Task IDs assigned to the scheduled TML async import operations. | __None__
| `task_status` | __Array of strings__. Status of the scheduled import tasks to filter on. The following options are available: +

* `COMPLETED` +
* `IN_QUEUE` +
* `IN_PROGRESS` +
* `FAILED`
| __None__
|`author_identifier`  +
__Optional__ |__String__. GUID of the author who initiated the import request or the name assigned to the import task being queried. For example, `ASYNC_TML_26:Nov:2024-06:06:24`. | __None__
|`include_import_response` +
__Optional__  |__Boolean__. Specify whether to include import response in the task status objects.| `false`
|`record_offset` +
__Optional__ |__Integer__. The offset point, starting from where the task status should
be included in the response. | `0`
|`record_size` +
__Optional__ |__Integer__. The number of task statuses to include in the
response starting from offset position. | `5`
|====

==== Example request

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-host}/api/rest/2.0/metadata/tml/async/status'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "record_offset": 0,
  "record_size": 5,
  "include_import_response": true,
  "task_ids": [
    "c8c8c4da-0bc8-4460-8039-cfa7fd598335"
  ],
  "task_status": [
    "COMPLETED"
  ],
  "author_identifier": "95ac814f-eb01-4625-93c7-c7624b29d226"
}'
----

==== Example response

If the API request is successful, ThoughtSpot returns the status details of the TML async import tasks.
If Orgs are enabled on your instance, the API returns task status only for objects within the current Org context.

[source,JSON]
----
{
  "status_list": [
    {
      "tenant_id": "default-tenant-id",
      "org_id": 0,
      "task_id": "c8c8c4da-0bc8-4460-8039-cfa7fd598335",
      "task_name": "ASYNC_TML_26:Nov:2024-06:06:24",
      "import_response": {
        "object": [
          {
            "filename": "tml_0",
            "zip_filename": "zip_tml_0",
            "response": {
              "status": {
                "status_code": "ERROR",
                "error_message": "Invalid YAML/JSON syntax in file."
              }
            },
            "request_index": 0
          },
          {
            "filename": "tml_1",
            "zip_filename": "zip_tml_1",
            "response": {
              "status": {
                "status_code": "ERROR",
                "error_message": "Invalid YAML/JSON syntax in file."
              }
            },
            "request_index": 1
          }
        ],
        "status": {
          "status_code": "OK",
          "error_code": 0,
          "error_message": ""
        }
      },
      "task_status": "COMPLETED",
      "author_id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
      "import_policy": "PARTIAL_OBJECT",
      "created_at": 1732601184212,
      "in_progress_at": 1732601184255,
      "completed_at": 1732601184476,
      "total_object_count": 2,
      "object_processed_count": 2,
      "modified_at": 1732601184476
    }
  ],
  "last_batch": true
}
----

===== Response codes

[options="header", cols="1,4"]
|====
|HTTP status code|Description
|**200**|Async TML import task status fetched successfully
|**400**|Invalid request
|**401**|Unauthorized access
|**403**|Forbidden access
|**500**|Unexpected Error
|====

== Export a TML
To export the TML data, your account must have the `DATAMANAGEMENT` (Can manage data) or `ADMINISTRATION` (Can administer ThoughtSpot) privilege..

It must be noted that the default format to export the objects is YAML is v1, and JSON in v2 APIs. To export the TML representation of the metadata objects from ThoughtSpot in JSON or YAML format, use one of the  following endpoints:

* `link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fexport-metadata-tml[**POST** /api/rest/2.0/metadata/tml/export]` (REST API v2)
* `xref:tml-api.adoc#export[**POST** /tspublic/v1/metadata/tml/export]` (REST API v1)

To export the TML representation of the metadata objects in a *batch*, use one of the following endpoints:

* `link:https://developers.thoughtspot.com/docs/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fexport-metadata-tml-batched[**POST** /api/rest/2.0/metadata/tml/export/batch]` (REST API v2)
* `xref:tml-api.adoc#BatchExport[**POST** /tspublic/v1/metadata/tml/export/batch]` (REST API v1)

There are several export options available with these APIs:

=== Export associated objects

To export associated objects, set the following attributes:

* `export_associated` +
When set to `true`, exports the associated objects for the `export_ids` specified in the API request. The API exports any underlying worksheets, tables, or views for a given object. By default, the API does not export these underlying objects.
* `export_dependent` +
Specifies if the Tables of the referenced Connection object must be included in the export.
* `export_connection_as_dependent` +
Specifies if a Connection object must be included as a dependent object when exporting a Table, Worksheet, Answer, or Liveboard TML.

=== Export FQNs

When `export_fqn=true`, the API exports the FQNs of the referenced objects in the TML data. For example, if you are exporting a Liveboard and its associated objects, the API returns the Liveboard TML data with the FQNs of the referenced Worksheet.
Note that the FQN of a referenced object is the same as the GUID of that object.

ThoughtSpot recommends adding the fqn property before importing the TML objects into the system, because only the name of a referenced object is not sufficient to identify the referenced object during TML import. For example, if your ThoughtSpot instance has two worksheets with the same name, the TML import for a Liveboard that uses one of these worksheets would fail unless the Liveboard TML includes the FQN of the referenced Worksheet.
The `export_fqn` attribute is useful when ThoughtSpot has multiple objects with the same name and you want to eliminate ambiguity during TML import. The `export_fqn=true` property adds the FQNs of the referenced objects in the TML export API response and saves the manual effort of adding FQNs for TML import.

=== Export schema

Specifies the schema version to use during TML export. By default, the API request uses v1 schema for Worksheets. If you are using Models, set `export_schema_version` to v2. link:https://docs.thoughtspot.com/cloud/latest/models[Models] are supported as new datasets from 9.10.0.cl onwards.

=== Export in a batch
This API operation supports exporting User, User Group, and Role objects only.
To export objects in a batch, set the following additional attributes:

* `batch_size` +
Exports the specified number of objects in a single API request. A batch size of up to 200 objects is allowed for a single API operation.

* `batch_offset` +
Offsets the API response by the specified number. Batch offset value defines the starting position of the records for the results returned by the API.


Visit xref:tml-api.adoc[Export a TML object] for more information.

== TML modification

ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules. Visit this page for detailed information on xref:modify-tml.adoc[TML modification].

== Limitations of working with TML files
There are certain limitations to the changes you can apply by editing a ThoughtSpot object through TML. Visit link:https://docs.thoughtspot.com/cloud/latest/tml#_limitations_of_working_with_tml_files[Limitations of working with TML files, window=_blank] for detailed information.

== Deployment and version control of TML objects
For information about version control and TML deployment, see the following pages:

* xref:version_control.adoc[Git integration and version control]
* xref:development-and-deployment.adoc[TML files from development to testing and production environments]

////
When embedding or deploying a third-party application in their environments, most organizations use defined practices at various stages of their SDLC process. Users typically use a version control system and CI-CD pipeline to push their .

ThoughtSpot instances act as a constantly running service, so deployment only involves publishing ThoughtSpot content, in the form of ThoughtSpot Modeling Language (TML) files to a given ThoughtSpot instance. The three traditional steps to building an SDLC process with ThoughtSpot are:

* Exporting TML objects into a source control system (Git, etc.)
* Altering copies of the TML files for the next stage/environment
* Importing the TML files into the new environment

But this changed with the link:https://developers.thoughtspot.com/docs/git-integration[Git integration] feature. ThoughtSpot now allows you to connect your deployment instance to a Git repository, push TML files to CI/CD pipelines, and deploy commits from your Git repository to your production environment.
However, ThoughtSpot’s Git integration does not support moving objects within the same Org or application instance. For example, it does not support moving objects in an environment where xref:multitenancy-without-orgs[multi-tenancy is implemented using groups].
///

