= TML
:toc: true
:toclevels: 1

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files
ThoughtSpot developed its own scriptable approach for exporting, enhancing, and migrating Worksheets, views, tables, Liveboards, Monitor alerts, and Answers.
Use link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[TML, window=_blank] (ThoughtSpot Modeling Language) to modify a ThoughtSpot object in a flat-file format. Users can model data and build out sophisticated dashboards in the test environment, before deploying to all users.

== Structure of a TML file
To work with TML files for Worksheets, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.

See the following pages for the detailed syntax of each type of TML file:

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers]

* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections]

* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for joins]

* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards]

* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor alerts]

* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL views]

* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for tables]

* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for views]

* link:https://docs.thoughtspot.com/cloud/latest/tml-worksheets[TML for Worksheets]

* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for models]


== TML API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

[NOTE]
====
ThoughtSpot exports TML files with `liveboard` as the object name instead of `pinboard`. Older TML files with the `pinboard` object name can still be imported into ThoughtSpot instances on 8.9.0.cl release version, but it will be replaced with `liveboard` during TML export. Importing a TML file generated from ThoughtSpot 8.9.0.cl into 8.8.0.cl or earlier versions is not supported if the object name is set to `liveboard`. To resolve this issue, replace `liveboard` with `pinboard` and then try to import it into earlier versions.
====

== Import a TML
To import a modified TML object, your account must have the `DATAMANAGEMENT` (Can manage data) or `ADMINISTRATION` (Can administer ThoughtsSpot) privilege.

You can import single or multiple objects using the `tml/import` API. If you are importing TML files one at a time, include the fqn property to distinguish objects that have the same name. For example, if you have multiple connections or tables with the same name, the connection or table you reference in your TML does not have a unique name and thus can lead to invalid object references. Adding fqn helps ThoughtSpot differentiate a table from another with the same name.

By default, the fqn parameter is not present in the TML file. However, you can export TML with FQNs and use it during the import.

To import TML representation of the metadata objects into ThoughtSpot, use the following API endpoints:

[div tableContainer]
--
[width="100%" cols="2,1"]
[options='header']
|=====
|API endpoint| Available from
|`xref:tml-api.adoc#import[**POST** /tspublic/v1/metadata/tml/import]` +
REST API v1|ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:tml-api.adoc#import[**POST** /api/rest/2.0/metadata/tml/import]` +
REST API v2 |ThoughtSpot Cloud [version noBackground]#9.0.0.cl or later# +
ThoughtSpot Software [version noBackground]#9.0.1.sw or later#
|=====
--

While the v1 API accepts a string containing a JSON array of TML objects to upload, in YAML or JSON format, the v2 accepts it only in the JSON format.

There are multiple kinds of imports possible. They are:

* `PARTIAL` imports all objects that validate successfully, and ignores objects that do not validate successfully.
* `ALL_OR_NONE` imports the objects that validate successfully.
* `VALIDATE_ONLY` validates the objects but does not import them.



[NOTE]
====
If you import only a Worksheet object, it may take some time for the Worksheet to become available in the ThoughtSpot system. You may need to wait for a few seconds to create answers and Liveboards.

However, if you import a Worksheet along with Liveboards, answers, and other dependent objects in a single API call, the imported objects will be immediately available for use.
====

Visit link:https://docs.thoughtspot.com/cloud/latest/scriptability[Import a TML object] for more information.

== Export a TML
To export the TML data, your account must have the `DATAMANAGEMENT` (Can manage data) or `ADMINISTRATION` (Can administer ThoughtsSpot) privilege..

It must be noted that the default format to export the objects is YAML is v1, and JSON in v2 APIs. To export the TML representation of the metadata objects from ThoughtSpot in JSON or YAML format, use the following endpoints:

[div tableContainer]
--
[width="100%" cols="2,1"]
[options='header']
|=====
|API endpoint| Available from
|`xref:tml-api.adoc#export[**POST** /tspublic/v1/metadata/tml/export]` +
REST API v1 |ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:tml-api.adoc#export[**POST** /api/rest/2.0/metadata/tml/export]` +
REST API v2
|ThoughtSpot Cloud [version noBackground]#9.0.0.cl or later# +
ThoughtSpot Software [version noBackground]#9.0.1.sw or later#
|=====
--

There are several export options available with this API:
[div tableContainer]
--
[width="100%" cols="1,3"]
[options='header']
|=====
|Export Options| Description
|`export_associated` + |Specifies if you would like to export the associated objects. To export the objects associated with the objects specified in export_ids, set the value to true. When set to true, the API exports any underlying worksheets, tables, or views for a given object. By default, the API does not export these underlying objects.
|`export_fqn` + | When set to true, the API exports the FQNs of the referenced objects in the TML data. For example, if you are exporting a Liveboard and its associated objects, the API returns the Liveboard TML data with the FQNs of the referenced Worksheet.
Note that the FQN of a referenced object is the same as the GUID of that object.

ThoughtSpot recommends adding the fqn property before importing the TML objects into the system, because only the name of a referenced object is not sufficient to identify the referenced object during TML import. For example, if your ThoughtSpot instance has two worksheets with the same name, the TML import for a Liveboard that uses one of these worksheets would fail unless the Liveboard TML includes the FQN of the referenced Worksheet.
The `export_fqn` attribute is useful when ThoughtSpot has multiple objects with the same name and you want to eliminate ambiguity during TML import. The `export_fqn=true` property adds the FQNs of the referenced objects in the TML export API response and saves the manual effort of adding FQNs for TML import.
|`export_schema_version` + |Specifies the schema version to use during TML export. By default, the API request uses v1 schema for Worksheets. If you are using Models, set `export_schema_version` to v2. link:https://docs.thoughtspot.com/cloud/latest/models[Models] are supported as new datasets from 9.10.0.cl onwards.
| `export_dependent` + |Specifies if the Tables of the referenced Connection object must be included in the export.
| `export_connection_as_dependent` + |Specifies if a connection object must be included as a dependent object when exporting a Table, Worksheet, Answer, or Liveboard TML.
|=====
--

Visit link:https://docs.thoughtspot.com/cloud/latest/scriptability#export-object[Export a TML object] for more information.

== Development and deployment

When deploying embedded analytics, each organization will have defined practices for development, testing, and deployment of content to ThoughtSpot.
ThoughtSpot instances act as a constantly running service, so deployment only involves publishing ThoughtSpot content, in the form of ThoughtSpot Modeling Language (TML) files to a given ThoughtSpot instance.

Visit this page for detailed information on xref:development-and-deployment.adoc[Development and deployment using TML and REST API].

== TML modification
TML is slightly different for every object type, but all follow a general pattern that allows for programmatic editing.
ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules. Visit this page for detailed information on xref:modify-tml.adoc[TML modification].

== Limitations of working with TML files
There are certain limitations to the changes you can apply by editing a ThoughtSpot object through TML. Visit link:https://docs.thoughtspot.com/cloud/latest/tml#_limitations_of_working_with_tml_files[Limitations of working with TML files] for detailed information.
