= TML
:toc: true
:toclevels: 2

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files
// SOURCE: SCAL-307283, SCAL-317357

ThoughtSpot Modeling Language (TML) is a scriptable format developed by ThoughtSpot for exporting, modifying, and migrating metadata objects such as Models, Views, Tables, Liveboards, and Answers. TML files allow you to manage and version control these objects outside the ThoughtSpot UI, supporting workflows like bulk changes, migration between environments, and programmatic edits via REST API. Users can use link:https://docs.thoughtspot.com/cloud/latest/tml[TML] to model data and build analytics content in the test environment in a flat-file format, and then import and deploy it in their environments.

== Structure of a TML file

To work with TML files for Models, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects as a flat file in `.TML` format, modify, and subsequently upload the TMLs either to the same or a different cluster.

The TML syntax varies per object type. However, all TMLs follow a general pattern that allows programmatic edits. ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules.

See the following pages for the detailed syntax of TML files for each object type: +

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-collections[TML for Collections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for Joins, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor Alerts, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for Tables, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for Models, window=_blank] +
//* link:https://docs.thoughtspot.com/cloud/10.11.0.cl/tml-worksheets[TML for Worksheets, window=_blank]  +

For TML modification tips and recommendations, see xref:modify-tml.adoc[TML modification].


////
[NOTE]
====
Worksheets are deprecated in ThoughtSpot and replaced by Models.
====
////


== TML import and export via REST API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

* xref:tml-import.adoc[Import TML]
* xref:tml-export.adoc[Export TML]

== TML modification

Visit this page for detailed information on xref:modify-tml.adoc[TML modification].

== Limitations of working with TML files
There are certain limitations to the changes you can apply by editing a ThoughtSpot object through TML. Visit link:https://docs.thoughtspot.com/cloud/latest/tml#_limitations_of_working_with_tml_files[Limitations of working with TML files, window=_blank] for detailed information.


[#yamlReimport]
=== YAML reimport in REST API v2 Playground
If you are using the REST API Playground to import TML in YAML format, note that copying YAML content directly in the input field will likely result in the `Invalid YAML/JSON syntax in file` error.
When you copy the YAML output from the export TML API response in the Playground, the copied content is wrapped in quotation marks and include escaped newline characters (`\n`). When you paste this content directly in the `metadata_tml` input field, the API Playground double-escapes characters or removes necessary newline (`\n`) characters. Due to improper formatting, the YAML input becomes invalid for import, resulting in the `Invalid YAML/JSON syntax in file` error.

To work around this issue, follow these steps:

. After you +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fexport-metadata-tml">export TML</a>+++ in the Playground, use the `copy to clipboard` option to copy the YAML output from the API response as shown in this video.

+

[div videoContainer]
--
video::./images/tml-export.mp4[width=100%,options="autoplay,loop"]
--
+
The output copied from the API response is enclosed in quotation marks (`"`).
For example, `"guid: a162289a-c1ab-427e-9985-8fb5f7c7e539\nliveboard:\n  name: Liveboard 1\n"`.
. Paste the YAML output copied from the export TML API response into a text editor.
. Remove the quotation marks, update the TML, and ensure that the YAML is properly formatted: +
`guid: a162289a-c1ab-427e-9985-8fb5f7c7e539\nliveboard:\n  name: Liveboard 1\n`
. When +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fimport-metadata-tml">importing TML in the Playground</a>+++, do not paste the YAML directly into the `metadata_tmls` input field. Instead, use the JSON editor to add the YAML.
. To open the JSON editor, click *View JSON*. +
In the JSON preview, you'll see the following code:
+
[source,JSON]
----
{
  "metadata_tmls": [
    "metadata_tmls3",
    "metadata_tmls5",
  ],
  "import_policy": "PARTIAL",
  "create_new": false,
  "all_orgs_context": false
}
----
. Remove the text in the `metadata_tmls` array and paste your YAML content inside the array. If you are importing more than one TML, use a comma after pasting a TML YAML and then add YAML for the otehr TML.
+
[source,JSON]
----
{
  "metadata_tmls": [
    "guid: a162289a-c1ab-427e-9985-8fb5f7c7e539\nliveboard:\n  name: Liveboard 1\n"
  ],
  "import_policy": "PARTIAL",
  "create_new": false,
  "all_orgs_context": false
}
----
+
You may see double-escaped characters in JSON preview. For example, `\\n` instead `\n`. However,  these will not be imported in the actual payload.
. To submit the request, click **Try it Out**.

+
In the following video, you can see that pasting YAML directly in the `metadata_tmls` form field results in an error due to additional quotation marks and improper formatting. Using the JSON editor, you can paste the YAML inside the array and import TML successfully.
+

[div videoContainer]
--
video::./images/import-tml.mp4[width=100%,options="autoplay,loop"]
--

== Deployment and version control of TML objects
For information about version control and TML deployment, see the following pages:

* xref:version_control.adoc[Git integration and version control]
* xref:development-and-deployment.adoc[TML files from development to testing and production environments]

////
When embedding or deploying a third-party application in their environments, most organizations use defined practices at various stages of their SDLC process. Users typically use a version control system and CI-CD pipeline to push their .

ThoughtSpot instances act as a constantly running service, so deployment only involves publishing ThoughtSpot content, in the form of ThoughtSpot Modeling Language (TML) files to a given ThoughtSpot instance. The three traditional steps to building an SDLC process with ThoughtSpot are:

* Exporting TML objects into a source control system (Git, etc.)
* Altering copies of the TML files for the next stage/environment
* Importing the TML files into the new environment

But this changed with the link:https://developers.thoughtspot.com/docs/git-integration[Git integration] feature. ThoughtSpot now allows you to connect your deployment instance to a Git repository, push TML files to CI/CD pipelines, and deploy commits from your Git repository to your production environment.
However, ThoughtSpot’s Git integration does not support moving objects within the same Org or application instance. For example, it does not support moving objects in an environment where xref:multitenancy-without-orgs[multi-tenancy is implemented using groups].
////
