= TML
:toc: true
:toclevels: 1

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files
ThoughtSpot developed its own scriptable approach for exporting, enhancing, and migrating Worksheets, views, tables, Liveboards, Monitor alerts, and Answers.
Use link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[TML, window=_blank] (ThoughtSpot Modeling Language) to modify a ThoughtSpot object in a flat-file format. Users can model data and build out sophisticated dashboards in the test environment, before deploying to all users.

== Structure of a TML file
To work with TML files for Worksheets, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects to a flat file in `.TML` format, modify it, and subsequently upload this file either to the same cluster, or to a different cluster.

See the following pages for the detailed syntax of each type of TML file:

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers]

* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections]

* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for joins]

* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards]

* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor alerts]

* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL views]

* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for tables]

* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for views]

* link:https://docs.thoughtspot.com/cloud/latest/tml-worksheets[TML for Worksheets]

* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for models]


== TML API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

[NOTE]
====
ThoughtSpot exports TML files with `liveboard` as the object name instead of `pinboard`. Older TML files with the `pinboard` object name can still be imported into ThoughtSpot instances on 8.9.0.cl release version, but it will be replaced with `liveboard` during TML export. Importing a TML file generated from ThoughtSpot 8.9.0.cl into 8.8.0.cl or earlier versions is not supported if the object name is set to `liveboard`. To resolve this issue, replace `liveboard` with `pinboard` and then try to import it into earlier versions.
====

== Import a TML
To import a modified TML object, your account must have the `DATAMANAGEMENT` privilege.

You can import single or multiple objects using the `tml/import` API. To import TML representation of the metadata objects into ThoughtSpot, use the following API endpoints:

[div tableContainer]
--
[width="100%" cols="2,1"]
[options='header']
|=====
|API endpoint| Available from
|`xref:tml-api.adoc#import[**POST** /tspublic/v1/metadata/tml/import]` +
REST API v1|ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software: 9.0.1.sw or later
|`xref:tml-api.adoc#import[**POST** /api/rest/2.0/metadata/tml/import]` +
REST API v2 |ThoughtSpot Cloud [version noBackground]#9.0.0.cl or later# +
ThoughtSpot Software [version noBackground]#9.0.1.sw or later#
|=====
--

[NOTE]
====
If you import only a Worksheet object, it may take some time for the Worksheet to become available in the ThoughtSpot system. You may need to wait for a few seconds to create answers and Liveboards.

However, if you import a Worksheet along with Liveboards, answers, and other dependent objects in a single API call, the imported objects will be immediately available for use.
====

Visit link:https://docs.thoughtspot.com/cloud/latest/scriptability[Import a TML object] for more information.

== Export a TML
You must have at least view access to the objects to export the TML data.

To export the TML representation of the metadata objects from ThoughtSpot in JSON or YAML format, use the following endpoints:

[div tableContainer]
--
[width="100%" cols="2,1"]
[options='header']
|=====
|API endpoint| Available from
|`xref:tml-api.adoc#export[**POST** /tspublic/v1/metadata/tml/export]` +
REST API v1 |ThoughtSpot Cloud [version noBackground]#ts7.may.cl# +
ThoughtSpot Software [version noBackground]#7.1.1#
|`xref:tml-api.adoc#export[**POST** /api/rest/2.0/metadata/tml/export]` +
REST API v2
|ThoughtSpot Cloud [version noBackground]#9.0.0.cl or later# +
ThoughtSpot Software [version noBackground]#9.0.1.sw or later#
|=====
--

Visit link:https://docs.thoughtspot.com/cloud/latest/scriptability[Export a TML object] for more information.

== Development and deployment
When deploying embedded analytics, each organization will have defined practices for development, testing, and deployment of content to ThoughtSpot.
ThoughtSpot instances act as a constantly running service, so deployment only involves publishing ThoughtSpot content, in the form of ThoughtSpot Modeling Language (TML) files to a given ThoughtSpot instance.

Visit this page for detailed information on xref:development-and-deployment.adoc[Development and deployment using TML and REST API].

== TML modification
TML is slightly different for every object type, but all follow a general pattern that allows for programmatic editing.
ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules. Visit this page for detailed information on xref:modify-tml.adoc[TML modification].

== Limitations of working with TML files
There are certain limitations to the changes you can apply by editing a ThoughtSpot object through TML. Visit link:https://docs.thoughtspot.com/cloud/latest/tml#_limitations_of_working_with_tml_files[Limitations of working with TML files] for detailed information.
