= TML
:toc: true
:toclevels: 2

:page-title: TML
:page-pageid: tml
:page-description: The TML API endpoints allow you to export and import TML files

ThoughtSpot Modeling Language (TML) is a scriptable format developed by ThoughtSpot for exporting, modifying, and migrating metadata objects such as Models, Views, Tables, Liveboards, and Answers. TML files allow you to manage and version control these objects outside the ThoughtSpot UI, supporting workflows like bulk changes, migration between environments, and programmatic edits via REST API. Users can use link:https://docs.thoughtspot.com/cloud/latest/tml[TML] to model data and build analytics content in the test environment in a flat-file format, and then import and deploy it in their environments.

== Structure of a TML file

To work with TML files for Models, views, SQL views, tables, Answers, Liveboards, and Monitor alerts in ThoughtSpot, you can download these objects as a flat file in `.TML` format, modify, and subsequently upload the TMLs either to the same or a different cluster.

The TML syntax varies per object type. However, all TMLs follow a general pattern that allows programmatic edits. ThoughtSpot offers a lot of flexibility within its set of xref:intro-thoughtspot-objects.adoc[data objects], and there is no particular hierarchy to TML files, but rather just some rules.

See the following pages for the detailed syntax of TML files for each object type: +

* link:https://docs.thoughtspot.com/cloud/latest/tml-answers[TML for Answers, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-connections[TML for Connections, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-joins[TML for Joins, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-liveboards[TML for Liveboards, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-alerts[TML for Monitor Alerts, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-sql-views[TML for SQL Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-tables[TML for Tables, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-views[TML for Views, window=_blank] +
* link:https://docs.thoughtspot.com/cloud/latest/tml-models[TML for Models, window=_blank] +
//* link:https://docs.thoughtspot.com/cloud/10.11.0.cl/tml-worksheets[TML for Worksheets, window=_blank]  +

For TML modification tips and recommendations, see xref:modify-tml.adoc[TML modification].

[NOTE]
====
Worksheets are deprecated in ThoughtSpot and replaced by Models from 10.12.0.cl onwards.
====

== TML import and export via REST API

The TML API endpoints allow you to programmatically export, validate, and import scriptable TML files. You can use these API endpoints to automate the change management and deployment processes between your development and production environments. With TML API, you can easily migrate your ThoughtSpot content from one environment to another by automating the entire change management process and thereby reducing the risk of human error.

[NOTE]
====
If using older versions of TML files for Liveboards, ensure that your TML file has the object name as `liveboard`. Replace any `pinboard` occurrences with `liveboard` before import.
====

=== Supported object types

// SOURCE: SCAL-317357
The following object types are supported for TML import and export in 26.8.0.cl and later:

* Answers
* Collections
* Connections
* Joins
* Liveboards
* Models (Worksheets)
* Monitor Alerts
* SQL Views
* Tables
* Views

[NOTE]
====
*New in 26.8.0.cl:* The `COLLECTION` object type is now a supported enum value in the TML Import and Export APIs and the Update Metadata Object ID API. See xref:tml.adoc#_collections_tml_support[Collections TML support] below for details.
====

== Import TML
To import a modified TML object, your account must have the `DATAMANAGEMENT` (*Can manage data*) or `ADMINISTRATION` (*Can administer ThoughtSpot*) privilege.

You can import single or multiple objects using the `tml/import` API. If you are importing TML files one at a time, include the `fqn` property to distinguish objects that have the same name. If you have multiple connections or tables with the same name and the Connection or Table you reference in your TML does not have a unique name, it can lead to invalid object references. Adding `fqn` helps ThoughtSpot differentiate a Table from another with the same name.

By default, the `fqn` parameter is not present in the TML file. However, you can export TML with FQNs and use it during the import.

You can also set the `skip_diff_check` to `true` to skip diff check before processing TMLs for imports. This attribute helps  identify the objects that haven't been changed since the last import or TML update, and eliminates importing redundant objects.

To import TML representation of the metadata objects into ThoughtSpot, use one of the following API endpoints:

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fimport-metadata-tml">POST /api/rest/2.0/metadata/tml/import</a>+++ (REST API v2)
* xref:tml-api.adoc#import[POST /tspublic/v1/metadata/tml/import] (REST API v1)

//While the v1 API accepts a string containing a JSON array of TML objects to upload, in YAML or JSON format, the v2 accepts it only in the JSON format.

There are multiple kinds of imports possible:

* `PARTIAL` imports all objects that validate successfully, and ignores objects that do not validate successfully.
* `ALL_OR_NONE` imports the objects that validate successfully.
* `VALIDATE_ONLY` validates the objects but does not import them.
* `PARTIAL_OBJECT` (only applicable to REST API v2)
imports objects that validate successfully and skips the objects that do not validate successfully. If the import fails for a visualization object in a Liveboard TML, the Liveboard will be imported without that visualization object. Similarly, if importing a relationship in a logical table fails, the table TML will be imported with warnings in the API response.

You can also specify additional parameters to set the Org context and skip CDW validation checks for Table TMLs.

[NOTE]
====
If you import only a Model object, it may take some time for the Model to become available in the ThoughtSpot system. You may need to wait for a few seconds to create answers and Liveboards.

However, if you import a Model along with Liveboards, answers, and other dependent objects in a single API call, the imported objects will be immediately available for use.
====

== Import TML objects asynchronously
The REST v1 and v2  `metadata/tml/import` APIs import TML objects synchronously. When you try to import large and complex metadata objects, the synchronous import operation takes more time to process data and sometimes can result in a timeout error.

To allow mutually exclusive import tasks to run in parallel, process TML objects asynchronously, and check import task status, ThoughtSpot provides the following APIs:

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fimport-metadata-tml-async">POST /api/rest/2.0/metadata/tml/async/import</a>+++ +
Creates an import TML tasks and processes TMLs asynchronously

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Ffetch-async-import-task-status">POST /api/rest/2.0/metadata/tml/async/status</a>+++ +
Fetches status of import tasks

=== Schedule import tasks

You can import TML objects asynchronously by scheduling TML import tasks via `POST` request to POST `/api/rest/2.0/metadata/tml/async/import` API endpoint.

== Export TML

You can export TML files for supported objects using the following API endpoints:

* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fmetadata%2Fexport-metadata-tml">POST /api/rest/2.0/metadata/tml/export</a>+++ (REST API v2)
* xref:tml-api.adoc#export[POST /tspublic/v1/metadata/tml/export] (REST API v1)

[#_collections_tml_support]
== Collections TML support

// SOURCE: SCAL-317357
As of ThoughtSpot Cloud 26.8.0.cl and ThoughtSpot Software, the `COLLECTION` object type supports distributed object identity and TML-based management across the following APIs:

=== TML import and export

Collections can now be exported as TML files and imported back into ThoughtSpot using the standard TML import and export API endpoints. To export a Collection:

[source,JSON]
----
{
  "metadata": [
    {
      "identifier": "<collection-guid>",
      "type": "COLLECTION"
    }
  ]
}
----

Pass `"type": "COLLECTION"` in the `metadata` array of the `POST /api/rest/2.0/metadata/tml/export` request body. The exported TML file can be modified and re-imported using `POST /api/rest/2.0/metadata/tml/import`.

=== Update Object ID API

The `COLLECTION` object type is now a supported value in the Update Metadata Object ID API. This allows you to assign a stable, portable object identifier (`obj_id`) to a Collection, enabling consistent referencing across ThoughtSpot environments in SDLC and deployment workflows.

API endpoint: `POST /api/rest/2.0/metadata/update_metadata_obj_id`

// TODO: Verify the exact request body schema for COLLECTION type in update_metadata_obj_id with engineering (SCAL-317357)

=== Update Metadata Header API

The `COLLECTION` object type is now supported in the Update Metadata Header API. You can programmatically update the name and description of a Collection object.

// TODO: Verify the exact endpoint name for Update Metadata Header in REST API v2 with engineering (SCAL-317357)

This feature is available on both ThoughtSpot Cloud 26.8.0.cl and ThoughtSpot Software.

For the full list of supported metadata object types, see xref:rest-api-v2-reference.adoc#_metadata[Metadata REST API reference].
