= Token request service
:toc: true
:toclevels: 1

:page-title: trusted authentication
:page-pageid: trusted-auth-token-request-service
:page-description: You can configure support for token-based authentication service on ThoughtSpot.

== Overview
The *token request service* is the portion of the web application with access to the ThoughtSpot `xref:trusted-auth-secret-key.adoc[secret_key]` that issues the request to ThoughtSpot to generate tokens.

In most cases, the *token request service* is a REST API endpoint added to the web application. Providing a REST API service allows the Visual Embed SDK to request new tokens whenever they are needed to start a new ThoughtSpot session.

The `init()` function will call the *token request service* endpoint, which returns the *token* to the web browser, triggering the Visual Embed SDK to handle the rest of the login flow. The token request can instead happen on the back-end of the web app and the token embedded into the returned web page directly, but this will require a page reload if there is a need for a new token.

There are no requirements for how the *token request service* is built or hosted, other than being able to issue REST API commands to the ThoughtSpot instance and having access to the `secret_key`.  When using a ThoughtSpot cloud instance, the authenticator service will need outbound request access to the hosted ThoughtSpot cloud instance.

== Quick code example
Every web application framework has its own way of handling users, sessions, and making REST API requests to other services.

The following example show how a *token request service* might look in Node.js with Express and the `express-session` package used to manage a session in the embedding web application. 

[source,javascript]
----
app.get('/ts-token',(req,res) => {
  // req.session will be set by another endpoint handling login into the web application
  session=req.session;
  
 // secret_key must be stored securely; here we assume the ThoughtSpot server name and secret_key are stored in env file
 let thoughtspot_url = process.env.TS_SERVER_URI;
 let thoughtspot_secret_key = process.env.TS_SECRET_KEY;

  // Short-time out for cookie-based login; make longer for cookieless
  const timeoutInSec = 60; 

  // Assuming 'user_email' is the session value that matches to the username in ThoughtSpot
  if (session.user_email) {
        let tsTokenUrl = thoughtspot_url + "api/rest/2.0/auth/token/full";
        let tsTokenBody = {
            "username": session.user_email,
            "validity_time_in_sec": timeoutInSec,
            "auto_create": false,
            "secret_key": thoughtspot_secret_key
        };
        // using Fetch to make HTTP request; you may use other package
        const response = await fetch(tsTokenUrl, {
          method: 'POST',
          body: JSON.stringify(tsTokenBody),
          headers: { Accept: "application/json",
                     "X-Requested-By": "ThoughtSpot",
                     "Content-Type": "application/json"
          }
        });

        const results = await response.json();
        res.send(results.token);
    }
    else{
        res.send('No user session exists');
    }
})
----


== Authenticating the user
The *token request service* must access the authentication details of the web application logged-in user (at minimum, the *ThoughtSpot username* value), and then use those values in the subsequent REST API requests to ThoughtSpot.

Authentication details are often accessed from:

* web application's user session
* JWT token included in request
* LDAP or AD details

If your *token request service* must also create users and give them access, additional authentication details must be accessed:

* user email address +
* user display name +
* ThoughtSpot group names to add a user to +
* Org ID to which the user belongs +

*User password is not required* in the login token request when using the `secret_key`. 

ThoughtSpot user account passwords are neither checked nor modified by any single sign-on method.

== Login token request via REST API
If you are using ThoughtSpot Cloud, best practice is to use the V2 REST API Full Access Token. 

V1 login tokens only work for cookie-based Trusted Authentication, while the V2 tokens can be used for cookie-based or cookieless Trusted Auth. 

The V1 `/session/token/login` API endpoint can accept V1 or V2 tokens to establish a ThoughtSpot session.

If you are on an older software release, please use the features that are available in your deployed release.

=== V2 REST API
The REST API V2 *

=== V1 REST API
REST API call *necessary* after sign-in is the xref:session-api.adoc#session-authToken[request for the login token]. This is the call that utilizes the `secret_key`, which the *authenticator service* must also securely store and access along with the service account user credentials.

When a token has been requested in `FULL` mode, it will create a full ThoughtSpot session in the browser and application. The token for `FULL` access mode persists through several sessions and stays valid until another token is generated.

You can request a limited token using the `access_level=REPORT_BOOK_VIEW` option in REST API v1 and `/api/rest/2.0/auth/token/object` endpoint in REST API v2.0, but this is rarely used and not recommended.
Access control in ThoughtSpot (called Sharing) prohibits a signed-in user from loading any content to which they don't have access. Access control (sharing) can be granted during the login token request process by adding the user to the appropriate ThoughtSpot groups.

=== Login token expiration
Login tokens from the V1 and V2 REST APIs have different expiration rules.

==== V2 token
The V2 REST API token is a standard OAuth 2.0 token that encodes several properties with in the token, most notably the username and the expiration time.

The validity time of the token is never extended by any activity, so a new token must be requested after the intiial token passes its expiration time.

The V2 token REST API endpoint has a request argument called `validity_time_in_sec` that defaults to 300 seconds (5 minutes). 

For cookie-based Trusted Authentication, you may want to shorten the `validity_time_in_sec` to less than one minute, since the token is only used once and then there is a long-lived cookie-based session. The ThoughtSpot session end time will extend naturally as the user interacts with ThoughtSpot.

For cookieless Trusted Authentication, you will want to request the token with a longer validity, possibly 20 or 30 minutes or more. 

==== V1 token
The V1 REST API login token is a proprietary token format that cannot be decoded or used for any purpose other than to create a ThoughtSpot session.

V1 tokens stay valid for a length of time based on the following rules:

* A token stays valid indefinitely until another token for any user is generated.
* When a new token is generated using the same `secret_key`, the previous token will expire after five minutes.
* When a new `secret_key` is generated for the ThoughtSpot server and the first new login token is obtained using the new `secret_key`, all tokens generated using the previous `secret_key` become invalid.
* If users make multiple attempts to log in to ThoughtSpot using an invalid or expired token, they may get locked out of their accounts.

To set a consistent five-minute expiration time, you can generate a second token to start the expiration clock for the previous login token that is sent to the user's browser.

[NOTE]
====
On multi-tenant clusters with Orgs, users must use the Org-specific tokens when switching between Orgs.
====

== Just-in-time user provisioning and group assignment

Starting from 8.9.0.cl, the xref:session-api.adoc#session-authToken[/tspublic/v1/session/auth/token] endpoint supports just-in-time provisioning of users. If the user specified in the API request does not exist in the ThoughtSpot system, you can set the `autocreate` property to `true` to add the user to ThoughtSpot and assign the user to `groups`.

The typical flow of REST API requests for user creation at the time of a login token request is as follows: +

1. Make a REST API request to xref:user-api.adoc#get-user-details[get the user details].
2. If the user already exists, check the `assignedGroups` property. On clusters with Orgs feature enabled, check the `orgIds` property to verify if the user mapped to any Org.
3. If the user doesn't exist in ThoughtSpot, you can either xref:user-api.adoc#create-user[create a new user] or set the `autocreate` property to `true` in your API request to the `/tspublic/v1/session/auth/token` endpoint. You can also specify the Org ID and group name to add the user to the Org and groups in the same API request.
4. If the user should be logged in to a different Org context, specify the Org ID in the `orgid` property and set `autocreate` to `true`. +
+
[NOTE]
====
Org IDs are integers that are created automatically when a cluster administrator creates an Org. To know the Org IDs of Orgs, you can send a `GET` request to the `/tspublic/v1/session/orgs` API endpoint. If you have cluster administrator privileges, you can use the `/tspublic/v1/org/search` endpoint to get a list of all Orgs available on your cluster.
====

5. If the user should belong to other groups, add group names in the `groups` property when making an API call to the `/tspublic/v1/session/auth/token` endpoint. If these groups don't exist in the specified `orgid`, set `autocreate` to `true` to add these groups to the Org.
6. Request a login token from ThoughtSpot via `/tspublic/v1/session/auth/token` API endpoint.
7. Return the token to the user's web browser.

[NOTE]
====
The `/api/rest/2.0/auth/token/object` and `/api/rest/2.0/auth/token/full` endpoints in REST API v2.0 also support JIT  provisioning and assigning the user to groups and Orgs.
====

== Additional REST API requests
Because all of ThoughtSpot administration is possible via the REST API, you can incorporate even more functionality into the *authenticator service* if necessary, building it into an authentication and authorization service. The xref:api-user-management.adoc[user and group privileges] REST API documentation covers the additional requests related to authorization.

For example, you could use the xref:rest-api-reference.adoc#_groups_and_privileges[REST API v1] or xref:rest-api-v2-reference.adoc#_groups[REST API v2.0] group endpoints to implement ThoughtSpot groups that are intended for use in Row Level Security (RLS) rules. For these groups, the group name must match exactly with a value in a column in the data warehouse, so the name of the group itself serves as a __data entitlement__. You could adjust the flow described in the preceding section to create any group for RLS that did not already exist and assign it to the user, which would bring the process closer to a Role-based access control (RBAC) or Attribute-based access control (ABAC) pattern.

== Code examples

* A simple Python Flask implementation of an Authenticator Service is available in the link:https://github.com/thoughtspot/ts_everywhere_resources/tree/master/examples/token_auth[ts_everywhere_resources GitHub repository, window=_blank].  +

* link:https://github.com/thoughtspot/node-token-auth-server-example[https://github.com/thoughtspot/node-token-auth-server-example, window=_blank]

== Implement token login without the Visual Embed SDK
The Visual Embed SDK handles the final REST API request to create the session, but it is possible to perform the login using xref:session-api.adoc#session-loginToken[/session/login/token] or the xref:rest-api-v2-reference.adoc#_authentication[ REST API v2.0 token access endpoints]. For more information, see xref:api-auth-session.adoc#_authenticate_and_log_in_with_a_token_trusted_authentication[REST API v1 authentication] and xref:authentication.adoc#trusted-auth-v2[REST API v2.0 authentication].

[NOTE]
====
The REST API v1 `session/login/token` and v2.0 token access endpoints are not used for establishing a REST API session for backend processes or administration scripts. Use the xref:session-api.adoc#session-login[/session/login] endpoint with `username` and `password` to create a REST API session.

////
* The REST API v2.0 allows using bearer or trusted authentication tokens. The authentication tokens obtained from REST API separate from the REST API v1 login token.
////
====

////
REST API clients can make a `GET` or `POST` API call to the xref:session-api.adoc#session-loginToken[tspublic/v1/session/login/token] API endpoint to log in a user. Note that the `GET` call to the `tspublic/v1/session/login/token` endpoint must include a fully-encoded URL with the authentication token and resource endpoint in the request URL.

----
https://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/session/login/token?username=tsUser&auth_token=JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRPMFA2S0ZlNm51Qlo4NFBlZUppdzZ3PT0kMnJKaSswSHN6Yy96ZGxqdXUwd1dXZkovNVlHUW40d3FLMVdBT3hYVVgxaz0&redirect_url=https://<redirect-domain>/?authtoken=<auth_token>&embedApp=true&primaryNavHidden=true#/embed/viz/<Liveboard_id>/<visualization_id>
----

ThoughtSpot recommends sending the authentication attributes in a `POST` request body instead of a `GET` call.

----
curl -X POST \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Accept: application/json' \
-d 'username=tsuser&auth_token=JHNoaXJvMSRTSEEtMjU2JDUwMDAwMCRtL3dWcVo2ZTdWTzYvemdXN1ZoaTh3PT0kdmlyNnQ4NHlwYXlqNFV4VzBpRlNYbmQ1bzk5T1RFK2NVZy9ZRUhvUEkvST0&redirect_url=https://<ThoughtSpot-Host>/?embedV2=true#/pinboard/7a9a6715-e154-431b-baaf-7b58246c13dd%2F' \
'https://<ThoughtSpot-Host>/callosum/v1/tspublic/v1/session/login/token'
----

The API request must include the following attributes:

* `username` +
_String_. The `username` of the user requesting access to the embedded ThoughtSpot content.

* `auth_token` +
_String_. The authentication token obtained for the user.

* `redirect_url` +
_String_. The URL to which the user is redirected after successful authentication.

+
----
https://<redirect-domain>/?embedV2=true#/pinboard/7a9a6715-e154-431b-baaf-7b58246c13dd%2F
----
////

== Storing the secret_key securely
The `secret_key` allows a REST API request for a login token for *any username*. 

ThoughtSpot generates a new `xref:trusted-auth-secret-key.adoc[secret_key]` when trusted authentication is enabled on a ThoughtSpot instance. See the xref:trusted-auth-secret-key.adoc[secret_key documentation] for more details.

The `secret_key` must be stored by the *token request service* securely and never revealed to the user in their browser. Any examples using the `secret_key` from a front-end page are purely *for testing only*.
