= Token request service
:toc: true
:toclevels: 1

:page-title: trusted authentication
:page-pageid: trusted-auth-token-request-service
:page-description: You can configure support for token-based authentication service on ThoughtSpot.

== Token request service overview
The *token request service* is the portion of the web application with access to the ThoughtSpot `secret_key` that issues the request to ThoughtSpot to generate tokens.

In most cases, this is an API endpoint added to the web application, that will be called from the browser by the Visual Embed SDK `init()` function.

The `init()` function calls the *token request service*, which returns the *token* to the web browser.

There are no requirements for how the *token request service* is built or hosted, other than being able to issue REST API commands to the ThoughtSpot instance and having access to the `secret_key`.  When using a ThoughtSpot cloud instance, the authenticator service will need outbound request access to the hosted ThoughtSpot cloud instance.

== Storing the secret_key securely
ThoughtSpot generates a `secret_key` when trusted authentication is enabled on a ThoughtSpot application instance.

== Authenticating the user
The *token request service* must access the authentication details of the web application logged-in user (at minimum, the *ThoughtSpot username* value), and then use those values in the subsequent REST API requests to ThoughtSpot.

Authentication details are often accessed from:

* web application's user session
* JWT token included in request
* LDAP or AD details

If your *token request service* must also create users and give them access, additional authentication details must be accessed:

* user email address +
* user display name +
* ThoughtSpot group names to add a user to +
* Org ID to which the user belongs +

User password is not required in the login token request. It can be randomly generated if creating a user account in ThoughtSpot so that the user can only sign in via the embedding application.

=== REST API session sign-in
The *authenticator service* makes REST API requests to ThoughtSpot. To make a REST API request for a login token, the *authenticator service* must have xref:api-auth-session.adoc[created an active session] as a ThoughtSpot user with *server administrator* privileges, typically a service account created only for use by the *authenticator service*.

The authenticator service code will need logic to log in if there is no active session and secure access to the service account credentials. How you protect and securely access the service account credentials is up to you in the design of the service. Any examples with a username and password entered directly in the code are for *testing purposes only*.

=== Login token request via REST API
The only other REST API call *necessary* after sign-in is the xref:session-api.adoc#session-authToken[request for the login token]. This is the call that utilizes the `secret_key`, which the *authenticator service* must also securely store and access along with the service account user credentials.

When a token has been requested in `FULL` mode, it will create a full ThoughtSpot session in the browser and application. The token for `FULL` access mode persists through several sessions and stays valid until another token is generated.

You can request a limited token using the `access_level=REPORT_BOOK_VIEW` option in REST API v1 and `/api/rest/2.0/auth/token/object` endpoint in REST API v2.0, but this is rarely used and not recommended.
Access control in ThoughtSpot (called Sharing) prohibits a signed-in user from loading any content to which they don't have access. Access control (sharing) can be granted during the login token request process by adding the user to the appropriate ThoughtSpot groups.

== Just-in-time user provisioning and group assignment

Starting from 8.9.0.cl, the xref:session-api.adoc#session-authToken[/tspublic/v1/session/auth/token] endpoint supports just-in-time provisioning of users. If the user specified in the API request does not exist in the ThoughtSpot system, you can set the `autocreate` property to `true` to add the user to ThoughtSpot and assign the user to `groups`.

The typical flow of REST API requests for user creation at the time of a login token request is as follows: +

1. Make a REST API request to xref:user-api.adoc#get-user-details[get the user details].
2. If the user already exists, check the `assignedGroups` property. On clusters with Orgs feature enabled, check the `orgIds` property to verify if the user mapped to any Org.
3. If the user doesn't exist in ThoughtSpot, you can either xref:user-api.adoc#create-user[create a new user] or set the `autocreate` property to `true` in your API request to the `/tspublic/v1/session/auth/token` endpoint. You can also specify the Org ID and group name to add the user to the Org and groups in the same API request.
4. If the user should be logged in to a different Org context, specify the Org ID in the `orgid` property and set `autocreate` to `true`. +
+
[NOTE]
====
Org IDs are integers that are created automatically when a cluster administrator creates an Org. To know the Org IDs of Orgs, you can send a `GET` request to the `/tspublic/v1/session/orgs` API endpoint. If you have cluster administrator privileges, you can use the `/tspublic/v1/org/search` endpoint to get a list of all Orgs available on your cluster.
====

5. If the user should belong to other groups, add group names in the `groups` property when making an API call to the `/tspublic/v1/session/auth/token` endpoint. If these groups don't exist in the specified `orgid`, set `autocreate` to `true` to add these groups to the Org.
6. Request a login token from ThoughtSpot via `/tspublic/v1/session/auth/token` API endpoint.
7. Return the token to the user's web browser.

[NOTE]
====
The `/api/rest/2.0/auth/token/object` and `/api/rest/2.0/auth/token/full` endpoints in REST API v2.0 also support JIT  provisioning and assigning the user to groups and Orgs.
====

== Additional REST API requests
Because all of ThoughtSpot administration is possible via the REST API, you can incorporate even more functionality into the *authenticator service* if necessary, building it into an authentication and authorization service. The xref:api-user-management.adoc[user and group privileges] REST API documentation covers the additional requests related to authorization.

For example, you could use the xref:rest-api-reference.adoc#_groups_and_privileges[REST API v1] or xref:rest-api-v2-reference.adoc#_groups[REST API v2.0] group endpoints to implement ThoughtSpot groups that are intended for use in Row Level Security (RLS) rules. For these groups, the group name must match exactly with a value in a column in the data warehouse, so the name of the group itself serves as a __data entitlement__. You could adjust the flow described in the preceding section to create any group for RLS that did not already exist and assign it to the user, which would bring the process closer to a Role-based access control (RBAC) or Attribute-based access control (ABAC) pattern.
