= secret_key management
:toc: true
:toclevels: 1

:page-title: trusted authentication
:page-pageid: trusted-auth-secret-key
:page-description: You can configure support for token-based authentication service on ThoughtSpot.

== secret_key overview
The `secret_key` allows calling the ThoughtSpot *token request* REST APIs to generate a token for *any user*.

Requests with the `secret_key` do not require any type of user login or admin permissions - the `secret_key` is equivalent to an admin-level login for the token request REST APIs.

The `secret_key` must be stored securely and never exposed to end users in the web browser.


[#trusted-auth-enable]
== Enable trusted authentication to get a secret_key
A new secret key is generated when the ThoughtSpot administrator enables *Trusted authentication*. +

[NOTE]
====
Starting from 9.2.0.cl, Org administrators can generate a unique secret key for respective Orgs. To enable this feature on your cluster, contact ThoughtSpot Support.
====

To generate a secret key:

. Log in to the ThoughtSpot.
. If Orgs are configured on your instance, switch to the Org for which you want to generate a secret key.
+
If the per-Org secret key feature is not enabled on your instance and if you want to generate a separate secret key for each Org, contact ThoughtSpot Support. ThoughtSpot also allows you to generate a secret key at the primary Org (Org 0) level and use it to obtain an authentication token for a user.
. Go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit*.
. To enable trusted authentication, turn on the *Trusted authentication* toggle.
. To copy the secret key, click *Edit* again, navigate to *Trusted authentication*, and then click the clipboard icon.
+
The following example shows a ThoughtSpot-generated secret key string.
+
----
b0cb26a0-351e-40b4-9e42-00fa2265d50c
----
This key is required for making API calls to get a token for ThoughtSpot users.

. Store the key in a secure location.
. Click *Save Changes*.

== Request a new secret_key
Requesting a new `secret_key` simply involves disabling and re-enabling trusted authentication.

Any previous `secret_key` will be invalidated as soon as trusted auth has been disabled (see below).

== Disable trusted authentication

To disable trusted authentication, follow these steps:

. Log in to ThoughtSpot.
. If the per-Org secret key feature is enabled and Orgs are configured on your instance, switch to the Org for which you want to disable trusted authentication.
. Go to *Develop* > *Customizations* > *Security settings*.
. Click *Edit* and turn off the *Trusted authentication* toggle.
+
A pop-up window appears and prompts you to confirm the disable action.

. Click *Disable*.

+
When you disable trusted authentication, the validity of your existing secret key expires, and your app may become inoperable.
To a new secret key and generate authentication tokens, you must enable Trusted authentication.

