= Troubleshoot trusted authnetication
:toc: true
:toclevels: 1

:page-title: troubleshoot trusted authentication
:page-pageid: trusted-auth-troubleshoot
:page-description: Troubleshooting steps for trusted authentication

== Initial steps
CORS and CSP xref:security-settings.doc[must be configured correctly] for any embedding and REST API commands to work from the browser.
  
== Third-party cookie issues
When implementing trusted authentication with session cookies, check if your browser allows third-party cookies. 
  
Chrome now blocks third-party cookies in Incognito mode by default, while Safari blocks them by default even in standard mode. 
  
If your Web browser rejects third-party cookies, the embedded content will be blocked. 
  
To workaround this issue, you can either use cookieless authentication (`AuthType.TrustedAuthTokenCookieless`) in the SDK or xref:custom-domain-configuration.adoc[customize the ThoughtSpot instance domain] to match the top-level domain of your embedding web app.

== Tester HTML page
The token_auth directory contains a link:https://github.com/thoughtspot/ts_everywhere_resources/blob/master/examples/token_auth/trusted_auth_tester.html[trusted_auth_tester.html, window=_blank] page to help verify each step of the trusted authentication process.

== Use browser developer tools
  (1) call to /session/info (2) if that comes back 401 (3) call to get token (4) once token is received, call to V1 /session/login/token
