= Integrate with Vercel
:toc: true
:toclevels: 3

:page-title: Vercel and ThoughtSpot integration
:page-pageid: vercel-integration
:page-description: Learn how to integrate ThoughtSpot with Vercel.

If you are using Vercel to deploy and maintain your application, you can integrate your Vercel project with your ThoughtSpot instance and easily embed ThoughtSpot content in your app. With Vercel integration, you can connect your application to a data source in ThoughtSpot workspace and create the content that you want to embed in your app.

== Before you begin

Vercel integration requires the following setup:

* A Vercel account to which you want to install the integration
* A Vercel project that can access the integration
* ThoughtSpot application URL
* If you plan to use Trusted authentication, `secret_key` is required. +
The `secret_key` is generated if `Trusted authentication` is enabled on your instance. For more information, see xref:trusted-auth-secret-key.adoc[Secret key management].

== Get started with Vercel integration

Vercel integration with ThoughtSpot includes the following steps:

* Install ThoughtSpot integration
* Configure ThoughtSpot (Optional)
* Create a simple embed to ThoughtSpot

=== Install integration

To install integration:

.




The Vercel Integration should facilitate the following flow:

Install ThoughtSpot integration
[Optional] Configure ThoughtSpot
Create a simple embed to ThoughtSpot



Integration steps:

For auth: we should provide an authentication method, similar to the standardized way we envision having the COMS team build for all tools external to ThoughtSpot (ideally, not similar: just using that component).
If the user already has ThoughtSpot, let them log in via Basic Auth or SSO
If the user does not have Thoughtspot, let them create a Free Trial account rapidly.

There are three scenarios:
User does not have ThoughtSpot → Provide user with a way to create a Free Trial.
This is assuming that Free Trial has trusted auth (which means free trial is using orgs). Let's track that dependency to decide when to show the "Create free trial" option here.
User has ThoughtSpot Analytics (e.g. no TSE license):
Let user enter their cluster details.
Let user sign in with SSO or basic authentication.
Activate user's free trial of TSE for 30 days (this will be required as we'll need to be able to access Trusted Auth)
User has TSE
Let user enter their cluster details.
Let user sign in with SSO or basic authentication.



Once all streamlined connectivity / modeling tasks have been completed via the Vercel integrations UX, we should let developers open ThoughtSpot in a new tab to create content if they want to.


To get started:
The integration can be added into one Vercel project
Keep in mind that using ThoughtSpot's developer tools, you can easily embed analytics in many other projects - all you need is our Visual Embed SDK.
Installation steps
Set up your data model in ThoughtSpot
Provide URL of your ThoughtSpot instance, or subscribe to a free trial
Connecting to data
ThoughtSpot uses worksheets, which are logical views of data, to model complex datasets. In the Vercel integration, creating a connection will guide you through the creation of a new worksheet to analyze data that is not currently represented in ThoughtSpot. To analyze data from existing connections, pick "Connect to existing worksheets". Learn more about worksheets.
When a new connection is created: once tables and columns are selected, ThoughtSpot will auto-detect joins between the selected tables. Pick the association of tables you would like to run your analysis on, and ThoughtSpot will create a worksheet to allow analysis on this data set.
Embedding ThoughtSpot
ThoughtSpot's Vercel integration enables embedding Natural Language Search on your data source. ThoughtSpot allows you to embed many other components:
Liveboards: Javascript | React
Visualizations: Javascript | React
The full application (or specific pages in the application): Javascript | React
Token based search: Javascript | React


ThoughtSpot allows for a deeply customizable experienc to fit your application's look and feel, and tailor the experiences you wish to enable for your customers.
Authentication
ThoughtSpot's Vercel integration streamlines the set up of Trusted Authentication, our most popular and flexible authentication method. The code sample provided in the integration leverages the Trusted Authentication service deployed in Vercel to authenticate your users into ThoughtSpot seamlessly as they access your application.
However ThoughtSpot  supports several authentication options to authenticate and authorize the users of an embedded ThoughtSpot view:
Embedded SSO (to leverage an existing setup and authenticate your users into the embed without redirects)
SAML redirect SSO
OpenID Connect authentication
Trusted authentication (cookie-based, or cookie-less)

Important note: to finish setting up trusted authentication, you need to secure access to the trusted authentication service and put it behind your main application's authentication
< Subsection with instructions on how to do this>.



To learn more about ThoughtSpot itself, refer to this documentation.



ThoughtSpot's Vercel integration allows developers to quickly embed AI-powered analytics into their own application.







We will provide code samples here to let folks create simple ThoughtSpot embed. There will be two examples:
Embed Sage (include the init, the sage embed, the render). This is the preferred option that we should advertise on top as it bypasses the need to configure ThoughtSpot and create content (section above)
Embed a liveboard.

Let's use and set global variables in Vercel to make it easier for developers:
Authentication service URL
ThoughtSpot host URL
Secret key
And leverage these global variables both in the authentication backend template (if relevant) and in the sample code we provide to the developers for them to embed ThoughtSpot.
















