= Webhooks
:toc: true

:page-title: Webhooks
:page-pageid: webhooks
:page-description: Register a webhook to send KPI monitor and Liveboard schedule alerts to an external application

Webhooks in ThoughtSpot provide a way to automate workflows and integrate with external systems by sending real-time notifications when specific events occur. In ThoughtSpot, webhooks can be used for two primary alerting use cases:

* Liveboard schedule alerts [beta betaBackground]^Beta^ +
ThoughtSpot supports using a xref:webhooks-lb-schedule.adoc[webhook for delivering scheduled Liveboard notifications] to external applications and communication channels. To enable this feature, contact ThoughtSpot Support. +

* KPI alerts +
For KPI charts in a Liveboard or Answer, ThoughtSpot allows creating and scheduling alerts. KPI Monitor alerts notify users when a KPI metric meets a threshold condition or periodically as per the schedule configured by the user. You can send these alerts using a webhook and notify external applications when a KPI meets a defined threshold or changes value. For more information, see xref:webhooks-kpi-alerts.adoc[Webhooks for KPI monitor alerts].

== Integration with Amazon S3 bucket

Starting with the ThoughtSpot 26.3.0.cl release, ThoughtSpot supports configuring an Amazon S3 bucket as the storage destination for delivering Webhook attachments via REST APIs.

For more information, see xref:webhooks-s3-storage.adoc[S3 storage integration for Webhook delivery].

=== Response after webhook delivery

The webhook endpoint must respond with an HTTP 2xx status code to confirm successful receipt and processing of the request. The receiving server must send a 2xx response within 5 seconds of the webhook delivery.

If your server takes longer than 5 seconds to respond, returns a response code other than 2xx, or times out, ThoughtSpot may still deliver the Liveboard data and files. However, the notification status will be recorded as `FAILED` in the ThoughtSpot notification history, and the request will be retried.

To ensure a timely response, we recommend processing webhook payloads asynchronously. Your server can immediately return a 2xx response upon receipt of the webhook and then handle the payload in the background without blocking subsequent webhook deliveries.

== Webhook payload
For information about the payload content delivered to target destination, see xref:webhooks-payload.adoc[Webhook payload for Liveboard events].
