= Webhooks for Liveboard schedule events[beta betaBackground]^Beta^
:toc: true
:toclevels: 3

:page-title: Webhooks for Liveboard Schedueld Jobs
:page-pageid: webhooks-lb-schedule
:page-description: Configure Webhooks and send alerts to specific communication channels



To provide flexibility and programmatic control for users who want to customize notifications and automate workflows based on Liveboard scheduling events, ThoughtSpot provides the ability to configure a webhook communication channel. By configuring a webhook, users can send notifications automatically to a target application whenever a scheduled Liveboard job is triggered in ThoughtSpot.

Webhook support for Liveboard schedule events is available only on ThoughtSpot Cloud instances running 10.14.0.cl or later. This feature is currently in beta, and is not enabled by default. To enable this feature on your instance, contact ThoughtSpot Support.

== Overview

If you have scheduled a Liveboard job to receive a daily report via email, you can configure ThoughtSpot to send the report directly to the webhook endpoint such as your internal marketing or incident management app. With webhooks, you no longer need to manually handle the data received in email notifications from ThoughtSpot.

To automate sending scheduled Liveboard notifications to a webhook endpoint, ThoughtSpot administrators must configure the following:

* A webhook communication channel. +
Use the following REST APIs to set and view communication channel preferences:
** `POST /api/rest/2.0/system/preferences/communication-channels/configure`
** `POST /api/rest/2.0/system/preferences/communication-channels/search`
* A webhook for the Liveboard schedule event to enable programmatic communication between the target application and ThoughtSpot. +
To create and manage webhook APIs, use the following APIs:
** `POST /api/rest/2.0/webhooks/create`
** `POST /api/rest/2.0/webhooks/delete`
** `POST /api/rest/2.0/webhooks/search`
** `POST /api/rest/2.0/webhooks/{webhook_identifier}/update`

[NOTE]
====
In the current release:

* REST APIs support webhook channel configuration for `LIVEBOARD_SCHEDULE` events only.
* You can configure only one webhook for the Liveboard schedule event per Org.
====

== Get started
The webhooks setup for Liveboard Schedule events involves the following steps:

* xref:webhooks-lb-schedule.adoc#_configure_webhook_communication_channel[Configuring a webhook communication channel at the cluster or Org level].
* xref:webhooks-lb-schedule.adoc#_configure_a_webhook_for_liveboard_schedule_event[Creating a webhook to listen to the Liveboard schedule events].
* xref:webhooks-lb-schedule.adoc#_verify_the_webhook_payload[Verifying the webhook payload].

=== Before you begin

Check your application environment for the following prerequisites:

* Ensure that you have access to a ThoughtSpot instance with the required permissions to set communication channel preferences, create and manage webhooks, and schedule Liveboard jobs. +
If your instance has Role-based Access Control (RBAC) enabled, you must have the `CAN_MANAGE_WEBHOOKS` privilege to create and manage webhooks.
* Ensure that the REST APIs for setting communication channel preference and configuring webhooks are enabled on your instance.
* To allow outbound traffic from the ThoughtSpot to the webhook endpoint, add the webhook destination URL to the xref:security-settings.adoc#csp-connect-src[CSP connect-src] allowlist in ThoughtSpot.
* Add the ThoughtSpot application URL as a trusted host in your Webhook destination endpoint/app.

=== Configure a webhook communication channel for the Liveboard Schedule event

To create a webhook communication channel, use the system REST APIs.

In the current release, ThoughtSpot supports configuring a communication channel only for Liveboard schedule events.

==== Create a webhook communication channel

To create the webhook communication channel and set messaging preferences, send a `POST` request to the `/api/rest/2.0/system/preferences/communication-channels/configure` API endpoint. You can set preferences at the cluster level for all Orgs or at the Org level. When both are configured, the preferences set at the Org level take precedence.

===== Request parameters

[width="100%" cols="1,2,6"]
[options='header']
|=====
|Parameter|Description |
.3+| `cluster_preferences` 2+|__Array of strings__. Sets default preferences for all Orgs in the instance. You must specify the following parameters:

|`event_type`
a|__String__. Type of the event for which communication channels are configured. For Liveboard schedule event, set the parameter value as `LIVEBOARD_SCHEDULE`.

|`channels` a|
__Array of strings__. Communication channel for the event type specified in the request. Valid values are: +

* `EMAIL`
* `WEBHOOK` +
To create a webhook channel for the Liveboard schedule event, specify `WEBHOOK`.

.5+| `org_preferences`  2+|__Array of strings__. By default, preferences configured at the cluster level will apply to all Orgs in the instance. To override the default preferences for your Org, set the Org-specific preferences:

| `org_identifier`  a|
__String__. Name or ID of the Org.
| `preferences` a|
__Array of strings__. Define the following parameters to set communication channel preferences for the Org. If the preferences are not set, the Org will inherit the default preferences applied at the cluster level.

* `event_type` +
__String__. Type of the event for which communication channels are configured. For Liveboard schedule event, set the parameter value as `LIVEBOARD_SCHEDULE`.
* `channels` +
__Array of strings__. Communication channel for the event type specified in the request. Valid values are: +
+
** `EMAIL`
** `WEBHOOK` +
To set up a webhook channel for the Liveboard schedule event, specify `WEBHOOK`.

| `operation` a|__String__. Type of operation. The following options are available:

** `REPLACE` - To replace default preferences.
** ``RESET` - To restore default preferences. For reset operation, you'll also need to specify the event type. Note that this operation will remove any Org-specific overrides and restores the default preferences configured at the cluster level.

|`reset_events` a|__Array of strings__. For RESET operations, specify the event type to reset. Note that the reset operation removes  Org-specific configuration for the events specified in `reset_events`.
|||
|=====


===== Example request

The following example shows the request body for setting a communication channel preference at the cluster level.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/system/preferences/communication-channels/configure'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "cluster_preferences": [
    {
      "event_type": "LIVEBOARD_SCHEDULE",
      "channels": [
        "WEBHOOK"
      ]
    }
  ]
}'
----

The following example shows the sample request for setting communication channel preference at the Org level.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/system/preferences/communication-channels/configure'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "org_preferences": [
    {
      "org_identifier": "docstest",
      "operation": "REPLACE",
      "preferences": [
        {
          "event_type": "LIVEBOARD_SCHEDULE",
          "channels": [
            "WEBHOOK"
          ]
        }
      ]
    }
  ]
}'
----

===== API response
If the request is successful, the API returns a 204 response indicating successful operation.

==== View the communication channel preferences

To review and audit the communication channel preferences set on your instance, send a `POST` request to the `POST /api/rest/2.0/system/preferences/communication-channels/search` API endpoint.

to audit, review, or display the current communication channel settings, ensuring compliance or troubleshooting notification issues.

===== Request parameters

[width="100%" cols="2,4"]
[options='header']
|=====
|Parameter|Description

|`cluster_preferences` +
__Optional__ a|__Array of strings__. To filter API response by event type, specify the event type for which the communication channel preference is set at the cluster level.
| `org_preferences` +
__Optional__ a|__Array of strings__. To filter API response by Org-specific overrides, specify the following parameters:

* `org_identifier` __-String__. +
Name or ID of the Org.
* `event_types` __Array of strings__ +
Event types to search for. To get channel preferences for Liveboard schedule events, specify `LIVEBOARD_SCHEDULE`.
|=====

===== Example request

The following request fetches channel preferences configured for the Liveboard schedule event at the cluster level:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/system/preferences/communication-channels/search'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "cluster_preferences": [
    "LIVEBOARD_SCHEDULE"
  ]
}'
----

The following request fetches channel preferences configured for the Liveboard schedule event at the Org level:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/system/preferences/communication-channels/search'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "org_preferences": [
    {
      "org_identifier": "docstest",
      "event_types": [
        "LIVEBOARD_SCHEDULE"
      ]
    }
  ]
}'
----

If the request is successful, the API returns a 204 response indicating successful operation.

===== Example response

The following example shows the communication preferences configured for the specified event type at the cluster level:

[source,JSON]
----
{
  "cluster_preferences": [],
  "org_preferences": [
    {
      "org": {
        "id": "0",
        "name": "Primary"
      },
      "preferences": []
    },
    {
      "org": {
        "id": "1532970882",
        "name": "nr-git-prod"
      },
      "preferences": [
        {
          "event_type": "LIVEBOARD_SCHEDULE",
          "channels": [
            "EMAIL",
            "WEBHOOK"
          ]
        }
      ]
    },
    {
      "org": {
        "id": "2100019165",
        "name": "docstest"
      },
      "preferences": [
        {
          "event_type": "LIVEBOARD_SCHEDULE",
          "channels": [
            "WEBHOOK"
          ]
        }
      ]
    }
  ]
}
----

The following example shows the preferences returned for a specific Org:

[source,JSON]
----
{
  "cluster_preferences": [],
  "org_preferences": [
    {
      "org": {
        "id": "2100019165",
        "name": "docstest"
      },
      "preferences": [
        {
          "event_type": "LIVEBOARD_SCHEDULE",
          "channels": [
            "WEBHOOK"
          ]
        }
      ]
    }
  ]
}
----

=== Configure a webhook for the Liveboard Schedule event

To configure webhooks for the Liveboard schedule event, use the webhook REST API.

==== Create a webhook

To create a webhook for the Liveboard schedule event, send a `POST` request to the `/api/rest/2.0/webhooks/create` API endpoint. ThoughtSpot allows only one webhook per Org.

===== Request parameters

[width="100%" cols="1,6"]
[options='header']
|=====
|Parameter|Description
| `name` a|__String__. Name of the webhook.
| `description` +
__Optional__ a|__String__. Description text for the webhook
| `url` a|__String__. The fully qualified URL of the listening endpoint where the webhook payload will be sent. The webhook endpoint to which you want to send notifications.
|`url_params` a| A JSON map of key-value pairs of parameters to add as a GET query params in the webhook URL.
| `events` a|__Array of strings__. List of events to subscribe to. Specify the event as `LIVEBOARD_SCHEDULE`.
|`authentication` a|

Defines authentication method and credentials that ThoughtSpot will use when sending making HTTP requests to the webhook endpoint.

Specify the authentication type.

* `API_KEY` +
API key to authorize the payload requests. Specify the API key to use in the `X-API-Key` request header.
* `BASIC_AUTH` +
Authentication methods with username and password.
* `BEARER_TOKEN` +
Authentication token to authenticate and authorize requests.
* `OAUTH2` +
OAuth credentials to authorize API requests. Specify client ID, client secret key, and authorization URL.
If the registered webhook has Oauth authentication enabled, `Authorization: Bearer <access-token>` is sent in the request header.
|`signature_verification` +
__Optional__ a| Signature verification parameters for the webhook endpoint to verify the authenticity of incoming requests. This typically involves ThoughtSpot signing the webhook payload with a secret, and your webhook endpoint validating this signature using the shared secret.

If using signature verification, specify the following parameters.

* `type` +
Signature verification type. Supported type is `HMAC_SHA256`, which uses Hash-based Message Authentication Code (HMAC) algorithm with the SHA-256 hash function to generate a cryptographic signature for webhook payloads. When configured, ThoughtSpot will sign the webhook payload using a shared secret and the HMAC_SHA256 algorithm. Your receiving endpoint should use the same secret and algorithm to compute the HMAC of the received payload and compare it to the signature sent by ThoughtSpot.

* `header` +
HTTP header where the signature is sent.
* `algorithm` +
Hash algorithm used for signature verification.
* `secret` +
Shared secret used for HMAC signature generation.
|=====

===== Example request
The following example shows the request body for creating a webhook:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/webhooks/create'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "name": "webhook-lb-event",
  "url": "https://webhook.site/6643eba5-9d3e-42a1-85e0-bb686ba1524d",
  "events": [
    "LIVEBOARD_SCHEDULE"
  ],
  "authentication": {
    "BEARER_TOKEN": "Bearer {AUTH_TOKEN}"
  }
  "description": "Webhook for Liveboard schedule"
}'
----

===== Example response

If the webhook creation is successful, the API returns the following response:

[source,JSON]
----
{
  "id": "873dd4e2-6493-490d-a649-ba9ea66b11f5",
  "name": "webhook-lb-event",
  "description": "Webhook for Liveboard schedule",
  "org": {
    "id": "2100019165",
    "name": "docstest"
  },
  "url": "https://webhook.site/6643eba5-9d3e-42a1-85e0-bb686ba1524d",
  "url_params": null,
  "events": [
    "LIVEBOARD_SCHEDULE"
  ],
  "authentication": BEARER_TOKEN,
  "signature_verification": null,
  "creation_time_in_millis": 1761050197164,
  "modification_time_in_millis": 1761050197164,
  "created_by": {
    "id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
    "name": "UserA@thoughtspot.com"
  },
  "last_modified_by": null
}
----

==== View webhook properties

To view the properties of a webhook or get a list of webhooks configured on your ThoughtSpot instance, send a `POST` request to the `/api/rest/2.0/webhooks/search` API endpoint.

To get specific information, define the following parameters. If the API request is sent without any parameters in the request body, ThoughtSpot returns the webhooks configured for the Org contexts in ThoughtSpot.

===== Request parameters

[width="100%" cols="2,4"]
[options='header']
|=====
|Parameter|Description
| `org_identifier` +
__Optional__ |__String__. ID or name of the Org.
| `webhook_identifier` +
__Optional__ | __String__. ID or name of the webhook.
|`event_type` +
__Optional__| __String__. Type of webhook event to filter by. For Liveboard schedule events, specify `LIVEBOARD_SCHEDULE`.
|Pagination settings a| If fetching multiple records, specify the following parameters to paginate API response: +

* `record_offset` +
__Integer__. Specifies the starting point (index) from which records should be returned. Default is 0.
* `record_size` +
__Integer__. Specifies the number of records to return in the response. Default is 50.
| `sort_options` +
__Optional__|  Enables sorting of the API response by a specific field in ascending or descending order. Specify the `field_name` and define the desired sort order.
|
|=====

===== Example request

The following example shows the request body to fetch webhook properties:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/webhooks/search'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "record_offset": 0,
  "record_size": 50,
  "org_identifier": "docstest",
  "event_type": "LIVEBOARD_SCHEDULE"
}'
----

===== Example response

If the API request is successful, ThoughtSpot returns the webhook configuration details:

[source,JSON]
----
{
  "webhooks": [
    {
      "id": "873dd4e2-6493-490d-a649-ba9ea66b11f5",
      "name": "webhook-lb-event",
      "description": "Webhook for Liveboard schedule",
      "org": {
        "id": "2100019165",
        "name": "docstest"
      },
      "url": "https://webhook.site/view/6643eba5-9d3e-42a1-85e0-bb686ba1524d/29c02fc2-c1c6-4b20-8d62-e8d51cf8dfb3",
      "url_params": null,
      "events": [
        "LIVEBOARD_SCHEDULE"
      ],
      "authentication": null,
      "signature_verification": null,
      "creation_time_in_millis": 1761050197164,
      "modification_time_in_millis": 1761051944507,
      "created_by": {
        "id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
        "name": "UserA@thoughtspot.com"
      },
      "last_modified_by": {
        "id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
        "name": "UserA@thoughtspot.com"
      }
    }
  ],
  "pagination": {
    "record_offset": 0,
    "record_size": 50,
    "total_count": 1,
    "has_more": false
  }
}
----

==== Update the properties of a webhook

To update the properties of a webhook, send a `POST` request to the `/api/rest/2.0/webhooks/{webhook_identifier}/update` API endpoint.

===== Request parameters

Specify the `webhook_identifier` and pass it as a path parameter in the request URL.

The API operation allows you to update the following webhook properties:

* `name` +
Name of the webhook.
* `description` +
Description text of the webhook.
* `url` +
The URL of the webhook endpoint.
* `url_params` +
* `events` +
Events subscribed to the webhook. In the current release, ThoughtSpot supports only the `LIVEBOARD_SCHEDULE` event.
* `authentication` +
Authentication method and credentials that ThoughtSpot will use when sending HTTP requests to the webhook endpoint
* `signature_verification` +
Signature verification parameters for the webhook endpoint to verify the authenticity of incoming requests.

===== Example request

The following example shows the request body for updating the properties of a webhook:

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/webhooks/webhook-lb-test/update'  \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "name": "webhook-lb-event",
  "description": "Webhook for Liveboard schedule event",
  "url": "https://webhook.site/6643eba5-9d3e-42a1-85e0-bb686ba1524d/2e5251b2-8274-41f6-80a0-1b82854df31f",
  "events": [
    "LIVEBOARD_SCHEDULE"
  ]
}'
----

===== Example response

If the API request is successful, the API returns a 204 response code indicating a successful operation.

==== Delete a webhook

To delete a webhook, send a `POST` request to the `/api/rest/2.0/webhooks/delete` endpoint.

===== Request parameters

[width="100%" cols="2,4"]
[options='header']
|=====
|`webhook_identifiers` |__Array of strings__. ID of name of the webhooks to delete.
|=====

===== Example request

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/webhooks/delete'  \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {AUTH_TOKEN}' \
  --data-raw '{
  "webhook_identifiers": [
    "webhook-lb-test"
  ]
}'
----

===== Example response

If the API request is successful, ThoughtSpot details of the deleted webhook.

[source,JSON]
----
{
  "deleted_count": 1,
  "failed_count": 0,
  "deleted_webhooks": [
    {
      "id": "45fe7810-3239-4761-94fd-04c017df29c4",
      "name": "webhook-test",
      "description": "Webhook for testing purposes",
      "org": {
        "id": "1574427524",
        "name": "testOrg2025"
      },
      "url": "https://webhook.site/6643eba5-9d3e-42a1-85e0-bb686ba1524d/2e5251b2-8274-41f6-80a0-1b82854df31f",
      "url_params": null,
      "events": [
        "LIVEBOARD_SCHEDULE"
      ],
      "authentication": null,
      "signature_verification": null,
      "creation_time_in_millis": 1761184185887,
      "modification_time_in_millis": 1761184185887,
      "created_by": {
        "id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
        "name": "UserA@thoughtspot.com"
      },
      "last_modified_by": null
    }
  ],
  "failed_webhooks": []
}
----

=== Verify the webhook payload

If the webhook channel is configured for Liveboard schedule events and a webhook is created for the event, it can be applied to all Liveboard schedules in an Org.

For testing purposes, you can use a URL from the link:https://webhook.site/[Webhook site, window=_blank] and check the payload when the Liveboard schedule event is triggered. You can also monitor the incoming requests on the link:https://webhook-test-server-263n.onrender.com/[Webhooks test site, window=_blank].

When a Liveboard schedule event is triggered based on the conditions defined in the schedule, the webhook sends the payload to the configured endpoint. Depending upon the Liveboard job settings, the payload includes metadata such as webhook communication channel ID, recipient details, Liveboard schedule details, event properties, and a link to the Liveboard.

[source,JSON]
----
{
  "actor": {
    "actorType": "SYSTEM"
  },
  "data": {
    "aiHighlights": "",
    "channelID": "873dd4e2-6493-490d-a649-ba9ea66b11f5",
    "channelType": "webhook",
    "communicationType": "LiveboardSchedules",
    "msgUniqueId": "881fd036-5b2e-4e34-928c-e3839b2e5765",
    "recipients": [
      {
        "email": "UserA@thoughtspot.com",
        "id": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
        "locale": "en_GB",
        "name": "UserA",
        "type": "USER"
      }
    ],
    "scheduleDetails": {
      "authorId": "08c6b203-ff6e-4ed8-b923-35ebbbfef27b",
      "creationTime": "2025-10-21T12:51:01Z",
      "description": "",
      "emailIds": [],
      "exportRequest": {
        "liveboard_params": {
          "layout_type": "LIVEBOARD",
          "liveboard_viz_selection": {
            "complete_liveboard": true
          },
          "personalised_view_id": "",
          "print_document_params": {
            "include_cover_page": false,
            "include_filter_page": false,
            "pageFooterParams": {
              "include_logo": true,
              "include_page_number": true,
              "text": ""
            }
          },
          "visualization_format_options": {
            "truncate_tables": true
          }
        },
        "object_type": "LIVEBOARD",
        "output_type": "PDF",
        "pdf_params": {
          "orientation": "LANDSCAPE",
          "page_size": "A4"
        },
        "request_type": "SCHEDULE"
      },
      "fileFormat": "pdf",
      "groupIds": [],
      "name": "Sales-LB - Custom",
      "runId": "dc232f76-064f-4f40-a771-7c4a6f6a2906",
      "scheduleId": "e4bd8b30-dfad-490a-b09a-a50e969f7d32",
      "status": "SCHEDULED",
      "userIds": [],
      "viewInfo": null
    }
  },
  "eventId": "n.820c00f9-d7ef-48e9-ab08-2ec1a48de0ab",
  "eventType": "LIVEBOARD_SCHEDULE",
  "metadataObject": {
    "id": "daeef525-926a-44fc-9dbf-7dfa993d913a",
    "name": "Sales-LB",
    "objectType": "LIVEBOARD",
    "url": "https://my.thoughtspot.cloud/?utm_source=scheduled-pinboard&utm_medium=email&orgId=2100019165#/pinboard/daeef525-926a-44fc-9dbf-7dfa993d913a"
  },
  "schemaVersion": "1.0",
  "source": {
    "applicationName": "ThoughtSpot",
    "applicationUrl": "hhttps://my.thoughtspot.cloud",
    "instanceId": "672764c0-dc60-11ee-a6bf-13c83",
    "orgId": "2100019165"
  },
  "timestamp": "2025-10-21T13:05:31Z"
}
----

As shown in the preceding example, the JSON payload includes the following content:

* `actor` +
Initiator of the event. The actor type can be `USER`, `SYSTEM`, or `API_CLIENT`.
* `channelID` +
The communication channel ID used for event dissemination.
* `channelType` +
Type of the communication channel. The channel type used for webhook payloads is `webhook`.
* `communicationType` +
Type of the messaging event. For Liveboard schedule events, the communication type will be `LiveboardSchedules`.
* `MyUniqueID` +
Unique ID of the webhook payload. This ID can be used for traceability and deduplication on the receiving end.
* `recipients` +
Details of the ThoughtSpot users, groups, and email addresses of the external users who are configured as subscribers of the Liveboard schedule notifications and recipients of the webhook payload.
* `scheduleDetails` +
Details of the Liveboard schedule that triggered the event. This includes the schedule ID, object type, and output format. If the Liveboard job is configured to send data as a downloadable PDF, the file format will be set as `PDF`.
* `eventID` and `eventType` +
The ID and type of the event. For Liveboard schedule events, the type is `LIVEBOARD_SCHEDULE`.
* `metadataObject` +
Details of the Liveboard object.
* `schemaVersion` +
Schema version of the payload.
* `timestamp` +
Timestamp of when the event occurred.
* `source` +
Source of the webhook payload trigger. This includes the ThoughtSpot application name, URL, instance ID, and the ID of the Org context in ThoughtSpot.

Along with the JSON payload, if the Liveboard schedule is configured to send a PDF version of the Liveboard, a PDF attachment will be included in the payload.

== Additional resources

* link:https://docs.thoughtspot.com/cloud/latest/liveboard-schedule[Scheduling Liveboard jobs, window=_blank]
* +++<a href="{{navprefix}}/restV2-playground?apiResourceId=http%2Fapi-endpoints%2Fschedules%2Fcreate-schedule">Liveboard schedule REST APIs</a>+++




