= Webhooks
:toc: true

:page-title: Webhooks
:page-pageid: webhooks
:page-description: Register a webhook to send KPI monitor and Liveboard schedule alerts to an external application

Webhooks in ThoughtSpot provide a way to automate workflows and integrate with external systems by sending real-time notifications when specific events occur. In ThoughtSpot, webhooks can be used for two alerting use cases:

* Liveboard schedule alerts [beta betaBackground]^Beta^ +
ThoughtSpot supports using a xref:webhooks-lb-schedule.adoc[webhook for delivering scheduled Liveboard notifications] to external applications and communication channels.

* KPI alerts +
For KPI charts in a Liveboard or Answer, ThoughtSpot allows creating and scheduling alerts. KPI Monitor alerts notify users when a KPI metric meets a threshold condition or periodically as per the schedule configured by the user. You can send these alerts using a webhook and notify external applications when a KPI meets a defined threshold or changes value. For more information, see xref:webhooks-kpi-alerts.adoc[Webhooks for KPI monitor alerts].


== Webhook configuration

ThoughtSpot users with developer or administrator privileges can create webhooks via REST APIs or from the *Develop* page in the UI.

Webhooks configured via the REST API::
The REST API framework webhook configuration is intended for automation and integration scenarios; for example, delivering attachments to an external application or storage destinations such as the Amazon Web Services (AWS) S3 bucket. Currently, the Webhook REST APIs support creating and managing webhooks for Liveboard schedule events only.

Webhooks created from the Develop > Webhook page::
Webhooks created from the Develop page in the UI are typically used for integrating with KPI alerts. These webhooks are managed through the UI and can be selected as custom channels when configuring KPI alert notifications in the UI.

[NOTE]
====
* Webhooks created from the **Develop** page are different from the webhooks configured via REST APIs and follow a separate flow. Use REST APIs to create webhooks for custom notification channels or external storage destinations.
* To set up a webhook for Liveboard schedule notifications, you must first configure the xref:webhooks-comm-channel.adoc[webhook communication channel using the communication-channel preferences API].
====

== Integration with Amazon S3 bucket [beta betaBackground]^Beta^

Starting with the ThoughtSpot 26.3.0.cl release, ThoughtSpot supports configuring an Amazon S3 bucket as the storage destination for delivering webhook attachments via REST APIs.

For more information, see xref:webhooks-s3-storage.adoc[S3 storage integration for Webhook delivery].

== Response after webhook delivery

When a webhook delivery is attempted for a Liveboard schedule event, the webhook endpoint must respond with an HTTP 2xx status code within 5 seconds to confirm successful receipt and processing of the request.

If your server takes longer than 5 seconds to respond, returns a response code other than 2xx, or times out, ThoughtSpot may still deliver the Liveboard data and files. However, the notification status will be recorded as `FAILED` in the ThoughtSpot notification, and the request will be retried.

To ensure a timely response, we recommend processing webhook payloads asynchronously. Your server can immediately return a 2xx response upon receipt of the webhook and then handle the payload in the background without blocking subsequent webhook deliveries.

== Webhook payload
For information about the payload content delivered to a target destination, see xref:webhooks-payload.adoc[Webhook payload for Liveboard events].
