:toc: true
:toclevels: 2
:page-title: LiveboardEmbed
:page-pageid: Class/LiveboardEmbed
:page-description: Embed a ThoughtSpot Liveboard or a Thoughtspot visualization. When rendered it already waits for the authentication to complete, so no need to wait for AuthStatus.SUCCESS.

= LiveboardEmbed

Embed a ThoughtSpot Liveboard or a Thoughtspot visualization. When rendered it already
waits for the authentication to complete, so no need to wait for AuthStatus.SUCCESS.



`example` : 
```js
import { .. } from '@thoughtspot/visual-embed-sdk';
init({ ... });
const embed = new LiveboardEmbed("#container", {
  liveboardId: <your-id-here>,
// .. other params here.
})
```



`group` : Embed components





== Constructors

=== constructor



`Overrides V1Embed.constructor`



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/liveboard.ts#L125[embed/liveboard.ts, window=_blank]

[source, js]
----

new LiveboardEmbed(domSelector: DOMSelector , viewConfig: LiveboardViewConfig ) : LiveboardEmbed

----



==== Parameters

* domSelector: xref:DOMSelector.adoc[DOMSelector]



* viewConfig: xref:LiveboardViewConfig.adoc[LiveboardViewConfig]



==== Returns

xref:LiveboardEmbed.adoc[LiveboardEmbed]

== Methods

=== destroy





`Inherited from  V1Embed.destroy`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L811[embed/ts-embed.ts, window=_blank]

[source, js]
----

destroy() : void

----

Destroys the ThoughtSpot embed, and remove any nodes from the DOM.



`version` : SDK: 1.19.1 | ThoughtSpot: *









==== Returns

void

=== getThoughtSpotPostUrlParams





`Inherited from  V1Embed.getThoughtSpotPostUrlParams`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L783[embed/ts-embed.ts, window=_blank]

[source, js]
----

getThoughtSpotPostUrlParams() : string

----

Get the Post Url Params for THOUGHTSPOT from the current
host app URL.
THOUGHTSPOT URL params starts with a prefix "ts-"



`version` : SDK: 1.14.0 | ThoughtSpot: 8.4.0.cl, 8.4.1-sw









==== Returns

string

=== getUnderlyingFrameElement





`Inherited from  V1Embed.getUnderlyingFrameElement`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L819[embed/ts-embed.ts, window=_blank]

[source, js]
----

getUnderlyingFrameElement() : HTMLIFrameElement

----







==== Returns

xref:HTMLIFrameElement.adoc[HTMLIFrameElement]

=== navigateToLiveboard







Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/liveboard.ts#L263[embed/liveboard.ts, window=_blank]

[source, js]
----

navigateToLiveboard(liveboardId: string , vizId?: string , activeTabId?: string ) : void

----



==== Parameters

* liveboardId: string



* vizId: string



* activeTabId: string



==== Returns

void

=== off





`Inherited from  V1Embed.off`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L715[embed/ts-embed.ts, window=_blank]

[source, js]
----

off(messageType: EmbedEvent , callback: MessageCallback ) : TsEmbed

----

Removes an event listener for a particular event type.



`example` : 
```js
const errorHandler = (data) => { console.error(data); };
tsEmbed.on(EmbedEvent.Error, errorHandler);
tsEmbed.off(EmbedEvent.Error, errorHandler);
```





==== Parameters

* messageType: xref:EmbedEvent.adoc[EmbedEvent]


The message type



* callback: xref:MessageCallback.adoc[MessageCallback]


The callback to remove



==== Returns

xref:TsEmbed.adoc[TsEmbed]

=== on





`Inherited from  V1Embed.on`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L886[embed/ts-embed.ts, window=_blank]

[source, js]
----

on(messageType: EmbedEvent , callback: MessageCallback , options?: MessageOptions = ...) : TsEmbed

----





`example` : 
```js
tsEmbed.on(EmbedEvent.Error, (data) => {
  console.error(data);
});
```



`example` : 
```js
tsEmbed.on(EmbedEvent.Save, (data) => {
  console.log("Answer save clicked", data);
}, {
  start: true // This will trigger the callback on start of save
});
```





==== Parameters

* messageType: xref:EmbedEvent.adoc[EmbedEvent]



* callback: xref:MessageCallback.adoc[MessageCallback]



* options: xref:MessageOptions.adoc[MessageOptions] = ...



==== Returns

xref:TsEmbed.adoc[TsEmbed]

=== prerenderGeneric





`Inherited from  V1Embed.prerenderGeneric`

Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/ts-embed.ts#L831[embed/ts-embed.ts, window=_blank]

[source, js]
----

prerenderGeneric() : Promise<any>

----

Prerenders a generic instance of the TS component.
This means without the path but with the flags already applied.
This is useful for prerendering the component in the background.



`version` : SDK: 1.22.0








==== Returns

xref:Promise.adoc[Promise]<any>

=== render



`Overrides V1Embed.render`



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/liveboard.ts#L254[embed/liveboard.ts, window=_blank]

[source, js]
----

render() : LiveboardEmbed

----

Render an embedded ThoughtSpot Liveboard or visualization








==== Returns

xref:LiveboardEmbed.adoc[LiveboardEmbed]

=== trigger



`Overrides V1Embed.trigger`



Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/embed/liveboard.ts#L240[embed/liveboard.ts, window=_blank]

[source, js]
----

trigger(messageType: HostEvent , data?: any = {}) : Promise<any>

----

Triggers an event to the embedded app




==== Parameters

* messageType: xref:HostEvent.adoc[HostEvent]


The event type



* data: any = {}


The payload to send with the message




==== Returns

xref:Promise.adoc[Promise]<any>