:toc: true
:toclevels: 2
:page-title: EmbedConfig
:page-pageid: Interface/EmbedConfig
:page-description: The configuration object for embedding ThoughtSpot content. It includes the ThoughtSpot hostname or IP address, the type of authentication, and the authentication endpoint if a trusted authentication server is used.

= EmbedConfig

The configuration object for embedding ThoughtSpot content.
It includes the ThoughtSpot hostname or IP address,
the type of authentication, and the authentication endpoint
if a trusted authentication server is used.



`group` : Authentication / Init





== Properties

* authEndpoint: string

[AuthServer] The trusted authentication endpoint to use to get the
authentication token. A GET request is made to the
authentication API endpoint, which  returns the token
as a plaintext response. For trusted authentication,
the `authEndpoint` or `getAuthToken` attribute is required.




* authTriggerContainer: string | HTMLElement

For inPopup SAMLRedirect or OIDCRedirect Auth, we need a button which the user
click to trigger the flow. This is the containing element
for that button.



`example` : 
```js
init({
  authType: AuthType.SAMLRedirect,
  inPopup: true,
  authTriggerContainer: '#auth-trigger-container'
})
```



`version` : SDK: 1.17.0 | ThoughtSpot: *





* authTriggerText: string

Text to show in the button which triggers the popup auth flow.
Default: "Authorize".



`version` : SDK: 1.17.0 | ThoughtSpot: *





* authType: xref:AuthType.adoc[AuthType]

The authentication mechanism to use.




* autoLogin: boolean

Re-login when session expires with the previous login options



`default` : false





* callPrefetch: boolean

Calls the prefetch method internally when set to true



`default` : false





* customCssUrl: string

Dynamic CSS Url to be injected in the loaded application.
You would also need to set `style-src` in the CSP settings.



`version` : SDK: 1.6.0 | ThoughtSpot: ts8.nov.cl, 8.4.1-sw



`default` : ''





* customizations: xref:CustomisationsInterface.adoc[CustomisationsInterface]

Custom style params for embed Config.



`version` : SDK: 1.17.0 | ThoughtSpot: 8.9.0.cl





* detectCookieAccessSlow: boolean

[AuthServer|Basic] Detect if 3rd party cookies are enabled by doing an
additional call. This is slower and should be avoided. Listen to the
NO_COOKIE_ACCESS event to handle the situation.
This is slightly slower than letting the browser handle the cookie check, as it
involves an extra network call.



`version` : SDK: 1.10.4 | ThoughtSpot: 8.2.0.cl, 8.4.1-sw





* disableLoginRedirect: boolean

Disable redirection to the login page when the embedded session expires
This flag is typically used alongside the combination of auth modes such as {@link
AuthType.AuthServer} and auto login behavior xref:EmbedConfig.adoc#autoLogin[EmbedConfig]



`version` : SDK: 1.9.3 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw



`default` : false





* inPopup: boolean

[SSO] For SSO Authentication, if `inPopup` is set to true, it will open
the SAML auth flow in a popup, instead of redirecting browser in place.
Need to use this with authTriggerContainer. Or manually trigger
the AuthEvent.TRIGGER_SSO_POPUP event on a user interaction.



`default` : false



`version` : SDK: 1.18.0





* loginFailedMessage: string

This message is displayed on the embed view when the login fails.



`version` : SDK: 1.10.1 | ThoughtSpot: 8.2.0.cl, 8.4.1-sw





* noRedirect: boolean

[SSO] For SSO Authentication, if `noRedirect` is set to true, it will
open the SAML auth flow in a popup, instead of redirecting browser in
place.



`default` : false



`deprecated` : 





* password: string

[Basic] The ThoughtSpot login password corresponding to the user name
Warning: This feature is primarily intended for developer testing. It is
strongly advised not to use this authentication method in production.




* queueMultiRenders: boolean

When there are multiple embeds, queue the render of embed to start
 after the previous embed's render is complete. This helps in the load
 performance by decreasing the load on the browser.



`version` : SDK: 1.5.0 | ThoughtSpot: ts7.oct.cl, 7.2.1



`default` : false





* redirectPath: string

[SSO] For SSO Authentication, one can supply an optional path param,
this will be the path on the host origin where the SAML flow will be
terminated.
Eg: "/dashboard", "#/foo" [Do not include the host]



`version` : SDK: 1.10.2 | 8.2.0.cl, 8.4.1-sw





* shouldEncodeUrlQueryParams: boolean

Should we encode URL Query Params using base64 encoding which thoughtspot
will generate for embedding. This provides additional security to
thoughtspot clusters against Cross site scripting attacks.



`default` : false





* suppressNoCookieAccessAlert: boolean

Suppress cookie access alert when third party cookies are blocked by the
user's browser. Third party cookie blocking is the default behaviour on
Safari and opt-in for Firefox/Chrome. If you set this to `true`, you are
encouraged to handle `noCookieAccess` event, to show your own treatment
in this case.



`default` : false





* suppressSearchEmbedBetaWarning: boolean

Hide beta alert warning message for SearchEmbed.



`version` : SDK: 1.12.0 | ThoughtSpot: 8.4.0.cl, 8.4.1-sw*





* thoughtSpotHost: string

The ThoughtSpot cluster hostname or IP address.




* useEventForSAMLPopup: boolean

Specify that we want to use the AuthEvent.TRIGGER_SSO_POPUP event to trigger
SAML popup. This is useful when you want to trigger the popup on a custom user
action.




* username: string

[AuthServer / Basic] The user name of the ThoughtSpot user. This
attribute is required for trusted authentication.




== Methods

=== getAuthToken







Defined in : link:https://github.com/thoughtspot/visual-embed-sdk/blob/main/src/types.ts#L273[types.ts, window=_blank]

[source, js]
----

getAuthToken() : Promise<string>

----

[AuthServer] A function that invokes the trusted authentication endpoint
and returns a Promise that resolves to the `auth token` string.
For trusted authentication, the `authEndpoint` or `getAuthToken`
attribute is required.
It is advisable to fetch a new token inside this method and not
reuse and older issued token, as because when auth expires this is
called again and if it is called with an older token the authentication
will not succeed.








==== Returns

xref:Promise.adoc[Promise]<string>