:toc: true
:toclevels: 2
:page-title: LiveboardViewConfig
:page-pageid: Interface/LiveboardViewConfig
:page-description: The configuration for the embedded Liveboard or visualization page view.

= LiveboardViewConfig

The configuration for the embedded Liveboard or visualization page view.



`group` : Embed components





== Properties

* activeTabId: string

Tab Id of the Liveboard that is supposed to be active



`version` : SDK: 1.15.0 | ThoughtSpot: 8.7.0.cl, 8.8.1-sw





* additionalFlags: [key: string ] : string | number | boolean

This is an object (key/val) of override flags which will be applied
to the internal embedded object. This can be used to add any
URL flag.
Warning: This option is for advanced use only and is used internally
to control embed behavior in non-regular ways. We do not publish the
list of supported keys and values associated with each.



`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw





* contextMenuTrigger: xref:ContextMenuTriggerOptions.adoc[ContextMenuTriggerOptions]

flag to set ContextMenu Trigger to either left or right click.



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl





* customizations: xref:CustomisationsInterface.adoc[CustomisationsInterface]

Dynamic CSSUrl and customCSS to be injected in the loaded application.
You would also need to set `style-src` in the CSP settings.



`version` : SDK: 1.17.2 | ThoughtSpot: 8.4.1-sw, 8.4.0.cl



`default` : ''





* defaultHeight: number

This is the minimum height(in pixels) for a full height Liveboard.
Setting this height helps resolves issues with empty Liveboards and
other screens navigable from a Liveboard.



`version` : SDK: 1.5.0 | ThoughtSpot: ts7.oct.cl, 7.2.1



`default` : 500





* disabledActionReason: string

The tooltip to display for disabled actions.




* disabledActions: Action[]

The list of actions to disable from the primary menu, more menu
(...), and the contextual menu. These actions will be disabled
for the user.
Use this to disable actions.



`example` : 
```js
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  disabledActions: [Action.Download, Action.Save]
});
```





* enableVizTransformations: boolean





`deprecated` : If set to true, the context menu in visualizations will be enabled.





* frameParams: xref:FrameParams.adoc[FrameParams]

The <b>width</b> and <b>height</b> dimensions to render an embedded
object inside your app.  Specify the values in pixels or percentage.




* fullHeight: boolean

If set to true, the embedded object container dynamically resizes
according to the height of the Liveboard.



`version` : SDK: 1.1.0 | ThoughtSpot: ts7.may.cl, 7.2.1





* hiddenActions: Action[]

The list of actions to hide from the embedded.
This actions will be hidden from the user.
Use this to hide an action.



`example` : 
```js
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  hiddenActions: [Action.Download, Action.Export]
});
```



`important` : 





* insertAsSibling: boolean

Insert as a sibling of the target container, instead of appending to a
child inside it.




* linkOverride: boolean

flag to override openNew tab context menu link



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl





* liveboardId: string

The Liveboard to display in the embedded view.
Use either of liveboardId or pinboardId to reference the Liveboard to embed.



`version` : SDK: 1.3.0 | ThoughtSpot ts7.aug.cl, 7.2.1





* liveboardV2: boolean

Render embedded Liveboards and visualizations in the new Liveboard experience mode



`version` : SDK: 1.14.0 | ThoughtSpot: 8.6.0.cl, 8.8.1-sw





* locale: string

The locale/language to use for the embedded view.



`version` : SDK: 1.9.4 | ThoughtSpot 8.1.0.cl, 8.4.1-sw





* preventLiveboardFilterRemoval: boolean

If set to true, all filter chips from a
Liveboard page will be read-only (no X buttons)



`version` : SDK: 1.3.0 | ThoughtSpot ts7.aug.cl, 7.2.1





* runtimeFilters: RuntimeFilter[]

The list of runtime filters to apply to a search answer,
visualization, or Liveboard.




* showAlerts: boolean

Show alert messages and toast messages in the embedded view.



`version` : SDK: 1.11.0 | ThoughtSpot: 8.3.0.cl, 8.4.1-sw





* usePrerenderedIfAvailable: boolean

Use a pre-rendered iframe from a pool of pre-rendered iframes
if available and matches the configuration.



`version` : SDK: 1.22.0

See [docs]() on how to create a prerender pool.





* visibleActions: Action[]

The list of actions to display from the primary menu, more menu
(...), and the contextual menu. These will be only actions that
are visible to the user.
Use this to hide all actions except the ones you want to show.
Use either this or hiddenActions.



`version` : SDK: 1.6.0 | ThoughtSpot: ts8.nov.cl, 8.4.1-sw



`important` : 





* visibleVizs: string[]

Array of viz ids which should be visible when the liveboard
first renders. This can be changed by triggering the "SetVisibleVizs"
event.



`version` : SDK: 1.9.1 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw





* vizId: string

The visualization within the Liveboard to display.


