:toc: true
:toclevels: 2
:page-title: SearchBarViewConfig
:page-pageid: Interface/SearchBarViewConfig
:page-description: 

= SearchBarViewConfig





`group` : Embed components





== Properties

* additionalFlags: [key: string ] : string | number | boolean

This is an object (key/val) of override flags which will be applied
to the internal embedded object. This can be used to add any
URL flag.
Warning: This option is for advanced use only and is used internally
to control embed behavior in non-regular ways. We do not publish the
list of supported keys and values associated with each.



`version` : SDK: 1.9.0 | ThoughtSpot: 8.1.0.cl, 8.4.1-sw





* contextMenuTrigger: xref:ContextMenuTriggerOptions.adoc[ContextMenuTriggerOptions]

flag to set ContextMenu Trigger to either left or right click.



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl





* customizations: xref:CustomisationsInterface.adoc[CustomisationsInterface]

Dynamic CSSUrl and customCSS to be injected in the loaded application.
You would also need to set `style-src` in the CSP settings.



`version` : SDK: 1.17.2 | ThoughtSpot: 8.4.1-sw, 8.4.0.cl



`default` : ''





* dataSource: string

The array of data source GUIDs to set on load.



`version:` : SDK: 1.19.0





* dataSources: string[]

The array of data source GUIDs to set on load.
Only a single dataSource supported currently.



`deprecated` : Use dataSource instead





* disabledActionReason: string

The tooltip to display for disabled actions.




* disabledActions: Action[]

The list of actions to disable from the primary menu, more menu
(...), and the contextual menu. These actions will be disabled
for the user.
Use this to disable actions.



`example` : 
```js
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  disabledActions: [Action.Download, Action.Save]
});
```





* frameParams: xref:FrameParams.adoc[FrameParams]

The <b>width</b> and <b>height</b> dimensions to render an embedded
object inside your app.  Specify the values in pixels or percentage.




* hiddenActions: Action[]

The list of actions to hide from the embedded.
This actions will be hidden from the user.
Use this to hide an action.



`example` : 
```js
const embed = new LiveboardEmbed('#embed', {
  ... // other liveboard view config
  hiddenActions: [Action.Download, Action.Export]
});
```



`important` : 





* insertAsSibling: boolean

Insert as a sibling of the target container, instead of appending to a
child inside it.




* linkOverride: boolean

flag to override openNew tab context menu link



`version` : SDK: 1.21.0 | ThoughtSpot: 9.2.0.cl





* locale: string

The locale/language to use for the embedded view.



`version` : SDK: 1.9.4 | ThoughtSpot 8.1.0.cl, 8.4.1-sw





* searchOptions: xref:SearchOptions.adoc[SearchOptions]

Configuration for search options




* usePrerenderedIfAvailable: boolean

Use a pre-rendered iframe from a pool of pre-rendered iframes
if available and matches the configuration.



`version` : SDK: 1.22.0

See [docs]() on how to create a prerender pool.





* visibleActions: Action[]

The list of actions to display from the primary menu, more menu
(...), and the contextual menu. These will be only actions that
are visible to the user.
Use this to hide all actions except the ones you want to show.
Use either this or hiddenActions.



`version` : SDK: 1.6.0 | ThoughtSpot: ts8.nov.cl, 8.4.1-sw



`important` : 



