= ThoughtSpot React Components Tutorial
:page-pageid: react-components__lesson-01
:description: Build a page that returns a ThoughtSpot component
:toc: true
:toclevels: 1

== app/dashboard/[dashboardId]/page.tsx
As mentioned in the intro, Next.js uses square brackets in a directory name to denote a variable route.

Note the URL says *dashboard*, rather than Liveboard. When embedding ThoughtSpot, you can present every aspect of ThoughtSpot as completely whitelabeled and matching your team's design preferences.

The React component should be able to load any Liveboard created within the ThoughtSpot system, if passed an ID that matches existing content.

The page starts with imports - some from React and some from the ThoughtSpot Visual Embed SDK.

[,typescript]
----
import { useEffect, useState } from "react";

import {
  LiveboardEmbed,
  useEmbedRef,
} from "@thoughtspot/visual-embed-sdk/react";
----
The React components of the ThoughtSpot Visual Embed SDK *wrap* around the embedded ThoughtSpot components, which remain 

`useEffect`, `useState` and `useEmbedRef` all are used for managing aspects of React that do not need to be re-run every time a component is refreshed.

