= Menus and other navigation elements
:page-pageid: react-components__lesson-03
:description: Use REST APIs to create menus and other navigation elements
:toc: true
:toclevels: 2

The ThoughtSpot component page from the previous lesson was designed to display any Liveboard with a valid ID as part of the URL.

While you can hardcode a set of known objects with their names and IDs into a navigation menu, ThoughtSpot's true power is allowing users to ask new questions and build their own answers and Liveboards.

The ThoughtSpot REST API provides the `/metadata/search` endpoint for listing out the content on the ThoughtSpot instance.

The REST API automatically filters the results to those objects a user has been granted access to via sharing, and provides many arguments for further filtering of the result set.

== /app/dashboard/page.tsx
The example app has a dedicated `page.tsx` to display a tabular menu of available Liveboards.

There are two steps to this page:

1. Make a REST API request to ThoughtSpot to retrieve the details of the objects
2. Building the table from the results, constructing links to the `/dashboard/{dashboardId}` page to display the Liveboard

== ThoughtSpot REST API TypeScript SDK
ThoughtSpot provides a link:https://developers.thoughtspot.com/docs/rest-api-sdk-typescript#_get_started[TypeScript REST API SDK^] that can be installed via Node and added to any React app.

The SDK allows calling any of the V2.0 REST API endpoints and returns in a native JSON format, making it ideal for retrieving the details of objects that a user can see.

To use the REST API SDK, import `createConfiguration`, `ServerConfiguration` and `ThoughtSpotRestApi` from `@thoughtspot/rest-api-sdk`:
[,typescript]
----
"use client";

import {useEffect, useState} from "react";
import Link from 'next/link';

/*
* Menu page to list available Liveboards to link to LiveboardEmbed display page
*/

import {createConfiguration, ServerConfiguration, ThoughtSpotRestApi} from "@thoughtspot/rest-api-sdk";

import {constants} from "@/lib/constants";
----

Note the `"use client";` at the very beginning of the code - this tells React that the REST API calls should be coming from the user's browser, rather than made on the server side. React doesn't explictly separate front and backend layers the way many traditional web application platforms did, so you have to be intentional when you do have a preference.

'''

xref:react-components_lesson-02.adoc[< Previous: 02 - ThoughtSpot component pages] | xref:react-components_lesson-04.adoc[Next: 04 - Event handling >]
