= ThoughtSpot React Components Tutorial
:page-pageid: react-components__intro
:description: This is a self-guided course on the ThoughtSpot Visual Embed SDK React Components
:toc: true
:toclevels: 2

ThoughtSpot provides React components as part of the Visual Embed SDK. 

There is also a REST API SDK available in TypeScript which can be included into any React app.

This tutorial walks through the process of installing and integrating the ThoughtSpot React components and REST API SDK into an exiting React app.

The tutorial will discuss common React app features and how to properly integrate the ThoughtSpot technologies into the React patterns.

== Getting started
link:https://react.dev/learn/thinking-in-react[React^] is a widely used web application framework. 

There are many great resources for understanding React itself, including the link:https://react.dev/learn/thinking-in-react[React project's own website]. In the tutorial, React concepts will be briefly explained in relation to integrating ThoughtSpot components within the embedding React app.

"React projects" almost always use many different packages on top of the baseline "React" install. 

Within the tutorial, all packages will be given a brief explanation, with links to those project's documentation. 

== Routes and pages
*Routes* are URLs that load different "pages" within the app. 

In some web application systems, a particular URL will load content from a distinct "page" that exists somewhere on the web server.

React apps are typically "single-page apps": rather than there being many separate "actual" HTML pages loaded by the web browser, an initial page is loaded and then updates are made to that "single page". 

*Routing* in React defines what components are retrieved for a given URL to update the "single page".

ThoughtSpot provides several different types of components that load objects using the specific IDs of content on the ThoughtSpot instance.

To make a flexible system, a page route must return the component and pass the ID of the content to load into the component.

=== React Router
The most common package for routing is *link:https://reactrouter.com/start/library/routing[react-router^]*, with most examples importing `react-router-dom` in their `App.tsx` file.

An example of a dynamic page route using React Router might look like: 

[,typescript]
----
const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    errorElement: <ErrorPage />,
  },
  {
    path: "dashboard/:id",
    element: <ThoughtSpotLiveboard />,
  },
]);
----

where the `:id` portion of the path will be passed on to the component as one of the *props*.  

=== Next.js
link:https://nextjs.org/docs/app/getting-started/project-structure[Next.js^] is a platform built on top of React, which provides automatic *file-based* routing via defined patterns.

Under the `app` directory, any subdirectory automatically becomes a URL route with the same name, with the `page.tsx` file inside defining the returned component.

Adding square brackets around a subdirectory name like `[variableName]` creates dynamic page route with the name in brackets sent to the component defined in `page.tsx`.

The tutorial app uses Next.js for routing.

== Tutorial app
The tutorial walks through building out an app using link:https://nextjs.org/docs/app/getting-started/project-structure[Next.js^]. 

The available pages are all defined under the `/app` structure.

=== app/layout.tsx
`app/layout.tsx` is a standard Next.js file that defines the overall layout of the app. 

It returns the `RootLayout()` function for the React framework, into with all other components will be added in as `{children}`.

The actual JSX that is returned is simple, as the tutorial app is composed of only a top menu and a full-width area for displaying ThoughtSpot content:

[,tsx]
----
 <body>
        <>
            <TopNavBar/>
            <ThoughtSpotEmbed>
                <div className="embeddedContent">{children}</div>
            </ThoughtSpotEmbed>
            <TSFooter/>
        </>
  </body>
----

Note that everything above is a React *component*, defined in other files and *included* at the top of `layout.tsx`.

=== Initializing the ThoughtSpot SDK 
The Visual Embed SDK provides an `init()` function that handles authentication and other shared configuration options for all SDK components.

It does not need to be for each component load, but rather before any other ThoughtSpot components are loaded.

In the tutorial app, which is *only* displaying ThoughtSpot content, the `init()` function is run as soon as the app is loaded, in the `layout.tsx` file, via the `ThoughtSpotEmbed` component.

=== components/ThoughtSpotEmbed.tsx
The pattern within `components/ThoughtSpotEmbed.tsx` is important, because it defines any initial configurations and other functions, and runs the `init()` function only once.

At the bottom, we run the `tsInitialize()` function once, and then return a `div` with `id=ts-embed` that will be used as the container for any individual ThoughtSpot embed components loaded by the app later:

[,tsx]
----
 tsInitialize();

return (
    <div className="w-full h-full">
        <div className="w-full h-full" id="ts-embed">
            {children}
        </div>
    </div>
);
----

The `tsInitialize()` function wraps around the entire process of calling the `init()` function from the Visual Embed SDK (note that auth has not been implemented in this example):

[,typescript]
----
    const tsInitialize = () => {
        console.log("Initializing ThoughtSpot SDK");

        // init() function defines basic configuration and auth for all ThoughtSpot embed components
        // https://developers.thoughtspot.com/docs/Interface_EmbedConfig for all configurations
        const ee = init({
            thoughtSpotHost: constants.tsURL,
            authType: AuthType.None,
            username: constants.username,
            getAuthToken: () => {
                return getAuthToken(constants.username);
            },
            callPrefetch: true,
            customizations: {},
        } as EmbedConfig);

        // Checks for Auth process completed as expected
        if (ee) {
            ee.on(AuthStatus.SUCCESS, () => {
                console.log("Success");
            })
                .on(AuthStatus.SDK_SUCCESS, () => {
                    console.log("SDK Success");
                })
                .on(AuthStatus.FAILURE, (reason) => {
                    console.log("Failure:  " + reason);
                });
        }
    };
----

== Conclusion
At this point, the tutorial app framework is started with a layout that initializes the ThoughtSpot Visual Embed SDK. 

The next lesson creates a page that will load an embed compponent into the layout.

'''

xref:react-components_lesson-01.adoc[Next: 01 - Component display pages >]

