= Event handling
:page-pageid: react-components__lesson-04
:description: React components attach event handlers differently than the JavaScript Visual Embed SDK
:toc: true
:toclevels: 2

The ThoughtSpot Visual Embed SDK provides a set of EmbedEvents that can be listened to and handled via callback functions.

== Event listener props
Every link:https://developers.thoughtspot.com/docs/Enumeration_EmbedEvent[EmbedEvent^] has an equivalent *prop* in the React components where the event is applicable, with the naming pattern `on{EmbedEvent}`:

[,tsx]
----
// Required for referencing the LiveboardEmbed that is created in other code
const embedRef = useEmbedRef<typeof LiveboardEmbed>();

return <LiveboardEmbed 
        frameParams={{width:'100%',height:'100%'}}
        liveboardId={renderContent.split("|")[0]} 
        ref={embedRef} 
        onLiveboardRendered={afterEmbedRendered}
        onData={removeLoader}
        onSave={updateMenuSystem}
  />
----

== Using embedRef to update ThoughtSpot component

By setting the *ref* prop to the *embedRef* const declared earlier within the page, functions can refence the embed component within their code to trigger a `HostEvent` without causing the React page to attempt to rerender the embedded ThoughtSpot component.   

For example, the handler function `afterEmbedRendered` assigned to `onLiveboardRendered` above might look like:
[,typescript]
----
const afterEmbedRendered = () => {
        embedRef.current.trigger(HostEvent.SetVisibleVizs, [
                 "3f84d633-e325-44b2-be25-c6650e5a49cf",
                 "28b73b4a-1341-4535-ab71-f76b6fe7bf92",
        ]);
};
----

The `embedRef.current` syntax allows for issuing the `.trigger()` method of calling a link:https://developers.thoughtspot.com/docs/Enumeration_HostEvent[HostEvent^] in when the `EmbedEvent` has fired off.

The same syntax can be used link other UI elements within the React page to the ThoughtSpot component without generating unnecessary and disruptive rerendering.   

'''

xref:react-components_lesson-03.adoc[< Previous: 03 - Menus and other navigation elements]
