= ThoughtSpot React Components Tutorial
:page-pageid: react-components_intro
:description: This is a self-guided course on the ThoughtSpot Visual Embed SDK React Components
:toc: true
:toclevels: 2

ThoughtSpot provides React components as part of the Visual Embed SDK. 

There is also a REST API SDK available in TypeScript which can be included into any React app.

This tutorial walks through the process of installing and integrating the ThoughtSpot React components and REST API SDK into an exiting React app.

The tutorial will discuss common React app features and how to properly integrate the ThoughtSpot technologies into the React patterns.

== Getting started
link:https://react.dev/learn/thinking-in-react[React] is a widely used web application framework. 

There are many great resources for understanding React itself, including the link:https://react.dev/learn/thinking-in-react[React project's own website]. In the tutorial, React concepts will be briefly explained in relation to integrating ThoughtSpot components within the embedding React app.

"React projects" almost always use many different packages on top of the baseline "React" install. 

Within the tutorial, all packages will be given a brief explanation, with links to those project's documentation. 

== Routes and pages
*Routes* are URLs that load different "pages" within the app. 

In some web application systems, a particular URL will load content from a distinct "page" that exists somewhere on the web server.

React apps are typically "single-page apps": rather than there being many separate "actual" HTML pages loaded by the web browser, an initial page is loaded and then updates are made to that "single page". 



