module.exports = {
    SITE_URL: 'https://developers.thoughtspot.com/docs',
    SITE_PREFIX: 'docs',
    DOC_REPO_NAME: '',
    DOC_NAV_PAGE_ID: 'nav',
    TS_HOST_PARAM: 'tshost',
    TS_ORIGIN_PARAM: 'origin',
    TS_APP_ROOT_PARAM: 'appRoot',
    TS_PAGE_ID_PARAM: 'pageid',
    NAV_PREFIX: 'navprefix',
    PREVIEW_PREFIX: 'previewPrefix',
    VISUAL_EMBED_SDK_PREFIX: 'visualEmbedSDKPrefix',
    NOT_FOUND_PAGE_ID: '404-error',
    HOME_PAGE_ID: 'introduction',
    NOT_FOUND_GO_HOME_PAGE_ID: 'introduction',
    TYPE_DOC_PREFIX: 'typedoc',
    DEFAULT_HOST: 'https://try-everywhere.thoughtspot.cloud',
    DEFAULT_PREVIEW_HOST: 'https://try-everywhere.thoughtspot.cloud/v2',
    DEFAULT_APP_ROOT: '/everywhere',
    IS_PUBLIC_SITE_OPEN: 'isPublicSiteOpen',
    TS_DEMO_LOGIN: '/callosum/v1/session/demo/login',
    TS_SESSION_TOKEN: '/prism/?op=GetSessionToken',
    TS_INFO: '/callosum/v1/session/info',
    TS_Version: 'Version',
    BUILD_ENVS: {
        PROD: 'PROD',
        DEV: 'DEV',
        STAGING: 'STAGING',
        PROD_VERSIONING: 'PROD_VERSIONING',
        LOCAL: 'LOCAL',
    },
    DEPLOY_ENVS: {
        RELEASE: 'release',
        DEV: 'dev',
    },
    VERSION_DROPDOWN: [
        {
            label: '10.14.0.cl',
            link: ' ',
            subLabel: 'Cloud (Latest)',
        },
        {
            label: '10.13.0.cl',
            link: ' ',
            subLabel: 'Cloud (Latest)',
            iframeUrl: 'https://developer-docs-10-13-0-cl.vercel.app/docs/',
        },
        {
            label: '10.12.0.cl',
            link: '10.12.0.cl',
            subLabel: 'Cloud',
            iframeUrl: 'https://developer-docs-10-12-0-cl.vercel.app/docs/',
        },
        {
            label: '10.10.0.sw',
            link: '10.10.0.sw',
            subLabel: 'Software (Latest)',
            iframeUrl: 'https://visual-embed-sdk-10-10.vercel.app/docs/',
        },
        {
            label: '10.1.0.sw',
            link: '10.1.0.sw',
            subLabel: 'Software',
            iframeUrl: 'https://visual-embed-sdk-10-1.vercel.app/docs/',
        },
        //{
        //    label: '10.11.0.cl',
        //    link: '10.11.0.cl',
        //    subLabel: 'Cloud',
        //    iframeUrl: 'https://developer-docs-10-11-0-cl.vercel.app/docs/',
        //},
        //{
        //    label: '10.10.0.cl',
        //     link: '10.10.0.cl',
        //    subLabel: 'Cloud',
        //    iframeUrl: 'https://developer-docs-10-10-0-cl.vercel.app/docs/',
        //},
        //{
        //     label: '10.9.0.cl',
        //     link: '10.9.0.cl',
        //     subLabel: 'Cloud',
        //     iframeUrl: 'https://developer-docs-10-9-0-cl.vercel.app/docs/',
        //},
        //{
        //     label: '10.8.0.cl',
        //     link: '10.8.0.cl',
        //     subLabel: 'Cloud',
        //     iframeUrl: 'https://developer-docs-10-8-0-cl.vercel.app/docs',
        //},
    ],
    CUSTOM_PAGE_ID: {
        API_PLAYGROUND: 'restV2-playground',
        ASK_DOCS: 'ask-docs',
        GQ_PLAYGROUND: 'graphql-play-ground',
        THEME_BUILDER: 'theme-builder',
    },
    CLUSTER_TYPES: {
        PROD: 'PROD',
    },
};
