= ThoughtSpot developer tutorials
:toc!:

:page-title: Developer tutorials
:page-pageid: tutorials-overview
:page-description: ThoughtSpot Developer tutorials are self-paced

ThoughtSpot developer tutorials are self-paced, hands-on guides for embedding ThoughtSpot content, calling the REST API, and integrating Spotter into your application.

[.non-link]
++++
<div class="document-body-wrapper">
<div class="row flex pb-10 tutorial-cards-row">
	<div class="col-md-4 flex">
<div class="boxDiv tutorialCard"><div>
      <h5>Embed with SpotterCode</h5>
			<p>Use SpotterCode, ThoughtSpot's AI coding assistant, to build faster and accelerate embedding ThoughtSpot Liveboards and Spotter in your application.</p>
</div><div>
			<p><a href="{{navprefix}}/tutorials/spottercode-embed/intro">Begin Tutorial &gt;</a></p>
</div>
	</div>
	</div>
	<div class="col-md-4 flex">
    <div class="boxDiv tutorialCard"><div>
			<h5>Data-driven embedded app</h5>
			<p>A hands-on guide to embedding a ThoughtSpot Liveboard and Spotter in a host application, built around one real embedding project.</p>
</div><div>
<p><a href="{{navprefix}}/tutorials/embed-data-driven-app/intro">Begin Tutorial &gt;</a></p></div>
	</div>
	</div>
<div class="col-md-4 flex">
    <div class="boxDiv tutorialCard"><div>
      <h5>Embedding fundamentals</h5>
      <p>A self-guided course on ThoughtSpot Embedding Fundamentals. Anyone looking to embed ThoughtSpot components into a web application should start with the Fundamentals tutorial.</p>
</div><div>
      <p>
        <a href="{{navprefix}}/tutorials/tse-fundamentals/intro">Begin Tutorial &gt;</a>
      </p>
	</div>
  </div>
	</div>
	</div>

<div class="row flex pb-10 tutorial-cards-row">
	<div class="col-md-4 flex">
<div class="boxDiv tutorialCard"><div>
      <h5>UI and style customization</h5>
			<p>Tutorial covering how to customize ThoughtSpot UI elements and styles using the Visual Embed SDK.</p>
</div><div>
			<p><a href="{{navprefix}}/tutorials/style-customization/intro">Begin Tutorial &gt;</a></p>
</div>
	</div>
	</div>
	<div class="col-md-4 flex">
    <div class="boxDiv tutorialCard"><div>
			<h5>ThoughtSpot REST API</h5>
			<p>Tutorial covering how to use the ThoughtSpot V2.0 REST API with examples in both Python and JavaScript.</p>
</div><div>
<p><a href="{{navprefix}}/tutorials/rest-api/intro">Begin Tutorial &gt;</a></p></div>
	</div>
	</div>
<div class="col-md-4 flex">
    <div class="boxDiv tutorialCard"><div>
      <h5>ThoughtSpot React Components</h5>
      <p>Learn how to build a React application that embeds ThoughtSpot Liveboards, search, and other components using the Visual Embed SDK React library.</p>
</div><div>
      <p>
        <a href="{{navprefix}}/tutorials/react-components/intro">Begin Tutorial &gt;</a>
      </p>
	</div>
  </div>
	</div>
	</div>
</div>
++++
