= ThoughtSpot developer tutorials
:toc: true
:toclevels: 1

:page-title: Developer tutorials
:page-pageid: tutorials-overview
:page-description: ThoughtSpot Developer tutorials are self-paced

== ThoughtSpot Embedding fundamentals
A self-guided course on ThoughtSpot Embedding Fundamentals. Anyone looking to embed ThoughtSpot components into a web application should start with the Fundamentals tutorial.

xref:tse-fundamentals-intro.adoc[Begin Tutorial >]

== ThoughtSpot REST API V2.0 
Tutorial covering how to use ThoughtSpot V2.0 REST API, with examples in both Python and JavaScript.

xref:rest-api-intro.adoc[Begin Tutorial >]

== ThoughtSpot UI elements and style customization
Tutorial covering how to use customize ThoughtSpot UI elements and styles using Visual Embed SDK.

xref:style-customization_tutorial.adoc[Begin Tutorial >]

== ThoughtSpot REST API V2.0
Tutorial covering how to use ThoughtSpot V2.0 REST API, with examples in both Python and JavaScript.

xref:rest-api-intro.adoc[Begin Tutorial >]

== ThoughtSpot Spotter
Tutorial covering how to integrate ThoughtSpot Spotter AI into a chatbot and embed conversational analytics.

xref:spotter-in-custom-chatbot.adoc[Begin Tutorial >]

