= Lesson 01: What is a REST API?
:page-pageid: rest-api_lesson-01
:description: Introduction to REST APIs in general
:toc: true
:toclevels: 1

== Overview
REST APIs are APIs that use web browser technology (HTTP) to send commands to a web server, which then does the requested actions and returns a response back to the command's sender.

HTTP is the communication protocol, so both sides can talk regardless of internal details.

Each specific command is called an endpoint, which is the URL of the command.

Any programming language or environment can use REST APIs with proper HTTP communication.

== HTTP Requests

HTTP requests are composed of: the URL, a verb, headers and an optional body

=== HTTP Verbs
There are 4 common request verbs: GET, POST, PUT, DELETE

[horizontal]
GET:: read, no body, can have parameters on the URL
POST:: create, typically has a body
PUT:: update, typically has a body
DELETE:: delete, often only has a URL (but some systems use a body)

[NOTE]
====
ThoughtSpot REST API V2.0 only uses *GET* and *POST* verbs. 

The full endpoint name includes the action the endpoint will take, rather than the same endpoint responding to different HTTP verbs.
====

=== HTTP Headers
Headers describe aspects of the request, and are mandatory

=== HTTP Body
Body is data sent with the request, that does not appear in the URL (is secure). The body will vary with each endpoint, and some endpoints do not require a body at all 




'''

xref:rest-api_lesson-02.adoc[Next: Lesson 02 >]
