= Lesson 02: Simple Python V2.0 REST API Implementation 
:page-pageid: rest-api_lesson-02
:description: A lesson on a simple implementation of the V2.0 using Python
:toc: true
:toclevels: 2

== Getting started
We'll use the files from the link:https://github.com/thoughtspot/tse-api-tutorial[tse-api-tutorial GitHub repository, target=_blank] that you downloaded at the beginning of the tutorial.

Open up your IDE (Visual Studio Code will be used in all images and instructions).

The files for Lesson 02 are `api_training_python_1_begin.py` and `api_training_python_1_end.py`

Open up your command line or terminal environment as well.

[NOTE]
====
There are many ways to install and configure Python on a system. This tutorial shows "plain" versions of all commands as if you are using the main system-wide install of Python for the tutorial.

Please adjust all Python commands according to your own environment.
====

== Section 01: Imports and variables
At the top of `api_training_python_1_begin.py`, there is a set of *imports* and *variables* that configure the overall script.

=== Importing Requests library 
To issue HTTP commands in a given programming language, you must use a library that sends and receives HTTP.

For this lesson, we'll use link:https://requests.readthedocs.io/en/latest/[Requests], the most commonly used high-level HTTP library for Python.

The file starts with *import* commands for the `json` standard Python package and the `requests` package, which must be installed.

[,python]
----
import requests
import json
----

==== Install requests package
If you followed the prerequisites and installed the link:https://github.com/thoughtspot/thoughtspot_rest_api_v1_python[thoughtspot_rest_api_v1 package] using your command line or terminal:

[code,bash]
----
pip install thoughtspot_rest_api_v1
----

The `requests` package should have automatically been installed along with the other requirements.

You can double-check the install or force a version upgrade via:

[code,bash]
----
pip install requests --upgrade
----

=== Setting global variables
It is very convenient to declare global variables at the beginning of a script so that they can be reused throughout.

The URL of the ThoughtSpot instance is always necessary to send a REST API command, and if the system has Orgs enabled, you need to send the `org_id` when you request a login token. We'll set those as global variables along with the `api_version` (which hasn't changed ever at this point).

[,python]
----
import requests
import json

thoughtspot_url = 'https://{}.thoughtspot.cloud'
org_id = 1613534286
api_version = '2.0'

----

Now let's construct the starting portion of any API endpoint URL and define the most basic headers that will be used by every call:

[,python]
----
...
base_url = '{thoughtspot_url}/api/rest/{version}/'.format(thoughtspot_url=thoughtspot_url, version=api_version)
api_headers = {
    'X-Requested-By': 'ThoughtSpot', 
    'Accept': 'application/json'
}
----



'''

xref:rest-api_lesson-03.adoc[Next: Lesson 03 >]
