= Lesson 03: Complex REST API Workflows
:page-pageid: rest-api_lesson-03
:description: Complex REST API Workflows
:toc: true
:toclevels: 1

== Getting started
The files for this tutorial are `api_training_python_2_begin.py` and `api_training_python_2_end.py`

You must have installed the `thoughtspot_rest_api_v1` library per the prerequisites at the beginning into the Python environment you are using.

== 01 - Introducing the thoughtspot_rest_api_v1 library
The *link:https://github.com/thoughtspot/thoughtspot_rest_api_v1_python[thoughtspot_rest_api_v1 library]* was originally created because the V1 ThoughtSpot REST API was not very uniform, so a library with an implementation of each individual endpoint was created as a "reference" on how to format and send each request correctly.

The V2.0 REST API  is simple enough to implement in any language - we’ve just done the initial steps in Python in the previous lesson.

The V2.0 portion of the library implements the repeated standard steps everyone would have to do for themselves each time,  and issues can be reported to and fixed in the library once for everyone.

The library encapsulates logic around making the REST API requests properly, so that you don’t have to rewrite code that everyone will need to do the same way. 

Endpoints are defined properly, along with HTTP request details and response handling. 

=== Importing and using the thoughtspot_rest_api_v1 library
Rather than helper functions like in JavaScript, the thoughtspot_rest_api_v1 library provides two `*classes* that represent the entire set of the two REST API versions: `TSRestApiV1` & `TSRestApiV2`

*Classes* define how to build *Objects*, which combine together data (called properties) and functions (called methods).

There are *methods* for each endpoint, typically named identically with the forward-slash replaced by an underscore: the `/metadata/search` endpoint becomes the `.metadata_search()` method.

You'll start by importing all of the classes from the library and then creating a `TSRestApiV2` object, that will be used for all subsequent calls:

[,python]
----
from thoughtspot_rest_api_v1 import *

username = 'username'  
password = 'password'  
server = 'https://{instance}.thoughtspot.cloud'         

ts: TSRestApiV2 = TSRestApiV2(server_url=server)
----

== 02 - Authentication
The TSRestApiV2 object doesn’t automatically log in, you must explicitly request an authentication token and set the `TSRestApiV2.bearer_token` property:

[,python]
----
from thoughtspot_rest_api_v1 import *

username = 'username'  
password = 'password'
org_id = 0
server = 'https://{instance}.thoughtspot.cloud'    

ts: TSRestApiV2 = TSRestApiV2(server_url=server)
try:
    auth_token_response = ts.auth_token_full(username=username, password=password, org_id=org_id, validity_time_in_sec=36000)
    ts.bearer_token = auth_token_response['token']
except requests.exceptions.HTTPError as e:
    print(e)
    print(e.response.content)
    exit()
----

You can also issue a `/session/login` request with token or username/password and the object will maintain authentication using its internal `requests.Session` object:

[,python]
----
ts.auth_session_login(bearer_token=auth_token_response['token'], remember_me=True)
# or
ts.auth_session_login(username=username, password=password, remember_me=True)
----

You'll notice that we've already accomplished everything we did in the previous lesson with much less code. 

== 03 - Using other endpoints

All of the methods of the TSRestApiV2 class are named after their equivalent REST endpoints, with an underscore character `_` replacing the forward-slashes `/` from the URLs.

ex. `/users/search` endpoint is accessed via `TSRestApiV2.users_search()` method

For endpoints that have only a few strictly defined arguments, the method will define Python arguments to match the endpoint’s arguments:

`users_delete(user_identifier:str)`


Endpoints with lots of request options simply take a `request=` argument, which expects a Python Dict matching the JSON request you see in the REST API Playground:
[,python]
----
# Get all Tables
search_request = {
    'metadata': [{'type': 'LOGICAL_TABLE'}],
    'record_offset': 0,
    'record_size': 100000  # default is 10
}
try:
    tables = ts.metadata_search(request=search_request)
except requests.exceptions.HTTPError as e:
    print(e)
    print(e.response.content)
    exit()
for t in table:
    # get details of each table and do further actions
    table_guid = t['id']
----
== 04 - Complex workflows

'''

xref:rest-api_lesson-04.adoc[Next: Lesson 04 >]
