Allows you to show, hide, or disable the primary buttons and menu options that appear in **More**  `...` or the contextual menu.

[NOTE]
====
Use either `visibleActions` or `hiddenActions` to show or hide actions in the UI. The SDK does not support simultaneous execution of `visibleActions` and `hiddenActions` APIs.
====

* To define visible actions, specify the action strings in the `visibleActions` attribute. 
+
Note that the UI displays only the actions specified in this attribute and does not show the other available actions. If you do not specify any actions and leave it as an empty array, no actions will appear in the UI.

+
[source,Javascript]
----
visibleActions: [Action.Save,Action.ShowUnderlyingData,Action.Download,Action.DownloadAsPDF]
----

* To disable an action, specify the action string in the `disabledActions` attribute. For example, to disable **Download** in the **More** menu, specify **Action.Download** in the `disabledActions` attribute. You can also set a tooltip for the disabled menu item in the `disabledActionReason` attribute.

* To hide an action menu item, specify the action text string in the `hiddenActions` attribute. Use this attribute only if the `visibleActions` attribute is not defined.
+
----
hiddenActions: [Action.DownloadAsPDF]
----
+
include::{path}/custom-action-note.adoc[]

+
For more information, see xref:embed-actions.adoc[Show or hide actions].