
When issuing a query through the ThoughtSpot UI, users make selections to disambiguate a query. It is often difficult to programmatically use the result set of a query that runs in the ThoughtSpot UI search bar. Because the selection is not possible with an API approach, the API query language is modified to include query disambiguation.

[#components]
==== Components of a search query

In ThoughtSpot Query Language, the components of a query are classified into various types of tokens:

* xref:Column[Column]
* xref:Operator[Operator]
* xref:Value[Value]
* xref:Date-Bucket[Date Bucket]
* xref:Keyword[Keyword]
* xref:Calendar[Calendar]

[#Column]
Column::
Columns must be enclosed in square brackets, [ ].

+
For example, in the query revenue by ship mode, both revenue and ship mode are columns. A valid query for the API is:

+
----
[revenue] by [ship mode]
----
[#Operator]
Operator:: ThoughtSpot supports various operators such as =, !=, >, >=, \<=, <, contains, not contains, and so on. Use these operators in the API query in the same manner as in the UI.
+
For example, specify revenue over 1000, and limit ship mode to 'air':

+
----
[revenue] > 1000 [ship mode] = 'air'
----
[#Value]
Value:: String (text) and date values must be enclosed within quotes, ''. Do not use quotes for numeric values, except for dates.
+
When using multiple values, separate them by a comma.

+
For example, when a ThoughtSpot UI query is revenue top 2 ship mode, the equivalent API query is:

+
----
[revenue] top 2 [ship mode]
----

+
For example, when a ThoughtSpot UI query is revenue ship mode = air, the equivalent API query is:

+
----
[revenue] [ship mode] = 'air'

----
[#Date-Bucket]
Date Bucket:: In the ThoughtSpot UI, when there are several date columns, users can bind date bucket tokens to a specific column. When using the API, this binding between the date column and the date bucket must be made explicit. Use a period to separate the column with which the date bucket is bound, and the date bucket token.
+
Single word date buckets can be expressed as is. Multi-word date buckets must be enclosed within quotes.

+
For example, when a ThoughtSpot UI query is `revenue commit date monthly`, and if monthly is bound to commit date, the equivalent API query is:

+
----
[revenue] [commit date].monthly
----
+
When a ThoughtSpot UI query is `revenue day of week = 5`, and if day of week is bound to commit date, the equivalent API query is as follows:

+
----
[revenue] [commit date].'day of week' = 5
----

[#Keyword]
Keyword:: Use keywords in the API query in the same manner as in the UI.
+
For example, when a ThoughtSpot UI query uses keywords growth of and sort by, the equivalent API query is as follows:

+
----
growth of [revenue] by [commit date]
----

[#Calendar]
Calendar:: You can specify a custom calendar in the query. Use the calendar.calendar_name format explicitly.
+
When the calendar name contains multiple words, enclose these words in single quotes.

+
For example, when a ThoughtSpot UI query is revenue by commit date fiscal, where the name of the calendar is fiscal, the equivalent API query is as follows:

+
----
[revenue] by [commit date] calendar.fiscal
----
+
For example, when a ThoughtSpot UI query is revenue by commit date my calendar, where the name of the calendar is my calendar, the equivalent API query is:

+
----
[revenue] by [commit date] calendar.'my calendar'
----

==== Functional limitations

* To avoid join path ambiguities, a query can use only a single data source.

* Search execution of query strings is not case-sensitive.

* All column names in the data source must have unique names and must pass the _case-insensitivity_ test.
+
For example, Columns `[Revenue]` and `[revenue]` are not unique.
* Column names cannot contain square brackets, `[` or `]`.

* Values must be enclosed in quotes, `‘’`, but they cannot contain quotes.

* The API does not support **in-query formula** definitions. To use a formula, create it on the Worksheet or a table using the ThoughtSpot UI, and then use the named formula inside the API query.

* Users must be authenticated and have read access to the data source.

* Your browser locale must be `en-US`. Swagger does not accept other variations of English, such as British English, or other languages. Your search keywords must also be in American English. Your column names and other data values do not need to be in American English. You can change your preferred locale to `en-US` in your browser settings.
